### ISSUE TITLE
Jasper doesn't run

### ISSUE THREAD

**Issue by Samat15** [jasp-stats/jasp-issues#1002]
* JASP version: 0.13.1

* OS name and version: Windows 7, 64 bits
* Analysis: Descriptive statistics
* Bug description: Jasper does not display any descriptive statistics on the right side of the screen. I load data but nothing happens
* Expected behaviour: I saw on tutorials that basic descriptive statistics should be shown on the right (see screenshot)
![Jasp](https://user-images.githubusercontent.com/72689010/95675357-f0fd0800-0bb6-11eb-8e3b-04e2a78f1dc2.JPG)

**Comment by boutinb** [comment]
We have encountered lately some users having problems with JASP with Windows 7. The problem is that Windows 7 is not anymore supported by Microsoft self since the beginning of the year. 
By asking them to upgrade to Windows 10, solved their problem.
If you stay to Windows 7, you won't get updates from Microsoft and your installed software won't be able to upgrade either. And even more importantly, you won't get upgrade for security issues, making your PC more vulnerable.

**Comment by Samat15** [comment]
Thank you very much for your replay.
Windows 7 is obsolete and is causing many problems. I'll upgrade soon to Windows 10.

**Comment by JorisGoosen** [comment]
In the meantime you can try "safe graphics" mode through FileMenu->Preferences->Interface.
