### ISSUE TITLE
Custom JASP storage location

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#1016]
When I install some version of JASP, in the hard disks D, E, F, anyway most of the installation goes to C, in which I have very little space. My recommendation is to avoid this situation, to have a better control of the installation and the space used on the disks. 

Best regards.
r.

**Comment by boutinb** [comment]
@JorisGoosen Is it something we could add in the Windows setup?

**Comment by romanogino** [comment]
I do not have knowledge about it. I found a web page https://www.funduc.com/app_mover.htm that could be useful.  With JASP 0.14 I installed the software in D hard disk, but the main space was used in C hard disk. 
https://forums.tomshardware.com/threads/prevent-any-software-from-installing-on-c-drive.2154987/ 

Best regards.
r.

**Comment by JorisGoosen** [comment]
Well, the bulk of the software is really installed to the other drive if you specify it as such.
The only problem for you is that we use temporary files (which can get huge because the shared memory could become large and is stored there).

If you have such a low amount of space on C, maybe it is a good plan to move your users/documents folder to a different drive.

On the other hand, it wouldn't be such a bad plan to add an option to JASP where you specify an alternative storage folder, but this might take a while to be implemented though.

**Comment by romanogino** [comment]
Thanks for the advice. I will tray to probe it.
Best regards.
r.
