### ISSUE TITLE
Make it easier to add factors to linear regression

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1022]
https://twitter.com/AlbertBrown_sq/status/1319878522781847553

I think we should do this -- we've done it for logistic regression, apparently.
E.J.

**Comment by rmporsch** [comment]
I think its important to emphasize how important this issue is.
Currently the interface implies that all variables, no matter the type can be used in a linear regression. However, factors currently cannot be added. 
For new users this can be quiet frustrating and I am sure this can be confusing to people who are currently learning statistics.
Given that factors are so common in all analysis, I am actually surprised this hasn't come up earlier. 
However, it could also be I am missing something very obvious.

Linear regression:
![Screenshot from linear regression](https://user-images.githubusercontent.com/3382854/100543080-f7d7fb00-3288-11eb-9004-0e8e1ba8c798.png)

Logistic Regression:
![Screenshot from Logistic Regression](https://user-images.githubusercontent.com/3382854/100543141-61f0a000-3289-11eb-94b2-d2bb3cb4174f.png)

**Comment by EJWagenmakers** [comment]
Yes, good catch. We are aware of this and will add factors in the next major release (not the upcoming bug fix release)
Cheers,
E.J.
