### ISSUE TITLE
Error in installing JASP with most recent Mac Catalina update

### ISSUE THREAD

**Issue by jennawneal** [jasp-stats/jasp-issues#1042]
<img width="420" alt="Screen Shot 2020-11-04 at 2 13 37 PM" src="https://user-images.githubusercontent.com/74001593/98244986-46ba9b00-1f3e-11eb-834a-afe2a077d5b5.png">
<img width="420" alt="Screen Shot 2020-11-04 at 2 13 37 PM" src="https://user-images.githubusercontent.com/74001593/98245009-50440300-1f3e-11eb-8254-6f9cade68b73.png">

* JASP version:  0.14
 MacOS
* OS name and version: Catalina 10.15.7

* Bug description:  One of my students can't open and install the JASP download file using MacOS with the latest Catalina update.  Do you have any thoughts on what she can do to remedy the problem?

<!--- A note from the developers:
If possible please attach your data and/or JASP file to the issue, this makes solving the bug a lot easier. If you would prefer to not make your data publicly available then you could also mail it to us.
Note that github requires you to zip the file to upload it here.

**Comment by tomtomme** [comment]
MacOS says the file is damaged and I would treat it that way. Maybe he downloaded via a instable WLAN connection or something is wrong with his network-hardware. Try downloading via another computer and transfer the file via usb-stick. If this does not help, report back.

**Comment by jennawneal** [comment]
That didn't help. The issue seems to be a problem only for students with the most recent Mac Catalina update (I have another student who had a similar issue as well).

**Comment by FransMeerhoff** [comment]
Hi @jennawneal 
I'm running here on MacOS Catalina Version 10.15.7 and can't reproduce the problem.
Could you ask the students:
1. To send the file info of the downloaded .dmg file (By right clicking on the file and choose 'Get Info') 
![Screen Shot 2020-11-10 at 11 16 39](https://user-images.githubusercontent.com/15656960/98661248-83273600-2346-11eb-94d8-dcd9dccf0dea.png)
2. A wild guess: but could you ask them to download JASP by means of safari or chrome instead of Firefox?

**Comment by jennawneal** [comment]
Using a different browser solved the problem!  Thanks so much for your help!
