### ISSUE TITLE
I can't open the app after installing it many times.

### ISSUE THREAD

**Issue by algncn7** [jasp-stats/jasp-issues#1043]
I have installed the app many times but I cannot open it. Please reply ASAP. My midterm exam is coming and I can't do my requirements because we need ro use this app.

jasp ver. : JASP 0.14.0.0
laptop specs: windows 10, 64 bit

**Comment by EJWagenmakers** [comment]
Dear algncn7, 
What message are you getting, or does nothing happen? Do you have admin rights on your laptop? Have you tried our zip file? (it can just be unzipped and you can click the .exe file, no need for installation)
E.J.

**Comment by tomtomme** [comment]
https://static.jasp-stats.org/JASP-0.14.0-64bit.zip
heres the zip

**Comment by bradyse** [comment]
I also have a Windows 10, 64 bit and the same thing happened to me (using the installer file), which was you click to open the app and nothing happens. When I tried to download the zip file, and install it that way, the following error occurred: "The application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem." But when I installed it using the installation method, nothing happens when I attempt to run the program (either as an administrator or not). This only happened after my most recent Windows 10 updated (JASP was working fine previously).

**Comment by boutinb** [comment]
I have heard that sometimes there is a problem with the Visual C++ redistributable libraries. These libraries are shipped with JASP, but after a Windows upgrade something goes wrong. Could you install these libraries yourself: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
And then try again to start JASP.

**Comment by bradyse** [comment]
I downloaded the x64: vc_redist.x64.exe file since I have a 64 bit system. It did nothing and JASP still won't open. When I tried to download the logtoFile info (per another thread), the file does not exist in my AppData\Roaming folder.

**Comment by boutinb** [comment]
This issue is now here: https://github.com/jasp-stats/jasp-issues/issues/1121
