### ISSUE TITLE
Can D3.js visualization library be integrated in JASP

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1050]
I have no clue if you could even add javascript to the JASP code base, but D3.js seems like a very powerful solution to enhance graphing / plotting capabilities of JASP. See: https://flowingdata.com/2020/11/11/tour-of-the-d3-ecosystem/

**Comment by boutinb** [comment]
@vandenman Can you have a look if it is something we could use for plot editing?

**Comment by vandenman** [comment]
Although D3.js certainly is a power graphing library, it would require a complete rewrite of all plots (which are currently written in R) as well as javascript integration into R. I suppose integrating javascript into R is possible with `V8`, but to do something like that we're talking years rather than weeks or months. I'd see more potential for something like [`plotly`](https://plotly.com/ggplot2/geom_raster/). However, `plotly` might introduce a kind of watermark and might also complicate editing or saving figures to different formats (e.g., pdf, svg).

**Comment by boutinb** [comment]
Also for your information: we will already implementing some plot editing features, that will be available in 0.15

**Comment by tomtomme** [comment]
thanks for looking into this. I will close this then for now :+1:
