### ISSUE TITLE
Prediction and Confidence Intervals in Regression in Predictor and Outcome Units

### ISSUE THREAD

**Issue by jlwoodard** [jasp-stats/jasp-issues#1051]
* Enhancement: Allow users to decide whether to graph prediction and confidence intervals not only in residual units, but in raw score units for the predictor and outcome variables as well.
* Purpose: I am so happy to see the prediction and confidence intervals being made part of the regression options, but I could not see a way to prepare these graphs in units other than the residuals. I was not clear why users are only able to perform these graphs on the residuals.

**Describe the solution you'd like**
 
 If a user wanted to determine the predicted Y score for a specific value of X, for example, there seems to be no way to obtain such a plot. The only way to generate prediction and confidence intervals seems to be as part of the residuals analysis.

**Comment by boutinb** [comment]
@Kucharssim Can you have a look at this request?

**Comment by fqixiang** [comment]
@jlwoodard Sorry this took a long time. I just briefly looked into this. Just to be sure: is your request about the partial plots where you would like the x-axis and y-axis to be on the original measurement units of the variables? See below.
![image](https://user-images.githubusercontent.com/20680189/132695078-abb2de4f-36af-454b-b72a-6a3cf0a68196.png)

If this is the case, then I don't think your request is possible because the idea behind a regression partial plot is exactly the plotting of the relationship between the residuals of the DV and the residuals of the IV of choice (See [here](https://stats.stackexchange.com/a/125575/238154) for more information). This allows one to visualize the exact, unique relationship between a particular IV and the DV, while all the other IVs are accounted for. I don't think there is a direct way to transform the residuals into the original measurement units without breaking the nature of a regression partial plot.

On the other hand, you might be thinking of so-called marginal effect plots, where you can visualize the effect of an IV on the DV on the original measurement scales, assuming some values of the other IVs (often just averages). See [here](https://cran.r-project.org/web/packages/sjPlot/vignettes/plot_marginal_effects.html) for examples. Such plots are available in R via packages like effects, margins and sjPlot. I don't think they are currently available in JASP though. Is this something useful to implement? @jlwoodard @koenderks @Kucharssim

**Comment by jlwoodard** [comment]
@fqixiang Thank you for getting back to me! I see your point regarding the partial plots, but I think being able to plot the prediction intervals and confidence intervals is essential for any regression. What I am hoping to achieve is illustrated on this page: https://rpubs.com/Bio-Geek/71339. You will see that the IV and DV are on their respective original measurement scales. Such a plot can indicate, for a given value of the IV, what is the predicted value on the DV, and what are the confidence and prediction intervals around that estimate. @fqixiang @koenderks @Kucharssim

**Comment by fqixiang** [comment]
@jlwoodard Hi, thanks for the clarification. The exiting partial plots option does already provide confidence and prediction intervals. I looked at the link you provided - that is a special case (only one IV and one DV in a regression model) of **marginal effect plots** that I mentioned earlier (which are quite different from partial plots). Of course, confidence and prediction intervals are possible for marginal effect plots. 
JASP does not provide the option of making such marginal effect plots yet, but I do think they are valuable and can be added. What do you think? @koenderks @Kucharssim

**Comment by Kucharssim** [comment]
I agree that marginal plots would be nice to implement!
