### ISSUE TITLE
Fuzzy c-means clustering

### ISSUE THREAD

**Issue by hpapadogiannis** [jasp-stats/jasp-issues#1073]
his analysis terminated unexpectedly. 

Error: cannot allocate vector of size 22.6 Gb

Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.clusteringTable(dataset, options, jaspResults, ready, position = 1, type = 'cmeans')

.clustering(dataset, options, jaspResults, ready, type = type)

.cMeansClustering(dataset, options, jaspResults)

summary(cluster::silhouette(cfit_tmp$cluster, dist(dataset[, .v(options[['predictors']])])))

cluster::silhouette(cfit_tmp$cluster, dist(dataset[, .v(options[['predictors']])]))

silhouette.default(cfit_tmp$cluster, dist(dataset[, .v(options[['predictors']])]))

as.dist(dist)

dist(dataset[, .v(options[['predictors']])])
version 0.14
I have 40 gb left in my disc.
please help

**Comment by vandenman** [comment]
how many variables and observations do you have? Would it be possible to upload the .jasp file to GitHub?

**Comment by hpapadogiannis** [comment]
Hi, and thanks for the immediate response!
I have 80000 rows and 20 columns
Elias

**Comment by hpapadogiannis** [comment]
.jasp file inside

[agymn.zip](https://github.com/jasp-stats/jasp-issues/files/5588954/agymn.zip)

**Comment by koenderks** [comment]
I can still reproduce this with the latest build of JASP. @vandenman How should we handle this? Is this just a memory problem (and specific to the user / computer)?

**Comment by vandenman** [comment]
@koenderks this goes wrong because on line https://github.com/jasp-stats/jaspMachineLearning/blob/68f5b25f34f6e7f21b5cb8de7c6d30382c3df260/R/mlClusteringFuzzyCMeans.R#L78 we do

```r
dist(dat[, options$predictors])
```
and this scales terribly in terms of memory (O(n^2)).

I'm not sure we can fix this in general, perhaps we can make it work for `100 000` observations but then surely it'll crash for `1 000 000`. The error does seem isolated to this function, so perhaps it should fail more gracefully?
