### ISSUE TITLE
Please add checkbox for scatter plot to section Regression => linear Regression and f(x)

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1085]
I can produce scatter plots in Descriptives and in Correlation, but not in linear Regression. Please addd a checkbox in the Plots-Section at the bottom  - above the Residual Plots.
The scatter plot should show the regression line and if possible also the function f(x) = a + b*x + ...

Thank you!

(I am almost sorry to bring up so many issues during the last weeks. But me and a colleague are going full JASP this year with all classes first time. I managed to not open SPSS once and only mentioned that it exists as an alternative that many still have to use)

**Comment by vandenman** [comment]
> I am almost sorry to bring up so many issues during the last weeks.

No worries! It makes much more sense for us to develop features that people will actually use.

> But me and a colleague are going full JASP this year with all classes first time.

Happy to read that!



Just to make sure we're on the same page, rather than the partial plots below, which are on the scale of the residuals,

![image](https://user-images.githubusercontent.com/21319932/100517991-21146080-318f-11eb-87ae-6981629af045.png)


you would like a checkbox for a plot on the scale of the raw data, like in descriptives? Something like this:

![image](https://user-images.githubusercontent.com/21319932/100518082-9ed86c00-318f-11eb-9d26-504aa3beeffb.png)


Note that visualizing a function like `f(x, y, z) = a + b*x + c*y + d*z + ...` in a single plot can get kinda difficult when there are multiple predictors. Or would you like to plot the model predictions against the observed values?

**Comment by tomtomme** [comment]
Thanks. What you show in the lower plots is what I want (like in descriptives). 2 variables per plot are fine. However descriptives can already a third variable via Splits if it is binary / dichotomous via colour coding. Maybe this could be copied over without too much work.

Your "visual modeling" / Flexplot module is even more flexible.... It can display 4 variables of any scale and would automatically categorize and colour code a third metric variable and produce a multiple plot pane for a fourth variable. However I guess that one is not that easy to copy over.

So all solutions I seek are already somewhere available within JASP and it would be kind of duplicate functionality. But still, a missing normal Scatterplot feels like a hole within the Regression-Module. Its unintuitive to search for it somewhere else ... first world problems ...

Thx!

**Comment by tomtomme** [comment]
Still valid with JASP 0.16.4
Bivariate Scatterplots within Regression module would be cool.

**Comment by tomtomme** [comment]
Nobody else seems interested in this and I can live without it, since flexplot does a good job and I now just teach that your first analysis step is always doing plots with flexplot. 

And showing the function of the regression is tracked here: 
https://github.com/jasp-stats/jasp-issues/issues/1475
https://github.com/jasp-stats/INTERNAL-jasp/issues/2401
