### ISSUE TITLE
qq plots

### ISSUE THREAD

**Issue by philippberens** [jasp-stats/jasp-issues#1096]
While using JASP during teaching, my students and I stumbled upon unexpected behavior of different qq-plot implementations at different places in JASP:

qqplot under descriptive stats plots standardized residuals on the y-axis, while qq-plot in Distributions the Sample numbers. Also, the lines shown are not identical. I think it would be nice to harmonize the behavior.

![image (1)](https://user-images.githubusercontent.com/1633247/102099924-24fbe000-3e29-11eb-94c1-63c883945284.png)
* JASP version: 14.0

**Comment by vandenman** [comment]
So in descriptives standardizes the variable and then compares it to the quantiles of a standard normal distribution. In contrast, the distributions module uses maximum likelihood estimation to obtain parameter estimates for the normal distribution (and other distribution) and then compares the sample quantiles to the fitted distribution. I've now changed it so that descriptives also compares the sample quantiles on the y-axis. It doesn't do any fitting however, so the x-axis may have a different scale:

Descriptives (development version)            |  Distributions
:-------------------------:|:-------------------------:
![](https://user-images.githubusercontent.com/21319932/102200187-cedc7a80-3ec4-11eb-9538-0542e729cf30.png)  |  ![](https://user-images.githubusercontent.com/21319932/102200213-d734b580-3ec4-11eb-8473-af69a1c3c715.png)

I'll tweak the axis titles and y-axis ticks of the distributions module so that they match those in descriptives.

**Comment by philippberens** [comment]
Thanks for tackling this quickly. The two methods are equivalent for a Normal distribution, in my opinion, as standardization requires estimating mu and sigma, and the estimates are the ML estimates.

**Comment by vandenman** [comment]
> The two methods are equivalent for a Normal distribution

They are indeed identical for a normal distribution. However, in the distributions module, the plotting code is set up generically, so that it works for all distributions. It would also not make sense to standardize e.g., gamma-distributed variables as subtracting the mean would introduce negative values.

**Comment by philippberens** [comment]
Ah great, but that means that the two plots are now identical in the two tabs for Gaussians, which I think makes sense. Maybe adjust the axis labels.

**Comment by tomtomme** [comment]
@philippberens 
It seems like this is solved?
Feel free to reopen, if I misunderstood.
