### ISSUE TITLE
Cannot create scatter/correlation plot

### ISSUE THREAD

**Issue by stephleo** [jasp-stats/jasp-issues#1130]
* JASP version: Version 0.9.2

* OS name and version: OS X Yosemite
* Analysis: Cannot create a correlation/scatter plot.  It says the analysis terminated unexpectedly.
<img width="500" alt="Screen Shot 2021-01-23 at 1 44 22 PM" src="https://user-images.githubusercontent.com/77896838/105611054-2356fd80-5d81-11eb-9f61-f0b400dd75af.png">

* Bug description: I attached a screenshot of the error code because I do not understand it.
* Expected behaviour: I just want to create a scatter plot.

**Comment by boutinb** [comment]
Hi @stephleo , you use a quite old version of JASP, could you upgrade to 0.14?

**Comment by stephleo** [comment]
Hi @boutinb @Kucharssim  , I could try.  When I looked up which version to download for my software on my Mac, it said that 0.9.2 was the latest compatible version.  Would version 0.14 work with OS X Yosemite operating system?

**Comment by boutinb** [comment]
Hi @stephleo Yosemite is not supported by Apple anymore since July 2017... You should really upgrade your computer. There is for example no security update. We don't have such a computer either where we can try to reproduce your problem, and we will anyway not update the 0.9 JASP version. So I'm afraid the only solution is upgrade your MacOS, and to install the newest version of JASP.
