### ISSUE TITLE
Frequentist Repeated Measures ANOVA: Incorrect effect size (Cohen's d) for paired comparisons

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#1144]
[Bugs.zip](https://github.com/jasp-stats/jasp-issues/files/5900755/Bugs.zip)
The values of Cohen's paired effect size are false.

**Comment by JohnnyDoorn** [comment]
Hi @NikitaKhromov-Borisov 

I think you are misusing the online tools you link, because the results of JASP are correct. I think you incorrectly used the effect size calculator for between samples t-test, instead of paired samples. See the screenshot below for my JASP output (both the RM ANOVA post hoc tests, with the non-pooled error terms, and the paired samples t-test), which feature the exact same results as the cohen.d function from the effectsize package in R:
```
library(effectsize)
dat <- read.csv(  "~/Downloads/3DIA.csv")

cohens_d(dat$X014_20, dat$X017_20, paired = TRUE)  #  -2.67 | [-3.70, -1.76]

cohens_d(dat$X014_20, dat$X020_20, paired = TRUE)  #  -0.27 | [-0.74, 0.18]

cohens_d(dat$X017_20, dat$X020_20, paired = TRUE)  #   1.94 | [1.21, 2.75]

```

![Screenshot from 2021-02-01 11-46-24](https://user-images.githubusercontent.com/15704203/106448792-892f3d80-6483-11eb-983f-12014c168ce0.png)

I am closing this issue now, please reopen if you have further comments or questions.

Kind regards,
Johnny

**Comment by NikitaKhromov-Borisov** [comment]
Dear Johny,
I do not agree. I have sent you the results of calculation of Cohen's d
with two programs, which look more realistic: -0.41, -0.054 and 0,36.
Please, take a look at the mean differences, they are extremely low and
d=-2.67, -0.27 and 1.94 are impossible.
The attached are the histograms (PAST
https://www.nhm.uio.no/english/research/infrastructure/past/). You see they
are extremely overlapping. [image: image.png]

When d = 2 the overlapping should be like the attached figure
https://rpsychologist.com/cohend/

Please, find a time to check your algorithms.
BTW, your bootstrap is working too slowly. Using PAST I can easily apply
1000000 random samples.
Cheers,
Nikita

пн, 1 февр. 2021 г. в 13:50, JohnnyDoorn <notifications@github.com>:

**Comment by JohnnyDoorn** [comment]
Hi @NikitaKhromov-Borisov,

I do look at the mean differences, but also at the standard deviations, which are also extremely low, so the Cohen's d values do seem realistic to me. Cohen's d for the paired samples t-test is the mean of the differences, divided by the standard deviation of the differences. The mean difference between your V014 and V017 is  -0.00435 and the sd of the differences is 0.00163. If you take the ratio of these 2 numbers, you get 2.67, which is what JASP, and numerous R packages give if you conduct a paired t-test. If you conduct an unpaired t-test (i.e., two-sample), you get the value that you are citing, of -0.43, hence my comment that you might have run a different analysis. 

Your links don't seem to be working, I don't see any histogram, just "[image: image.png]".

Your comment about the bootstrapping is noted, I will discuss this at the next team meeting. 

Kind regards
Johnny

**Comment by EJWagenmakers** [comment]
Side-note: an upcoming blog post will show the results of a JASP validation project. This project examined most of the frequentist methods and checked that they give the same results as SPSS, SAS, Minitab, and R. This was virtually always the case.
