### ISSUE TITLE
Reliability module: More helpful error message?

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1148]
* Enhancement: More helpful error message in Reliability module
* Purpose: Let the user understand why Cronbach's alpha gives an error
* Use-case: In case of calculating Cronbach's alpha when the average covariance between items is negative.

**Is your feature request related to a problem? Please describe.**
Cronbach's alpha is negative when the average covariance between items is negative. In this case JASP shows an uninformative error message:

<img width="2277" alt="Schermafbeelding 2021-02-01 om 19 31 03" src="https://user-images.githubusercontent.com/5346286/106502641-e8617200-64c4-11eb-9666-185cb2e4ef33.png">

**Describe the solution you'd like**
JASP could show an informative message, something like in SPSS 27.0.1: "The value is negative due to a negative average covariance among items. This violates reliability model assumptions. You may want to check item codings."

<img width="319" alt="Schermafbeelding 2021-02-01 om 19 38 12" src="https://user-images.githubusercontent.com/5346286/106502748-0cbd4e80-64c5-11eb-8ae3-f58512f77dd0.png">

**Describe alternatives you've considered**
None

[test.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5905966/test.jasp.zip)

**Comment by juliuspf** [comment]
Thanks. This error message is not due to the alpha calculation but some other coefficient. I think this is also related to another issue of yours: https://github.com/jasp-stats/jasp-issues/issues/1026. I have rewritten the reliability module to deal with errors in a better fashion. However feedback is always welcome. Attached is a screenshot of the analysis as it is on my machine. Would you say it is sufficient to alert the user to items correlating negatively with the scale? 
![Screenshot 2021-02-02 at 10 05 39](https://user-images.githubusercontent.com/38500953/106577453-abd25c80-653e-11eb-93b1-24c2825533cc.png)

**Comment by djdekker** [comment]
Hi Julius,

That looks perfect. Thank you!
