### ISSUE TITLE
Double-standardization of paths in mediation model (non-latent)

### ISSUE THREAD

**Issue by sonnyrosenthal** [jasp-stats/jasp-issues#1152]
* JASP version: 0.14.1
* OS name and version: Windows 10 Home
* Analysis: Mediation Analysis
* Bug description / Expected behaviour: The standardized paths in a mediation model should match the standardized paths from the equivalent OLS regression models. E.g., paths b and c' should match b1 and b2 from the regression model, Y-hat = Mb1 + Xb2 (where M is the mediator and X is the predictor). They do not. I found if I multiply the "standardized" paths from the mediation model by the standard deviation of X, the results match the regression model results. I suspect the unstandardized paths were double-standardized, which is why I need to multiply by the standard deviation. Note, I am running this analysis on mean-score composites, not on latent variables. Related, I noticed the path plot of the standardized model shows variances. I believe those values should be the item self-correlations, with values of 1.

**Comment by tomtomme** [comment]
@sonnyrosenthal & @Kucharssim 
The path plot shows paths a b c. 
The standardized estimate of path b is the same now (JASP 0.18.3) as the path in OLS regression. I do not know about path c. It does not match with "album sales" data set from the data library. But maybe this is expected, since mediation assumes a direction between IV and Mediator, where multiple Regression only defines the direction from IVs to DVs? 
And does lavaan SEM even use OLS here? I left the estimate setting on auto. 
You see I am not yet very familiar with such models.
