### ISSUE TITLE
correlational cut-off increase help required

### ISSUE THREAD

**Issue by babu301** [jasp-stats/jasp-issues#1161]
How can I inter-connected items of  correlational cut-off increase in JASP? 
For example: correlational cut-off = 0.35  and then to correlational cut-off = 0.40 and then to plot a network diagram respectively.

**Comment by vandenman** [comment]
So I have a couple of questions:

- What OS and JASP version do you use?
- What analysis does this relate to? Network analysis?
- Is this a bug or a feature request?
  - If it's a bug, please describe the bug as well as expected behavior.
  - If it's a feature request, please provide the expected behavior.

The more details the better!

**Comment by babu301** [comment]
I am using Windows 7  and JASP version 0.13.1.0.
It is related to network analysis as I am going through one paper and find
below network analysis performed in JASP.

[image: image.png]
The above figure shows a correlation based network among the items.  This I
am able to get.

[image: image.png]

The above figure shows the strong cluster of inter-connected items  at a
correlational cut-off = 0.35. This I am not able to find how to do in JSAP.

[image: image.png]

The above figure shows the strong cluster of inter-connected items at a
correlational cut-off = 0.40. This also I am not able to do in JSAP.

Regards,
Krishn

**Comment by vandenman** [comment]
Could you use GitHub's website directly to upload the images? If you email them then unfortunately GitHub cannot display them.
