### ISSUE TITLE
Multiple invariance tests simultaneously for Structural Equation Modeling

### ISSUE THREAD

**Issue by andremonezi** [jasp-stats/jasp-issues#1178]
At the moment, JASP has no commands for assessing invariance measures on SEM Model. These are very important in the psychometrics field, for example.
See the link as an example: https://jihongz.github.io/lavaan/2017/11/12/MESUREMENT-INVARIANCE.html
Also, it would be very helpful if JASP could present the fit indexes for each invariant, as shown in this figure. The figure was collected from the link above.
Surely, this would be a significant advance in MGCFA analysis!
![Invariance Table Example](https://user-images.githubusercontent.com/64216719/109165317-2cf5cb80-775a-11eb-879b-be6744690abf.PNG)

**Comment by juliuspf** [comment]
@Kucharssim, I was under the impression we offer invariance testing?

**Comment by Kucharssim** [comment]
@juliuspf Indeed, invariance testing is now available in the CFA analysis under the Multigroup CFA Section. For SEM models, it is possible to do more flexible constraints under Multigroup SEM section, or by simply using the lavaan syntax.

However, there is an argument that the multigroup SEM (in-)equality constraints could be done per model, not per analysis (https://github.com/jasp-stats/INTERNAL-jasp/issues/2092), so that it's possible to test models with different constraints to each other (without using the lavaan syntax to do that).
