### ISSUE TITLE
the classical linear regression got a problem in my computer (JASP 0.14.1.0)

### ISSUE THREAD

**Issue by 69933152** [jasp-stats/jasp-issues#1188]
the video showing the problem:
https://user-images.githubusercontent.com/79885837/109586522-52ab1800-7b40-11eb-9f7f-2a2ac52a21e2.mp4

the normal screenshot from my friend:
![266857765838123888](https://user-images.githubusercontent.com/79885837/109586629-8be38800-7b40-11eb-8718-73d74955d0f5.jpg)

**Comment by 69933152** [comment]
64 bit JASP 0.14.1.0

**Comment by vandenman** [comment]
Hi, we've disallowed factors in linear regression because the results were incorrect (they were treated as continuous predictors). In the next release, it will be possible again to add factors (with correct results). In the meantime, if you really want to add the predictor you can change the type of the variable from ordinal to scale:

![image](https://user-images.githubusercontent.com/21319932/109618196-8cc3ec00-7b37-11eb-88cf-76cdab413fcc.png)

After that, it should be possible to add the variable to the box `Covariates`.

Hope that helps!

**Comment by juliuspf** [comment]
I think this issue can be closed, @69933152 if issues remain feel free to reopen it.
