### ISSUE TITLE
JASP opens SAV in JASP despite custom editor setting

### ISSUE THREAD

**Issue by keunes** [jasp-stats/jasp-issues#1189]
* JASP version: 0.14.1
* OS name and version: Windows 10
* Bug description: JASP opens SAV in JASP despite custom editor setting
* Expected behaviour: Open the dataset in LibreOffice, as set in the Data Preferences (C:/Users/first.last/.programmes/LibreOfficePortable/LibreOfficeCalcPortable.exe)

#### Steps to reproduce:
1. Make JASP default programme for sav files
2. Open sav file
3. Double-click on data array

**Comment by boutinb** [comment]
Hi @keunes I thought that LibreOffice could not open a sav file. If it is the case then I could change this behaviour.

**Comment by keunes** [comment]
> Hi @keunes I thought that LibreOffice could not open a sav file.

I don't know actually, that might be it. Somehow I thought JASP converted the file to CSV or its own format in the background.

Either way, if the set editor can't open it, I'd expect an error rather than current behaviour.

**Comment by boutinb** [comment]
Hi @keunes, JASP loads the data from a file (here the sav file), and synchronizes its data each time this file is changed. So it does not make a new file. 
As sav file can be edited only by SPSS, that's why when you double-click the data panel to edit the data, JASP assuming that the default application associated with the sav file is SPSS, starts this default application. In your case, it opens JASP again, making it indeed quite confusing. 
I'll have a look to this problem. But for the time being, what you can do is to use the 'Export Data' menu: this generates a csv file. If you load this file in JASP, and double-click the data panel, it should then open the LibreOffice application. Each time you modify this file in LibreOffice, JASP should synchronize its data with your change (and rerun the analyses in case).

**Comment by keunes** [comment]
> JASP loads the data from a file (here the sav file), and synchronizes its data each time this file is changed. So it does not make a new file
for the time being, what you can do is to use the 'Export Data' menu: this generates a csv file

Hah, ok. I understand. I also have a CSV version of my dataset, so I can use that. But thanks for the tip :)

It was more about usability; just to get the vicious circle fixed for others. 'cause it's still odd that the 'custom editor' setting is ignored. I would expect LO to try and open it, then say "sorry, can't handle it"
