### ISSUE TITLE
t test for independent samples: use grouping factor with >2 levels

### ISSUE THREAD

**Issue by hugoquene** [jasp-stats/jasp-issues#1201]
* Enhancement: allow independent variable with >2 groups in t-test for independent samples, while requiring the user to define which values of the IV correspond with groups 1 and 2.
* Purpose: No need to filter data by selected values of IV before conducting t-test for independent samples. No need to discard filter afterwards. 
* Use-case: Data set R:::hqmisc::talkers, IV is *region*, conduct a t-test to compare speakers from W and N region, for educational/demonstrative purposes. 

**Is your feature request related to a problem? Please describe.**
 
No. 

**Describe the solution you'd like**
 
In the Use-case described above: enter *region* as independent (grouping) factor, then define which values or levels correspond with which of the two groups being compared. 

**Describe alternatives you've considered**
 
Filter out all but two values or levels of the IV, and then use the IV as grouping factor. Afterwards, do not forget to remove or adjust this filter.

**Comment by vandenman** [comment]
I can come up with quite a few ways to do this:

1. Create a computed column. That way there is no need to delete the filter afterward.
![image](https://user-images.githubusercontent.com/21319932/110754284-ec14b100-8247-11eb-96bb-d75fac23d7d1.png)

2. Directly filter the levels of `region`.
![image](https://user-images.githubusercontent.com/21319932/110754354-064e8f00-8248-11eb-902e-074230b7f677.png)

3. Use a custom filter to filter the levels of `region`. 
![image](https://user-images.githubusercontent.com/21319932/110754595-4ada2a80-8248-11eb-9ab5-1ae2f355ad1a.png)


If you don't want to remove the filter afterward, then option 1 is probably the easiest. We could implement a filter behind the scenes for this, but people might wonder, why only the t-test and not, say, ANOVA? Rather than implementing this individually for all analyses that handle categorical variables, it makes more sense to use one of the three global methods described above to do this (and these methods are also more flexible).

**Comment by hugoquene** [comment]
Beste Don,

Thanks for your response! Indeed there are other ways to achieve this, and your method #1 was indeed already suggested to me.
I think I'll take back that suggestion to our teaching team (this is for an intro Meth & Stats course) to include such a step into our students' assignment.
Thanks again and best wishes, Hugo


--
Prof.dr. Hugo Quené | hoogleraar Kwantitatieve Methoden |
Dept Talen Literatuur en Communicatie | Utrecht inst of Linguistics OTS | Trans 10 | 3512 JK Utrecht | +31 30 253 6070 |
Centre for Digital Humanities | Drift 10 | 3512 BS Utrecht |
Universiteit Utrecht | ***@***.******@***.***> | www.uu.nl/gw/medewerkers/HQuene<http://www.uu.nl/gw/medewerkers/HQuene> | www.hugoquene.nl<http://www.hugoquene.nl> |

New:
Quené, H. & Van den Bergh, H. (2021). Quantitative Methods and Statistics. <https://hugoquene.github.io/QMS-EN/>  Open textbook, 270 pp.
Quené, H. & Van den Bergh, H. (2021). Kwantitatieve Methoden en Statistiek<https://hugoquene.github.io/KMS-NL/> [in Dutch]. Open<https://www.oercommons.org/courses/kwantitatieve-methoden-en-statistiek> textbook, 284 pp.




"Don van den Bergh" ***@***.******@***.***>> schreef op 2021.03.11, 9:04 :


I can come up with quite a few ways to do this:

1.       Create a computed column. That way there is no need to delete the filter afterward.
[Image removed by sender. image]<https://user-images.githubusercontent.com/21319932/110754284-ec14b100-8247-11eb-96bb-d75fac23d7d1.png>

2.       Directly filter the levels of region.
[Image removed by sender. image]<https://user-images.githubusercontent.com/21319932/110754354-064e8f00-8248-11eb-902e-074230b7f677.png>

3.       Use a custom filter to filter the levels of region.
[Image removed by sender. image]<https://user-images.githubusercontent.com/21319932/110754595-4ada2a80-8248-11eb-9ab5-1ae2f355ad1a.png>

If you don't want to remove the filter afterward, then option 1 is probably the easiest. We could implement a filter behind the scenes for this, but people might wonder, why only the t-test and not, say, ANOVA? Rather than implementing this individually for all analyses that handle categorical variables, it makes more sense to use one of the three global methods described above to do this (and these methods are also more flexible).

**Comment by vandenman** [comment]
Sure! It is high on our agenda to make these kinds of data manipulations easier and more accessible (e.g., without having to enter R-code), so hopefully in the future, this becomes an acceptable solution.

I'll close this issue now, but if there is anything else, feel free to re-open or open another issue!
