### ISSUE TITLE
JASP vs. SPSS: slightly different result in Hedges' g

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#1210]
* JASP version: 0.14.1
* OS name and version: macOS Big Sur 11.2.3
* Analysis: Independent Samples T-Test
* Bug description: for Hedges' g, JASP 0.14.1 and SPSS 27.0.1 calculate a slightly different 95% CI
* Expected behaviour: JASP and SPSS calculate the same values for the 95% CI of Hedges' g

Steps to reproduce:

1. Open the attached dataset.
          [wiscijfers.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6151759/wiscijfers.jasp.zip)
2. In T-Tests > Classical Independent Samples T-Tests, check "Effect Size", "Hedges' g" and "Confidence interval".
3. JASP 0.14.1 reports a 95% CI of [–0.386; 0.646], whereas SPSS 27.0.1 reports a 95% CI of [–.380;.639].

-- 

<img width="1128" alt="jasp" src="https://user-images.githubusercontent.com/5346286/111366949-76b83e80-8694-11eb-99f9-378a62f903d5.png">

-- 

<img width="1046" alt="spss" src="https://user-images.githubusercontent.com/5346286/111366956-7a4bc580-8694-11eb-9a25-551b90b2f707.png">

**Comment by boutinb** [comment]
@JTPetter Is this analysis in the validation project?

**Comment by JTPetter** [comment]
> @JTPetter Is this analysis in the validation project?

No, not yet!

**Comment by boutinb** [comment]
@vandenman Can you have a look?

**Comment by vandenman** [comment]
Okay I think I figured out where the difference comes from, although I can't really judge whether what SPSS does makes sense...

I also don't have SPSS lying around so perhaps I'm not the right person to test this out.

If you go to ftp://public.dhe.ibm.com/software/analytics/spss/documentation/statistics/27.0/en/client/Manuals/IBM_SPSS_Statistics_Algorithms.pdf

then on page 811 there is 
![image](https://user-images.githubusercontent.com/21319932/111783509-9335c000-88ba-11eb-9b6f-b7c35b683d40.png)

so SPSS computed the CIs for Hedges' g as a function of the confidence intervals for Cohen's d. In contrast, we plug the estimate for Hedges' g directly into a noncentral t-distribution and use the interval obtained from that:

https://github.com/jasp-stats/jaspTTests/blob/6ed7542a957c9f0229fd54a6161e94b2964407a7/R/ttestindependentsamples.R#L336-L343
```r
    if (optionsList$wantsConfidenceEffSize){
      # From MBESS package by Ken Kelley, v4.6
      dfEffSize  <-  ifelse(effSize == "glass", ns[2] - 1, df)
      alphaLevel <- ifelse(direction == "two.sided", 1 - (ciEffSize + 1) / 2, 1 - ciEffSize)
      confIntEffSize <- .confidenceLimitsEffectSizes(ncp = d * sqrt((prod(ns)) / (sum(ns))), 
                                                     df = dfEffSize, alpha.lower = alphaLevel, 
                                                     alpha.upper = alphaLevel)[c(1, 3)]
      confIntEffSize <- unlist(confIntEffSize) * sqrt((sum(ns)) / (prod(ns)))
```
the issue here is that in `.confidenceLimitsEffectSizes(ncp = d * sqrt((prod(ns)) / (sum(ns)))` we're actually passing in Hedges' g. If I pass in Cohen's d and apply the correction from SPSS I do obtain the same results (after rounding).

@AlexanderLyNL any idea whether what SPSS does make sense?

**Comment by AlexanderLyNL** [comment]
What SPSS provides seems to be a [prediction interval](https://en.wikipedia.org/wiki/Prediction_interval) at the estimate. This does not correspond to a test, and would break the duality between confidence intervals and hypothesis tests as described by Bickel and Doksum (2015) Section 4.5, or Casella and Berger (2002) Section 9.2.1. As such the confidence interval of a parameter doesn't change if the estimate changes.

**Comment by tomtomme** [comment]
@djdekker 
Since the difference is now explained, can this issue be closed?

Also jasps t-test help section mentions how the CI is computed off a t-distribution:
"Hedges' g: Applies a correction factor to Cohen's d to make it unbiased.
Confidence interval: Confidence interval for the effect size based on the non-central t-distribution for Cohen's d, Glass' delta and Hedges' g, and normal approximation of the Fisher transformed rank biserial correlation."

Does this suffice? Maybe we could link this issue in the helpfile for people who want a more detailed explanation.

**Comment by djdekker** [comment]
@tomtomme Thank you very much. For me the issue can be closed.
