### ISSUE TITLE
Cohen's D effect size error

### ISSUE THREAD

**Issue by aybukemah** [jasp-stats/jasp-issues#1212]
* JASP version: 0.14.1

* OS name and version: Mac Mojave 10.14.6
* Bug description: I cannot calculate Cohen's D with effect size. It says 'note: computed effect sizes ignore the test value. 
* I need to calculate one sample t-test cohen's d with a specific effect size.
<img width="1269" alt="Ekran Resmi 2021-03-17 18 38 50" src="https://user-images.githubusercontent.com/80841258/111495105-1a1a5980-8750-11eb-9adc-f7b428184d3b.png">

#### Steps to reproduce:
4. See an error

**Comment by vandenman** [comment]
So this box:
![image](https://user-images.githubusercontent.com/21319932/111505809-4ed6e280-8749-11eb-8a6d-1cc9ce82c3f4.png)

displays a *known* bug. This will be fixed in the next version of JASP. So it's not necessary to open an issue when you see this.

If you really need the effect size for a particular value, you could create a new column where you subtract the test value from `SCmean` and then compare against zero.
