### ISSUE TITLE
Descriptive statistic table

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#1219]
Hello!

I suggest a descriptive table that lists all the desired variables, from top to bottom, and not only from left to right, to facilitate reading and analysis. It is especially useful in descriptive statistics.
I attach two screenshots, one from JASP and one from SPSS, to compare and better illustrate the idea.

Maybe JASP already has the option, but I can't find it and I have tried all the options available in descriptive statistics.

![SPSS 01](https://user-images.githubusercontent.com/1270242/111917479-3965ff00-8a4e-11eb-9568-ba1ebf52e91c.jpg)
![JASP 0 14](https://user-images.githubusercontent.com/1270242/111917481-3a972c00-8a4e-11eb-9071-e294abcab715.jpg)

**Comment by vandenman** [comment]
I've added a checkbox:

![image](https://user-images.githubusercontent.com/21319932/111974575-d2088780-8aff-11eb-9fb2-6ed58b7568dc.png)

and when it's checked you obtain the bottom table rather than the top one:

![image](https://user-images.githubusercontent.com/21319932/111973993-59a1c680-8aff-11eb-9fec-1c92069366ee.png)


would that solve the issue?

**Comment by EJWagenmakers** [comment]
That looks awesome to me. I thought this was a good suggestion, it's great that you implemented it so quickly Don!

**Comment by romanogino** [comment]
Dear @vandenman 
Thank you very much! 
Best regards.
