### ISSUE TITLE
error displaying values in correlation matrix

### ISSUE THREAD

**Issue by fischmobbing** [jasp-stats/jasp-issues#1226]
* JASP version: 0.14.1

* OS name and version: Catalina 10.15.7
* Analysis: 
* Bug description: random (?) errors in displaying values in the correlation matrix
* Expected behaviour: exact values
![Bildschirmfoto 2021-03-26 um 09 16 42](https://user-images.githubusercontent.com/81410616/112603613-86aeeb80-8e15-11eb-8f01-8cfb3f3f0ced.png)

**Comment by vandenman** [comment]
A number like `2.964e-4` is scientific notation for `0.0002962`. This is practical because it's decimal notation kinda gets ugly when numbers become very large or very small (e.g., `1.539e-16` is short for `0.0000000000000001539`). See also [Scientific notation](https://en.wikipedia.org/wiki/Scientific_notation).

**Comment by fischmobbing** [comment]
> A number like `2.964e-4` is scientific notation for `0.0002962`. This is practical because it's decimal notation kinda gets ugly when numbers become very large or very small (e.g., `1.539e-16` is short for `0.0000000000000001539`). See also [Scientific notation](https://en.wikipedia.org/wiki/Scientific_notation).

Thanks a lot for your quick help!
