### ISSUE TITLE
Large datasets?

### ISSUE THREAD

**Issue by mspezio** [jasp-stats/jasp-issues#1231]
* JASP version: 0.14.1

* OS name and version: Mac OS 10.15.7
* Analysis: Classical Independent Samples T-Test
* Bug description: T-Test not run on large dataset
* Expected behaviour: T-Test successful

[Data_5_9yearcutoff.csv.zip](https://github.com/jasp-stats/jasp-issues/files/6237427/Data_5_9yearcutoff.csv.zip)

Tried to conduct a T-Test using a large dataset with JASP. See attached image for the variables used.

Problem was no Results returned.

What is the limit on rows in JASP? Thank you.

![Screen Shot 2021-03-31 at 7 49 02 AM](https://user-images.githubusercontent.com/26719547/113164093-a66b5880-91f5-11eb-96e7-4814efae9c86.png)

**Comment by JorisGoosen** [comment]
So the problem here seems to not be the size of your data which, while respectable, is not crazy-large. 
There seems to have been some problem in the analysis somewhere. But I didn't analyse to deeply because I simply tested the scenario out in 0.14.1 (jasp stumbled and got stuck) and a development version of 0.15 (can be downloaded from https://static.jasp-stats.org/Nightlies/ but those are highly experimental!).

In the development version your dataset works fine and the analysis is done in a jiffy. So I consider this issue solved.

You could work with the development version if you are in a hurry with these results, but we haven't gone through the full testing regime yet. We hope to have the next official version ready in 1 or 2 months. If you *do decide* to use a nightly be sure to read the warnings and disclaimers at the top of the nightly download page.
