### ISSUE TITLE
a and b pathways in Mediation not reported

### ISSUE THREAD

**Issue by mjkofler** [jasp-stats/jasp-issues#1237]
In Mediation Analysis (under the SEM menu), some pathways are not reported in the output, specifically:
a pathways (relations between the predictors and the mediators),
b pathways (relations between the mediators and the outcomes controlling for the predictors)

These pathways are of interest - could you please add a table with these results to the output (or add an option so they can be selected to be added to the output)? 

Thanks!

**Comment by Kucharssim** [comment]
Dear @mjkofler,

since 0.16.4 version all path coefficients in the mediation model can be requested so in the output you can find whatever pathway you are interested in (see https://github.com/jasp-stats/jaspSem/pull/95 for reference). I am closing this issue now, please do not hesitate to reopen if this is not what you wanted.
