### ISSUE TITLE
Error in Post-hoc estimation in RM ANOVA?

### ISSUE THREAD

**Issue by mjprioris** [jasp-stats/jasp-issues#1246]
Operating system: OX 10.15.7 CATALINA
JASP version 14

The same problem was note in 
Operating system: windows 10
Jasp version 14.1

I have ran a RM ANOVA in an early version of JASP (I don´t know exactly which, I suppose it was v. 13) an I obtained post-hoc results that matched SPSS results. The following:

<img width="740" alt="Captura de pantalla 2021-04-08 a las 18 34 44" src="https://user-images.githubusercontent.com/41793848/114063936-6cefb880-9899-11eb-824a-ef1c07a07b76.png">

Yet, recently, I have re-ran the analysis with v 14 and 14.1 and the post-hoc results (I check Bongferroni) do not math the ones of previous version or SPPSS, and in some cases differences are huge. This are the results with the new version
<img width="605" alt="Captura de pantalla 2021-04-08 a las 18 34 57" src="https://user-images.githubusercontent.com/41793848/114064068-8c86e100-9899-11eb-9d3f-633ff26f792e.png">

Note that descriptive statistic is the same. I checked the data and everything  seems fine. 

Anybody else noted this?

Thanks in advance

**Comment by JTPetter** [comment]
Hi @mjprioris,
I've looked into this, but I fail to reproduce the issue. When I run the "AlcoholAttitudes" data set from the JASP data library through JASP 0.14.1 and SPSS 26 I get the same results. See here:
![image](https://user-images.githubusercontent.com/61797391/114088677-8e5e9d80-98b5-11eb-92b2-000763457603.png)
![image](https://user-images.githubusercontent.com/61797391/114088930-daa9dd80-98b5-11eb-9cc6-a3f7f0946cb0.png)
![image](https://user-images.githubusercontent.com/61797391/114088963-e39aaf00-98b5-11eb-9958-5e9280c71df8.png)
Where the coding is for drink  1 = beer, 2 = wine, 3 = water and for imagery 1 = pos, 2 = neu, 3 = neg.

Would you mind sharing your data set with us so I can investigate the issue further?

Greetings,
Jonas

**Comment by mjprioris** [comment]
Hi Jonas

Thank you very much for the quick response. 
Please find  attached the database for the previous example. 

I ran the analysis also directly in R and results do not match JASP 14 or  14.1

Here are the results from R 

<img width="612" alt="Captura de pantalla 2021-04-09 a las 12 25 25" src="https://user-images.githubusercontent.com/41793848/114167114-d968c700-992e-11eb-9d92-ca5472cfdf16.png">

[R_depre.xlsx](https://github.com/jasp-stats/jasp-issues/files/6285011/R_depre.xlsx)

Best, 
María J

**Comment by JTPetter** [comment]
Hi María,

thanks for sharing the data set! I was able to reproduce the issue. The difference in results comes about when the option "Pool error terms for RM factors" is checked. This might not have been the default for previous versions of JASP, explaining the difference. 
![image](https://user-images.githubusercontent.com/61797391/114266037-5742d600-99f4-11eb-8a3a-5f87935477d4.png)

Note how the SE for all the levels of time are .703 in your output - this is because the SE is calculated over all levels of time, not individually. This is desired behavior.

If you uncheck this option, the output is the same as in SPSS 26:

![image](https://user-images.githubusercontent.com/61797391/114266100-aab52400-99f4-11eb-91e5-ac063165cfc5.png)
![image](https://user-images.githubusercontent.com/61797391/114266107-bacd0380-99f4-11eb-89e7-9a2f41f6e913.png)

I hope this helped. 

Greetings,
Jonas

**Comment by mjprioris** [comment]
Dear Jonas 

Yes, that was the difference between programs. Thank you very much for your quick and helpful answer. 

Best

María José
