### ISSUE TITLE
File not opening correctly in preferred editor

### ISSUE THREAD

**Issue by clmcd** [jasp-stats/jasp-issues#1253]
* JASP version: 14.1
* OS name and version: Windows 10
* Bug description: I am opening a .jasp file in JASP. It was original a .sav file, which I then saved as .jasp. When I double click to edit, it doesn't know what program to use. I changed my preferred editor in Preferences to Excel. However, when the file opens in Excel, it appears to be a .sav file and doesn't display properly. 
* Expected behaviour: I'd like to be able to edit the data in Excel, even if it's a .sav file or if it's a .jasp converted from a .sav
* 
* <img width="673" alt="JASP excel" src="https://user-images.githubusercontent.com/82574651/114840352-13980400-9e1a-11eb-8cec-87e36c6ed1b3.PNG">

**Comment by boutinb** [comment]
Hi @boutinb JASP still knows that the source file was a sav file, and when you double-click the Data View, it tries to open this sav file. As apparently you don't have SPSS, it cannot open the file. The best you can do is to export the data (with the Export Data menu) to csv file, and then afterwards synchronize JASP with this csv file (with Sync Data menu).
We are aware that this situation is not really user-friendly and we have changed this behaviour (for the next JASP version), so that when you double-click on the Data View, and JASP sees that SPSS does not start, then it asks you to generated a csv file and to synchronize automatically JASP to this file.

**Comment by clmcd** [comment]
Thank you - that will be a helpful feature.
I did set my preferred editor to Excel, though, and it opens in Excel - I'm just curious about why it's not opening properly. 
I was having issues when exporting to CSV, but I can now see that re-saving as a .jasp file from CSV seems to work - thanks!
