### ISSUE TITLE
Vector format export of fails

### ISSUE THREAD

**Issue by ndpegram** [jasp-stats/jasp-issues#1255]
* JASP version: 0.14.3
* OS name and version: Linux, Ubuntu 20.04 LTS
* Analysis: Graphic export error
* Bug description: When trying to export a scree plot to EPS, PDF or SVG, an error dialog appears with the message, "'x' is a list, but does not have components 'x' and 'y'". Note, the same plot exports successfully to PNG.
* Expected behaviour: Successful export.

#### Steps to reproduce:
Select a confirmatory factor analysis report with an associate scree plot.
Select "save image as" from the "Model plot" menu.
Select one of the above three vector graphics formats
Give the plot a name and click on save.
Error message appears.

Please note the file is private data and provided only for debugging purposes.
*file removed by vandenman*

**Comment by vandenman** [comment]
@ndpegram Thanks for reporting this issue! I can replicate it on Ubuntu as well. 

> Please note the file is private data and provided only for debugging purposes.

Note that this forum is *public*, so I've removed your upload and added my own which uses our dummy data set:

[cfa_pdf_export_fails.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6323163/cfa_pdf_export_fails.jasp.zip)
(rename and drop .zip)

It does look like the issue is fixed already in our current development version.

**Comment by ndpegram** [comment]
Great, thanks
