### ISSUE TITLE
Error resizing plot

### ISSUE THREAD

**Issue by Zntznkv** [jasp-stats/jasp-issues#1263]
* JASP version: 0.14.1.0

* OS name and version: Windows 64-bit, 20H2
* Analysis: Descriptives
* Bug description: ERROR RESIZING PLOT, no plot object was found
* Expected behaviour: Can't see the whole plot, or graph seems to be cutted off (for example can't be seen whole legend, it's cutted).. I tried to resize the plot but error pops up every time
* UPDATE: I ran it again and I'm able to resized, but problem persists, Graph is cutted off
* 
![ErrorJasp](https://user-images.githubusercontent.com/56439115/115616671-c1ab1e80-a2f0-11eb-98a9-8e0105527214.png)

**Comment by boutinb** [comment]
I think this problem will be solved in 0.15 with plot editing. But maybe can @vandenman better answer.

**Comment by vandenman** [comment]
Hi @Zntznkv and thanks for reporting the issue!

Would it be possible to share the .jasp file that causes an error upon resizing? That way I can verify whether this will be solved in the next release.

If yes, you can either attach the jasp file as a zip file to this issue (note that this is a public forum) or send it to me at d.vandenbergh <at> jasp-stats.org (in that case I'll delete the data set once the issue is resolved).
