### ISSUE TITLE
Is there a way to display the correlations among the latent variables?

### ISSUE THREAD

**Issue by krutcher7069** [jasp-stats/jasp-issues#1275]
* JASP version: 0.14.1

* OS name and version: Windows
* Analysis: SEM
* Bug description: After having run the analysis, I scanned the output but couldn't find any table that contains the correlations among the latent variables
* Expected behaviour: I expected to find a table that contains the correlations among the latent variables

#### Steps to reproduce:
1. Go to SEM and then select Structural Equation Modeling
2. Enter the following syntax

stressor =~ Language + Culture + Academic + SocialInter
support =~ Socio + Instrument
strat_h =~ Heritage
strat_t =~ Thai
well =~ Creative + Coping + Social + Essential + Physical

well ~ strat_h + strat_t
strat_h ~ support + stressor 
strat_t ~ support + stressor

Socio ~~ Instrument
Heritage ~~ Essential
Thai ~~ Essential
Language ~~ Culture
Culture ~~ Essential
SocialInter ~~ Socio
Instrument ~~ Coping
SocialInter ~~ Creative
Socio ~~ Social
Instrument ~~ Social

3. Select the following options

![image](https://user-images.githubusercontent.com/67669189/116691473-0c115700-a9e5-11eb-9c38-a4b43d43d3d5.png)
![image](https://user-images.githubusercontent.com/67669189/116691539-1f242700-a9e5-11eb-8b1b-783d22265672.png)

4. That's all! Thank you very much for looking into this for me!

**Comment by JMBKoch** [comment]
@krutcher7069 This is very much possible! A correlation is nothing than a standardized covariance. So, in order to display the latent correlations you need to look into the standardized model output. See this example where I fit a CFA model with the well-known Holzinger Swineford data from lavaan. 

![exampleLvCor0](https://user-images.githubusercontent.com/67152739/132673126-048d61c6-447c-4f3b-8a0b-c1f6a573e4dd.png)

Here, it's thus crucial to check "Standardized estimates" .

![exampleLvCor05](https://user-images.githubusercontent.com/67152739/132673261-b3e55437-1690-417c-bf14-e6d21d64fd74.png)

Then, in the output under covariances, you can find the correlations in the column LV (second from the right). 
![exampleLvCorr1](https://user-images.githubusercontent.com/67152739/132673362-ddaad549-a031-4e60-b2af-e202d35c829d.png)
