### ISSUE TITLE
Effect sizes in post hoc tests for mixed ANOVAs

### ISSUE THREAD

**Issue by jaume-masip** [jasp-stats/jasp-issues#1303]
* JASP version: 0.14.1

* OS name and version: macOS Big Sur Version 11.3.1
* Analysis: Classical Repeated Measures Anova - Post Hoc Tests for Intra x Inter interaction - "Effect size" selected
* Bug description: Effect sizes for pairwise comparisons not displayed in table in output. Selecting/unselecting "effect size" makes no difference. But the function works for main effect. It also worked for this interaction in earlier JASP version.
* Expected behaviour: Effect sizes to be displayed in output.

#### Steps to reproduce:

1. Run mixed ANOVA (i conducted an Intra1 (2 levels) x Intra 2 (2 levels) x Inter (2 levels) ANOVA)
2. Go to 'Post Hoc Tests'
3. Move Intra x Inter to the box on the right
4. Click on 'Effect size'
5. Scroll down to 'Post-Hoc tests' in Results section
6
[Captura de pantalla 2021-05-20 a las 15.10.18.png.zip](https://github.com/jasp-stats/jasp-issues/files/6516153/Captura.de.pantalla.2021-05-20.a.las.15.10.18.png.zip)
. See error

**Comment by RenzoLanfranco** [comment]
I'm having the same issue but with RM ANOVAs. I think there's a glitch in the calculation of the effect sizes of each pairwise comparison. The Cohen's d scores aren't shown.

**Comment by boutinb** [comment]
Hi @JohnnyDoorn Can you have a look at this issue?

**Comment by JohnnyDoorn** [comment]
Hi @jaume-masip,

I removed the computation for effect sizes since I believed they were not correct, and wanted to err on the side of caution since it is not straightforward to compute effect sizes for interaction effects. We are currently sorting this out, and hopefully we will add proper effect size measures for interactions in the next version of JASP (after 0.15). Apologies for the inconvenience.

Kind regards
Johnny

**Comment by juliuspf** [comment]
Due to some tricky wording this wasn't closed through https://github.com/jasp-stats/jaspAnova/pull/90, but it should have been
