### ISSUE TITLE
JASP won´t open my file 

### ISSUE THREAD

**Issue by PBB-code** [jasp-stats/jasp-issues#1315]
* JASP version: 0.14.1

* OS name and version: Windows 10
* Analysis: 
* Bug description: For a couple of days now I have problems to open a jasp file that I have been working on for the last weeks. I did some correlations and some regressional analysis, and never had problems to open my file. Now, it takes several minutes for JASP to open it, and since today it can´t be opened at all. Kind regards
* Expected behaviour:

**Comment by vandenman** [comment]
Hi @PBB-code, would it be possible to share the jasp file somehow so we can look into this? You can upload the file in this issue as a zip file (but note that this is a public forum) or email it to me directly at d.vandenbergh at jasp-stats.org

**Comment by PBB-code** [comment]
Hi, thanks for the fast reply. I´m going to ask my lecturer if it is fine with her to send you my file. Kind regards

**Comment by hynekcigler** [comment]
Hi, I have been having very similar problem for about one year. If I double-click on the JASP file, nothing happens. I have to open JASP software and then use menu/open/... This is really annoying and it does not happen to me only, my colleagues and students have (sometimes) the similar experiences. I have Win 10.

**Comment by vandenman** [comment]
@hynekcigler, could you perhaps share the JASP file? While we can understand that this behavior is not very pleasant, we can do very little to solve it if we cannot replicate the problem.

**Comment by boutinb** [comment]
Hi @hynekcigler There is maybe something wrong during the installation of JASP, so that the .jasp files do not get the right default associated application (JASP). We will have a look, but just to check: can you set this association manually (http://www.rawinfopages.com/tips/2014/11/change-the-default-programs-for-file-types-in-windows-8/), and tell us if it works?

**Comment by hynekcigler** [comment]
> Hi @hynekcigler There is maybe something wrong during the installation of JASP, so that the .jasp files do not get the right default associated application (JASP). We will have a look, but just to check: can you set this association manually (http://www.rawinfopages.com/tips/2014/11/change-the-default-programs-for-file-types-in-windows-8/), and tell us if it works?

Thanks @boutinb. I tried some time ago, but I have tried once more. I see the JASP icon, but without an app name (which is strange). Unfortunately, there is not any option to brows a disk (Citing from the page you linked: "Unfortunately, there is no option to browse the disk and select any app you want. You can only select from the list. However, if you scroll right down to the bottom, there is an option to search the Windows Store for a suitable app. It is not ideal, but we are stuck with this small list."). Searching on Windows Store did not help :)
![image](https://user-images.githubusercontent.com/20371612/120439375-bed92a00-c382-11eb-9e82-9c9b490c756e.png)

**Comment by romanogino** [comment]
I have the same issue: if I double-click on the JASP file, nothing happens. I have to open JASP software and then use menu/open/...  and believe that .jasp files do not get the right default associated application (JASP 0.14.0). 
![2021-06-05_105327](https://user-images.githubusercontent.com/1270242/120897611-a79d7500-c5ec-11eb-94ca-de24888cd713.jpg)

I could upload my data files, but I believe that the problem is around installation.

I remember that JASP is an excellent program and the detail described is intended to improve quality.
Best regards.
r.

**Comment by boutinb** [comment]
On my PC (Windows 10), if I right-click on a file in Explorer, select Properties, and click the 'Open with' button, I get at the bottom of the list the possibility to select an application on my PC (Look for another app on this PC): 
![searchapp](https://user-images.githubusercontent.com/503332/121189279-3d920380-c86a-11eb-9550-6bf9416f3fbe.png)

If I then set it for one jasp file, then all jasp file will then open with JASP.

**Comment by hynekcigler** [comment]
@boutinb Hi, thank you. However, I have tried, but it does not work. I choose JASP app, but nothing happen. Anyway, at my PC, association is the same is @romanogino described above.

**Comment by boutinb** [comment]
That is quite strange you don't have the possibility to change the default app with an app on your PC. Maybe @JorisGoosen has an idea why? And also why the setup does not set this association automatically?

**Comment by hynekcigler** [comment]
@boutinb It works for all the other files, but not for JASP files.

**Comment by JorisGoosen** [comment]
Well, I honestly wouldn't know if it even works on my system as I never use this way of starting JASP.

Quite possibly something goes wrong in the installer, the way to set that up is a bit opaque.

First of all though the original issue here by @PBB-code was about a file that could be opened before and now no longer could be opened.
While @hynekcigler 's issue is that he cannot open a jasp-file by double-clicking it. I see from the screenshot that it is running in some other locale (looks slavic) and it is quite possible that something goes wrong because of that.

However, I would suggest keeping things ordered and not have these two issues at the same time. @hynekcigler could you open a new issue for your problem?

That way @PBB-code can communicate with @vandenman through this issue and we do not muddle things.
