### ISSUE TITLE
I converted the menu to Japanese 

### ISSUE THREAD

**Issue by ko-ynu** [jasp-stats/jasp-issues#1316]
* Enhancement:Japanese Translation
* Purpose:I want you to take in  my translations
* Use-case: For japanese student and my student
[jasp_ja.zip](https://github.com/jasp-stats/jasp-issues/files/6568558/jasp_ja.zip)

**Comment by boutinb** [comment]
Dear @ko-ynu, how did you generate this file? We use since some months WebLate (https://weblate.org/) to translate JASP. We use such a site since different people around the world are translating JASP and we need a way to coordinate this. We have written also a guide how to use WebLate to translate JASP (https://github.com/jasp-stats/jasp-desktop/blob/development/Docs/development/jasp-guideline-translators.md)
Several people have already translated some parts of JASP in Japanese. I can see from your file that you have made a lot of work and have made translations also in other parts of JASP. But it would be quite difficult to merge your file with the current ones (there are now different translation file for each module).
So which tool did you use, and would it be possible to use WebLate instead?

**Comment by ko-ynu** [comment]
Dear Team,

Thank you for your reply.
I have already translated some words on that system.
However, I found it very laborious to convert over 4000 words.
It takes time, but I try to translate little by little.

Best regard,

**Comment by EJWagenmakers** [comment]
Dear @ko-ynu, 

Thanks for your translations. I realize that the Weblate "surprise" leads to additional work. We are grateful for anything you can do. Please note that the Weblate system should allow a much more efficient translation for future versions. Also, it may be a good idea to get into contact with the other Japanese translators, in order to distribute the workload.
Your efforts are really appreciated, and we are looking forward to a complete Japanese version of JASP!
 
Cheers,
E.J.

**Comment by shun2wang** [comment]
Now that all translations are hosted on [Weblate](https://hosted.weblate.org/projects/jasp/) and the author of this issue has contributed to the translations (@ko-ynu thanks for your efforts!).

So we can close it for now.
