### ISSUE TITLE
JASP Known Bug: Computed Effect Sizes Ignore the Test Value

### ISSUE THREAD

**Issue by vickyyytoriaaa** [jasp-stats/jasp-issues#1329]
* JASP version: 0.14.1

* OS name and version: MacOS Catalina & BigSur 
* Analysis: 
* Bug description: *Known Bug: Computed Effect Sizes Ignore the Test Value* 
<img width="636" alt="Screenshot 2021-06-09 at 10 46 10 AM" src="https://user-images.githubusercontent.com/85597585/121284743-ea728c00-c90f-11eb-963a-37c1d0ecd812.png">

* Expected behaviour:

**Comment by vandenman** [comment]
So this box:
![image](https://user-images.githubusercontent.com/21319932/111505809-4ed6e280-8749-11eb-8a6d-1cc9ce82c3f4.png)

displays a *known* bug. This will be fixed in the next version of JASP, so it's not necessary to open an issue when you see this.

If you really need the effect size for a particular value, you could create a new column where you subtract the test value from `SCmean` and then compare against zero.
