### ISSUE TITLE
JASP on Chromebook

### ISSUE THREAD

**Issue by boutinb** [jasp-stats/jasp-issues#134]
## Template for enhancement requests
 
* Enhancement: Build JASP on Chrome OS with Native Client 
* Purpose: Qt Applications like JASP may be able built for Chrome OS (https://wiki.qt.io/Qt_for_Google_Native_Client), and then be available for Chromebooks.

**Comment by AlexanderLyNL** [comment]
rollApp:

https://www.rollapp.com/app/jasp

**Comment by JorisGoosen** [comment]
See this manual: https://flatpak.org/setup/Chrome%20OS/

Apparently it is possible to actually run flatpak on chromebook. So that would be nice. Not all chromebooks seem to be supported but at least all from 2019 onwards.
And quite a lot from before if I can believe the lists linked there.

Now I just need someone with a (compatible) chromebook to actually test this.

**Comment by JorisGoosen** [comment]
Ok I've tested this on an x86 and an aarch64 chromebook and it works fine in both cases. And Ive heard back from several users that it works. So this issue can be closed.
