### ISSUE TITLE
data layout in network analysis

### ISSUE THREAD

**Issue by agnesegattone** [jasp-stats/jasp-issues#1366]
[pre+post.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/6891103/pre%2Bpost.jasp.zip)

* JASP version: 0.14.1

* OS name and version: MacOS Big Sur
* Analysis: Network Analysis
* Bug description: This analysis is terminated unexpectedly.
Error in if curve (curve[I] = 0 & !XKCD & knots[I] = 0) {: missing value where TRUE/FALSE needed 
* Expected behaviour: The network plot of the second network should obtain the layout of the first network.

Steps to reproduce:
1. Go to 'network analysis' 
2. Click on 'graphical options'
3. Scroll down to 'layout' and click on 'data'

**It does not allow uploading of JASP file**

**Comment by vandenman** [comment]
hi @agnesegattone in order to upload a jasp file here, you either need to zip the file, or change the extension of the file to .zip. It would be very helpful if you could upload the file, as otherwise, it will be difficult to debug this issue.

**Comment by agnesegattone** [comment]
Hi @vandenman, thanks for the tip! I just added the data as a zip file.

**Comment by boutinb** [comment]
@vandenman Could you check this issue with the file sent by @agnesegattone ?

**Comment by vandenman** [comment]
Hi so I looked a bit deeper into this and the reason this fails is that your column names are called differently in the pre and post analyses (e.g., Income_T0 vs Income_T3). When exporting the layout, we add the names like so:
![image](https://user-images.githubusercontent.com/21319932/134654752-7caff7c2-ff14-4656-b722-07b632ad313f.png)

The reason we add the names, is that if you'd want to reuse the layout you'd need to enter the variables in the exact same order (otherwise the nodes get swapped). I wrote a warning message for this situation, but unfortunately there was an error there. In the updates I'll add soon, you'd get this output (a footnote and a circle layout) instead:
![image](https://user-images.githubusercontent.com/21319932/134656809-4e5b63ca-7f13-449b-9b8b-fecdb7fdc478.png)


A solution is to transform the data into long format, so that there is one column that indicates `T0`, `T1`, etc. That way, you can use the `Split` variable to create multiple networks side-by-side (which automatically have the same layout).
