### ISSUE TITLE
Error when Adding Interaction effect to Bayesian RM ANOVA

### ISSUE THREAD

**Issue by GregBorghi** [jasp-stats/jasp-issues#1376]
* JASP version: 0.14.1
* OS name and version: Windows 10
* Analysis: Bayesian RM ANOVA
* Bug description: when running a 2-way (2x2) ANOVA with 1 between subject factor with 2 levels and 2 covariates the moment I add the Cortisol covariate in the interaction terms the analysis present this error --> "Error in array(0, dim = c(steps, nparam, 2), dimnames = list(NULL, names(weightedMeans), : length of 'dimnames' [2] not equal to array extent"
However, the cortisol variable vector should have the same length as the other variables, and indeed when I run the same analysis with Testosterone instead, the analysis works perfectly fine.
* Expected behaviour: it should present the table with the "effects across all models" but that does not succeed.

#### Steps to reproduce:
1. Go to 'Bayesian RM ANOVA'
2. Click on 'RM factors', add all the RM factors and between subject factor and 2 covariate
3. Scroll down to 'Tables'
4. Click 'Effects'
5. Scroll drown to Model
6. Press key "ctrl" + click on "cortisol, gender, valence, response'
7. Click on the "adding arrow"
8. wait for the entire loading time
4. See error: "Error in array(0, dim = c(steps, nparam, 2), dimnames = list(NULL, names(weightedMeans), : length of 'dimnames' [2] not equal to array extent"

[Behavioural_Accuracy_Bayes_Analysis.zip](https://github.com/jasp-stats/jasp-issues/files/6933383/Behavioural_Accuracy_Bayes_Analysis.zip)

**Comment by vandenman** [comment]
Thanks for reporting this issue! Luckily, I could not replicate it in our current development version (I recently fixed a bug similar to this one and it seems like it also solved your issue). If you'd like, you can use a nightly version (available at https://static.jasp-stats.org/Nightlies/), but there should also be a new release in a month or so that contains the fixed version.

As in #1375, there are a large number of interactions effects specified under `Model`. This certainly increases the computation time so if you're not particularly interested in those you may want to remove them.

**Comment by juliuspf** [comment]
@GregBorghi can you confirm the issue is fixed, and subsequently close the issue?
