### ISSUE TITLE
JASP won't open after install

### ISSUE THREAD

**Issue by kriscoul** [jasp-stats/jasp-issues#1381]
* JASP version: 0.14.1

* OS name and version: MacOS Big Sur version 11.4
* Bug description: When I try to open JASP after installing it, JASP does not open and I get an error message saying "JASP quit unexpectedly". I've tried reinstalling and still get the same issue. Please advise.

**Comment by JorisGoosen** [comment]
Hello @kriscoul 

Well, I also run Big Sur 11.4 and it does work for me...

Maybe you could try one of our development versions: https://static.jasp-stats.org/Nightlies/MacOS/JASP-nightly-development-6f00996c6355ebf73012dc7685ed7d43db924a6f.dmg

I wouldn't recommend using it to heavily, but it is roughly the upcoming version and we are running tests now. Would be good to know whether it works or not.
Keep in mind this one is not "signed" so that MacOS will complain, but once you've installed it be sure to open it by right-clicking with your mouse and opening it through the menu. Otherwise MacOS will just suggest deleting it.
