### ISSUE TITLE
jasp won't open

### ISSUE THREAD

**Issue by katelyn8401** [jasp-stats/jasp-issues#1385]
I downloaded the jasp application and I have Mac Catalina. I clicked on that and it downloaded just fine. I went to open the disc on my home screen and it opened and had the jasp with an arrow pointing to the applications folder. However, I went to double click on the jasp application and then it did warn me that this was an internet application and I pressed open and then the app just disappeared from my task bar and did not open. I need this application for school this semester so I am freaking out a little bit. I did download the quartz application and that downloaded just fine. Even when my computer said the jasp was in my applications folder it was not there. Please help me!

**Comment by boutinb** [comment]
Hi @katelyn8401, sorry for the late answer.
Just to be sure, did you download the Catalina & Big Sur Mac OS version (the name of the dmg file should be JASP-0.14.1.0-postMojave.dmg)? Then did you drag the JASP icon to the Application icon? This is in order to copy it to the application folder, if not it will stay in an 'image' that can be easily removed. If you did copy JASP to the Application folder, it should not disappear, even if starting JASP does not work...
