### ISSUE TITLE
ifElse broken in compute column point-and-click interface

### ISSUE THREAD

**Issue by AlexanderLyNL** [jasp-stats/jasp-issues#1430]
**JASP version:**
0.15

**OS name and version:**
macOS 11.5 and Windows 10

**Analysis: **
Compute column click interface

**Bug description:**
- Originally reported here https://forum.cogsci.nl/discussion/5671/ifelse#latest
- Compute column ifElse broken.
- Data type not read correctly it seems

https://www.dropbox.com/s/98kycsztqoppm6p/ifElseBrokenComputeColumn.jasp?dl=0

**Expected behaviour:**
- The same behaviour as the R code, see compute column temp2

**Comment by paulamarentette** [comment]
Still hoping for this to be solved. I am not au fait with how stuff gets entered here, but I have a larger scale test of this:
In a class of 14 stats tutors, 4 experienced this error. It does occur across platforms and mysteriously using an identical data set. 
In a class of 250 intro stats students, so far I have 3 error reports. Not all will report (they just get frustrated and stop trying). I'm trying to collect some more accurate error rate info from our class Discord, but it is end of term, we'll see if they are even reading that.
Thanks
Paula Marentette

[IfElse_Errormessage_dataset.zip](https://github.com/jasp-stats/jasp-issues/files/8444014/IfElse_Errormessage_dataset.zip)

**Comment by tomtomme** [comment]
for me this was solved in version 0.16.1 on manjaro (linux)

**Comment by Kucharssim** [comment]
There used to be a bug in that the S3 methods were not exported properly - this has been fixed by @vandenman (https://github.com/jasp-stats/jaspBase/commit/75c30c178831d0ba098b65dc28bc2691ef313948) and should indeed work in 0.16.1. So in case this does not work for some people on 0.16.1, we would probably need some more details (I also cannot reproduce it).

Note that you need to be careful about the column type. For example, if you create a "scale" column using drag and drop, then

```
ifElse(variable < 0, negative, positive)
```
would not work, because JASP expects the output of the `ifElse` function be a number. That's the one thing where things could have gone wrong that I can think of at the moment (perhaps we could return some nice error message if that's the case).

**Comment by tomtomme** [comment]
To make it more clear (at least for me)

This should work with nominal:
ifElse(variable < 0, negative, positive)

This should work with ordinal:
ifElse(variable < 0, -1, 1)

This should work with scale:
ifElse(variable < 0, -0.1, 0.1)

Right?

Yeah some hints for the user in this direction through error messages would be highly appreciated! This has already caused some confusion with colleaugues and students, because it is not obvious what JASP expects nomi, ordi, scale to be.

**Comment by paulamarentette** [comment]
I see this student was trying to make a new scale variable with this command. 
Someone wrote that JASP expects output of IfElse to be a number. 
I will get my students to try this.

Here is an example of the identical error when a different student was trying to create a **nominal variable.** 
The command appears accurate to me:
IFElse (variable ≥ median(Variable), more, less))
Minimally it would be helpful to have an error message that was friendlier (ideally to my very naive students, but at least to me since I am their unwilling tech support).

Here is the trouble: 
For most of my students the words do work! The trouble for me is the inconsistency of this error. Most of the time it works but not always. I know inconsistent errors are a bear to fix, but I was hoping the error message would a true JASPer figure out what happened!


![IfElse Error Nominal](https://user-images.githubusercontent.com/48217084/162485504-6a4ad18a-4119-44cf-acc9-345338763d12.jpg)
)

**Comment by paulamarentette** [comment]
Also, if I need to provide more information I need to know exactly what information to provide. Trust me it is hard to get this stuff out of most undergraduates.

**Comment by Kucharssim** [comment]
Dear @paulamarentette,

sorry for the tardy response.  The error message in the screenshot is consistent with the bug that was fixed for release 0.16.1, so it is indeed strange that it would appear for version 0.16.1 and above. I also fail to reproduce it using your example on 0.16.1, 0.16.2, 0.16.3, and 0.16.4 version (at least on a Mac, that is). 

Please if you encounter the error again, could you save the .jasp file, zip it, and attach it here to this GitHub post? I am afraid I cannot do much more than that atm about this error unfortunately.
