### ISSUE TITLE
Suggestion: Add Mixed Multilevel Models - Linear and Generalized

### ISSUE THREAD

**Issue by melindahiggins2000** [jasp-stats/jasp-issues#15]
In addition to RM-ANOVA, it would be great to also have the ability to run Multilevel (aka. nested, mixed, hierarchical (HLM)) linear models (MLM) and generalized linear model (GzMLM) options (e.g. poisson, binomial, gamma with various link functions: log, logit, etc). I almost never use RM-ANOVA but use MLM and GzMLM all the time in SPSS (as well as SAS and R). Thank you for your great work on JASP so far!! We're seriously considering it as a replacement to SPSS in the future!

**Comment by Farscape1** [comment]
I would like to BUMP this  feature too. Love using JASP and teaching it but lack of mixed models (both Inferential and Bayesian) hinders using it for full blown analyses.

**Comment by jenlissemore** [comment]
I would also like to push this feature. Often ANOVA isn't flexible enough to cover all analyses. As an example, I recently used a linear mixed effects model (lmer in R) because I had a time-varying covariate, which could not be included in a repeated measures ANOVA. JASP would benefit from the inclusion of linear mixed models, ideally with a Bayesian equivalent (lmBF in R).

**Comment by farscape11** [comment]
Any updated on the linear mixed effects models. Would love to see this feature and it would make JASP complete for our stat teaching purposes.

**Comment by EJWagenmakers** [comment]
It's in the upcoming release, a few weeks away!

**Comment by jdebeer2005** [comment]
Please include this enhancement.  I need a GLM feature.

**Comment by jdebeer2005** [comment]
I hope this request is for categorical independent variables in the regression module.  I vote it moves up on the list.  I could use it today.
