### ISSUE TITLE
[Feature Request]: Quality control module-Six Sigma Tools for Quality and Process Improvement

### ISSUE THREAD

**Issue by icekylin** [jasp-stats/jasp-issues#1501]
### Description

Thank you for your great work. I have seen quality control modules in some nightly builds of JASP, but I don't know why it was not released in the end. Could you please add modules for Quality Control at some point, including Six Sigma etc.

### Purpose

Complete reliability and quality control analysis module

### Describe alternatives that you have considered

Here are some open source references for R packages：https://cran.r-project.org/web/packages/SixSigma/index.html

**Comment by EJWagenmakers** [comment]
Yes, have have this under development. We are about to have a new release (0.16), but it looks as if the six sigma tools will be in the next one. We might to a special nightly dedicated to the six sigma tools at some point. I'm closing this now because this is one of our main priorities at the moment.
