### ISSUE TITLE
[Bug]: The function that turns variables into Z-scores in the compute columns interface creates a column with empty cells and provides an error message (included in body)

### ISSUE THREAD

**Issue by Zwildin** [jasp-stats/jasp-issues#1561]
### JASP Version

0.16

### What analysis are you seeing the problem on?

compute columns interface

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I just downloaded JASP 0.16. Whenever I try to convert a variable into Z-scores, no matter which data file I use, it does not work and provides me with the following error message: 

> Error: no applicable method for 'zScores' applied to an object of class "c('double', 'numeric')"
> tryCatch(suppressWarnings({

Please let me know if there is anything I can do to fix this. Thanks!

Here is a screenshot incase this would be helpful
![image](https://user-images.githubusercontent.com/96878360/147765833-7d8b6a97-b404-4350-8f55-8fb1a6b109e0.png)

### Expected Behaviour

I would expect this function to create column in which the original columns' scores are transformed into Z-scores. I am able to accomplish this when I type in the R-code manually, but it would be much quicker using the drag and drop function. 

Screen shot:
![image](https://user-images.githubusercontent.com/96878360/147766417-5151ac19-bf6e-4f6e-89f4-de93eef202df.png)

### Steps to Reproduce

1.  Click on 'add computed column'
2.  Scroll down to select 'Zscores(y)'
3.  Drag and drop variable into parentheses next to the Zscores(y) command
4.  Click 'compute column'

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by vandenman** [comment]
Thanks for reporting this!

This problem has also been reported in https://github.com/jasp-stats/jasp-issues/issues/1507 and is now fixed in the development version of JASP. The next version of JASP should no longer have this problem, therefore I will close this issue now (but feel free to reopen if this is not the case!).

@JorisGoosen is it possible to add this to the list of known issues? I'm not sure if issues in the filter/ computed columns are supported.
