### ISSUE TITLE
Interactions between covariates in Bayesian and classic ANOVA

### ISSUE THREAD

**Issue by Maland18** [jasp-stats/jasp-issues#163]
## Template for bug reports

* JASP version: 0.8.6
* OS name and version:
* Analysis: ANCOVA and Bayesian ANCOVA
* Steps to reproduce: Add DV; add fixed factors (I had one) and  list of covariates (I had 6)

## Template for enhancement requests
 
* Enhancement:The classic ANCOVA includes covariates as main effects, whereas the Bayesian version accounts for all possible interactions between covariates which makes analyses difficult to compare. How can I include interactions into the classical ANCOVA (apart from doing it manually) and vice versa have only main effects in the Bayesian version?
* Purpose: Make analyses comparable

**Comment by JohnnyDoorn** [comment]
Dear Maland,
There is a difference in the way the results are shown. For the Bayesian ANOVA, the table lists Bayesian results for each of the models that are specified, based on the variables selected in the "model" tab. All possible permutations are then run, and the results presented, _per model_.

However, if you want the results to be a bit more like the frequentist results, you can tick the "Effects" box in the Bayesian AN(C)OVA to get a table with Bayesian results for each of the variables that were selected in the "model" tab. Now you have a result for each effect, rather than for each possible model. It is important to keep in mind though, that the "effects" table results are based on all possible models, and not just the full model (like in the frequentist table).

We like to keep the interactions of the covariates in the ANCOVA to be manually specified and not automatically added, while we do automatically include interactions between factors. 
As of the current version (0.9.1), this is the case for both the Bayesian and frequentist ANCOVA. 

Please reopen this issue if you have any further questions! 
Kind regards,
Johnny
