### ISSUE TITLE
[Feature Request]: Additional statistics for the regression module

### ISSUE THREAD

**Issue by gtobin26** [jasp-stats/jasp-issues#1637]
### Description

The regression module is quite good but lacks some important features. The first, and most important, is the absence of an Omnibus ANOVA. Second, although the program provides statistical data on categorical variable, the comparisons are fixed, with the first group providing the reference level. Finally, of lesser importance is the absence of the often-used measures AIC and BIC.

### Purpose

To add important statistical analyses to allow the regression model to be a standalone program.

### Use-case

N/A

### Is your feature request related to a problem?

No, except in the sense that alternative sources are needed for the full regression analysis.

### Describe the solution you would like

Add options for Omnibus ANOVA, selection of the reference group/level for categorical analysis, and AIC and BIC

### Describe alternatives that you have considered

Other software packages

**Comment by juliuspf** [comment]
Hi @gtobin26. thank you for the request, and I apologize for the late reply. Let me ask one of our module maintainers for additional help. @Kucharssim, do you know if this is feasible and who could take this up?

**Comment by Kucharssim** [comment]
Dear @gtobin26,

1. Could you clarify what you are missing regarding the omnibus test? JASP already reports the ANOVA F test for the model (it's the second table in the regression output titled "ANOVA"). Or did I misinterpret your request?

2. The first level of a categorical predictor is indeed used as a reference category in the model. In order to change the reference category, you can reorder the category levels in the data viewer. See [this gif](https://jasp-stats.org/wp-content/uploads/2018/01/LabelEditing.gif) for an example of how to enter the menu for reordering the category levels. 

3. Adding AIC and BIC sounds quite reasonable to me and I agree it would be a good addition! We can add them in the model summary table.

**Comment by gtobin26** [comment]
Hi Julius, the layout is given in ANOVA in the R lm package. It includes an option for each of the thee types, I, II, and III.

**Comment by tomtomme** [comment]
@gtobin26 
BIC AIC now available via nightlies: https://github.com/jasp-stats/jaspRegression/pull/296
