### ISSUE TITLE
[Bug]: Application stops responding when filtering data

### ISSUE THREAD

**Issue by flamingodancer** [jasp-stats/jasp-issues#1644]
### JASP Version

0.16

### What analysis are you seeing the problem on?

Filtering data in my sheet

### What OS are you seeing the problem on?

mac OS big sur 11.6

### Bug Description

I need to filter my data to perform simple effects. Sometimes I can successfully filter but frequently I will filter only women for example and JASP will show the loading icon on my cursor for over 10 seconds and then when I right click the app icon on my Mac doc it says the application has stopped responding and recommends me to force quit JASP.

I am using a data sheet with 400 participants and currently have about 20 analyses open. I also leave the application open because I am working on a long-term data project. Unfortunately I cannot share the data I am using as I have collected it for a study and do not have permission to use it for other purposes.

### Expected Behaviour

I should be able to filter the data without the application failing to respond.

### Steps to Reproduce

1. Open a data sheet
2. Click a variable to filter it
3. After changing the filters a few times JASP crashes
...

### Log (if any)

[JASP 2022-03-03 16_24_50 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/8183358/JASP.2022-03-03.16_24_50.Engine.1.log)
[JASP 2022-03-03 16_24_50 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/8183359/JASP.2022-03-03.16_24_50.Engine.2.log)
[JASP 2022-03-03 16_24_50 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/8183360/JASP.2022-03-03.16_24_50.Engine.3.log)
[JASP 2022-03-03 16_24_50 Engine 4.log](https://github.com/jasp-stats/jasp-issues/files/8183361/JASP.2022-03-03.16_24_50.Engine.4.log)
[JASP 2022-03-03 20_03_16 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/8183362/JASP.2022-03-03.20_03_16.Desktop.log)
[JASP 2022-03-03 20_03_16 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/8183363/JASP.2022-03-03.20_03_16.Engine.0.log)
[JASP 2022-03-03 20_03_16 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/8183364/JASP.2022-03-03.20_03_16.Engine.1.log)
[JASP 2022-03-03 20_03_16 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/8183365/JASP.2022-03-03.20_03_16.Engine.2.log)
[JASP 2022-03-03 20_03_16 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/8183366/JASP.2022-03-03.20_03_16.Engine.3.log)
[JASP 2022-03-03 21_47_37 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/8183368/JASP.2022-03-03.21_47_37.Desktop.log)
[JASP 2022-03-03 21_47_37 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/8183369/JASP.2022-03-03.21_47_37.Engine.0.log)

JASP crashed at 9:47pm

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
You could try it with a beta version: http://static.jasp-stats.org/Nightlies/macOS-x86_64/JASP-nightly-stable-2509cc21037a54e6f20c5dc5d54b81403ae7690f.dmg

**Comment by kadewe** [comment]
I am using 0.16.4 on macOS both Intel AND Apple Silicon build. I can confirm crashed as described in this issue. It does not happen, when I first filter a variable, but later, when I uncheck a response in the variable filter pane, the app hangs both on Intel & Apple Silicon.

crash reporter dump

Command:          JASP
Path:             /Applications/JASP.app/Contents/MacOS/JASP
Identifier:       org.jasp-stats.jasp
Version:          0.16 (0.16.4.0)
Team ID:          AWJJ3YVK9B
Is First Party:   No
Architecture:     x86_64
Parent:           launchd [1]
PID:              16340
Time Since Fork:  12302s

Event:            hang
Duration:         93.75s
Duration Sampled: 1.50s (process was unresponsive for 92 seconds before sampling)
Steps:            15 (100ms sampling interval)

Hardware model:   iMac19,1
Active cpus:      6
HW page size:     4096
VM page size:     4096

Time Since Boot:  114082s
Time Awake Since Boot: 88417s
Time Since Wake:  1270s

Fan speed:        1204 rpm
Total CPU Time:   2.773s (11.9G cycles, 12.1G instructions, 0.98c/i)
Advisory levels:  Battery -> 3, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  848.94 GB/2907.03 GB, low space threshold 3072 MB
Vnodes Available: 81.40% (214226/263168)

Preferred User Language: de-DE, en
Country Code:     DE
OS Cryptex File Extents: 833

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------


Heaviest stack for the main thread of the target process:
  15  start + 2432 (dyld + 25360) [0x7ff80da0f310]
  15  main + 2968 (JASP + 1274120) [0x105076108]
  15  QCoreApplication::exec() + 133 (QtCore + 456581) [0x1085bb785]
  15  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 486 (QtCore + 493686) [0x1085c4876]
  15  ??? (libqcocoa.dylib + 94140) [0x106db7fbc]
  15  -[NSApplication run] + 586 (AppKit + 193527) [0x7ff810f593f7]
  15  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219 (AppKit + 249268) [0x7ff810f66db4]
  15  _DPSNextEvent + 909 (AppKit + 253747) [0x7ff810f67f33]
  15  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 193203) [0x7ff8177602b3]
  15  ReceiveNextEventCommon + 199 (HIToolbox + 193430) [0x7ff817760396]
  15  RunCurrentEventLoopInMode + 292 (HIToolbox + 194406) [0x7ff817760766]
  15  CFRunLoopRunSpecific + 560 (CoreFoundation + 514944) [0x7ff80de1bb80]
  15  __CFRunLoopRun + 929 (CoreFoundation + 517531) [0x7ff80de1c59b]
  15  __CFRunLoopDoSources0 + 308 (CoreFoundation + 522625) [0x7ff80de1d981]
  15  __CFRunLoopDoSource0 + 157 (CoreFoundation + 523079) [0x7ff80de1db47]
  15  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 523160) [0x7ff80de1db98]
  15  ??? (libqcocoa.dylib + 98731) [0x106db91ab]
  15  ??? (libqcocoa.dylib + 96923) [0x106db8a9b]
  15  QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 802 (QtCore + 459426) [0x1085bc2a2]
  15  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 170 (QtCore + 455050) [0x1085bb18a]
  15  Application::notify(QObject*, QEvent*) + 26 (JASP + 1980618) [0x1051228ca]
  15  QApplication::notify(QObject*, QEvent*) + 499 (QtWidgets + 58035) [0x106fd82b3]
  15  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247 (QtWidgets + 54007) [0x106fd72f7]
  15  QObject::event(QEvent*) + 729 (QtCore + 751769) [0x108603899]
  15  EngineSync::process() + 908 (JASP + 1184396) [0x10506028c]
  15  EngineSync::processFilterScript() + 281 (JASP + 1185977) [0x1050608b9]
  15  EngineSync::resumeEngines() + 417 (JASP + 1192433) [0x1050621f1]
  14  EngineRepresentation::processReplies() + 84 (JASP + 1141684) [0x105055bb4]
  7   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52]


Process:          JASP [16340]
UUID:             6E5BCF64-0B86-3268-A959-212DCC370F16
Path:             /Applications/JASP.app/Contents/MacOS/JASP
Identifier:       org.jasp-stats.jasp
Version:          0.16 (0.16.4.0)
Team ID:          AWJJ3YVK9B
Is First Party:   No
Shared Cache:     EA7F9772-219E-3ECE-A4D9-20AEEE3BC80F slid base address 0x7ff80d975000, slide 0xd975000 (System Primary)
Architecture:     x86_64
Parent:           launchd [1]
UID:              501
Footprint:        587.48 MB
Time Since Fork:  12302s
Num samples:      15 (1-15)
CPU Time:         1.400s (6.0G cycles, 7.0G instructions, 0.86c/i)
Note:             Unresponsive for 92 seconds before sampling
Note:             1 idle work queue thread omitted

  Thread 0x71afc    DispatchQueue "com.apple.main-thread"(1)    Thread name "CrBrowserMain"    15 samples (1-15)    priority 46 (base 46)    cpu time 1.395s (6.0G cycles, 7.0G instructions, 0.86c/i)
  <thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [533], IO tier 0>
  15  start + 2432 (dyld + 25360) [0x7ff80da0f310] 1-15
    15  main + 2968 (JASP + 1274120) [0x105076108] 1-15
      15  QCoreApplication::exec() + 133 (QtCore + 456581) [0x1085bb785] 1-15
        15  QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 486 (QtCore + 493686) [0x1085c4876] 1-15
          15  ??? (libqcocoa.dylib + 94140) [0x106db7fbc] 1-15
            15  -[NSApplication run] + 586 (AppKit + 193527) [0x7ff810f593f7] 1-15
              15  -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1219 (AppKit + 249268) [0x7ff810f66db4] 1-15
                15  _DPSNextEvent + 909 (AppKit + 253747) [0x7ff810f67f33] 1-15
                  15  _BlockUntilNextEventMatchingListInModeWithFilter + 70 (HIToolbox + 193203) [0x7ff8177602b3] 1-15
                    15  ReceiveNextEventCommon + 199 (HIToolbox + 193430) [0x7ff817760396] 1-15
                      15  RunCurrentEventLoopInMode + 292 (HIToolbox + 194406) [0x7ff817760766] 1-15
                        15  CFRunLoopRunSpecific + 560 (CoreFoundation + 514944) [0x7ff80de1bb80] 1-15
                          15  __CFRunLoopRun + 929 (CoreFoundation + 517531) [0x7ff80de1c59b] 1-15
                            15  __CFRunLoopDoSources0 + 308 (CoreFoundation + 522625) [0x7ff80de1d981] 1-15
                              15  __CFRunLoopDoSource0 + 157 (CoreFoundation + 523079) [0x7ff80de1db47] 1-15
                                15  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17 (CoreFoundation + 523160) [0x7ff80de1db98] 1-15
                                  15  ??? (libqcocoa.dylib + 98731) [0x106db91ab] 1-15
                                    15  ??? (libqcocoa.dylib + 96923) [0x106db8a9b] 1-15
                                      15  QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 802 (QtCore + 459426) [0x1085bc2a2] 1-15
                                        15  QCoreApplication::notifyInternal2(QObject*, QEvent*) + 170 (QtCore + 455050) [0x1085bb18a] 1-15
                                          15  Application::notify(QObject*, QEvent*) + 26 (JASP + 1980618) [0x1051228ca] 1-15
                                            15  QApplication::notify(QObject*, QEvent*) + 499 (QtWidgets + 58035) [0x106fd82b3] 1-15
                                              15  QApplicationPrivate::notify_helper(QObject*, QEvent*) + 247 (QtWidgets + 54007) [0x106fd72f7] 1-15
                                                15  QObject::event(QEvent*) + 729 (QtCore + 751769) [0x108603899] 1-15
                                                  15  EngineSync::process() + 908 (JASP + 1184396) [0x10506028c] 1-15
                                                    15  EngineSync::processFilterScript() + 281 (JASP + 1185977) [0x1050608b9] 1-15
                                                      15  EngineSync::resumeEngines() + 417 (JASP + 1192433) [0x1050621f1] 1-15
                                                        5   EngineRepresentation::processReplies() + 84 (JASP + 1141684) [0x105055bb4] 1-5
                                                          2   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] (running) 1-2
                                                          1   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] 3
                                                           *1   hndl_unix_scall64 + 10 (kernel + 695690) [0xffffff8000385d8a] (running) 3
                                                          2   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] (running) 4-5
                                                        1   EngineRepresentation::processReplies() + 126 (JASP + 1141726) [0x105055bde] (running) 6
                                                        9   EngineRepresentation::processReplies() + 84 (JASP + 1141684) [0x105055bb4] 7-15
                                                          2   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] (running) 7-8
                                                          5   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] 9-13
                                                           *2   hndl_unix_scall64 + 22 (kernel + 695702) [0xffffff8000385d96] 9-10
                                                             *2   unix_syscall64 + 475 (kernel + 7837835) [0xffffff8000a5588b] 9-10
                                                               *1   sem_trywait + 210 (kernel + 7130066) [0xffffff80009a8bd2] 9
                                                                 *1   ??? (kernel + 6319201) [0xffffff80008e2c61] 9
                                                                   *1   lck_mtx_unlock_slow + 135 (kernel + 2493831) [0xffffff800053cd87] (running) 9
                                                               *1   sem_trywait + 120 (kernel + 7129976) [0xffffff80009a8b78] 10
                                                                 *1   mac_posixsem_check_wait + 162 (kernel + 9402882) [0xffffff8000bd3a02] 10
                                                                   *1   hook_posixsem_check_wait + 111 (com.apple.security.sandbox + 48020) [0xffffff80033e9b94] 10
                                                                     *1   cred_sb_evaluate + 119 (com.apple.security.sandbox + 34756) [0xffffff80033e67c4] 10
                                                                       *1   sb_evaluate_internal + 493 (com.apple.security.sandbox + 85989) [0xffffff80033f2fe5] (running) 10
                                                           *1   hndl_unix_scall64 + 10 (kernel + 695690) [0xffffff8000385d8a] (running) 11
                                                           *1   hndl_unix_scall64 + 22 (kernel + 695702) [0xffffff8000385d96] 12
                                                             *1   unix_syscall64 + 475 (kernel + 7837835) [0xffffff8000a5588b] 12
                                                               *1   sem_trywait + 120 (kernel + 7129976) [0xffffff80009a8b78] 12
                                                                 *1   mac_posixsem_check_wait + 162 (kernel + 9402882) [0xffffff8000bd3a02] 12
                                                                   *1   __bzero + 6 (kernel + 4342) [0xffffff80001010f6] (running) 12
                                                           *1   hndl_unix_scall64 + 10 (kernel + 695690) [0xffffff8000385d8a] (running) 13
                                                          1   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] (running) 14
                                                          1   sem_trywait + 10 (libsystem_kernel.dylib + 52306) [0x7ff80dd0ec52] 15
                                                           *1   hndl_unix_scall64 + 22 (kernel + 695702) [0xffffff8000385d96] 15
                                                             *1   unix_syscall64 + 475 (kernel + 7837835) [0xffffff8000a5588b] 15
                                                               *1   sem_trywait + 120 (kernel + 7129976) [0xffffff80009a8b78] 15
                                                                 *1   mac_posixsem_check_wait + 162 (kernel + 9402882) [0xffffff8000bd3a02] 15
                                                                   *1   hook_posixsem_check_wait + 111 (com.apple.security.sandbox + 48020) [0xffffff80033e9b94] 15
                                                                     *1   cred_sb_evaluate + 119 (com.apple.security.sandbox + 34756) [0xffffff80033e67c4] 15
                                                                       *1   sb_evaluate_internal + 206 (com.apple.security.sandbox + 85702) [0xffffff80033f2ec6] 15
                                                                         *1   eval + 12303 (com.apple.security.sandbox + 105207) [0xffffff80033f7af7] 15
                                                                           *1   _read24 + 4 (com.apple.security.sandbox + 110659) [0xffffff80033f9043] (running) 15

**Comment by shun2wang** [comment]
Let's just keep it open as may related to https://github.com/jasp-stats/INTERNAL-jasp/issues/2145
