### ISSUE TITLE
[Bug]: Network Analysis Graph and Centrality Plot Options

### ISSUE THREAD

**Issue by bruno-fd** [jasp-stats/jasp-issues#1653]
### JASP Version

0.16.1

### JASP Module

jaspNetwork

### What analysis are you seeing the problem on?

Network Analysis (Graph and others)

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am running a network analysis on JASP 0.16.1 and the graph is showing some issues.

Firstly, not all group names are being shown in the label of the figure. The problem seems to be happening when we have more than 4 groupings.

More than that, the selected collors are not being respected. In my case, the fifht group appears in white, when I select purple.

Also, in measures of the centrality plot, the term 'Betweeness' is repeated. I believe that the second 'Betweenes" refers to 'Degree'.

### Expected Behaviour

1) Correct grouping and colors of the graph
2) Correct the names in the Centrality Plot options.
3) Adequate show the name of the groups in the plot

### Steps to Reproduce

1. Run a network analysis with 5+ grouping
2. Try to manually collor them;

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by bruno-fd** [comment]
Hey, Vandenman! Thanks for your response.

I am not being able to attach the .zip file (it says the file can´t be processed). But here you find it: [https://psicometriaonline.com.br/wp-content/uploads/2022/03/BigFiveInventory.zip]

**Comment by tomtomme** [comment]
@bruno-fd 

- Firstly, not all group names are being shown in the label of the figure. The problem seems to be happening when we have more than 4 groupings.

fixed

- More than that, the selected collors are not being respected. In my case, the fifht group appears in white, when I select purple.

fixed

- Also, in measures of the centrality plot, the term 'Betweeness' is repeated. I believe that the second 'Betweenes" refers to 'Degree'.

fixed


I tested with jasp 0.18.3.
Feel free to reopen, if not fixed on your side.
