### ISSUE TITLE
[Bug]: jaspRegression-Squared Pearson residual plot display is abnormal

### ISSUE THREAD

**Issue by shun2wang** [jasp-stats/jasp-issues#1654]
### JASP Version

0.16.1 (Nightly)

### Commit ID

a7d4928c2decd3e28bff64c333db7ec3b78eee52

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Logistic Regression

### What OS are you seeing the problem on?

Windows 10 21H2

### Bug Description

Axis labels seem to overlap . Please see screenshot and sample dataset (to remove .zip suffix).
![Snipaste_2022-03-13_16-14-36](https://user-images.githubusercontent.com/10348402/158051534-3421e514-61fd-4dd4-95d1-7536515331c1.png)
[plot error.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/8239184/plot.error.jasp.zip)

### Expected Behaviour

plot should be disply normal

### Steps to Reproduce

see the pic or the file.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
@fqixiang could you have a look?

**Comment by fqixiang** [comment]
I found out the reason: the R code draws the residuals (on the y-scale) with pretty breaks. However, these residuals are too small (almost zero). Because of this, the segment line, which is fixed at y = 1 and used to tell how the residuals are distributed, compresses the y-scale too much so that all the labels on the y-scale overlap. 

The reason why the residuals are so small here is that `participant` is entered as a predictor, which gives every participant its own intercept and therefore the model makes almost perfect prediction / explanation. I don't think using `participant` as a predictor is a good idea, and I also don't think most real-world models do this or have such low residuals. 

Therefore, in my opinion, this is more a matter of the model and the data, instead of the code. I would say there's nothing to be fixed and close this issue. Please reopen it if you think otherwise. Cheers.
