### ISSUE TITLE
[Feature Request]: Can Bayesian t-tests produce a prior-posterior plot on the raw scale? 

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#1664]
### Description

For Bayesian t-tests to produce a prior-posterior plot on the raw scale 

### Purpose

Better intuition what the results mean

### Use-case

All Bayesian t-tests

### Is your feature request related to a problem?

not knowing what the current posterior means on the raw scale

### Describe the solution you would like

For Bayesian t-tests to produce a prior-posterior plot on the raw scale

### Describe alternatives that you have considered

none

### Additional context

This is from a feature request on the forum. I am not sure how much work this is but it seems worthwhile.

**Comment by tomtomme** [comment]
related:
https://github.com/jasp-stats/jasp-issues/issues/437 (wants those plots also for anova)
https://github.com/jasp-stats/jasp-issues/issues/1883 (wants this for credible intervals)
https://github.com/jasp-stats/jasp-issues/issues/2559 (wants to set priors in raw)

since all of those want raw units instead of standardized ones in bayesian analysis.
#1555 goes further and wants e.g. SI-unit in all tables right next to the numbers (not only embedded in the variable name)
