### ISSUE TITLE
[Feature Request]: Split-plot (or other experimental designs) ANOVA

### ISSUE THREAD

**Issue by sustia** [jasp-stats/jasp-issues#1682]
### Description

Hello, I discovered JASP and I like it really a lot. However, I would like to analyze some data for ANOVA using the split-plot design but I don't see such option in the ANOVA menu. It would be really interesting to have the opportunity to choose which experimental design we are analyzing, to have the right ANOVA and make the software more flexible. Thanks.

### Purpose

Analyzing different experimental set-up

**Comment by tomtomme** [comment]
@sustia 
is this about the missing "random effects" category of the RM ANOVA module? 
And the Linear mixed model is also somehow not suitable here?

**Comment by tomtomme** [comment]
@sustia 
So I read up on the term "split-plot". It stems from agricultural research and is often calculated just as an RM ANOVA + a between subjects factor (see wiki-quote below). So this is already covered by our RM ANOVA module. 
However there are also examples where the term is used for a >1 factorial ANOVA without RM (covered by our ANOVA module), see https://people.math.ethz.ch/~meier/teaching/anova/split-plot-designs.html

So there seems to be some ambiguity here around the term split-plot. And at the same time it seems that we already cover all functionality needed within JASP to analyze such a design. What we could do, is to include the specific terms of ANOVA designs from agricultural research in our help files, but since there is this ambiguity, I do not know if it is worth the effort.

I am 90% sure I got this one right but not 100%. So, if I am mistaken, feel free to reopen!!

Wikipedia, it seems, does not know
"In [statistics](https://en.wikipedia.org/wiki/Statistics), a mixed-design analysis of variance model, also known as a split-plot ANOVA, is used to test for differences between two or more independent groups whilst subjecting participants to [repeated measures](https://en.wikipedia.org/wiki/Repeated_measures). Thus, in a mixed-design [ANOVA](https://en.wikipedia.org/wiki/ANOVA) model, one factor (a [fixed effects factor](https://en.wikipedia.org/wiki/Fixed_effects_model)) is a between-subjects variable and the other (a [random effects factor](https://en.wikipedia.org/wiki/Random_effects_model)) is a within-subjects variable. Thus, overall, the model is a type of [mixed-effects model](https://en.wikipedia.org/wiki/Mixed_model)."
