### ISSUE TITLE
[Bug]: Density line missing or "wavy"

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#1695]
### JASP Version

0.16.2

### JASP Module

jaspDescriptives

### What analysis are you seeing the problem on?

Basic plots

### What OS are you seeing the problem on?

macOS Catalina 10.15.7

### Bug Description

Advance warning: I might be doing something terribly wrong.
As discussed in https://forum.cogsci.nl/discussion/7949/jasp-0-16-2-density-line-missing/ .

Getting no density line for distribution plots, and very wavy lines for correlation plots.
Distribution plots reload after marking "Display density", but line does not appear.
Correlation plots look like this (example for Q2):
![image](https://user-images.githubusercontent.com/112888/165840250-62861183-2f7e-4cc4-8a79-ccefb59e36bf.png)

### Expected Behaviour

Presumably distribution plots should get a density line, and correlation plots should have a more smooth line.

### Steps to Reproduce

1. Open "Fear of Statistics.csv", for example, from https://osf.io/a6qdv/ .
2. Click "Descriptives".
3. Add Q1-Q3 to "Variables".
4. In "Plots", mark "Distribution plots" and "Correlation plots"
5. Mark "Display density".

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @richlv, thanks for reporting the issue. I cannot recreate the exact issue, because on my machine this is the distribution plot for Q1. 
<img width="514" alt="Screenshot 2022-05-02 at 11 20 06" src="https://user-images.githubusercontent.com/38500953/166260029-826e3e64-dfe0-433e-92be-a31927ff2c68.png">
 I think the plot can be definitely be enhanced. I assume the curvy line is on purpose as the variable is categorical and thus the density is displayed for each category. I also assume you would still like a single density over all categories as if the variable was continuous. We will see if that is feasible.

**Comment by richlv** [comment]
Thank you for looking into this.
How could I debug further why distribution plots show no density line?

Here are the settings along with the line-less plot.
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/112888/166268308-1424378c-36d5-4fb7-ab4a-5dd289a59bce.png">

**Comment by juliuspf** [comment]
<img width="1518" alt="Screenshot 2022-05-02 at 13 11 40" src="https://user-images.githubusercontent.com/38500953/166293152-8216bc98-4697-4fb5-8ab8-12c80cb6a25e.png">

I see this with the exact same variable, which is weird. Maybe this is due to different OS versions... (I am on Monterey 12). 
Anyways, the plot that I see should not look the way it looks. I hope @vandenman can help.

**Comment by juliuspf** [comment]
okay. I at least know why my plot was different. The variable was still read as continuous by JASP, after I changed that to ordinal I got the same plot as you do, also with the density line missing. If you changed the scale of the variable to "scale" you would also get the wavy density line. Again, this could be desired behaviour as it is a categorical variable. I suppose one could force the density line to be very smooth, but that would not really be true to the distribution any more.

**Comment by richlv** [comment]
Ahh, that explains [part of] it - changing to scale indeed makes the density line show up.
The bars are a bit weirdly distributed, as in your screenshots (1 and 2 squished together, others not), not sure whether that is OK.

It's a bit weird that with ordinal distribution plots don't get the density line, but the correlation plots get it.
In any case, leaving any needed fixes up to you - thank you so much for figuring out the reason :)

**Comment by richlv** [comment]
Another user shared a screenshot of JASP 16.1 showing density line for ordinal data (although I don't have access to the source data) - so the behaviour might not be that consistent currently.
![image](https://user-images.githubusercontent.com/112888/166473577-cf7dbe94-5364-48c3-b941-8bf87d3f3eeb.png)

**Comment by juliuspf** [comment]
Thank you. Yes there is definitely something going wrong there!

**Comment by richlv** [comment]
Hi - with my studies resuming :) - is there any additional testing data that would be useful to provide?

**Comment by tomtomme** [comment]
@richlv @juliuspfadt 
there was an issue in the past, where a scale switch did not refresh an analysis. So the "other user" probably did switch a scale variable to ordinal and had still the density line, because the analysis did not refresh.
This issue is fixed for me however. Scale switches are applied immideatly. Thus the behaviour seems consistent now for distribution plots aka density line only for scale vars.
Also I agree with julius, that the wavyness is expected. Since in this case you had a discrete variable and tried to display it as a continuous one (a density is meant to visualize continuous vars). 

You are right however, that correlation plots in the descriptive module do show the density line regardless of the scale. The correlation plot in the correlation module however does handle this better / correct.
So this might be considered a bug within the descriptives module. But I would not (at least not of high prio), since under customizable plots you then can again decide if you want density or bars.

Also: Vandenman had a project going at some point to make plots more consistent across analyses. So the team is aware, that the situation could be improved here and there.

So, if you agree, feel free to close this issue!

**Comment by richlv** [comment]
Thank you do much for looking into this.
Is there an existing issue about the density line in the descriptive module? It would be useful for other users to find out about the current behaviour.

**Comment by tomtomme** [comment]
I do not know (yet) of such an issue.

**Comment by richlv** [comment]
Would it make sense to track that in this issue, create a new issue, or just close this and not track it? :)

**Comment by tomtomme** [comment]
Honestly, I do not know. It could be a feature request, to make such plots more aligned across analysis, or a bug about correlation plot defaults not working for ordinal variables. 
But don't take my word for it. Do what you think is best! Because this will drive the quality of JASP for you - the user. And that is the whole point of it being open source and all. Everybody can - and should - scratch their own itch. The dev team then decides which itches crawl up often enough and then makes a project off of it.
Would be cool, if we were devs ourselves, hough? Then we wouldn't sit here crossing our fingers to get our requests in faster :D 
And sure, the amount of requests must be mindboggling, but thats the way it is, when you get popular O_o

**Comment by tomtomme** [comment]
@richlv
This is now fixed in latest 0.19 beta, I guess:
- Correlation plot in descriptives module shows density in histograms regardless of scale. 
- Correlation plot in correlation module shows density now also for ordinals, so regardless of scale

So this is now a unified behaviour. 
To test yourself you could get the latest beta from here: https://static.jasp-stats.org/Nightlies/

One could consider this still as a missing feature / bug, since it might be more desirable to show bar graphs instead of histograms+density lines IF variable ordinal. Please open a new request for this, if you need this, so we do not have the comment-baggage of this old and mostly solved issue. Thx!
