### ISSUE TITLE
[Feature Request]: Mean and CI in RainCloud plots

### ISSUE THREAD

**Issue by Trebicky** [jasp-stats/jasp-issues#1698]
### Description

Let user choose whether to shop boxplot ir Mean and its confidence intervals

### Purpose

When comparing means (and their CIs), I want to visualise them in a corresponding raincloud plot. 

### Use-case

Runnig any mean comparison test.

### Is your feature request related to a problem?

When plotting data for a given anylsis, the data should be visible in the plot. Thus whne comparing means, median and percentiles don't help.

### Describe the solution you would like

Let user choose whether to show boxplot or mean+CI (maybe in the graph settings dialogue?)

### Describe alternatives that you have considered

Showing both the boxplot and mean+CI as a default in Raincloud plots

### Additional context

I like raincloud plots, and I see the advantage in showing raw data point, their density and some central tendency with associated dispersion.

But frequently, the mean does not overlap with the median, and IQR does not represent the confidence interval. 

When I run parametric tests for means differences (having normally distributed data and fulfilling all assumptions...) I want to visualise the associated statistics  - means and CI. When I run non-parametric tests, I would prefer to show the median and IQR.

Let the user pick which central tendency and dispersion to show in rainclouds.

**Comment by juliuspf** [comment]
Hi @Trebicky, thanks for the request. Let's see if Don can help.

**Comment by EJWagenmakers** [comment]
We have people helping out with raincloud plots in the near future, so let's leave this one for them
EJ

**Comment by tomtomme** [comment]
Just linking all issues related to rainclouds here:
#1698
#1529
#1757
#1948
#1784
#2101
#2176
#1818
#2112
#2270

**Comment by EJWagenmakers** [comment]
OK, so the issue I have is that rainclouds are meant as descriptive tools, not inferential tools. So adding the mean is OK (although unclear how much that adds over the median, which is already displayed), but the CI is an inference, and it will change based on the underlying model (in case of more groups). But maybe we could have an inferential version of the raincloud, where mean and SE or CI is shown. Hmm I am not against it, but it should not be the default option.

**Comment by Trebicky** [comment]
By browsing those other Lister threads, other users would like to see Raincloud plots listed in descriptives (+1 from me). As said, it is supposed to be only descriptions; let's move it under Descriptives.

However, as it is now in the inferential section, having the option to show inferential information would be well received (as mentioned in multiple threads).

**Comment by vincentott** [comment]
I am currently working on a raincloud plots module and will soon look into also implementing means.
I find it very interesting to hear that there is the demand for Means and CIs in raincloud plots! Because I myself have also been wondering to what extent it would make sense to implement them.

**Comment by tomtomme** [comment]
To add another perspective to the discussion - I do not see how any statistical measure or graph can be seen as "only" descriptive or "only" inferential. For example:

a) Descriptive Table with means, SDs and n's - if meanDiff and n big and SD small I already can infer big signal to noise ratio aka big t, small p.
b) Same for Scatterplots or Rainclouds: I can use them to graphically infer deviations from normality, variance homegeneity. And I also can see the signal to noise ratio roughly. At least for simple models. For multivariate stuff Flexplot does a nice job to enable inference from graphs with added variable plots

And so it does not really matter what the inventors thought, how their creations were supposed to be used. Once the tool is out there, it will be used and misused in all ways thinkable.

**Comment by tomtomme** [comment]
To get an overview and to close some very related issues - we need:

- [ ] Boxplot with mean + 95% CI
- [ ] Boxplot Notches =  median + 95% CI
for 1 group via MedianCI function in DescTools package 
for >1 group via groupwiseMedian function from rcompanion package
or via http://shiny.chemgrid.org/boxplotr/
(from https://github.com/jasp-stats/jasp-issues/issues/1529 and https://github.com/jasp-stats/jasp-issues/issues/602)

Both possibly via RainClouds.

**Comment by vincentott** [comment]
Do you think it would be a good design choice - and that users would be fine with it -
if users can choose EITHER between box plots OR means with standard deviations?

I think that would make everything a lot tidier.
Unless you think there is a pressing need to show both
(though EJ already pointed out above that simultaneous Median and Mean would not add much),
I won´t ponder about the implementation for now.

At the moment I am keeping the boxplots as they are defined:
with medians, the middle 50%, and whiskers according to the 1.5 * interquartile distance.
Because I assume that this is what most people will understand when they see a boxplot.
And anything else might be misleading, even with a corresponding note?

The means, standard deviations (and potentially CIs) are visualized differently
with a ggplot diamond shape (square rotated by 90 degrees) and outgoing whiskers.

Could it be misleading to offer standard deviations?
Because even with a note they will look like CIs at first glance?
Thus EITHER boxplots OR Means (+ CIs?) but without SDs?

Also, are there ways to make the rainclouds more appealing to Bayesians?
What measure of central tendency do they usually use (Means or Median)?

Instead of implementing various statistical modeling under the hood in the raincloud plots module,
maybe we can have the user simply specify the CREDIBLE or CONFIDENCE intervals themselves?
By default there could be boxplots and if users want to visualize their statistical model,
then they can do so with the appropriate input?

**Comment by tomtomme** [comment]
EJ said, mean and CI should not be default. They can be an option for the user to choose. The Flexplot module handels this nicely via a dropdown that shows:
![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/5d1c29ad-b9a2-4e84-a7d4-9afc10d648ee)

In our case the following order from top to bottom in the dropdown might be:

raincloud with a
- standard boxplot (default)
- mean + SD
- Boxplot with notches =  median + 95% CI
- Boxplot with mean + 95% CI

But I do not think that the order is really important. The important thing is, that the old raincloud with standard boxplot should be default, and that the user has options to change that. Also a way to change the 95% to SE or 99% or something else would be sensible and in line with JASPs options in other modules.

**Comment by Trebicky** [comment]
The option to choose Boxplot or Mean + [a measure of dispersion] would be great, solving most requests.

I see that the general inclination is to keep the plot as a descriptive tool only. However, as the rain clouds are inside an inferential test module, people will want to use them to visualize the inference they are making within the ANOVA (or whatever means comparisons test).

Providing SD is nice, but not an inferential error measure... 95% CI is the current expectation.

If it is supposed to stay descriptive, move it into the Descriptives module...

**Comment by Trebicky** [comment]
+1 for Toms post above.

**Comment by EJWagenmakers** [comment]
1. We do have descriptive plots to accompany the inferential tests, and for good reason. For instance, when you test a correlation (inference) the user also sees a scatterplot (description), because the scatterplot provides a visual check on whether the inference makes sense. I would not want to relegate all descriptive plots to Descriptives, because it makes it easier for people to forget to do some fundamental data inspection. See Anscombe's quartet for my favorite demonstration.
2. One immediate issue is that if you want a box-plot style inferential plot, it would ideally be sensitive to the underlying model. I can see it being useful, but I have not encountered it before. I wonder whether there is a good reason for this. Suppose I show a boxplot or the individual data points, and then put a mean and some interval in there as well. It is natural to think of the interval as a property of the spread of the dots. However, when the interval is an SE or 95% CI, it is actually a property of the *mean* of the dots. So the individual dots can be widely varying, but if there are a sufficient number of them the CI will nonetheless be very narrow. This may cause confusion. And we already allow plots of the 95% CIs, just not with the individual data added on to it.  So I can see @vincentott 's point. I also think we can delay this decision. Let's first finish the regular raincloud plot, and keep discussing the value of the additional options. Choice is good, but confusion is bad. The case would be more compelling if the "raincloud/boxplot + inferential measures about the mean"-plot was already in common use -- but I have not seen it.

**Comment by vincentott** [comment]
I am currently implementing the following options:

Mean only
Mean ± 1 standard deviation
Mean ± 1 standard error of the mean

Mean with confidence interval (see jaspDescriptives module)
-> option width: 95%
-> option method: normal model, t model, bootstrap

Potentially I will have the time to implement the option to specify custom interval limits.
Because at the moment, the confidence interval assumes that all cells of the design are independent of each other (only between factors).

The default will still be boxplots and they will be default boxplots (i.e., whiskers, 50% box, median).

**Comment by tomtomme** [comment]
@Trebicky 
This is now available via 0.19 beta. If you want to test the new functionality pre-release, see: https://static.jasp-stats.org/Nightlies/
Cheers :)

**Comment by Trebicky** [comment]
🤩

Dne po 27. 5. 2024 11:30 uživatel Thomas Langkamp ***@***.***>
napsal:
