### ISSUE TITLE
[Feature Request]: Partial Least Squares for SEM

### ISSUE THREAD

**Issue by ariefjusuf** [jasp-stats/jasp-issues#1711]
### Description

Structural Equation Modelling using Partial Least Square

### Purpose

Academic Research

### Is your feature request related to a problem?

Normality

### Describe the solution you would like

Module availability

### Describe alternatives that you have considered

Non parametric method

### Additional context

The partial least square method has many benefit than covarian based SEM.

Thank you

**Comment by ariefjusuf** [comment]
@juliuspf i have read on the web, perhaps R package which use for PLS SEM is plspm.
Thank you

**Comment by ariefjusuf** [comment]
Thank you

**Comment by ariefjusuf** [comment]
Thank you for this information @Kucharssim

**Comment by LSLindeloo** [comment]
Sure! I’m also not quite familiar with the method, but I will do some research :) @Kucharssim @ariefjusuf

**Comment by FloSchuberth** [comment]
@LSLindeloo: As mentioned in Issue #354, I have developed a PLS implementation for R. It is based on lavaan syntax. Hence, if you have implemented SEM/CFA via lavaan, an implementation of PLS should be straightforward. I would be happy to help.

Best regards, 
Florian

**Comment by LSLindeloo** [comment]
@FloSchuberth Thanks alot! I will start implementing PLS very soon. If I have a question regarding the package, I know where to find you :)!

**Comment by FloSchuberth** [comment]
@LSLindeloo: I saw that PLS-PM is implemented now in JASP, at least in the development version: https://static.jasp-stats.org/Nightlies/
It looks quite promising, but unfortunately I am not able to produce any results. In the results window it says: "Error evaluating: sink(.outputSink). Am I doing sth wrong or is it just not ready yet?

Best regards, 
Florian

**Comment by Ghassan-Okour** [comment]
This feature is currently working within JASP nightlies 0.17

**Comment by FloSchuberth** [comment]
Dear @Ghassan-Okour, 

Thank you for letting me know. I checked the version number of my nighlies JASP version and it says 0.17. The issue is that JASP does not produce results for PLS-SEM in the result window. Instead it returns a warning, see the file attached.

![JASP](https://user-images.githubusercontent.com/16427204/212271928-99ff3d99-f841-4048-b629-a15e602937e1.PNG)

Considering your references for PLS-SEM, you currently refer to a book of Sarstedt et al. I am not aware of a book with that author order. So you might want to check this reference.  

Moreover, there is no consent on how PLS-SEM should be applied. On the one hand, there is the group around J. F. Hair who labels PLS mode a as reflective measurement model and PLS mode B as formative measurement model (which is in contrast to the SEM literature). Yet, they recommend to apply metrics, such as AVE, to evaluate their 'reflective' measurement models. This practice has been heavily criticized in the past as the metrics will be biased due to the use of inconsistent estimates, see e.g., McIntosh et al. (2014), Rönkkö et al. (2015), Rönkkö et al. (2016), Rönkkö et al. (in press), Schuberth (2021).
 
On the other hand, there is a group of researchers who sticks to the original terminology of SEM and recommend to use consistent PLS (Dijkstra & Henseler, 2015) to estimate reflective measurement models to obtain consistent estimates. This is in line with the cSEM default options which uses PLSc if a reflective measurement model is specified (=~ in lavaan syntax). However, currently this strand of literature is not represented in JASP (if I click on "Show info for this analysis"). Hence, you might want to add some of the following papers/book to provide a more balanced view:
 - J. Benitez, J. Henseler, A. Castillo, and F. Schuberth, “How to perform and report an impactful analysis using partial least squares: Guidelines for confirmatory and explanatory IS research,” Information & Management, vol. 2, no. 57, p. 103168, 2020, doi: 10.1016/j.im.2019.05.003.
 -    J. Henseler, Composite-Based Structural Equation Modeling: Analyzing Latent and Emergent Variables. New York, NY: Guilford Press, 2021. (this book also contains various tutorials using cSEM. 
 - J. Evermann and M. Rönkkö, “Recent developments in PLS,” Communications of the Association for Information Systems, vol. 44, 2021.

If you prefer that I open a new issue considering the references, please let me know. 

Best regards, 
Florian


References: 
T. K. Dijkstra and J. Henseler, “Consistent and asymptotically normal PLS estimators for linear structural equations,” Computational Statistics & Data Analysis, vol. 81, pp. 10–23, 2015, doi: 10.1016/j.csda.2014.07.008.

C. N. McIntosh, J. R. Edwards, and J. Antonakis, “Reflections on partial least squares path modeling,” Organizational Research Methods, vol. 17, no. 2, pp. 210–251, 2014.

M. Rönkkö, C. N. McIntosh, J. Antonakis, and J. R. Edwards, “Partial Least Squares Path modeling: Time for some serious second thoughts,” Journal of Operations Management, vol. 47–48, pp. 9–27, 2016, doi: 10.1016/j.jom.2016.05.002.

M. Rönkkö, C. N. McIntosh, and J. Antonakis, “On the adoption of partial least squares in psychological research: Caveat emptor,” Personality and Individual Differences, vol. 87, no. 87, pp. 76–84, 2015, doi: 10.1016/j.paid.2015.07.019.

M. Rönkkö, N. Lee, J. Evermann, C. McIntosh, and J. Antonakis, “Marketing or Methodology? Exposing the fallacies of PLS with simple demonstrations,” European Journal of Marketing.

F. Schuberth, “Confirmatory composite analysis using partial least squares: Setting the record straight,” Review of Managerial Science, vol. 15, pp. 1311–1345, 2021, doi: 10.1007/s11846-020-00405-0.

**Comment by Kucharssim** [comment]
Dear @FloSchuberth,

thanks for looking into it in such a detail!

First, you are right, the analysis is broken in our nightlies. However, the analysis code seems to work as expected, the crash happens somewhere else. I wonder if @JorisGoosen has an idea?

Thanks for the references, @LSLindeloo could you update it please?

**Comment by FloSchuberth** [comment]
Dear @Kucharssim, 

you are welcome. 

I expect that more people will use cSEM via JASP as it is much more user-friendly (I must admit I haven't used JASP before so yesterday was my first time. It looks pretty nice and I think I will also use it for my classes; at the University of Twente we also finally shift away from SPSS). That having said, if you will receive some user request or face some bugs in cSEM (the PLS-PM implementation in cSEM was quite often tested and I also gave workshops with it, so I don't expect any issues, but yes you are never sure), please let me know. 

Best regards, 
Florian
