### ISSUE TITLE
JASP should used a system-wide R

### ISSUE THREAD

**Issue by zirneklitis** [jasp-stats/jasp-issues#1713]
### Description

JASP should not be tithed-up to any particular R version.  Well, "not elder then n.nn version" must be the only restriction.

### Purpose

To achieve uniform data processing.

**Comment by zirneklitis** [comment]
1. Replace R (./R) and R libraries (./Modules/renv-cache/v5/*) withe latest versions
2.Try to launch JASP
3. JASP crashes.

**Comment by juliuspf** [comment]
Hi @zirneklitis, thanks for the request. I can't say much about this issue, but Joris might.

**Comment by vandenman** [comment]
So I'm not really sure what this request is about.

1. If you compile JASP yourself, it is possible to use a system-wide version of R (although this might require some small changes on Windows).
2. If you do not build JASP yourself, but rather would want that an installed version of JASP uses some system-wide installation of R, then this is not a good idea and this will most likely never be implemented. The few most straightforward downsides I've pointed out below. These downsides also apply if you compile JASP yourself but if you do that you should be aware you might be shooting yourself in the foot. 

Some of the most important downsides are:
1. R packages are not always backward-compatible and there is no convenient way to avoid future upgrades of R packages to break JASP. Put differently, if you try to build JASP 0.8 now with the R packages of today you'll find that many things are broken. However, because JASP 0.8 uses its own R you can still install and use it. If it would use a system-wide R then 
    - You cannot upgrade any packages used directly or indirectly by JASP without risking breaking JASP.
    - Effectively, you can only use the R packages with the versions that JASP requires, so JASP would take your system library hostage.

2. We can no longer guarantee the correctness of any analyses. These would be dependent on the internal state of the system library. We have had issues before where JASP accidentally used a system library on macOS (if there was one) and it lead to a bunch of headaches. This means you could have one machine with JASP giving the same results as SPSS or some other statistical software program, but another one gives different (incorrect) results due to the internal state of someone's system library.

There are more downsides, but the risk of JASP breaking or returning incorrect results is enough reason for me to advise against this.

**Comment by sukanka** [comment]
Hello, I'm doing the same thing, I build jasp on archlinux from source. Now I build it successfully, but some other things have to be done so that the app can  work. You can have a look at my repo, see https://github.com/sukanka/jaspOnArch
