### ISSUE TITLE
[Feature Request]: cfa plot numbers are not clear - u may remove leading zeroes

### ISSUE THREAD

**Issue by estatistics** [jasp-stats/jasp-issues#1730]
### Description

 cfa plot numbers are not clear - u may remove leading zeroes

### Purpose

 cfa plot numbers are not clear - u may remove leading zeroes

### Use-case

cfa plot numbers are not clear - u may remove leading zeroes

### Is your feature request related to a problem?

cfa plot numbers are not clear - u may remove leading zeroes

### Describe the solution you would like

u may remove leading zeroes

### Describe alternatives that you have considered

u may also have options to reduce font size in cfa.

### Additional context

cfa plot numbers are not clear - u may remove leading zeroes   

see attached pic
[https://i.postimg.cc/VNXTq2Zz/image.png](url)

**Comment by tomtomme** [comment]
I am reposting the link, because clicking it, does not work: https://postimg.cc/kVXf9YdH
To solve the font size problem you could resize the image. Go to the lower right corner of the plot to get a resize triangle. You can also resize the whole result window with Strg+Scroll wheel or the whole App via Settings=>Interface=>Zoom - (also some font settings there) 
I hope this helps!
The leading zeros might still be a valid feature request!
