### ISSUE TITLE
[Bug]: Neighborhood-Based Clustering

### ISSUE THREAD

**Issue by danilomoggia** [jasp-stats/jasp-issues#1749]
### JASP Version

0.16.3

### JASP Module

jaspMachineLearning

### What analysis are you seeing the problem on?

Neighborhood-Based Clustering

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The Bug happens when plotting the t-SNE cluster plot.

![Screenshot 2022-06-17 172031](https://user-images.githubusercontent.com/85121548/174328155-fde710f1-71b6-4cf4-8da6-dba79aaa912b.png)

### Expected Behaviour

To obtain the plot.

### Steps to Reproduce

1. Machine Learning
2. Neighborhood-Based Clustering
3. Select the variables on Features
4. Training parameters > Algorithmic Settings > Center type --> Medoids
5. Training parameters > Algorithmic Settings > Algorithm --> PAM
6. Plots > Elbow method
7. Plots > t-SNE cluster plot > Legend
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
This is caused by the fact that the predictions in the tsne do not have the same length as the data. The t-sne removes duplicate rows in the data. I'll try to fix this asap, but for now i would try one of the following 2 things:
- make sure there are no missing values in the data
- remove rows with exactly the same values in the data

This may make it work!
