### ISSUE TITLE
[Bug]: Error in density based clustering t-SNE cluster plot

### ISSUE THREAD

**Issue by JuanjoUCAM** [jasp-stats/jasp-issues#1768]
### JASP Version

0.16.3

### JASP Module

jaspMachineLearning

### What OS are you seeing the problem on?

Windows 11

### Bug Description

tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

mlClusteringDensityBased(...)

.mlClusteringPlotTsne(dataset, options, jaspResults, ready, position = 8, type = 'densitybased')

data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], cluster = predictions)

stop(gettextf('arguments imply differing number of rows: %s', paste(unique(nrows), collapse = ', ')), domain = NA)

### Expected Behaviour

A cluster plot should be plotted 

### Steps to Reproduce

1.  I attached the data.
2.  Click on Machine Learning Module -> Density-based 
![Captura de pantalla 2022-07-02 125853](https://user-images.githubusercontent.com/108574448/176997856-90c63fa9-855c-42fd-9a25-afebe3bde835.png)
[Bruno_Prueba.csv](https://github.com/jasp-stats/jasp-issues/files/9032872/Bruno_Prueba.csv)

3. 
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
This issue is fixed by https://github.com/jasp-stats/jaspMachineLearning/commit/27a91484d7eec16fadeb06fb1cb9895b7d8164b6. 

However, @JuanjoUCAM I can imagine that you still want this to work in the current version of JASP. The way to do this is to remove all duplicated values in the 4 variables that you use for clustering, I did this for you in this file: [Bruno_Prueba_no_duplicates.csv](https://github.com/jasp-stats/jasp-issues/files/9046862/Bruno_Prueba_no_duplicates.csv). The t-sne plot cannot handle duplicated values.

This works on my pc. Let me know if it works for you as well. If so, you may close this issue.

![image](https://user-images.githubusercontent.com/25059399/177343969-d2a98301-ad04-403b-949c-ddbd171be7c1.png)
