### ISSUE TITLE
[Feature Request]: Network Proxy Aware

### ISSUE THREAD

**Issue by AlanFNQ** [jasp-stats/jasp-issues#1773]
### Description

Make JASP network proxy aware for better use in large institutions

### Purpose

JASP does not currently prompt for proxy access when checking Internet connections nor are there any proxy settings in the Preferences.  Large businesses and government organisations use proxies to govern Internet access.

### Use-case

JASP currently fails at start if it can't connect to homebase to check for "issues" with the current version because it does not use  the local network proxy to make its connection.

### Is your feature request related to a problem?

JASP currently fails - as in the program shuts itself down in a second - at start if it can't connect to homebase to check for "issues" with the current version because it does not use  the local network proxy to make its connection.

### Describe the solution you would like

Make JASP network proxy aware either through settings or searching environment variables, such as http_proxy.

### Describe alternatives that you have considered

The program can run without any network connection - this generates an error while no error is generated otherwise.  The error indicates that the program has failed to check for "issues" with the version in use.  It is unknown to me how no network access would impact full use of the application.

### Additional context

![JASP-no-network-error](https://user-images.githubusercontent.com/109498753/179446454-4374f89e-d412-473b-822a-91c19b720700.png)
![JASP-no-network-error2](https://user-images.githubusercontent.com/109498753/179446458-136e0074-0cc5-4b37-bc7e-b22a51706d46.png)
The screen captures attached contain the errors generated when the network is disabled before starting JASP.  After clicking on OK, the program appears to run as normal.  I am not familiar with the program and I am really only meant to get it installed and working for my research staff.  I do not know if continued limited or no network access would ultimately impact the use
[jasp-log.txt](https://github.com/jasp-stats/jasp-issues/files/9129475/jasp-log.txt)
 of the program as intended.  Frustratingly, when trying to run the program on our corporate network the program would start and stop within a couple of seconds and would not generate any errors as to why.  I have also attached a log of what the program is doing during start-up while attached to the network.

**Comment by JorisGoosen** [comment]
Well, 

> ### Description
> 
> Make JASP network proxy aware for better use in large institutions
> ### Purpose
> 
> JASP does not currently prompt for proxy access when checking Internet connections nor are there any proxy settings in the Preferences. Large businesses and government organisations use proxies to govern Internet access.

Aah yes this is a very good point indeed. I think we can add a "proxy" setting to the preferences.

> ### Use-case
> 
> JASP currently fails at start if it can't connect to homebase to check for "issues" with the current version because it does not use the local network proxy to make its connection.

Yes and a proxy setting would solve this handily.

> ### Is your feature request related to a problem?
> 
> JASP currently fails - as in the program shuts itself down in a second - at start if it can't connect to homebase to check for "issues" with the current version because it does not use the local network proxy to make its connection.

> ### Describe the solution you would like
> 
> Make JASP network proxy aware either through settings or searching environment variables, such as http_proxy.
> ### Describe alternatives that you have considered
> 
> The program can run without any network connection - this generates an error while no error is generated otherwise. The error indicates that the program has failed to check for "issues" with the version in use. It is unknown to me how no network access would impact full use of the application.

Normally there should be no problem if JASP cannot connect to the server for the "issues". The only thing that does is show some warnings in some specific analyses in case there is some problem that might invalidate the results.
However there are very few problems like this and those that existed have been solved in 0.16.3.

I guess adding a checkbox for "check for version" to allow for disabling the check which might be useful for people who either get into trouble through proxies, other network issues or simply no connection. 

> ### Additional context
> 
>  **Some images**
> The screen captures attached contain the errors generated when the network is disabled before starting JASP. After clicking on OK, the program appears to run as normal. I am not familiar with the program and I am really only meant to get it installed and working for my research staff. I do not know if continued limited or no network access would ultimately impact the use.

No it wouldnt impact the use at all, except if we find a troubling problem in an analysis which due to diligent testing and regression testing shouldnt be prevalent.

> Log of the program as intended. Frustratingly, when trying to run the program on our corporate network the program would start and stop within a couple of seconds and would not generate any errors as to why. I have also attached a log of what the program is doing during start-up while attached to the network.

This obviously shouldn't be happening.

From the errormessage I can see you use Windows. Could you specify the version used?

**Comment by AlanFNQ** [comment]
We currently use Windows 10 in my organisation.

**Comment by JorisGoosen** [comment]
Hello @AlanFNQ 

I did not have time to look at this issue for this release, but will get to it.

However, one thing I now realize looking at this issue is that your crash is most likely unrelated to the networking issue.
If I start JASP on a windows computer without network I do gets warnings, but no crash.

Perhaps there is some other setting or configuration issue that is causing JASP to crash?

This testing version of JASP: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-stable-9b3c805d7def1671e889b9f5bbf51ac7edaa5d1b.msi

Should be quite close to what we will be releasing, it isnt signed or anything but if you could test it and see whether it then also crashes we could look into why exactly it crashes.

**Comment by AlanFNQ** [comment]
Thank you for continuing to look into this, Joris.  I believe I noted above that the program could run with no network enabled.  The issue with this, for our organisation, would be training users how to disable and re-enable their network connections.  Also, at the time that I made the request it was unknown to me how no internet access for the program would affect operations in the long term.
 
I wouldn't know where to begin an investigation on determining what setting or system configuration could be impacting the quick fail when the network is unreachable due to proxy.  The logfile didn't seem to indicate much, and the on-screen errors only displayed when there was no network device available at all.

**Comment by AlanFNQ** [comment]
Thank you for continuing to look into this, Joris.  I believe I noted that the program could run with no network enabled.  The issue with this, for our organisation, would be training users how to disable and re-enable their network connections.  Also, at the time that I made the request it was unknown to me how no internet access for the program would affect operations in the long term.
 
I wouldn't know where to begin an investigation on determining what setting or system configuration could be impacting the quick fail when the network is unreachable due to proxy.

**Comment by JorisGoosen** [comment]
Hmm, I want to work on this but Im having trouble thinking of a good way to reproduce this problem...
How can I get a local proxy that causes the same problem for me...

Another way could be that I create a testversion of JASP that logs lots of relevant parts of the process where the problem most likely lies and then you run that in the problematic environment?

**Comment by tomtomme** [comment]
@JorisGoosen 
I have seen pull requests, where you worked on disabling the "known issues" stuff, if no network is available, correct? This might not solve this particular situation with proxied network.

@AlanFNQ 
It might still be worth testing jasp 0.18.3

**Comment by JorisGoosen** [comment]
> @JorisGoosen I have seen pull requests, where you worked on disabling the "known issues" stuff, if no network is available, correct? This might not solve this particular situation with proxied network, does it? Related: #1986

It should actually help though because the only problem here is the warning about not being able to reach the known issues.
And this warning was removed as it just scares people and is not the most important feature.

The crash mentioned seems to be unrelated anyhow.
But @AlanFNQ might be able to tell us that.
