### ISSUE TITLE
[Bug]: JASP crashing on mac when creating linear regression

### ISSUE THREAD

**Issue by stats-matt** [jasp-stats/jasp-issues#1777]
### JASP Version

0.16.3

### JASP Module

jaspRegression

### What analysis are you seeing the problem on?

Linear Regression

### What OS are you seeing the problem on?

macOS 12.4

### Bug Description

JASP crashes - other analyses like t-tests do not cause JASP to crash. Edit: bill_length_mm causes a crash, but flipper_length_mm doesn't, though there doesn't seem to be any obvious difference to me.

### Expected Behaviour

JASP created linear regression output

### Steps to Reproduce

1. Import dataset (example file included)
2. Open linear regression
3. Add variable to dependent variable in linear regression menu
[penguins.csv](https://github.com/jasp-stats/jasp-issues/files/9143655/penguins.csv)

### Log (if any)

[JASP 2022-07-19 14_13_38 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9143660/JASP.2022-07-19.14_13_38.Desktop.log)
[JASP 2022-07-19 14_13_38 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9143661/JASP.2022-07-19.14_13_38.Engine.0.log)
[JASP 2022-07-19 14_15_02 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/9143662/JASP.2022-07-19.14_15_02.Desktop.log)
[JASP 2022-07-19 14_15_02 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9143663/JASP.2022-07-19.14_15_02.Engine.0.log)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by juliuspf** [comment]
Hi @stats-matt, thanks for reporting this. I cannot even recreate this issue, because reading in the data results in the variables you names (bill_length_mm, etc.) to be scaled as nominal, so I cannot add them as dependent variables in the regression at all. Is it possible you send a zipped jasp file?

**Comment by stats-matt** [comment]
Interesting @juliuspf ! Here's my jasp file - when I load the csv file, bill_length_mm is continuous
[penguins.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/9149848/penguins.jasp.zip)
.

**Comment by stats-matt** [comment]
And here's a screenshot in case anything else looks different on your sid
<img width="1360" alt="Screen Shot 2022-07-20 at 8 44 59 AM" src="https://user-images.githubusercontent.com/9168722/179985283-e8fe80fc-cb4c-4e81-962d-e6b0bda42bce.png">
e

**Comment by juliuspf** [comment]
so this is kind of weird, the crash can definitely be reproduced and it's quite the hard crash, not error message whatsoever. I think this happens because the data has some weird format. For the bill_length_mm column I changed the numbers without a decimal, e.g., 42, to 42.0, and then JASP does not crash anymore. You can see that the numbers without the decimal point are somewhat differently represented when looking at it in excel. This "workaround" seems quite annoying though, and it is definitely worth another look. Any ideas @vandenman, @JorisGoosen?

**Comment by JorisGoosen** [comment]
> Hi @stats-matt, thanks for reporting this. I cannot even recreate this issue, because reading in the data results in the variables you names (bill_length_mm, etc.) to be scaled as nominal, so I cannot add them as dependent variables in the regression at all. 

Aah that is weird, I do also get them continuous like @stats-matt .

And I also get a hard crash...

No clue why though...

**Comment by JorisGoosen** [comment]
Wow, apparently our json decoder thinks: `'3.2113941528363544e-312' is not a number.` 
So I guess one of those numbers was so big it didnt except it anymore?

I'll see what that is about.
