### ISSUE TITLE
[Bug]: Bayesian repeated measures ANOVA running slow

### ISSUE THREAD

**Issue by MelissaJEvans** [jasp-stats/jasp-issues#1780]
### JASP Version

0.16.3

### JASP Module

jaspAnova

### What analysis are you seeing the problem on?

Bayesian analysis of repeated measures ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I'm trying to run a Bayesian repeated measures ANOVA and it is running unbelievably slow (only two error % values have been computed in the 15 hours I've left it running - there are three factors with two levels each and 240 participants).

### Expected Behaviour

I ran this analysis previously and it only took an hour or so to run. 

### Steps to Reproduce

1. Load in data
2. Click ANVOA, Bayesian, repeated measures ANOVA
3. Set up three two level within subjects factors and put in the relevant data

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by MelissaJEvans** [comment]
It may be worth noting that I tried uninstalling and reinstalling JASP as well as reloading in this CSV file data and restarting the analyses.

**Comment by shun2wang** [comment]
Hi @MelissaJEvans thank you for your report. Could you please send a JASP file or CSV file here?

**Comment by MelissaJEvans** [comment]
Hello! I was able to get this running perfectly fine through Jamovi actually, so all is resolved!

**Comment by EJWagenmakers** [comment]
Well that is not quite the kind of resolution we'd like to see :-)

**Comment by EJWagenmakers** [comment]
In order to help other users we'd still appreciate some help fixing the issue!

**Comment by MelissaJEvans** [comment]
Hi, apologies for the delay. Here's the CSV file and the JASP file.
[Evans_Jamovi_error.zip](https://github.com/jasp-stats/jasp-issues/files/9183376/Evans_Jamovi_error.zip)

**Comment by shun2wang** [comment]
@MelissaJEvans thank you for your example file.

I can't reproduce the "slowly" issue, but if I refresh that .jasp file, I got a different error message every time. maybe @vandenman can take a look?

**Comment by MelissaJEvans** [comment]
That is odd. For me, when I try to run the analysis it just won't run. I tried it on two different computers and after a few hours only one or two numbers would be computed at most.

**Comment by vandenman** [comment]
@MelissaJEvans The main difference is that since Jasp 0.16.3 the repeated measures ANOVA now includes random slopes by default. Computing Bayes factors for models with random slopes simply takes more time, but without the random slopes the results could be completely wrong. See [this preprint](https://psyarxiv.com/fb8zn/) that illustrates the difference between the old and new approach.

I'm not 100% sure what Jamovi does for their Bayesian repeated measures ANOVA, but their original implementation was copied from Jasp. If they have not updated anything in the meantime then for your data set and the models you specified (e.g., models with interactions among the repeated measures factor) their implementation can produce incorrect results.

At the same time, I do notice that for your data set the analysis takes awfully long to run. I'll see if there is anything I can do about that.

@Jiashun97 I do not get any error message, the jasp file just works. Can you create a separate issue for it?

**Comment by shun2wang** [comment]
@vandenman Ahaha i'm not jiashun wang,  for the error message,It's because I'm reproducing on a different branch than stable, so please ignore it and i am looking into it for now, thanks.

**Comment by vandenman** [comment]
@shun2wang Sorry, I failed at reading... Let me know if the error persists and you need help with it in the future!

**Comment by MelissaJEvans** [comment]
@vandenman Yes I saw the preprint and was wondering if that had to do with the slowness. I think when I got it to run before it must have been before I updated JASP. 
Jamovi's jsq package is based on JASP before the update, so I do want to rerun with JASP. I'll try and set it up on a computer that can handle running something for a while, but I would appreciate hearing if there's a way to speed it up. Thank you!
