### ISSUE TITLE
[Bug]: Failed to convert column contains text

### ISSUE THREAD

**Issue by HavvaSibel** [jasp-stats/jasp-issues#1793]
### JASP Version

0.16.3

### What analysis are you seeing the problem on?

Pearson Correlation

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I try to change the column „videogamin“ category from nominal to scale but a mistake accures:
Failed to convert column to continuous: values contain text.

could you please help me? I am a student and trying to write my bachelor theses and I think wirhout this change I can not make the right correlation.

Thanks a lot!

### Expected Behaviour

The column should be changed to contionous

### Steps to Reproduce

The bug accures although I checked the excel-file 
Hope you can help me

### Log (if any)

>
[MTK06_data_wide.csv](https://github.com/jasp-stats/jasp-issues/files/9252674/MTK06_data_wide.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
This may be because your “videogamin” column contains commas as decimal points, e.g. `2,5` would not be considered a continuous.We're very sorry that JASP doesn't currently implement this (we are discussing support solutions). also '/' sign in your column is not a good for a dataset. 

A temporary solution may be that you need to replace the comma and other sign in the column with a dot in a data editor (eg excel),You may need to do some cleaning to keep the data ‘clean’, such as not mixing characters and numbers in columns as much as possible and adding appropriate 'number code' and 'characters labels' for it. 
i am closing this issue, if you have any other questions please feel free to ask us for help.

with thanks
