### ISSUE TITLE
[Feature Request]: Less string-clutter in UI

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#1827]
### Description

The descriptive sub-module "cusomizable plots" sometimes randomly includes strings like "show" or "display" which are useless because they are kind of included in the action of clicking the button

### Purpose

less clutter

### Use-case

being somewhot looking less overwhelming to new users

### Is your feature request related to a problem?

descriptive sub-module cusomizable plots looks cluttered

### Describe the solution you would like

delete unneeded strings

### Describe alternatives that you have considered

adding those strings everywhere to stay consistent, but that would look even more cluttered and useless

### Additional context

I added a kind of radical proposal to get rid of strings that seem not that neccessary
![Screenshot_20220914_084117](https://user-images.githubusercontent.com/4428185/190080054-460e9b00-ea6c-47c4-a0da-434125c56286.png)

I also commented on this in weblate, if this is the more appropriate location
https://hosted.weblate.org/translate/jasp/jaspdescriptives-qml/de/?checksum=8296c4301eca0d6d&q=anzeigen&sort_by=-priority%2Cposition#comments

**Comment by EJWagenmakers** [comment]
Although I agree in general terms, for these specific cases it seems to me that removing the redundancy makes the options less clear. I do agree the following can be shortened:
1. "Use color palette" -> Color
2. "Show legend" -> Legend
3. "Display legend" -> Legend

It makes sense to me to state "Add regression line" because when you don't tick that option, there won't be a regression line. Otherwise, if we say "Regression line", you'd have to add the option "None" and tick that by default. This results in more clutter, not less.

I am wondering what "Display density plots" does -- what is the purpose of selecting a density plot if you are not going to display it? What am I missing, @vandenman ?

**Comment by tomtomme** [comment]
If we shorten to "Regression line" why would we need to add a "none" option?
There is a button left to "regression line" (see green highlight) that is selectable and says visually "none" or "one" - so to say.

Same for "graph above scatter plot" - we could add a selection button left to it and axe all "none options. 

I painted even more suggestions in green :D : 
![Screenshot_20220914_084117](https://user-images.githubusercontent.com/4428185/190091428-2a6c36f2-cbbe-4315-8c24-f88844640204.png)

**Comment by vandenman** [comment]
@EJWagenmakers "Display density plots" shows density plots for all variables selected in the variables input box in descriptives. `Split` plots the density within each group in separate plots. `Separate densities` plots the density within each group in a single plot.


We can remove some of these strings (e.g., "~Graph~ above scatter plot", "~Show~ legend"), but I think we should consider two things here.

1. Clarity. For example, changing "~use~ color ~palette~" to "color" is arguably less clear. Another example is "~Display~ value". If there is only a checkbox called "Value", it's a bit unclear what it does. I prefer verbose and clear over minimal and unclear. 

2. Translations. For example, "Number of observations" is easy to translate while "count" is much more difficult, as translators would have to look up the context of "count" before they can translate it properly.

If the problem is that the user is confronted with too many options opening `Customizable plots`, then I would prefer to set this up with selectable components. E.g., under plots, you have a green + (like in `Learn Bayes`-> `Binomial Estimation` -> `Model`) and then you can select a plot type. That is a bit at odds with our usual approach where we grey out options rather than hiding them, but I think this would 1) reduce the clutter and 2) promote the reuse of plots across modules (the GUI elements are easily reused). We should still remove some of these strings though.

**Comment by shun2wang** [comment]
As a translator, I also strongly believe that character clarity is the first priority, especially for synonyms in different languages.So we should be careful to remove "redundant" strings.....

**Comment by tomtomme** [comment]
@vandenman

I suggested "Count" because it is already used in some places like contingency tables. But maybe we should change those instances into something more verbose, since I agree with your point of view, that sometimes those longer strings bring clarity. But in some instances they are just random appearances.

**Comment by tomtomme** [comment]
I do not see this issue going anywhere soon. So I am closing this for now. I think the descriptives module needs a general redesign, maybe even a split in two submodules, one for plots, one for stats. Because it is not a beginner friendly looking module anymore with all the options presented. It looks more complicated than many of the modules for advanced users. So I will create a new issue when I have time to do a proper mockup that is more thought through than this one.
