### ISSUE TITLE
[Bug]: Engine crashes for every analysis

### ISSUE THREAD

**Issue by KubaQWERT** [jasp-stats/jasp-issues#1875]
### JASP Version

0.16.4

### What analysis are you seeing the problem on?

All modules

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Jasp, regardless of the CSV file (large/small/very small/different) in every possible statistical module generates the error "The engine crashed while trying to run this analysis...".
This did not happen before. 

WIN 11, RTX 3050ti m, i-5 11400H

### Expected Behaviour

Instead of an error, a statistic should appear. Any inflicted.

### Steps to Reproduce

1.  Open Jasp
2. Open CVS
3. Click on any statistic
4. Error occured
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if any.
- [X] I have included a JASP file that causes the crash/bug, if any.
- [X] I have accurately described the bug, and steps to reproduce it.

[JASP 2022-10-29 09_43_59 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/9893225/JASP.2022-10-29.09_43_59.Engine.0.log)

**Comment by tomtomme** [comment]
@KubaQWERT 
could you re-test with jasp 0.18.3?

**Comment by tomtomme** [comment]
@KubaQWERT 
So I spottet this in the log:

00:00:00.751: Error when retrieving the data set: Nie można odnaleźć określonego pliku.

Thus this error may have originated from the special charakters in the file name. This should be fixed in newer jasp versions. Please share your feedback, if you can make time for it. Thx!
Closing until then.
