### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by joydanielle92** [jasp-stats/jasp-issues#1903]
### JASP Version

Others

### JASP Module

Unrelated

### What OS are you seeing the problem on?

ChromeOS

### Bug Description

I have not been able to get JASP to upload files save on my computers. I have a chromebook and a windows 7. JASP worked the first day I tried it. I created an excel on my chromebook and saved it under csv to open in JASP. I used my windows 7 computer to save the file and open in JASP from my desktop. It worked the first time and has not worked since.

### Expected Behaviour

I should see all of the documents saved on my desk top

### Steps to Reproduce

1.
2.
3.
...

Yes all I have to do is open the program and I can see it does not show any of the files save on my computer.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by joydanielle92** [comment]
I need JASP to do my stats course at TSU. My professor has not been helpful at offering problem resolutions or alternatives. She will fail me in this class if I don’t get it fix. I cannot afford to buy a third laptop for this class. Please help me.

**Comment by boutinb** [comment]
@joydanielle92 First of all, Windows 7 is not supported by JASP or by Microsoft either. So you should really upgrade your Windows version.
To help you, we need anyway more precise information: which JASP version you use, which version of Chromebook? What did you do exactly? You have saved a csv file on your Windows laptop and on your Chromebook? You said it was working the first time, but after not: did you change something between the 2 attempts, like upgrading JASP? And what does not work exactly: you open JASP, try to load the csv file, and you get an error? You should also give the log files so that we can get more internal information.
