### ISSUE TITLE
[Bug]: Installation on Windows

### ISSUE THREAD

**Issue by DarrenRhodes** [jasp-stats/jasp-issues#1904]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

None

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi! I didn’t know where to put this - but thought I would try here.

the story in a nutshell is… I am trying to get my university (Nottingham Trent) to install on our software hub, such that any user on a networked machine on campus can access JASP.

The issue our IT are having, or seeking to clarify, is that JASP apparently requires the Xbox game bar to be installed in order for it to work. The university doesn’t have any game related stuff installed on its computers due to storage etc - but JASP doesn’t work unless this module is installed.

any ideas? 

### Expected Behaviour

To work

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by DarrenRhodes** [comment]
This is what it wants… 
![33D18F8E-4C2D-467B-97F6-C7C0C6137EE2](https://user-images.githubusercontent.com/37701728/201717020-4a05c771-821b-4c60-85ee-8ee2aefc891e.png)

**Comment by JorisGoosen** [comment]
Hello @DarrenRhodes 

yeah this happens due to an unfortunate set of circumstances:
- JASP runs the interface in OpenGL, which is also used by games. So windows wants to load the gamebar (this is built into windows, not something we have control over)
- Some it-departments however decide not to install it (or it might not be part of perhaps the education version of windows or something). This can be done and doesnt lead to problems for most software.

However, because JASP looks like a game to windows these two things intersect and cause this problem.

What the it people could do is set some group policies in their active-directory or whatever they use to deploy windows to the systems. Fairly sure that  the following would do the trick: method 3 descibed as per: https://www.top-password.com/blog/disable-game-bar-and-game-dvr-in-windows-10/
