### ISSUE TITLE
[Feature Request]: More clarity in descriptive statistic module

### ISSUE THREAD

**Issue by PerPalmgren** [jasp-stats/jasp-issues#1927]
### Description

It would be great with two things 1) In descriptive statistics, when deselecting all defaults under the statistics button the "Descriptive  Statistics" table would disappear. Like that if you have categorical  data you only see your selected Frequency table.  2) I think the the Frequency table button (now folder) should be moved up to the top and with out embedded in a folder (like it use to be in previous JASP edition). The stem and leaf could just be tabbed in to the right.

### Purpose

Clarity and more user friendly

### Is your feature request related to a problem?

No!

### Describe the solution you would like

This is done in JAMOVI.

**Comment by PerPalmgren** [comment]
A possibility?

**Comment by EJWagenmakers** [comment]
Hi Per,

wrt point 2: We moved the frequency table inside the tab because we felt it was too prominent otherwise. Also, this way we keep the interface simple. So it was a conscious choice to do it this way, and I don't see an urgent reason to switch back.
wrt point 1: yes, we could have the table disappear when all options are unticked. I don't have a strong opinion either way -- people will rarely (if ever) untick all options, and when they still see a table with only the selected variables, presumably they would not mind too much.
