### ISSUE TITLE
[Bug]: Machine learning NN does not allow trained model to be saved  

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#2014]
### JASP Version

0.17.0

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

NN

### What OS are you seeing the problem on?

Windows 10, Windows 11

### Bug Description

Received via email:

> under Mashine Learning/Regression/NeuralNetwork/
>
> whatever NN i try out i cant save trained model so no prediction possible.
>
> Win10 22H2 x64 Enterprise Jasp 17 version

It might be that the user misunderstood something.

### Expected Behaviour

I guess the users wants the NN to make predictions. I think we handle this directly, but this was the complaint

### Steps to Reproduce

I just got the email, and apparently the user is not a big fan of GitHub :-)

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
I cannot reproduce this with the latest release version. Here is a .jasp file with an analysis where I am able to save a NN model for the Iris day set correctly.

Download and change the file extension `.zip` to `.jasp`:
[saveNNmodel.zip](https://github.com/jasp-stats/jasp-issues/files/10720196/saveNNmodel.zip)

@EJWagenmakers Is it an option to send the above JASP file (with instructions to change .jasp to .zip) to the user to show how to save a ml model in JASP.

<img width="1512" alt="Screenshot 2023-02-13 at 09 37 35" src="https://user-images.githubusercontent.com/25059399/218409691-514e122d-082d-4ce8-9d5d-ece13b5a66e8.png">

**Comment by koenderks** [comment]
They will probably need to set the save location to somewhere on their own pc, currently it is set to my local directory.

**Comment by koenderks** [comment]
Ok, I realise the problem now. When you fill in the file location in Classification the main table updates and shows "Model is not saved until 'Save trained model' is checked", which prompt you to click "Save trained model". However, in regression the main table does not update because the dependency on the file location is placed on the results instead of the main table and hence it might look like there is nothing happening.

I made a PR that puts the dependency in the right place. Thank you to the user that indicated this bug.
