### ISSUE TITLE
[Bug]: Error in `[.data.frame`(dataset, , c(tempRe$value, me)): undefined columns selected

### ISSUE THREAD

**Issue by YingerPanda** [jasp-stats/jasp-issues#2077]
### JASP Version

0.17.1

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

Linear Mixed Models  &  Generalised linear mixed models

### What OS are you seeing the problem on?

Windows 10

### Bug Description

any dtat is wrong，even the data  in JASP for Generalised linear mixed models
![image](https://user-images.githubusercontent.com/91263372/229043204-7eb7d062-c329-43b3-9eee-364d6df7d410.png)

### Expected Behaviour

It can run, but It can not  now.

### Steps to Reproduce

1.input the data
2.choose Linear Mixed Models or  Generalised linear mixed models
3.Wrong
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
@FBartos Can you have a look at this issue?

**Comment by boutinb** [comment]
Hi @YingerPanda we cannot reproduce this problem. What could help is that you send a data file, and the exact steps you do to reproduce this problem.

**Comment by danielschad** [comment]
I'm getting the same problem.
JASP Version: 0.18.0.0
JASP Module: Mixed Models
What analysis are you seeing the problem on? Linear Mixed Models & Generalised linear mixed models
What OS are you seeing the problem on? macOS BigSur 11.7.1
Bug Description:
The same error message as posted above occurs any time I run a (G)LMM.
One easy way for me to get this error message is to open the following data set:
Data library > 17. Mixed Models > Larks and Owls
Then, e.g., remove the dependent variable and enter it back in - which causes JASP to re-estimate the model.
Any other analysis using (G)LMMs that I have tested (e.g., switching to LMMs rather than GLMMs, also a Bayesian LMM), showed the same error message.

**Comment by danielschad** [comment]
It seems that a re-installation of the same JASP version has solved the problem. No errors occurring any more.

**Comment by danielschad** [comment]
I get the same error as described above (with JASP 0.18.0.0, macOS) when I set the language to German.
When I set the language to English, I don't get the error message, and the analysis runs smoothly.

**Comment by shun2wang** [comment]
Well, I can reproduce it, this is step:
1. Load `Larks and Owls` dataset .jasp
2. Change GUI to Chinese/German language;
3. Refresh analysis

seems all  Linear Mixed Models & Generalised linear mixed models will have this issue with language change.

**Comment by shun2wang** [comment]
ah, if so, it's possible that this is not an isolated case? which is why I tried to reproduce it by setting the locale in `jasptools` that day.
