### ISSUE TITLE
[Bug]: Software won't open, won't install, won't uninstall

### ISSUE THREAD

**Issue by kmhhollenbaugh** [jasp-stats/jasp-issues#2094]
### JASP Version

0.16.4

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

when I try to open JASP, I click on it, and nothing happens. 

I thought maybe I need to update to the new version. Tried to install the new version, right at the end it gave an error that there was something wrong with the software. 

I tried to uninstall the current version. Again i got a message there was something wrong with the software. 

![image](https://user-images.githubusercontent.com/130682704/231808545-0222138a-b29e-4be7-bfac-43aa66d8206a.png)

### Expected Behaviour

It should have opened. I don't know what's going on. 

### Steps to Reproduce

1. I could try all of those things again
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
That's quite strange. Maybe a JASP process is still running. preventing JASP to be uninstalled. In this case the best thing to do is to restart your PC.

**Comment by JorisGoosen** [comment]
@kmhhollenbaugh do you by any chance have an intel videocard?
Could you try updating the drivers for that?

**Comment by FeelingAlive** [comment]
Hello. I have encountered a similar issue. The application cannot be installed silently on clean VMs using the /qb parameter or any other silent switch. The error code returned was 1603. The installation log shows the following actual error:

CustomAction FixModulesJunctions returned actual error code -1073741515 (please note that this may not be 100% accurate if translation occurred inside a sandbox).

The issue is likely related to this custom action. I have successfully installed the application manually with the full UI mode on every VM. Also, I was able to install it silently on one VM without any issues, and the only difference was the presence of preinstalled Microsoft Office 365 x64 for business on that VM. When I installed Microsoft Office on other VMs, the error was resolved. I have tested this on various VMs as part of my work as a software packager, and the same positive result was consistently achieved. Although it is unclear how Microsoft Office resolves the application installation issue, but I can confirm that this solution has worked effectively for us.
The video driver was the same for every VM.
Hope this might help someone.

**Comment by JorisGoosen** [comment]
Thanks @FeelingAlive!

Very weird there would be a cross-interaction between office and the junctions-fixer in the installer.
The only that does is start a jaspEngine to recreate some junctions in the installfolder...

Perhaps @kmhhollenbaugh can try this out as well?

Otherwise it might be a similar problem as in https://github.com/jasp-stats/jasp-issues/issues/1841

**Comment by SunnyH666** [comment]
I would like to ask if you have solved this problem? I had a similar problem with version 0.18.1.0. At first it wouldn't install, then I chose to install for the current user only and it worked. But after successful installation, clicking on JASP.exe did not respond and now I can't uninstall it either!

**Comment by kmhhollenbaugh** [comment]
Hi! I didn't ever solve the problem, some of the suggestions were a little too technical for my computer expertise, and it's a university computer so they have all kinds of limitations to what I can and can't do without admin permissions-

in response to @JorisGoosen , to clarify- do you want me to go ahead and use the test version only to see if it will install correctly? (but not actually use it?)

**Comment by JorisGoosen** [comment]
> do you want me to go ahead and use the test version only to see if it will install correctly? (but not actually use it?)

well you can use it, but there might be unforeseen problems and because were still finalizing 0.18.2 release some things might change. Would be good to help you out in any case.
The release is coming in a few weeks

**Comment by SunnyH666** [comment]
> @RensDofferhoff is hard at work creating a new kind of installer for Windows. (MSIX)
> 
> This could solve these problems.
> 
> A test (Really, dont use it for statistics!) version can be found: https://static.jasp-stats.org/Nightlies/WindowsMSIX/JASP-nightly-MSIX-0a58ac5b48dc39937fad202ae8a06aa4b6cd4ec9.msix
> 
> It would be good feedback to know whether it solves this problem.
> 
> When we release this time we will also add it to the microsoft store for convenience.

Hello, I tried it and it still doesn't work, it reports an error: This app package's publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates.
BTW, I turned on developer mode

**Comment by JorisGoosen** [comment]
Ooh yeah right, its not signed yet...
Well, @RensDofferhoff when will we have a signed msix nightly/testversion?

I know its possible with some command prompt thing and a program called `magix` but that might be taking it too far.
In any case, the new release should be out soon.

**Comment by kmhhollenbaugh** [comment]
Just wanted to let you all know I was just able to download the newest version and it's working! Thank you :)

**Comment by shun2wang** [comment]
@kmhhollenbaugh Good to know, thanks!
