### ISSUE TITLE
[Bug]: RM ANOVA: Wrong Confidence Intervals

### ISSUE THREAD

**Issue by maximusmontis** [jasp-stats/jasp-issues#2127]
### JASP Version

0.17.1

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures ANOVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Hi,

when calculating an RM ANOVA, I encountered a problem. Under "Descriptive Plots" you can set that confidence intervals are displayed. However, these confidence intervals do not match the confidence intervals that are output by SPSS. The confidence intervals in JASP are much smaller. I have attached screenshots of the JASP graph and SPSS graph. Both analyses are based on exactly the same data set. CI's were set to 95% in both cases.

What could be the reason for this?
![SPSS](https://github.com/jasp-stats/jasp-issues/assets/30093109/b8f8e277-09d4-4366-a71d-aaed2dea9eab)
![JASP](https://github.com/jasp-stats/jasp-issues/assets/30093109/d95ea9fe-5de3-43ae-8be2-0045607991f5)

### Expected Behaviour

I would expect the Confidence Intervals to be similar to the ones given by SPSS.

### Steps to Reproduce

1. Calculate any RM ANOVA.
2. Create a Descriptives Plot with 95% CI.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [x] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @maximusmontis ,

We follow a special procedure for the RM ANOVA plots. This is from our helpfile:
Display error bars: By selecting this option, error bars will be displayed in the plot. The error bars can either represent confidence intervals or standard errors. In order to get accurate confidence intervals and standard errors, the data are normalized by subtracting the appropriate participantʹs mean performance from each observation, and then adding the grand mean score to every observation. The variances of the resulting normalized values in each condition, and thus the size of the bars, no longer depend on the participant effects and are therefore a more accurate representation of the experimental manipulation. See Morey (2008) for a thorough discussion of this procedure.

We apply the procedure from Morey (2008), where some normalization is applied, so it is not as straightforward as sd / sqrt(n). See
Morey, R. D. (2008) Confidence Intervals from Normalized Data: A correction to Cousineau (2005). Tutorial in Quantatitative Methods for Psychology, 4(2), 61-64.


I do think we should add a checkbox that makes this procedure optional, and more salient. 

Kind regards
Johnny

**Comment by maximusmontis** [comment]
Unfortunately I think there is still some issure with the RM ANOVA confidence intervals. I understand that in version 0.19, Morey's correction has been made optional (with the checkbox "normalize error bars"). However, even with this disabled, the CI bars still deviate from the SPSS graph; they even get a bit smaller and therefore deviate further. Both JASP graphs suggest a notable difference in T3 (no overlap in the CIs), while SPSS does not. I would expect the non-normalized graph from JASP to be identical to the SPSS graph, or am I wrong?

**JASP normalized:**
![JASP_normalized](https://github.com/user-attachments/assets/f7961e7a-a413-4c8c-bfc1-15125c5c9c9a)

**JASP non-normalized**
![JASP_not normalized](https://github.com/user-attachments/assets/f75aeee3-9188-4d72-8d54-c9fcc86f6308)

**SPSS:**
![SPSS](https://github.com/user-attachments/assets/9cae2d6c-b791-4a32-b07b-ab13b1c39cde)

**Comment by tomtomme** [comment]
@maximusmontis 
Thx for the report. It might not be crucial here, but can you share the .jasp file by renaming to zip and drag and dropping it here?

**Comment by maximusmontis** [comment]
Hi @tomtomme,

sure, here's the file:
[RMANOVA.zip](https://github.com/user-attachments/files/16281188/RMANOVA.zip)

**Comment by tomtomme** [comment]
for what its worth, I can confirm the JASP results. 

@JohnnyDoorn 
Any idea whats going (wr)on(g) here?

**Comment by boutinb** [comment]
@JohnnyDoorn is on holidays, maybe @vandenman can have a look.

**Comment by maximusmontis** [comment]
Small addition: I just noticed that when conducting a Paired Samples T-Test and generating a Descriptives Plot, the checkbox "normalize error bars" does not change anything, the confidence interval bars stay exactly the same. Apparently, it is not an isolated ANOVA issue.

**Comment by JohnnyDoorn** [comment]
Hi @maximusmontis,

Thanks for your report. How did you create the graph in SPSS? It might not take into account the repeated measures structure (in the chart builder, if i remember correctly), which affects the standard deviations. In JASP, we first center the observations for each subject to account for the repeated measures structure, so maybe that is causing a discrepancy between JASP and SPSS? Only after this centering do we apply the Morey correction or not. 
I did just update the t-test behavior, since that one indeed did not account for the option being selected while it should (similar to how it behaves for the bar chart). 

Cheers,
Johnny

**Comment by maximusmontis** [comment]
Hi @JohnnyDoorn,

thank you for you answer. In SPSS, I used General Linear Model -> Repeated Measures -> defined the within-subject factor with 3 levels (measurement) and one between-subject factor (condition). For creating the plot, I used these settings:

![grafik](https://github.com/user-attachments/assets/6d37f9a6-ab13-497e-ad87-71ed54e2a181)

**Comment by JohnnyDoorn** [comment]
Hi @maximusmontis,

I cannot find much information about how the current version of SPSS computes the error bars, but [this paper from 2014 ](https://www.tqmp.org/RegularArticles/vol10-1/p056/) and [this one from 2021](https://journals.sagepub.com/doi/10.1177/25152459211035109) suggest that SPSS does not apply any correction procedures to the error bars, while we subtract each participant’s overall mean (across conditions or time points) from their individual scores, then add the grand mean of all scores. I think that explains the discrepancy. I do realize that JASP's option to normalize was only concerning the Morey correction component, and not the full normalization initially proposed by Cousineau. Based on this I will revise how JASP handles the normalization, with the checkbox on by default, but with the normalization (not just the Morey factor) optional when you are interested in the between subject effects of the RM ANOVA design. PR is here https://github.com/jasp-stats/jaspAnova/pull/385 

Cheers,
Johnny

**Comment by maximusmontis** [comment]
Hi @JohnnyDoorn,

I see, thank you very much for the information and the fix!

**Comment by maximusmontis** [comment]
Hi @JohnnyDoorn,

it appears this fix is not included in version 0.19.1, is that intended?

**Comment by JohnnyDoorn** [comment]
@maximusmontis unfortunately we decided to have a speedy hotfix, rather than incorporate statistics fixes that need testing, so it will only be in the version after this one (planned for October). If you already want a version with the fix, you could try one of the "development" nightlies from https://static.jasp-stats.org/Nightlies/

Cheers
Johnny

**Comment by maximusmontis** [comment]
@JohnnyDoorn I see, thank you for the link!
