### ISSUE TITLE
[Feature Request]: Robust Estimation in CFA

### ISSUE THREAD

**Issue by UsamaSyedIITK** [jasp-stats/jasp-issues#2162]
### Description

Inclusion of MLM and MLR estimator in CFA

### Purpose

Anlaysis using MLM estimator

### Use-case

To estimate model when data is non-normal.

### Is your feature request related to a problem?

This issue is related to the results of Confirmatory Factor Analsysis. Under the advanced options, clicking on Robust estimation, the results simply don't change. They are always the same as in Standard estimation.

### Is your feature request related to a JASP module?

Factor

### Describe the solution you would like

Inclusion of Robust estimators. When including Robust estimation, please give us the option to choose between MLM and MLR estimators.

### Describe alternatives that you have considered

I've been using lavaan package for the same.

**Comment by juliuspfadt** [comment]
Hi @UsamaSyedIITK, I am uncertain what you mean by this. There are robust standard errors in the CFA, but no "robust estimation". So far it is not possible to choose the model test as it is in the SEM module. so when you run a CFA and choose robust standard errors, the standard errors do change. I think your request is still valid, since you would like the option to specify the estimation, the test, and the standard errors (which is also what we are striving for in the SEM module)
