### ISSUE TITLE
[Bug]: JASP closes when I "save as," and the file is stored as a .jasp.tmp file that then cannot be opened with JASP 

### ISSUE THREAD

**Issue by asdfjklasd** [jasp-stats/jasp-issues#2239]
### JASP Version

Others

### JASP Module

ANOVA

### What OS are you seeing the problem on?

Windows 10

### Bug Description

When I attempt to save my JASP file, I select a name, destination, and leave the file type as .jasp. However, as soon as it appears to finish saving, it closes JASP (without being told to) and the file is instead saved as a .jasp.tmp file. When I try to open it by browsing under open file within jasp, it does not appear, even though it is in the folder. 

Note that the analysis I am running (a repeated measures ANOVA) works perfectly fine, and if I save before it has completed, while it is still processing, the file is properly saved in the normal .jasp format that I can open. 

### Expected Behaviour

It should save the file as a .jasp file without closing the program. 

### Steps to Reproduce

1. save as 
2. it crashes
3. 
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
Could you provide a more instructions on exactly how to reproduce this.
I cannot seem to reproduce this bug.

**Comment by shun2wang** [comment]
Maybe I can reproduce it but im not sure it is the same thing.
On Linux:
1. Open a example .jasp file like: Alcohol Altitude.jasp
2. Click Save as...
3. Change to anther save path and save
4. See a .temp file and also a .jasp file, but .jasp file cannot open?

This is also for export result as .html... but it seems that this is not a problem, because when you switch the path of the file browser, the .temp file will disappear, and then the .jasp file can be opened, similar to a cache refreshing.

**Comment by JorisGoosen** [comment]
I also cant reproduce this...

**Comment by tomtomme** [comment]
@asdfjklasd 
I hope you could resolve this. Please reopen if you have more details.
