### ISSUE TITLE
[Feature Request]: make reverse/recoding of variables possible without using any code

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#2325]
### Description

Reverse/recoding is very useful in the context of survey/questionnaire analysis

### Use-case

I agree that a little snippet of  code isn't really a big problem, but as teachers/instructors I think we all know that undergraduates can get terrified of even the simplest of expressions

### Is your feature request related to a problem?

This could work wonderfully with the new data editing and a per-variable missing values feature that Bruno said would be coming at some point!

### Is your feature request related to a JASP module?

Unrelated

### Describe the solution you would like

Implement a GUI for recoding/reverse coding of variables

### Describe alternatives that you have considered

Teach students the relevant code or do this manipulation in SPSS

### Additional context

I think this feature would be extremely useful for teaching, and with this and the missing data feature it will become ever easier to convince departments to ditch IBM!

This was previously requested in #1071. I tried to comment there, but I couldn't reopen the issue. I know you have a variable level editor,, that's not quite same either. Because we want to change the underlying values in the dataset, not just the labels. Reverse coding is possible within the reliability module, so maybe you could just take this code and add a checkbox to the compute column window? To be clear, I know that splitting variables into categories is very easily possible using the GUI constructor for computed columns, and I think this would be a great addition to that.

**Comment by JorisGoosen** [comment]
Hey @TarandeepKang 

I dont have a license for SPSS (and dont like giving them money ;) ) so I dont know exactly what their tool looks like.

But you want to be able to change the values as well in the variables editor?
So here: 
<img width="234" alt="afbeelding" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/41ef9a65-8c04-4059-93d8-bd107856d485">
We can now only filter on/off or change the label.

Also, at the moment the actual values in the analyses are always based on the order in this particular GUI.
So regardless the "real" value in the dataset R will only see "1" for the first label (and not "0" like in  above example).

I suppose that allowing for changing the value would do what you want though?
Or maybe I misunderstand

**Comment by tomtomme** [comment]
@JorisGoosen 
Consider Var1 with values from 1 to 5
You want to change those values, so that they go from 5 to 1.
Currenlty I need to compute a new column with this Code:

1 + (5 - Var1)

This switches the values in the new Var. Note: This code only works if no missing values are present. For Vars with missing values I need to code with if(Else).


If we want to improve this / make it faster, please consider:
This kind of operation to the raw data should alwayas create a new Var / Column, the original column should be preserved as a backup.

In SPSS all this is done via an extremely clunky interface, so better do not open this link, which shows how it works: https://libguides.library.kent.edu/spss/recodevariables

;)

**Comment by JorisGoosen** [comment]
So we could just have a button in the variableswindow/labeleditor thing (where you can reverse and change order easily) that says: "Copy column recoded" ?

Then that would create a new column next to the selected one but with the values set to 1...N for each label in order?

**Comment by tomtomme** [comment]
yes

**Comment by TarandeepKang** [comment]
Sorry, I missed this. But yes Tom explained exactly what I was thinking. There is however one thing I would like to add. We very often need to perform very simple operations like these:

https://community.rstudio.com/t/dplyr-way-s-and-base-r-way-s-of-creating-age-group-from-age/89226/5

You have in the help documentation a example of splitting a variable into three equal categories, I wonder if you could either add an example of splitting continuous variable into user-defined categories to the help documentation, or preferably, somehow at this to the  GUI interface? The coding is very simple indeed, but…

**Comment by JorisGoosen** [comment]
> [community.rstudio.com/t/dplyr-way-s-and-base-r-way-s-of-creating-age-group-from-age/89226/5](https://community.rstudio.com/t/dplyr-way-s-and-base-r-way-s-of-creating-age-group-from-age/89226/5)
> 
> You have in the help documentation a example of splitting a variable into three equal categories, I wonder if you could either add an example of splitting continuous variable into user-defined categories to the help documentation, or preferably, somehow at this to the GUI interface? The coding is very simple indeed, but…

Well if someone writes a nice R example here I can add it in the documentation but as Im not exactly an R programmer im not sure what a nice way would be. Also to make a proper GUI for this would probably require so much work that it would be better to ask such in a separate issue.

**Comment by TarandeepKang** [comment]
That was quick, I was just going to paste in an example:

toy_df["age_group"] = cut(toy_df$age, c(0, 14, 44, 64, Inf), c("0-14", "15-44", "45-64", ">64"), include.lowest=TRUE)

Ok, I'll make a new issue!

**Comment by JohnnyDoorn** [comment]
@JorisGoosen 
There is very general R-code that works for reverse coding ordinal variables (the only type of variable that should be reverse-coded), so if **y** is a numeric vector of integers
```
(max(y) - y) + min(y)
```
I would suggest to add this to the list operators in the compute column GUI, something like "reverseCode(y)"

**Comment by JorisGoosen** [comment]
https://github.com/jasp-stats/jasp-desktop/pull/5367 should allow for lots of recoding stuff.
At least the data backend.

But those changes only allow for manual recoding currently.

The problem is that the computed columns expect either `factor`s in R (thus always from 1 to N), strings (but then you cant recode) or scalar, which would drop the labels...

These are both available in R already and I can add some convenience function to get a column as scalar or as ordinal or something. 

Problem is, how would you se both the values and labels at the same time from R in a nice and convenient way?
To allow for programmatic recoding that is.

Btw, if you want to add nice convenience R stuff you can do that here: https://github.com/jasp-stats/jaspBase/blob/master/R/friendlyConstructorFunctions.R I can then add them to the GUI for you

**Comment by tomtomme** [comment]
@JohnnyDoorn 
That R-Code you wrote cannot handle missings. Can it?
Currently, if I recode vars I do lots of nested if(else) stuff.

**Comment by tomtomme** [comment]
@JohnnyDoorn 
This is not what I meant with missings. Sorry for being imprecise. Using na.rm does nothing here since we are not computing the mean or similar.

What I meant was the following:
Suppose you have a likert scale item (1 to 5 points theoretically), but your respondents only used 2 to 5 points (so 2 to 5 practically in your dataset, then your above recode will fail. You would need to find and define Max and Min yourself. 

`5 - y + 1`

@JorisGoosen 
There is no way JASP could figure out the theoretical scale from 1 to 5 if it is not given anywhere / by the data or the user, right? So if recoding should be implemented via a Button, that button always would need to ask for  the theoretical Max and Min of the scale, since they could be missing in data.

@juliuspfadt 
I wonder how our Reliability => unidemensional => Reverse-scaled items handles this. Might be a major bug. Can you check the code?

**Comment by JorisGoosen** [comment]
> There is no way JASP could figure out the theoretical scale from 1 to 5 if it is not given anywhere / by the data or the user, right? So if recoding should be implemented via a Button, that button always would need to ask for the theoretical Max and Min of the scale, since they could be missing in data.
And yes, there is still the problem that currenly we can only recode if the variable is metric/scale, not if it is ordinal.

Well, the easy thing to implement is automatically reversing all values by:
- order all labels by by value
- switch highest with lowest
- switch highest -1 with lowest+1
- etc

However, automatically setting values on labels, possibly with non-linear changes or different min-maxes would entail adding a more substantial gui.

However the new features in https://github.com/jasp-stats/jasp-desktop/pull/5367 will at least allow for manual recoding, which is of course very flexible, but perhaps a bit painful.

The better GUI will be added at some point but im not sure on the timeline.

**Comment by tomtomme** [comment]
This is now possible via latest 0.19beta via right click on the variable name. This only works for fully enumerated scales.

**Comment by JorisGoosen** [comment]
> This is now possible via latest 0.19beta via right click on the variable name. This only works for fully enumerated scales.

No it just ignores values that arent numbers and puts them at the end in whatever order they were

**Comment by iGrzegorz** [comment]
> Hey @TarandeepKang
> 
> I dont have a license for SPSS (and dont like giving them money ;) ) so I dont know exactly what their tool looks like.
> 
> But you want to be able to change the values as well in the variables editor? So here: <img alt="afbeelding" width="234" src="https://private-user-images.githubusercontent.com/29062713/295899358-41ef9a65-8c04-4059-93d8-bd107856d485.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTMxOTksIm5iZiI6MTcxODYxMjg5OSwicGF0aCI6Ii8yOTA2MjcxMy8yOTU4OTkzNTgtNDFlZjlhNjUtOGMwNC00MDU5LTkzZDgtYmQxMDc4NTZkNDg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4MjgxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiOThjZjU3Njg2ZDIwNGU3ZDUwODExODI0YTEwNjU3NjA3YzA2NDViM2IxMWRjZjUxZGExNzIwNDIzYTNiMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I6eDJ5thE6HoFkbqv0sDnG3G_t9j-W03ITRUuorn8eQ"> We can now only filter on/off or change the label.
> 
> Also, at the moment the actual values in the analyses are always based on the order in this particular GUI. So regardless the "real" value in the dataset R will only see "1" for the first label (and not "0" like in above example).
> 
> I suppose that allowing for changing the value would do what you want though? Or maybe I misunderstand

In SPSS it is quite simple - you have a window where you set the source value, for example 1 and the output value for example 4 if you want to recode 1 into 4. As on the following screenshot. I was looking today for a simple way to recode test variables in JASP, then I retreated to SPSS. 
![Zrzut ekranu 2024-06-17 o 10 32 56](https://github.com/jasp-stats/jasp-issues/assets/133985123/5f14425d-e2f0-4664-bbac-37a6b9c7f468)

**Comment by JorisGoosen** [comment]
@iGrzegorz next release will make things a lot easier, see the nightlies for how we do it in JASP now: https://static.jasp-stats.org/Nightlies/

We are currently going into the testing phase

**Comment by iGrzegorz** [comment]
Thanks for the workaround @tomtomme 
I am looking forward for 0.19. For now in my opinion the only thing it is more intuitive to do in SPSS than in JASP is recalculating variables.
