### ISSUE TITLE
[Bug]: jasp doesn’t open my csv file for some unknown reason…

### ISSUE THREAD

**Issue by katie17-cloud** [jasp-stats/jasp-issues#2334]
### JASP Version

0.18.1

### JASP Module

Other

### What analysis are you seeing the problem on?

all

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have a problem with opening a file in JASP. When I try, an error message shows up and the file won't open. Oddly, it works on my friend's computer but not on mine. I can't understand the error message because it shows weird symbols like black diamonds and question marks (photo attached). Any advice?

### Expected Behaviour

Jasp should open up my csv file.

### Steps to Reproduce

1. open any csv file using jasp

![IMG_1420](https://github.com/jasp-stats/jasp-issues/assets/147538421/b210ca58-200b-4989-a640-873ea2721326)

[Week5_수집데이터_v2.csv](https://github.com/jasp-stats/jasp-issues/files/12871603/Week5_._v2.csv)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by RensDofferhoff** [comment]
What are the language settings of your computer. Is it in Chinese or Korean?
What was the Filename of the csv? Is it possible to share the file? Or an empty file with the same name?

**Comment by katie17-cloud** [comment]
wow thank you so much. I changed the file name into english and it worked out perfectly! Thank you so much for your help! On Oct 11, 2023, at 5:16 PM, RensDofferhoff ***@***.***> wrote:﻿
What are the language settings of your computer. Is it in Chinese or Korean?
What was the Filename of the csv? Is it possible to share the file? Or an empty file with the same name?

**Comment by JorisGoosen** [comment]
Or the computer of the friend had a different codepage than @katie17-cloud , and when friend saved csv they did so with a name using characters from that codepage.
Then on Katies system windows would already not have the correct characters let alone the utf8 conversion in JASP?

Would be nice to know the filename and if it was any different between the two computers.

**Comment by katie17-cloud** [comment]
This is the file I used. It opened fine on my friend's computer, but it showed an error on mine. Both computers have Windows 11 and use Korean language. When I changed the file name from Korean to English, JASP finally opened it correctly.


￼

**Comment by katie17-cloud** [comment]
The way I did it was this: I got an error message, so I sent the CSV file to my own email. Then, I opened it on my friend's computer and saw that it worked fine on his computer.

**Comment by JorisGoosen** [comment]
Hey sorry @katie17-cloud attachments are thrown away from emails to github.
Could you go to https://github.com/jasp-stats/jasp-issues/issues/2334 and upload the file there?

**Comment by katie17-cloud** [comment]
Sure. I uploaded the csv file in my original posting.

**Comment by JorisGoosen** [comment]
Ok, my point is, the filename looks like this on the githubpage: 
<img width="194" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/c990286d-bdf9-4831-8055-3c5eebb87017">

While the download looks like this:
<img width="150" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/7f37cc41-1d7c-4833-9d30-16f4158cc586">

either you or github removed the korean characters and I can thus open it without trouble.
But to really solve this problem I also need to see a screenshot of the filenames as they look on your computer.
Because I can not read korean nor can I be 100% be sure that what I see on my screen is the same as I would see on your screen.

Without this its hard to guess how to reproduce and fix this problem.

It would also be very useful to know the regional settings of your PC.
But just the screenshot alone would be very helpful
