### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by R180** [jasp-stats/jasp-issues#2342]
### JASP Version

0.18.1

### JASP Module

Mixed Models

### What analysis are you seeing the problem on?

Generalized; Logit

### What OS are you seeing the problem on?

Windows 10

### Bug Description

The 'dependent variable' has icons indicating that it will accept a nominal variable. However, it will not. Apparently, it will only accept an ordinal variable. 
![temp491Untitled](https://github.com/jasp-stats/jasp-issues/assets/16230091/11518d67-a1d2-4e26-a6c1-bb3fd4c79743)

See the attached example file (.
[Classical Logistic Linear Mixed Effect Model Will Not Take a Nominal DV.zip](https://github.com/jasp-stats/jasp-issues/files/12907434/Classical.Logistic.Linear.Mixed.Effect.Model.Will.Not.Take.a.Nominal.DV.zip)
jasp)

### Expected Behaviour

It should accept a (two-leveled) nominal variable.

### Steps to Reproduce

Open the attached jasp file.
Observe that the dependent variable field will not accept the nominal, 'response' variable.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by FBartos** [comment]
Sorry for the late response--I missed the original notification. The dependent variable accepts only numerical factors (0/1 coded for binomial family.  (I can see that you are trying to use a nominal text variable, i.e., variable where the values are strings rather than 0/1. 
You can use the compute new variable column in JASP function to transform your text levels into 0/1 levels. 

Please, re-open the issue in case this did not answer your question.

**Comment by R180** [comment]
Hi. The problem is there's a conflict between the actual behavior (as you put it, "The dependent variable accepts only numerical factors (0/1 coded for binomial family"), and the behavior that the interface advertises (the "circles," "bar-graph," and "ruler" icons tell the user--falsely--that the dependent-variable field also accepts nominal and ordinal variables). So the advertised ad actual behaviors need to be harmonized.

**Comment by FBartos** [comment]
That's not actually true, your response variable has a circle + "a" in the bottom right corner -- it's a string factor variable which is different from numeric factor variables. That is why you can't input the given variable.

The different families then allow for different input types, that's why there are multiple variable options (also, your 0/1 response for binomial family can be formated as scale or ordinal variable).

**Comment by R180** [comment]
ok.
