### ISSUE TITLE
[Bug]: Wrong values of Nagelkerke and Cox and Snell R^2 reported

### ISSUE THREAD

**Issue by Apratimguha** [jasp-stats/jasp-issues#2368]
### JASP Version

0.18.1

### JASP Module

Regression

### What analysis are you seeing the problem on?

Logistic Regression

### What OS are you seeing the problem on?

Windows 11

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/57554757/4eb24167-e5de-4706-a246-bff7b6e94b2d)

![image](https://github.com/jasp-stats/jasp-issues/assets/57554757/a921b174-2c58-4176-bbd3-ddba52678e14)

### Expected Behaviour

Both Nagelkerke R^2 and Cox and Snell R^2 are coming as 1. The later is not even theoretically possible, as this R^2 is capped at 0.75. Please check. Both SPSS and R are giving Nagelkerke R^2 as 0.212.

I shall share the data by email.

### Steps to Reproduce

1. Read the data.
2. Run logistic regression with "left" as response, and "last_evaluation" and "satisfaction_level" as predictors.
3. Look at various R^2 reported.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by Kucharssim** [comment]
Dear @Apratimguha,

Thank you a lot for reporting this bug and for sending the data set! I was able to reproduce the bug.

The issue caused by a numerical overflow, I made the calculations more robust to handle cases like yours.

**Comment by Kucharssim** [comment]
Unfortunately you will probably need to wait for a new release of JASP that implements this fix, unless you want to teach with a development version of JASP (which may or may not be compatible with other versions and may or may not be stable).

Otherwise, for smaller datasets than yours the calculations will likely not break, so if you are using this dataset for illustrative purposes you *could* make it smaller to avoid this bug in the current version of JASP. Or you can use this bug as a good example of being skeptical and always double check, and encourage your students to report bugs if they find any :))

**Comment by Apratimguha** [comment]
Hi,

I have just now encountered another bug, which is relatively more serious.
The confidence interval for mean, for "T model", is not changing when Width
is changed. I checked with multiple data sets and the error is always there.

With Best Regards,
Apratim

________________________________________________
অপ্রতিম গুহ | Apratim Guha
Professor, Production, Operations and Decision Sciences Area
XLRI  - Xavier School of Management
Jamshedpur, INDIA
Ph: 91-657-223-3452
