### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by koertstribos** [jasp-stats/jasp-issues#2380]
### JASP Version

0.18.1

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Bug happens as soon as I start JASP, it does not go away when minimizing and reentering the screen. When resizing my JASP window to some sizes, such as the smallest size possible, the screen looks normal.

![JASP_rip](https://github.com/jasp-stats/jasp-issues/assets/149697538/85fc927b-d620-44d0-8096-6689b6493587)

### Expected Behaviour

The window should work in all sizes

### Steps to Reproduce

Unsure if this bug also occurs on other devices, or where to look in my device to find the settings that lead to this.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by boutinb** [comment]
Hi @koertstribos if you resize to minimal, so that you can set in Preferences/Interface the 'Safe graphics mode', do you get then the same problem (if you have restarted JASP)?

**Comment by koertstribos** [comment]
Hello Bruno,

I have attached a compilation of my graphics specs, as well as my task
manager looking at performance.
In the task manager, I see that I have two GPU processes. GPU 1  is the
most active, and GPU 0 does not activate at all when opening JASP in safe
graphics mode.
I also opened JASP in Qt mode again, and I noticed that this process caused
some activation in GPU 0. I have added two screenshots of my task manager
in the compilation

I hope that you find these useful
kind regards,
Koert Stribos

**Comment by boutinb** [comment]
Hi @koertstribos If you want to attach some pictures, please do not use your email with attachments: this won't be added in the GitHub issue, and I cannot see them. Use instead directly the GitHub issue, and use the drag-and-drop to add your files.

**Comment by koertstribos** [comment]
Here is the image directly uploaded to github


![JASP_rip](https://github.com/jasp-stats/jasp-issues/assets/149697538/3fc927e9-4c7b-4a31-8ebd-7627e6b387c2)

**Comment by JorisGoosen** [comment]
@koertstribos the activation of GPU1 when in safe graphics mode is probably just the showing of JASP at all.
That GPU0 is activated when not in safe-graphics mode makes sense.

If you want to not be in safe graphics mode all the time there are I think 2 things you could do:
- try setting up your video driver to run JASP on the integrated GPU (GPU1) instead of GPU0 (Its not like jasp really needs to run on a dedicated card anyway)
- try updating the drivers to the latest version. I did not see any mention of what youve got installed but its probably fixed that way. Because the error from the screenshot in the issue does seem to be caused by your videocard and not by JASP
