### ISSUE TITLE
[Bug]: Prediction Error in "levels<-"

### ISSUE THREAD

**Issue by billybhaub** [jasp-stats/jasp-issues#2416]
### JASP Version

0.18.1

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Prediction

### What OS are you seeing the problem on?

Ubuntu

### Bug Description

I created a model with "boosting" in the machine learning module.

Then, when I loaded a new data set to test the model, I got this message :

-----
This analysis terminated unexpectedly.

Error in `levels<-`(`*tmp*`, value = as.character(levels)): factor level [3] is duplicated

Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)

.mlPredictionsTable(model, dataset, options, jaspResults, ready, position = 2)

.mlPredictionsState(model, dataset, options, jaspResults, ready)

createJaspState(.mlPredictionGetPredictions(model, dataset))

jaspStateR$new(object = object, dependencies = dependencies)

initialize(...)

.mlPredictionGetPredictions(model, dataset)

.mlPredictionGetPredictions.gbm(model, dataset)

gbm:::predict.gbm(model, newdata = dataset, n.trees = model[['n.trees']], type = 'response')

factor(x[, i], levels = object$var.levels[[i]])

To receive assistance with this problem, please report the message above at: https://jasp-stats.org/bug-reports
----

here's a screen shot : 
![Screenshot from 2023-11-15 15-42-50](https://github.com/jasp-stats/jasp-issues/assets/71944966/62f81b3b-ad79-4020-9d53-383a51279760)

### Expected Behaviour

The module should run the prediction normally.

### Steps to Reproduce

1. Create a "boosting" model
2. Open a new data set
3. Try to run the aforementionned model

### Log (if any)

I have the most recent logs, and I included the model I tried to use.

[JASP 2023-11-15 15_.zip](https://github.com/jasp-stats/jasp-issues/files/13370762/JASP.2023-11-15.15_.zip)

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by koenderks** [comment]
Hi @billybhaub,

First of all, thanks for reporting. It is a little difficult to find the error with just the logs, the data set that you used alongside a step-by-step reproducible example would be appreciated. I do notice some things that you may try first to fix this issue:

- I see that you loaded a trained model without the .jaspML extension. This does not work, all trained models are saved with the .jaspML extension, like shown below. In your case I just see `mlb_predictive_model_001` without the .jaspML extension. I think you can just remake and save the model, or alternatively, just add `.jaspML` as an extension to the model file.
<img width="120" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/25059399/030129fa-4b2a-49b9-a9a8-5ef8b726729d">

- I cannot see your data set but if there are spaces in any variable names these should be removed.

Let me know if this works. If not, maybe you can send your data set so that I can look further into the problem?

**Comment by billybhaub** [comment]
@koenderks Thanks for the reply.

The problem was effectively that the trained model file was lacking the extension.

I retrained it and saved it with the extension and it works.

What happened is that I assumed that JASP would add the extension. It could be a little "quality of life" improvement if it did, but it's absolutely just a detail 

Thank you very muche for the quick support.

**Comment by koenderks** [comment]
Good to hear that is worked! I was under the impression that JASP automatically adds the .jaspML extension, it does so on windows and mac. Could this be a ubuntu thing? @vandenman @JorisGoosen

**Comment by vandenman** [comment]
@koenderks I'm not sure why it doesn't get added automatically, but it doesn't hurt to check this in
https://github.com/jasp-stats/jaspMachineLearning/blob/7fa435c7dd55b3e739b5e7243a21df7755699f1c/R/commonMachineLearningRegression.R#L461

for example:
```r
path <- options[["savePath"]]
if (!endsWith(path, ".jaspML"))
  path <- paste0(path, ".jaspML")
```
