### ISSUE TITLE
[Feature Request]: Add PDF export preview and warning message for too large tables

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2484]
still valid for 0.19 beta

PDF export of large tables is broken, see example file: 

[Eigenvector Adult.zip](https://github.com/jasp-stats/jasp-issues/files/13740783/Eigenvector.Adult.zip)

and 
![grafik](https://github.com/jasp-stats/jasp-issues/assets/4428185/07a60ed3-9ad3-428c-9438-1c0b29e2665a)

### Expected Behaviour

exported tables should be truncated OR the user should get a warning message with a preview of the problem, when tables are bigger than DIN A4 and idealy be able to shrink the tables or change to A3 etc.

**Comment by boutinb** [comment]
`PDF export of large tables is broken, see example file:
[Uploading Eigenvector Adult.zip…](https://github.com/jasp-stats/jasp-issues/issues/2484)`

Hi @tomtomme your link points to this issue...

**Comment by tomtomme** [comment]
link fixed.
I did not wait long enough for the download to finish.

**Comment by shun2wang** [comment]
This is what I did intentionally at current... 

The reason is that very wide tables will be truncated when printed by the browser (about more than 15 columns)，this behaves consistently across all web browsers, and the truncation is difficult for users to notice. so I force them to be arranged on the same page (about 30 columns) to fit common A4 pages see: https://github.com/jasp-stats/jasp-desktop/pull/5248.

This is difficult to implement a behaves consistently. A better approach would be to provide a print preview for resizing crowded pages, such as optional A2, A1 size pages, although I doubt people would need such a large paper to print such a wide table.Or extremely small fonts allow users to zoom in and out of the PDF to read.

@boutinb what do you think.

**Comment by boutinb** [comment]
I'm not so sure if we have to handle this, because it seems to me that the user will know that a wide table will not fit in A4. What we could do maybe is to add an option to show how it looks like in a A4 pdf, so that before exporting it, the user can change some analysis options, or change the zoom level to fit it better.

**Comment by tomtomme** [comment]
fixed by new PDF settings for landscape mode and paper size
