### ISSUE TITLE
[Feature Request]: splitting/grouping by multiple factors

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#2492]
### Description

As discussed in https://forum.cogsci.nl/discussion/4066/split-data-by-more-than-one-factor-without-multiple-spreadsheets and https://forum.cogsci.nl/discussion/7912/jasp-split-by-two-factors , it could be useful to allow splitting by more than one factor. This seems to be useful for descriptives, T-tests and possibly more modules.

### Purpose

Easier multi-factor splitting without creating separate files or adding columns.

### Use-case

One of the forum threads talks about splitting by gender and income groups. Another usecase is splitting by gender, then by experimental manipulation. This would end up splitting in a "multiple of all factors" number of groups.

### Describe the solution you would like

Ability to add more than one factor to split/group by.

### Describe alternatives that you have considered

Manual data splitting or additional columns

**Comment by tomtomme** [comment]
I do see how this is useful for descriptives and the module "visual modeling => flexplot" already solves this visually. 
I do not see how this is useful for t-Tests, as afaik only ANOVAs alow multifactorial designs and there this functionality already exists, also on the descriptive level. So you can just use the ANOVA module if your IVs are categorial, correct?

If you think of multiple t-tests, each with one factor, but different factors over all those t-Tests, this is also already solved by duplicating the t-Test via the green +Button or just opening multiple t-Tests or descriptive analysis tabs.

In the forum thread it sounds to be a bit more about splitting the file and I do not know why you would want to do that, since we have filters for that. Running the analysis only for one gender? Filter for men, then save the file. Filter for women, then save into a second file. This way you do not really have to split your data file and can always go back to full data by disabling the filter. 
Also: Instead of this "splitting" you might want use the gender or income variable as a covariate or go mixed model or something. This is also true for correlations for different income bands as mentioned in the forum post. This is might be a mixed model too. I do not think it is good to do those correlations separately for all those different income bands, even if the analysis is at an exploratory state. 

Again, I might misunderstand the problem you or the forum poster want to solve. Maybe you can detail your request a bit more.

**Comment by richlv** [comment]
I might have not been that familiar with filtering, it might indeed be possible to avoid file splitting that way.
Not sure about the exact usecase for the forum posters, but my example indeed involved descriptives, where I ended up creating a new column with the 4 different values - being able to add multiple factors would allow to skip the separate column.

**Comment by tomtomme** [comment]
I guess, since ANOVA already implements splitting descriptives table by multiple factors this should be possible to implement for the descriptives module too. 

@vandenman 
Is this feasible?

**Comment by JorisGoosen** [comment]
Wouldnt this fall more under #33 ?

**Comment by tomtomme** [comment]
@JorisGoosen 
I do not see how this is related. This is just about alowing a second split factor in descriptives like jamovi allows also, see: 
![194449760-2a62f0a0-c19e-4fb1-88b6-2a15ee887041](https://github.com/jasp-stats/jasp-issues/assets/4428185/ff11e948-97a9-4886-80ed-8c29c15f37cd)

from the duplicate https://github.com/jasp-stats/jasp-issues/issues/1850

**Comment by tomtomme** [comment]
Now tracked here: #2649
