### ISSUE TITLE
Application was unable to start correctly (0xc0000022)

### ISSUE THREAD

**Issue by philfletcher** [jasp-stats/jasp-issues#2524]
### Description

Application was unable to start correctly (0xc0000022)

### Is your feature request related to a problem?

Application was unable to start correctly (0xc0000022)

### Additional context

Ive tried and the university IT department have to install JASP on my windows 11 Dell laptop. It goes through the whole install until it time to launch the program it says Application was unable to start correctly (0xc0000022) Click OK to close the application. Ive tried reinstalling from the website and saving on USB to install and nothing. Having googled the Application error it says about permissions which i have allowed full access but still not working. Any help or advise would be amazing.

**Comment by JorisGoosen** [comment]
Have you tried using the zip release?

**Comment by philfletcher** [comment]
Hi yes but same issue

**Comment by RensDofferhoff** [comment]
That is very strange.
Does our windows store installer also not work? https://www.microsoft.com/store/apps/9P08CWG12JNL
Its an isolated runtime so it definitely should.

If not we will have to debug this using procmon which is very tricky.

**Comment by boutinb** [comment]
Could you also try to start JASP from the command line:

- Start a command prompt by typing 'command prompt' in the Start menu.
- Type "c:\Program Files (x86)\JASP\JASP.exe --safeGraphics" > log.txt to start JASP. (if JASP is installed in c:\Program Files (x86), if installed somewhere else, change the path to JASP.exe)
- Check whether JASP starts or not.
- Type 'notepad log.txt' to see the log file.
- Send me this log file in a comment of this GitHub issue.

**Comment by tomtomme** [comment]
This one reminds me of the proxy issue, because "university" and jasp just not starting. But sure, the error message is different, so might also be not correlated at all. Fore reference:
https://github.com/jasp-stats/jasp-issues/issues/1880
https://github.com/jasp-stats/jasp-issues/issues/1773
https://github.com/jasp-stats/jasp-issues/issues/1986

@philfletcher 
a) If you switch internet off, and then try to start jasp - does that work? If yes, its the proxy thing.
b) microsoft also suggests, that this might be a corrupt filesystem, see: https://answers.microsoft.com/en-us/windows/forum/all/the-application-was-unable-to-start-correctly/e06ee08a-26c5-447a-80bd-ed339488d0f3
