### ISSUE TITLE
[Bug]: Computed column does not respect the filtering exclusions

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#2553]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Generic

### What OS are you seeing the problem on?

Windows 11

### Bug Description

From Dan Simons:
"  I have a class dataset with three groups in it representing data from different class years as well as 300 additional simulated data rows (2022, 2024, and simulated). I had filtered to exclude the simulated data so that we're dealing with data from the actual classes. I then created a new computed column for deviation scores for an extraversion measure:
Extraversion - Mean(Extraversion)

  It seems that the mean(Extraversion) part does not respect the filtering exclusions. That is, it computed a mean across all 400 data points, including the 300 simulated data points and not just the 100 data rows from the 2022 and 2024 class years. That is, the computation wasn't limited to the included rows only.

 I'm guessing that the mean function was not written to respect the previous filter operation. I didn't check any of the other operations for computing new columns (e.g., standard deviation, scale, etc.), but I'm guessing they have the same issue. 

 I'm not sure how easy that is to fix given that it would either require refreshing all calculated columns with each new filtering operation or would require separate columns and some sort of indicator of whether it did or didn't respect filtering. But the current version is problematic if people assume that means are calculated only on the included data. Maybe there could be a toggle to "respect filtering" in some way?

  The descriptives and other statistics all appear to respect the filtering. It's just the computation of new columns that can be an issue for things like computed deviation scores (using the wrong mean)."

### Expected Behaviour

Computed column should respect the filtering exclusions

### Steps to Reproduce

I am copy-pasting from Dan's email, and will follow up with a question immediately

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by EJWagenmakers** [comment]
This does seem like an important bug to fix. I vaguely recall that this was pointed out before, but maybe not...

**Comment by boutinb** [comment]
I have just made a test, and I can see that a computed column takes care of the filter. So I cannot reproduce the problem is I don't have an example. Can I have a JASP file where I can check the issue?

**Comment by tomtomme** [comment]
Works also fine on my end

**Comment by boutinb** [comment]
Oh I can reproduce it with the Debug DataSet: make a "facFifty - Mean" computed column with as value `facFify - mean(facFiflty`, and remove the 1 in the contBinom, then the Mean of "FacFifty - Mean" column is not 0 but the mean of the filtered facFifty (24.155) minus the mean of the non-filtered facFifty (25.5), that is -1.345.
So the computed column is computed with the whole dataset and not the filtered dataset.

![Screenshot 2024-01-31 at 13 18 16](https://github.com/jasp-stats/jasp-issues/assets/503332/3cf951ca-cd73-4e88-bdee-d0a1b4424fcb)

This problem exists in fact since the computed columns feature was added in JASP.
One issue is then: what to do when a computed column is used in the filter self? This becomes a vicious circle...
We could add a checkbox in the Computed Column, like 'Use filtered data'. Per default is it unset (since it is the current default value). If it is set, it uses the filtered data, but it cannot be used anymore in a filter.

**Comment by profsimons-uiuc** [comment]
Another possibility would be to add the ability to filter as part of computing a column so that the filtering is specific to that computed column.  The column could then indicate that it was both filtered and computed. That might lead to some rows being empty for that computed variable, but it would give a clear indication of how it was computed even if people change the overall filtering later. That approach also would have another advantage - it would make it possible to have analyses based on different filtering within the same JASP file, something that's not currently possible as far as I can tell. Users could create two versions of the relevant column with different filtering and have analyses for each.

**Comment by JorisGoosen** [comment]
> Another possibility would be to add the ability to filter as part of computing a column so that the filtering is specific to that computed column. 

That is a great idea.
Just add a function like 'loadFilter("Filter 1")' to JASP, also under a nice dropdown that generates it for the drag&drop interface.
If that is combined with the support for multiple filters then the computed column knows which filter to use and JASP can detect any loops. Similar to how computed columns themselves already work

**Comment by tomtomme** [comment]
Everybody seems to agree that this is a "critical bug".
We should really do something about it before 0.19, should we not? At least document the bug properly as I suggested earlier, which is not yet done with 0.19 beta as of June 18th.

**Comment by JorisGoosen** [comment]
@tomtomme I am open to a pullrequest changing the help file, but I have no time to look into this problem and I go on vacation for quite a while after today.

So this will be done in 0.19.1 or maybe 0.20.
In the PR https://github.com/jasp-stats/jasp-desktop/pull/5576 here I did already make sure that the computed-columns/filtering data loading backend can respect filtering or not. But it requires a bit more work on the processing of the data side...

**Comment by tomtomme** [comment]
@JorisGoosen 
You are completely correct of course. _I_ should do something about this now @RensDofferhoff pulled it off to get the dev modus working on flatpak. So, sorry for sounding demanding. You and Rens and everybody in the team outdid themselves again during 0.19 developement. 
So yeah, maybe I can set it all up next week. Atm I have a cold and cannot think straight enough to pull it off.

Have a nice vacation Joris!

**Comment by JorisGoosen** [comment]
> So, sorry for sounding demanding. You and Rens and everybody in the team outdid themselves again during 0.19 developement. 

It's okay, it can be hard to have nice nuanced comunication through text-threads like these.
The new release is hopefully going to be a massive improvement ^^

> Atm I have a cold and cannot think straight enough to pull it off.

Gute besserung!

> Have a nice vacation Joris!

Thank you ^^
