### ISSUE TITLE
[Bug]: Greyed out "no data" button and missing handles

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2555]
### JASP Version

0.19 beta

### JASP Module

Distributions and others that do not need data to be started.

### Bug Description

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/e22e8d49-882b-4d38-a3ce-3cc0a74b03bc)

If I start JASP without data and then select an analysis that can rund without data, the handles on the left are missing and the "edit data" button becomes a greyed out "no data" button. I have to delete the analysis, to get back to data view or enter data. And I probablo do NOT want to delete the analyses.

Also, after starting this way, JASP hard crashes earlier or later completely, e.g. on entering data after closing the analysis or on deleting rows, columns etc.

### Expected Behaviour

Using a data-less module should not prevent me from getting back into data view or edit data mode.

### Steps to Reproduce

1. start jasp
2. open a distribution module

**Comment by boutinb** [comment]
I think we decided years ago to implement this behaviour because some analyses reacted differently with a dataset or not, but I can't see now what was the problem really: I can just see that some options are disabled when no dataset is loaded. But that won't change the results if a dataset is added.
Another argument is maybe that if JASP has already some analyses, if you open a data file, you expect then a new JASP instance to be started. But this is debatable in case the analyses have no dataset... One could say that if the dataset is loaded in the same JASP instance, there would be no (easy) way to start a new JASP instance...
Maybe the reasons we had to implement this behaviour are not relevant anymore.
We could maybe add a new option in the File menu "Add datafile in this workspace" if analyses already exist but have no data.
Any thought @EJWagenmakers, @Kucharssim, @vandenman ?
