### ISSUE TITLE
Make debug.csv great again

### ISSUE THREAD

**Issue by FBartos** [jasp-stats/jasp-issues#2558]
### JASP Version

0.18.3

### JASP Module

Unrelated

### What OS are you seeing the problem on?

Windows 11

### Bug Description

Seems like some of the comma handling fixes messed up csv loading of the debug,csv.
For example, running unit tests in R using the following 
```
results <- jaspTools::runAnalysis("ClassicalMetaAnalysis", "debug.csv", options)
```
results in loading only 99 rows instead of 100.
Probably affects unit tests of other modules too.

### Expected Behaviour

work

### Steps to Reproduce

...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JorisGoosen** [comment]
@vandenman this is most likely part of what broke a bunch of unittests.

Probably cause of my changes to debug.csv in https://github.com/jasp-stats/jasp-desktop/commit/349ea62d80582047bdf8f66b3dea5080f9361b24

Those changes are totally fine in JASP, but I (and @boutinb) were entirely unaware that that same dataset was also used for unittests.
I would like to keep this weird debug.csv in JASP because it helps us detect weird comma-sensitivities issues a bit earlier than after release...

But I also dont wanna break the R-unittests..
So perhaps we can just put the original `debug.csv` in jaspTools or something?

**Comment by vandenman** [comment]
>  So perhaps we can just put the original debug.csv in jaspTools or something?

This is also a solution. Do you prefer that?

In fact...  there is already this file:

https://github.com/jasp-stats/jaspTools/blob/4a510a8b933aef1d3025cf79749af9070e80b2cf/inst/extdata/test.csv

So I could just make the name "debug.csv" resolve to that file and never to the file in jasp.

But, it would be pretty confusing for people if `debug` is a different dataset in jasp than it is in `jaspTools`.

Isn't it possible for you to revert the changes and use a different dataset for debugging that is fine to change? E.g., just add debug2.csv or so. If you want, I can make it impossible to then use that file through jaspTools.

**Comment by FBartos** [comment]
Yeah, I agree with Don that having a different debug in JASP and jaspTools would be confusing---we often use the JASP one to generate unit tests later run with jaspTools one, so these should be identical...

**Comment by JorisGoosen** [comment]
See PR ^^
