### ISSUE TITLE
[Bug]: lavaan ERROR: some models (but not all) have a meanstructure

### ISSUE THREAD

**Issue by DonaSonrisa** [jasp-stats/jasp-issues#2574]
### JASP Version

0.18.3

### JASP Module

SEM

### What analysis are you seeing the problem on?

Multigroup SEM

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

Trying to calculate the multigroup measurement invariance with JASP's SEM Module. (Following the instructions here:(https://jasp-stats.org/2022/01/25/measurement-invariance-testing-using-the-structural-equation-modeling-sem-module-in-jasp/))
When adding Model 3 I receive this error:
Error in (function (object, ..., method = 'default', A.method = 'delta', : lavaan ERROR: some models (but not all) have a meanstructure

### Expected Behaviour

<img width="1314" alt="Screenshot 2024-02-10 at 2 50 29 PM" src="https://github.com/jasp-stats/jasp-issues/assets/159508616/de93d022-1bbc-4d5a-b830-329f06e026d6">
[Final V2 deleted reversed.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14228404/Final.V2.deleted.reversed.jasp.zip)

### Steps to Reproduce

1. Model 1: #factor loadings
CE =~ Ca + Cb + Cc
FX =~ Fa + Fb + Fc
SI =~ Sa + Sb + Sc
ES =~ Ea + Eb + Ec
OP =~ Oa + Ob + Oc
2. Model 2: #factor loadings (labeled equal)
CE =~ c1*Ca + c2*Cb + c3*Cc
FX =~ f1*Fa + f2*Fb + f3*Fc
SI =~ s1*Sa + s2*Sb + s3*Sc
ES =~ e1*Ea + e2*Eb + e3*Ec
OP =~ o1*Oa + o2*Ob + o3*Oc
3. Model 3:#factor loadings (labeled equal)
CE =~ c1*Ca + c2*Cb + c3*Cc
FX =~ f1*Fa + f2*Fb + f3*Fc
SI =~ s1*Sa + s2*Sb + s3*Sc
ES =~ e1*Ea + e2*Eb + e3*Ec
OP =~ o1*Oa + o2*Ob + o3*Oc

Ca~a*1
Cb~b*1
Cc~c*1
Fa~d*1
Fb~e*1
Fc~f*1
Sa~g*1
Sb~h*1
Sc~i*1
Ea~j*1
Eb~l*1
Ec~k*1
Oa~m*1
Ob~n*1
Oc~o*1

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@DonaSonrisa 
Can you share your .jasp file by renaming to .zip and drag and drop here?
Easier to debug then

**Comment by DonaSonrisa** [comment]
[Final V2 deleted reversed.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14231088/Final.V2.deleted.reversed.jasp.zip)

**Comment by tomtomme** [comment]
@DonaSonrisa 
See
[fi.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/14231755/fi.jasp.zip)
I reconstructed your code and ran the analysis without any errors.
Please download and check if I made different settings than you wanted etc. because your jasp file did only contain data, no settings or code.
If you still get an error with your settings pleas upload your jasp file including all settings and code again! Thx!

And next time you want to post model code within a commen put it in code brackets available from the formatting buttons above each comment window, like so:

```
CE =~ Ca + Cb + Cc
FX =~ Fa + Fb + Fc
SI =~ Sa + Sb + Sc
ES =~ Ea + Eb + Ec
OP =~ Oa + Ob + Oc
```
```
CE =~ c1*Ca + c2*Cb + c3*Cc
FX =~ f1*Fa + f2*Fb + f3*Fc
SI =~ s1*Sa + s2*Sb + s3*Sc
ES =~ e1*Ea + e2*Eb + e3*Ec
OP =~ o1*Oa + o2*Ob + o3*Oc
```
```
CE =~ c1*Ca + c2*Cb + c3*Cc
FX =~ f1*Fa + f2*Fb + f3*Fc
SI =~ s1*Sa + s2*Sb + s3*Sc
ES =~ e1*Ea + e2*Eb + e3*Ec
OP =~ o1*Oa + o2*Ob + o3*Oc

Ca~a*1
Cb~b*1
Cc~c*1
Fa~d*1
Fb~e*1
Fc~f*1
Sa~g*1
Sb~h*1
Sc~i*1
Ea~j*1
Eb~l*1
Ec~k*1
Oa~m*1
Ob~n*1
Oc~o*1
```

**Comment by DonaSonrisa** [comment]
@tomtomme Thanks for the reply and the hint re posting code, I pretty much have no idea what I am doing!
I'm still getting an error code on the third model. The only setting I have changed is the estimator to DWLS (and then the missing data handling to listwise deletion).

**Comment by tomtomme** [comment]
@DonaSonrisa 
Thx for the details. There we have it. The error is produced with "listwise deletion" and "pairwise deletion". This must be a bug, since you do not have any missings.
The solution for you at the moment is to just use the default "FIML". It does not matter since you do not have missings anyway. Also you cannot use DWLS in combination with FIML, so just leave it to Auto. If you cannot do that you will have to wait for a fix via the next jasp verstion 0.19 coming in a month or so.

**Comment by juliuspfadt** [comment]
@DonaSonrisa what is your grouping variable? Could you share all the options?

**Comment by DonaSonrisa** [comment]
@juliuspfadt 
The grouping variable is 'Groups'. 
The scale items have been parcelled for ease but are taken from a Likert scale which is why I am using DWLS.

**Comment by juliuspfadt** [comment]
@DonaSonrisa, I assume you mean "Group"? Anyways, I think the issues comes from the fact that you are comparing three models that cannot be compared, since the third model estimates a mean structure while the first two do not. When you do not specify a group, you also see that the models are equivalent: even though you specify intercepts in Model 3 they are not estimated when there is no grouping.  
So what you can do is estimate model 1 and 2 independently from model 3. in any case you cannot compare all three models.

**Comment by juliuspfadt** [comment]
But the fact that changing back to FIML rectifies the error is strange, and I should look into it.

**Comment by juliuspfadt** [comment]
Ah, so my original point stands, you can only compare the models if all have a meanstructure specified. When FIML was chosen as a missing data handling the underlying R package automatically adds a meanstructure to the model even of none was specifically requested. So when changing to listwise, we actually obtain model that are not nested anymore so the analysis fails. I would close this as it is actually desired behavior, and the error message seems informative enough in my opinion. Feel free to re-open.
