### ISSUE TITLE
[Feature Request]: Move "Reset scales" button

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2575]
Valid for japs 0.19 beta

"Reset scales" button seems burried. Could be moved somewhere into data edit mode. But where?

(Other remarks were invalid)

**Comment by boutinb** [comment]
These are 2 different things: the workspace settings are the settings of the current JASP file (you have loaded, of you are making), the data preference settings are the settings of the user. This difference is quite important especially for the missing values: someone else can make a JASP file with some missing values setting. If another user opens this JASP file, the same missing values settings must be used, but they are not necessarily the same as the missing values of the user: in this case the workspace settings of the missing values are different than the ones of the data preference.

**Comment by tomtomme** [comment]
@boutinb 
ah thx for the explainer.
It would still be nice to have the "Import threshold" stuff more visible within data edit mode, not burried in the settings. But the "workspace" sidebar sounds not to be the right place, now that I know what its for...

**Comment by boutinb** [comment]
Simple, clear, logical, Intuitive user interface is a difficult job! 
A Data Preference menu seems to me quite logical: they are the settings settable by the user how he wants the data to be read. But it is true that the button 'Reset types of loaded variables' is an action on the current data, so it could be in the workspace settings. In this case, we would have to display which threshold the button will use, this threshold should be also settable (would be annoying not to be able to set the threshold), duplicating the feature in the Data Preference... Both thresholds should be synchronized I suppose (strange to have different values in the workspace and in the Data preferences), but then it would be even stranger to have this setting synchronized, and not the Missing Values settings (the Missing Values should not be synchronized as explained before)...
Well, if you have an idea of a clean interface so that every people in the world would immediately understand, you are more than welcome!

**Comment by tomtomme** [comment]
I will think about it

**Comment by JorisGoosen** [comment]
The threshold button could be added in the "right side menu" (where the modules are shown in analysis mode).
Might be better than changes the settings and applying them from the preferences.

**Comment by tomtomme** [comment]
@JorisGoosen @boutinb 
I think it would be strange to see the button within analysis mode. I tried with a mockup, but it looks too crammed:

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/50891bd8-6f7f-4970-b15b-2d5675a926d7)

Source file, if you wanna try to refine it:
[mockup.odt](https://github.com/jasp-stats/jasp-issues/files/14307849/mockup.odt)

**Comment by JorisGoosen** [comment]
<img width="1276" alt="image" src="https://github.com/jasp-stats/jasp-issues/assets/29062713/d73ebc58-4cc8-4e5e-8144-8c4654208eaf">
It would only be visible in editing mode anyway, the right hand side of this.

I think this functionality is not something you need so often (as it resets all the data) so im not sure the ribbon is the right place for it. It would also require changes to the "RibbonButton"s and putting it in the sidemenu would be way easier in any case. Also allows for extra info there.

**Comment by JorisGoosen** [comment]
> @JorisGoosen putting it in the side bar is fine by me, but @boutinb also had some fine remarks on why that might be confusing. So I will let you two figure that one out :D O_o

Did he?
I dont think I read that in his comment.

He just mentions that having the setting duplicated would be confusing, but I wouldnt put it there as a "setting".
I would put it as a button that reinterprets the data when clicked.

Then there is also the data-preference thing, which would not have the button.
But actually this should of course be part of the import-data-GUI somehow.

In any case, I think it is a bit weird to use this feature too much in any case.
Because pressing that button would drop lots of information from the columns in any case.

While if someone really just wants to change the datatype they can easily do so...

**Comment by tomtomme** [comment]
@JorisGoosen 
Maybe I misinterpret boutinbs comment. And I will leave you to it, to implement this button somewhere else or not. Its just a bit burried atm, but I can put that in my tutorials and the students will find it hopefully :D

What I do not understand - why would pressing that button would drop information? Changing scales in the past never dropped information - only as of recent versions labels are lost and if I understood correctly you try to fix this currently.

**Comment by tomtomme** [comment]
closing in favor of implementing https://github.com/jasp-stats/jasp-issues/issues/2483
