### ISSUE TITLE
[Bug]: Labels missing

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#2594]
### Bug Description

https://github.com/jasp-stats/jasp-issues/labels

This site misses labels for
- the new Process module
- Chromebooks as a hardware platform
- MSIX / WinStore installer
- Results / Tables
- import / export

**Comment by boutinb** [comment]
Hi @tomtomme I have added the "Module: jaspProcess" and the "OS: Chromebook" labels
I think we could structure beter some labels: there are now the labels 'Accessibility', 'Data Editing', 'Fonts', 'Graph Plots', 'Plot Editing', 'R Syntax', that can be grouped with 'Component: Accessibility', 'Component: Data Editing', etc.. with one color, and there I can add 'Component: Result Tables', and 'Component: import / export'.
What do you mean exactly by 'MSIX / WinStore installer': is it for issues that occur during the JASP installation? Because for this we have the 'install' label. We could also have a new kind of labels 'Installer...': 'Installer: Windows ZIP', 'Installer: Windows MSIX', 'Installer: MS Store' (we may have one day 'Installer: Apple Store'...).
I'm not sure of the usefulness of the 'First project' label.

**Comment by tomtomme** [comment]
@boutinb 

Yes, I like the idea of "component: ..." and "installer: ..." 

But shouldn't it be?
Installer: Windows ZIP
Installer: Windows MSI
Installer: MS Store (MSIX)

If I understood correctly, jasp-stats.org still always downloads the old MSI installer and MS Store always uses the new MSIX. But the old MSI will be phased out in the coming months.
The 3 above then would replace the generic install label. Or maybe that should stay to not loose those labels from old issues.

The "First project" label is used to indicate issues, that can be picked up easily by new JASP developers / students. I guess that should stay.

**Comment by boutinb** [comment]
OK, you are right with the installer. I have updated the labels.

**Comment by boutinb** [comment]
One issue less!

**Comment by boutinb** [comment]
Done

**Comment by tomtomme** [comment]
loving it
