### ISSUE TITLE
[Bug]:  random forest bug in prediction

### ISSUE THREAD

**Issue by fnkie** [jasp-stats/jasp-issues#2600]
### JASP Version

0.18.3

### JASP Module

Machine Learning

### What analysis are you seeing the problem on?

Random Forest Classification

### What OS are you seeing the problem on?

Windows 10

### Bug Description

This analysis terminated unexpectedly.
Error in randomForest:::predict.randomForest(model, newdata = dataset): New factor levels not present in the training data
Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
.mlPredictionsTable(model, dataset, options, jaspResults, ready, position = 2)
.mlPredictionsState(model, dataset, options, jaspResults, ready)
createJaspState(.mlPredictionGetPredictions(model, dataset))
jaspStateR$new(object = object, dependencies = dependencies)
initialize(...)
.mlPredictionGetPredictions(model, dataset)
.mlPredictionGetPredictions.randomForest(model, dataset)
randomForest:::predict.randomForest(model, newdata = dataset)
stop('New factor levels not present in the training data')

### Expected Behaviour

the predictive model should have given a result but does not run it gives an error message

### Steps to Reproduce

1.
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [ ] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@fnkie 
can you share your .jasp file by renaming to .zip and then drag and drop here?
makes it easier to see whats going on.

**Comment by koenderks** [comment]
It is a message from R, which we may catch but not solve. The problem is in the dataset you want to make predictions about. In general, you cannot make predictions using discrete data with values that the algorithm has never seen before in the training set. That is because the algorithm did not learn the relationship between these unseen factor levels and the outcome variable. I would remove the factor levels that were not in the training data and make predictions for the remaining data, or create the training set such that these levels are present in the training data.
