### ISSUE TITLE
JASP creates quite different results for Wilcoxon test compared to SPSS

### ISSUE THREAD

**Issue by MichlF** [jasp-stats/jasp-issues#263]
* JASP version: 9.1.0.
* OS name and version: Windows 10
* Bug description: As can be seen from the two pictures, a Wilcoxon test of related samples (paired samples t-test) creates quite different output. At least the Z values are very odd in JASP. Either they are very high or just 0.
[wilcoxon.zip](https://github.com/jasp-stats/jasp-issues/files/2643726/wilcoxon.zip)

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn ?

**Comment by JohnnyDoorn** [comment]
Hi Mich,
JASP reports Wilcoxon's W statistic that is also reported by R's wilcox.test() function.
It is obtained by summing up the positive ranks of the differences - since the pairs are turned around in your setup for JASP and SPSS, you can look at the 'negative ranks' numbers to see the same numbers as you see in JASP under 'Statistic'. 
The effect size that JASP reports is not the Z-value - your image missed the footnote of the table that states that the effect size for Wilcoxon is the matched rank-biserial correlation. 
I hope this clarifies it for you, please let me know if you have any additional questions!
Johnny

**Comment by MichlF** [comment]
Cristal-clear Johnny!
Thanks so much.

**Comment by einGlasRotwein** [comment]
Heya,

I don't know if this is still relevant, but if you are looking to compare the SPSS statistics to the JASP/R statistics, this might be good to know. I came here because I wanted to report the results of a wilcox.text (paired = FALSE, i.e. Mann-Whitney U) "SPSS like", i.e. reporting U, not W. Like you do e.g. in APA style.

You will read online that the U statistic (from SPSS) is basically the W that R (and JASP) gives you. However, I noted that they don't correspond ALL the time. Digging deeper, I stumbled across [this link](https://www-01.ibm.com/support/docview.wss?uid=swg21479010) explaining that there are two Us that can be calculated - one for each group. SPSS will always give you the smaller one of the two. R, however, gives you W that corresponds to the U of the first group provided as input. So, only if that one happens to be the smaller one, JASP/R and SPSS will correspond.

You can specify the order of groups in R, but using the JASP interface, you might not even be aware that the order matters. It will give you W corresponding to the U of the first group in your grouping variable. Try it and switch the order of the groups around - you will get a different W!

You can calculate the second U if you know the first U and the size of both groups:
U2 = n of group1 * n of group2 - U1

Using R, this can be easily implemented in a function (which was my solution for the problem), but using only JASP, you can just switch the labels of your group (clicking on the variable name and using the little arrows), re-run the test and then report the smaller W as SPSS-like U.
