### ISSUE TITLE
[Bug]: WLSMV corrected statistics are not reported in the output

### ISSUE THREAD

**Issue by PetrPalisek** [jasp-stats/jasp-issues#2644]
### JASP Version

0.18.3

### JASP Module

Factor, SEM

### What analysis are you seeing the problem on?

SEM / CFA

### What OS are you seeing the problem on?

macOS Silicon

### Bug Description

JASP's SEM module appears to correctly use the WLSMV estimation procedure via the combination of selecting robust SEs and scaled+shifted test statistics, but it fails to report the corrected test statistics in the fit indices section. It appears JASP simply does not read the second column in the lavaan::summary(model)
<img width="920" alt="Screenshot 2024-03-23 at 18 55 03" src="https://github.com/jasp-stats/jasp-issues/assets/61236825/5203cb64-bda9-4d47-b96d-5f0469803e26">

### Expected Behaviour

JASP should have reported both version of the fit indices, just as lavaan does. Factor module should provide a WLSMV option as well.

### Steps to Reproduce

1. Fit any SEM on ordinal items
2. Select robust standard errors and scaled and shifted test statistic.

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@PetrPalisek 
This sounds like a feature request... is it?

**Comment by tomtomme** [comment]
@juliuspfadt 
Can you help out here? Thx

**Comment by juliuspfadt** [comment]
thats correct. it is a bug. those should be changed. I am wondering however, since when lavaan also puts out a regular, a scaled, and a robust value for each of the fit indices (that are based on chi^2). I will look into it.

**Comment by brianmsm** [comment]
Whenever a different standard estimator (MLR, WLSM, WLSMV, etc.) is used, lavaan calculates the fit indices for the standard test and for the specific test (satorra bentler, yuan bentler, mplus yuan bentler, adjusted mean variance, or scaled-shifted).

Because of this, the lavaan output with summary(fit, fit.measures = TRUE) usually shows 2 columns (first for standard, and second for the requested test). You could use the same decision rule that lavaan uses for the detection of the test used or create your own:

https://github.com/yrosseel/lavaan/blob/da18deb8e6f0152b5074af7f028132e5704d19c1/R/lav_fit_measures.R#L195-L211

In the jaspFactor module there is already a relatively functional way of reporting the reported fit indices depending on the estimator used:

https://github.com/jasp-stats/jaspFactor/blob/3d95858eb087d9993704c10e5cde4e6d4ef3238d/R/confirmatoryfactoranalysis.R#L434-L446

Unfortunately it also has a bug that it only does it correctly if you leave the setting on “Auto” (default), but when set to “DWLS” it stops working, because the coding is neglecting that option (wasn't sure whether to create a separate issue about this)

Default:

![image](https://github.com/jasp-stats/jasp-issues/assets/28207224/1f114efb-9e11-4b48-ad27-2fd0c12c84e4)

Selecting DWLS (which should be the same):

![image](https://github.com/jasp-stats/jasp-issues/assets/28207224/12b91cc9-1fd2-456f-9aef-f7a7866855f0)

**Comment by juliuspfadt** [comment]
thanks all for finding these and providing the resources. I will try getting to these over the summer.
