### ISSUE TITLE
[Feature Request]: bar charts for descriptives

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#2706]
### Description

Bar charts should be added to the descriptives module along the lines of ANOVA etc

### Is your feature request related to a JASP module?

Descriptives

### Additional context

I thought they had been implemented? But either I'm imagining this or I can't find them any longer?

**Comment by tomtomme** [comment]
they are implemented for nominal and ordinal data via distribution plots. If you switch to metric / scale you get histograms. Is this sufficient?

**Comment by tomtomme** [comment]
@TarandeepKang 
not really and kind of at the same time.
0.19 beta now has this:

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/ceadfce3-866e-4eda-93db-24753a880052)

Both flexplot and rainclouds are quite flexible and customizable, e.g.:

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/617c6aad-4cca-4e75-b52d-7f22d1acd396)


But of course we always could add more customizations and plots. I also think that the Descriptives Module should stay (already is) the central hub for plotting, but some specialized plots will stay with their analysis (e.g. forest plot with meta-analysis) since it would probably be hard to implement/copy ALL plots to descriptives.
At some point the main descriptives module could be split in "statistics" and "plots" maybe, so that the module does not get that overwhelmingly big. But at the same time splitting in those 2 would seem artificial since those descriptives kind of belong to those plots... 
Maybe you have a more fleshed out idea?

**Comment by TarandeepKang** [comment]
Well, a little. Most other GUI based statistics programs have a centralised chart building area and I wonder if it wouldn't be a good idea to create something like that? That would be as an especially good idea once be start adding clustered and stacked bar charts/ mosaic as well as doughnut, ring and radar that I saw you had made an issue for somewhere else, etc.


To go back to the bar charts above, one thing I wonder whether it would be able good idea to do when creating bar charts in the descriptives module is have horizontal axis and separate plots boxes like elsewhere?

**Comment by tomtomme** [comment]
We have stacked density and stacked histogram will come with 0.19. make them horizontally would be cool. I will add that to my other issue.

I guess stacked bars and rings etc could be added in the same way under customizable plots.
Other multivariate plots would fit in there too. And once you go >3 vars flexplot got you covered already.
So I still do not see yet the need for a separate module. And I also do not like that other stat packages tend to hide plots away into a separate, slightly complicated gui (I am looking at you SPSS ;))

What did you mean with "...separate plots boxes like elsewhere?"

**Comment by TarandeepKang** [comment]
I meant this element:

[image](https://github.com/jasp-stats/jasp-issues/assets/37591817/9b976590-e12a-4ae2-b04e-2811e051f0c7)

**Comment by tomtomme** [comment]
> I meant this element:
> 
> [image](https://github.com/jasp-stats/jasp-issues/assets/37591817/9b976590-e12a-4ae2-b04e-2811e051f0c7)
> 

I think we have that already, via the split field in descriptives, don't we?

**Comment by TarandeepKang** [comment]
Indeed we do. Issue dealt with! :)
