### ISSUE TITLE
W in Wilcoxon Signed Rank Test does not report smallest sum of ranks but total sum

### ISSUE THREAD

**Issue by tultimatte** [jasp-stats/jasp-issues#271]
I'm a novice to statistics. Please, excuse if I'm mistaken.

In Wilcoxon Signed Rank Test the W that is reported seems to be the the total sum of ranks.
However, I think, the smallest sum of positive or negative ranks should be reported (in order to be able to check for significance).

Thank you for your great work!

* JASP version: 0.9.1
* OS name and version: Windows 10 1809
* Analysis: Wilcoxon Signed Rank Test

**Comment by JohnnyDoorn** [comment]
Hi Tultimatte,
JASP uses the wilcox.test() function in R. This function gives the test statistic W that is calculated as:
`sum ( rank ( abs ( x - y ) ) * ( x > y ) )`
In regular words: the absolute values of the difference between x and y are ranked - then you sum the ranks of the positive difference scores. So it matters if your first column is x, or your first column is y. However, the W statistic is symmetrical round the null point (i.e., the point of testing, which is equal to 
`(n * ( n + 1 ) ) / 4 `  
so for (two-sided) significance testing this does not matter. 
If you conduct a one-sample t-test and want to sum the negative ranks, you could use the Compute Columns function in JASP and multiply the column you want to analyze by -1, in order to "flip it".
Another way would be to take the difference between your observed test statistic and the null point, and then add/subtract that difference from the null point (if the observed W is lower/higher than the null point, respectively).
Does this clarify your issue?
Kind regards
Johnny

**Comment by tultimatte** [comment]
Thank you for the clarification. My (German) literature says that the lowest sum of either positive or negative ranks should be reported as W. They are apparently wrong.
Thanks again,
Daniel
