### ISSUE TITLE
[Bug]: Unexpected ordering, repeated info in footnote

### ISSUE THREAD

**Issue by richlv** [jasp-stats/jasp-issues#2747]
### JASP Version

0.18.3

### JASP Module

Regression

### What analysis are you seeing the problem on?

Correlation

### What OS are you seeing the problem on?

macOS Intel

### Bug Description

After doing a correlation by adding items in batches, the resulting footnote ordering was unexpected - namely, in this example, I'd have expected all the alphabetic notes to be grouped together.
Instead, "*" is between k and j.

![k-*-j](https://github.com/jasp-stats/jasp-issues/assets/112888/23236f93-b503-4aed-a0ff-3338ffcdbf8c)

Actually, taking a closer look, a whole bunch of these are repeated in the note - for example, WKINJURY is in a, c, g, k and INJEFFECT is in b, f, i, k.

As far as I can tell, the lettered references do not appear in the actual correlation table - does such a repetition make sense?

Also, couldn't spot note j in the correlation table, and thus figure out what it is about. Is this expected?
If needed, can supply data file and JASP file, if the issue is unclear without those.

### Expected Behaviour

As per above.

### Steps to Reproduce

Data can be supplied if needed.

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @richlv,

Thanks for the report - a jasp file (change extension to .zip so you can upload here, or send it directly to me at j.b.vandoorn@uva.nl) would be very handy here, since I cannot recreate this with other data (a variance of 0 only leads to a single footnote, even though there are multiple pairs with it). 

Cheers
Johnny

**Comment by richlv** [comment]
Thank you so much for looking into this, *.jasp file sent.

**Comment by JohnnyDoorn** [comment]
Hi @richlv,

It will not be so much as a fix, as it will have the correlation behave like other analyses and have informative errors when your variables do not meet certain criteria. Here, that means having 3 or more observations per variable, a non-zero variance, and no infinities. The errors will then not be in the footnotes anymore, but the whole analysis won't run until you have removed those variables, since they are not giving any information anyway (cannot compute any correlation for variables that have 0 variance, for instance). For now, you could already manually remove those variables that are mentioned in the footnotes, and then they will also not clog your table too much. 

Kind regards
Johnny

**Comment by richlv** [comment]
Thanks, they absolutely should be removed - just noticed something seemingly weird in JASP :)

I guess "Number of observations" stems from the other errors (no variance in those variables?) - is that correct?

**Comment by JohnnyDoorn** [comment]
This is the new error message, for your data:
![image](https://github.com/jasp-stats/jasp-issues/assets/15704203/7e11f922-c99a-403a-96cb-386d3ab53941)
It seems those columns are empty.

**Comment by richlv** [comment]
Thank you so much, hopefully that will also help other users detect problems sooner :)
