### ISSUE TITLE
Results pane

### ISSUE THREAD

**Issue by ramhsoni** [jasp-stats/jasp-issues#2759]
### JASP Version

0.18.3

### JASP Module

Other

### What analysis are you seeing the problem on?

Descriptive analysis

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I am using JASP 0.18.3. My results pane always remain blank and does not the descriptive results. However, I can export the same.

### Expected Behaviour

.

### Steps to Reproduce

1.Results pane does not show results
2.
3.
...

### Final Checklist

- [ ] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by shun2wang** [comment]
Hi @ramhsoni thanks for the report.

Could you try the test version and see if it still happen: https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-187467da878e0a9ec26b16983b5369e7eab0fc79.msi

Please note that this is a development version only and may have other issues. The official version will be released soon later.

**Comment by ramhsoni** [comment]
[New Microsoft Word Document.docx](https://github.com/user-attachments/files/15598056/New.Microsoft.Word.Document.docx)

**Comment by shun2wang** [comment]
@ramhsoni This is from test version right?

**Comment by tomtomme** [comment]
@shun2wang 
no, that new pic is still from version 0.18.3. I can tell because of the greyed out edit data button.

@ramhsoni 
Again. Thx for the report. If you do not want to try the new test version, sometimes also one of the following suggestions helped other users with this problem:

- [ ] Are your graphics drivers up to date? Especially intel drivers gave problems in the past.
- [ ] Is Win10 fully up to date?
- [ ] Did you try installing JASP via the windows store?
- [ ] Did you try restarting the machine / PC?

**Comment by shun2wang** [comment]
Anyway the new version might help, if it dinn't then we need more debug on that machine to know what happened.
