### ISSUE TITLE
[Bug]: Q1, Q3 and IQR bad computations

### ISSUE THREAD

**Issue by MBB89** [jasp-stats/jasp-issues#2774]
### JASP Version

0.18.3

### JASP Module

Descriptives

### What analysis are you seeing the problem on?

Descriptives

### What OS are you seeing the problem on?

Windows 10

### Bug Description

Some strange things appear for a very basic example I want to use with students. I have a data set composed of 8 different values : [7,4;7,9;4,1;8,1;6,2;7,1;7,4;6,7]

I just would like to illustrate very basic things like mean, median, range, variance, standard deviation and quartiles. Most of the computations made by JASP are ok except Q1 and Q3, and therefore IQR

![JASP](https://github.com/jasp-stats/jasp-issues/assets/172269430/ca8ce20d-506e-4e0a-b519-93256cb32fb3)

### Expected Behaviour

I was expecting :
Q1 =  6.45  (<> 6.575 given by JASP)
Q3 = 7.65 (<> 7.525 given by JASP)
IQR = 1,2 (<> 0.95 given by JASP)

### Steps to Reproduce

1. edit data and insert data set in 1st column
2. click "Descriptives"
3. click the differents statistics options
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@MBB89 
There are many ways to compute quartiles. 
- Wikipedia lists 4 https://en.m.wikipedia.org/wiki/Quartile
- help(quantile) in R lists 9
 
I do not know which one of those 9 JASP uses, so this should definetly be documented in JASPs help file, which it is not currently. 
More details on this issue here: 
https://stats.stackexchange.com/questions/134229/finding-quartiles-in-r

Does this explain the result for you?

**Comment by MBB89** [comment]
@tomtomme 

Thank you for your swift reply and clues. Yes there are different ways to compute quartiles and I totally agree with your post. 

Nevertheless, I didn't find the way JASP is computing quartiles and I would like to argue for coming questions. I'll keep an eye on this post (not a "bug" report, more a question).

**Comment by EJWagenmakers** [comment]
@vandenman maybe you can take a look and add a few sentences to the help file? See below;

In R we enter
> x<-c(7.4, 7.9, 4.1, 8.1, 6.2, 7.1, 7.4, 6.7)
and then
> quantile(x,type=7)
which yields
   0%   25%   50%   75%  100% 
4.100 6.575 7.250 7.525 8.100
which is in line with JASP. So JASP uses the default output from R (which is also the default in S).
What you expect to get is returned when "type" is set to 5:
> quantile(x,type=5)
  0%  25%  50%  75% 100% 
4.10 6.45 7.25 7.65 8.10 
As the R helpfile mentions, "This is popular amongst hydrologists".

**Comment by TarandeepKang** [comment]
Hi EJ, and was wondering whether it might also be a good idea to make type 6 an option for alleged consistency with SPSS and maybe also 8 as recommended by

Hyndman, R. J. and Fan, Y. (1996) Sample quantiles in statistical packages, American Statistician 50, 361--365. 10.2307/2684934.

 as cited in the function documentation:

https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile

Just a thought!

Best,

Tarandeep

**Comment by EJWagenmakers** [comment]
I worry that when we overload JASP with options such as these, we will gradually transmogrify into SPSS...perhaps we can tuck away this option under an Advanced setting, or it may be part of a new module. I suspect that 99.99% of users do not care, and the remaining 0.01% perhaps *should* not care :-) Happy to be overruled.
EJ

**Comment by tomtomme** [comment]
If we change to more options for Q1, Q3, IQR in descriptives, then 
a) we would also need to activate those options for boxplots and in most (all?) other modules for consistency, right?
b) Or we say that the descriptives module IQR is a special place that deserves this treatmant for educational purposes, which we would also need to make clear in the help file.

Apart from that I share EJs point of view. I do not care if my IQR differs .25 or .5 from algorithm to algorithm because 
a) there are often larger sources of error anyway, like measurement error (this might be different in physics, biology etc.)
b) it is educational for students to see, that people have different opinions on how to calculate / define such a basic thing, which explains the even bigger differences between researchers in how to compute more complex models. So I usually embrace this problem in class and try to start a debate among students.

**Comment by MBB89** [comment]
Ok, thanks all for your answers. It's very clear now. R helpfile is also very clear about the different types of computations.
