### ISSUE TITLE
Repeated Measures ANOVA: Marginal Means

### ISSUE THREAD

**Issue by av949306** [jasp-stats/jasp-issues#2785]
### JASP Version

0.18.3

### JASP Module

ANOVA

### What analysis are you seeing the problem on?

Repeated Measures AnoVA

### What OS are you seeing the problem on?

Windows 11

### Bug Description

This is not a bug, but I am running a 3-way repeated measures ANOVA with a covariate (image of setup attached). I just want to confirm that the marginal means associated with the results are adjusting for the effect of the covariate?
Thank you!
- Ava
![RM_ANOVA_Setup](https://github.com/jasp-stats/jasp-issues/assets/173101796/cbd6add9-8052-4103-82ca-87e5e6252c94)

### Expected Behaviour

Please see above

### Steps to Reproduce

Please see above

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [ ] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by JohnnyDoorn** [comment]
Hi @av949306,

"Controlling for" simply means adding a variable to the model - I would put "Sex" in the between subjects factors box so that it gets treated as a categorical variable instead of a numeric covariate. That means it will still be taken into account when estimating the marginal means. Closing it now, but let me know if you have additional questions!

Kind regards
Johnny

**Comment by av949306** [comment]
Thank you so much! This answers my question perfectly :)
- Ava
________________________________
