### ISSUE TITLE
No boxplots when filters active

### ISSUE THREAD

**Issue by SvenHeimbuch** [jasp-stats/jasp-issues#281]
* JASP version: 0.9.2 (flatpak)
* OS name and version: Linux (Arch)
* Analysis: Descriptives - Descriptive Statistics
* Bug description: When a filter is active for a split variable, boxplots are not rendered for the remaining unfiltered groups.
* Expected behaviour: Show boxplots for remaining data that is not filtered.
* Steps to reproduce: 
1. Select a categorical variable in the data (e.g., Cohort) and activate filter for one group (e.g., 16/17)
2. Go to 'Descriptives - Descriptive Statistics'
3. Click on 'Plots - Boxplots - Boxplot Element'
4. See error: `This analysis terminated unexpectedly. Error in `row.names<-.data.frame`(`*tmp*`, value = yIndexToActual): duplicate 'row.names' are not allowed 
Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options, state = oldState)
.descriptivesSplitPlot(dataset = dataset, options = options, variable = var)
`row.names<-`(`*tmp*`, value = yIndexToActual)
`row.names<-.data.frame`(`*tmp*`, value = yIndexToActual)
stop('duplicate 'row.names' are not allowed')`

![jasp_boxplot-error](https://user-images.githubusercontent.com/27767378/50347084-bd11a800-0534-11e9-9753-79df613bec65.png)
[cookies.zip](https://github.com/jasp-stats/jasp-issues/files/2703136/cookies.zip)

**Comment by akashrajkn** [comment]
@SvenHeimbuch Thank you for reporting this. On first glance I wasn't able to find the problem.

**Work around for now**: I was able to run the analysis if Export the data and re-run the experiment.

**Comment by HeikoBreitsohl** [comment]
A similar error occurs when splitting without filtering:

* JASP version: 0.9.2
* OS name and version: Win10
* Analysis: Descriptives
* Bug description: No box plots are created for split output
* Expected behaviour: Show box plot for split data
* Steps to reproduce: 
1. Select categorical variable for "Split"
2. Click on 'Plots - Boxplots - Boxplot Element'
3. See error:

This analysis terminated unexpectedly.
Error in quantile.default(v, probs = c(0.25, 0.75)): missing values and NaN's not allowed if 'na.rm' is FALSE
Stack trace
analysis(jaspResults = jaspResults, dataset = dataset, options = options, state = oldState)
.descriptivesSplitPlot(dataset = dataset, options = options, variable = var)
quantile(v, probs = c(0.25, 0.75))
quantile.default(v, probs = c(0.25, 0.75))
stop('missing values and NaN's not allowed if 'na.rm' is FALSE')

**Comment by AlexanderLyNL** [comment]
There are missing values in the split by variable, which JASP should discard. A workaround is given in issue #304. This will be fixed in the next release. Sorry for the inconvenience. As I've responded in the other issue, I consider this as a duplicate and close this issue by which I mean that we're working on this.
