### ISSUE TITLE
JASP won't open .sav files

### ISSUE THREAD

**Issue by Alexdugin** [jasp-stats/jasp-issues#283]
Jasp version 0.9.2.0 won't open .sav data sets downloaded from several sources. 
I've tried with a few files and on 3 seperate computers, same issue, has no issues with other file types.

The error message is "Found no cases in .sav file" regardless of the contents of the .sav file. 

Thanks for the help.

**Comment by boutinb** [comment]
Sorry for the late answer...
Can you send me one of this sav file (in a zip format). I cannot reproduce your problem.

**Comment by FransMeerhoff** [comment]
Hi @Alexdugin 

Hereby a new request to send  us a zip file with the .sav files where you encounter your problem.
As said before we cannot reproduce it. If you have problems with sending the zip flle ( you can drag and drop it to this issue) please let us know. Otherwise we would like to close thjs issue.


Kind regards 
Frans Meerhoff

**Comment by Alexdugin** [comment]
Hey, sorry I couldn't reply earlier but I was reall busy for a long while.
I've actually managed to solve the issue for myself. The file I've downloaded had some empty columns in it, once I've removed these or filled them with date the problem was solved. 
The empty columns might've been caused by the fact that lots of programs have issues with hebrew letters and words in them, but I've managed to solve it. 

Thanks for the help anyways.
