### ISSUE TITLE
[Feature Request]: 'turn all filters off' option

### ISSUE THREAD

**Issue by timgitty** [jasp-stats/jasp-issues#2831]
### Description

I regularly use filters on multiple variables, and often struggle to find which filters I've turned on. It would be very helpful if there is a reset button, to start from scratch with all filters off. 

Additionally, it would be great to have an overview of all active filters, and perhaps even a history of used filters, but I can image that to be way more difficult to implement... 

### Describe the solution you would like

add an option to the filter module to reset filters

**Comment by tomtomme** [comment]
@timgitty 
thx for the request. I also think this would be a cool addition :D

**Comment by boutinb** [comment]
If you have several filters for different columns, then in the Label window is displayed a second eraser button, so that you can remove all filters at once.
<img width="425" alt="Screenshot 2024-07-18 at 13 31 58" src="https://github.com/user-attachments/assets/96161d3f-0525-456c-ae29-b2b55d5e24d9">

**Comment by timgitty** [comment]
Apologies, I overlooked this. Awesome!

**Comment by tomtomme** [comment]
Nice to know!
