### ISSUE TITLE
Question about formulas

### ISSUE THREAD

**Issue by jinxgoh** [jasp-stats/jasp-issues#286]
Hello,

I was wondering if it is possible to find out the formulas that are used in calculating the statistics in JASP. Specifically, I want to know the formulas that JASP (or the R package) uses to calculate the effect size for dependent t-test and the 95% CI of that effect size. My colleagues and I are facing issues with different output from various software. Thanks

 
* Enhancement:
* Purpose:
* Use-case:

**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
direction to specific formulas/ R package used to calculate effect size and its 95% CI for dependent t test

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by boutinb** [comment]
@JohnnyDoorn Can you answer this question?

**Comment by JohnnyDoorn** [comment]
Hi Jinxgoh,
You're right in that it is a bit of a tricky issue. You can read this forum thread on the JASP forum:
https://forum.cogsci.nl/discussion/3013/what-denominator-does-the-cohens-d-use-on-jasp#latest
Which provides a bit more insight into how JASP calculates stuff - it's basically the same as the effsize package does in R. For confidence intervals, we use the noncentral t-distribution for those (so if you use the effsize package, you specify that argument in the function call). The MBESS package does the same (it automatically uses the noncentral t-distribution for confidence intervals). 
Please let me know if you still have questions. 
We are working on more extensive helpfiles in JASP, because it would be great to have this information in the software already =)
Kind regards,
Johnny

**Comment by AlexanderLyNL** [comment]
Please reopen if it's still unclear.
