### ISSUE TITLE
Bayesian Mann-Whitney unstable BF estimates

### ISSUE THREAD

**Issue by AugustOlsson** [jasp-stats/jasp-issues#289]
* JASP version: Version 0.9.2
* OS name and version: Widows 10 Education
* Analysis: Bayesian Mann-Whitney U test

I have two groups and a dependent variable. I am testing the hypothesis that the group differ.

When running the Bayesian Mann-Whitney U test the BF10 estimates wary a lot, from BF10 67 to BF10 450 over 10 runs. I am using 10 000 samples which seems to be the max. The W values is always the same, and so is the BF10 value from the Student test.

*Proposed fix
If nothing is wrong with the actual calculations I propose increasing the max amount of sample to be able to find stable BF-factors.

Best,
August
[ManWhitney test.zip](https://github.com/jasp-stats/jasp-issues/files/2779186/ManWhitney.test.zip)

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn ?

**Comment by JohnnyDoorn** [comment]
Hi August,
The algorithm behind that analysis is indeed not as stable as the other Bayesian analyses, due to the data augmentation needed for the rank-based analyses. I was not aware that the limit on the number of samples is only 10,000 - I will increase this number and then hopefully it will be quite a bit more stable for you. However, there will always be somewhat of a variation and I'm currently working on an error % that gets included with the result (similar to the Bayesian ANOVA), in order to quantify the stability.
Kind regards,
Johnny

**Comment by AugustOlsson** [comment]
Hi Johanny,

Thanks for the quick reply. An error % which indicates stability would be very good. And ofc the possibility to run larger samples.

Best,
August

**Comment by AlexanderLyNL** [comment]
Will be solved in the next release (0.9.3), see also issue #299
