### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ndpegram** [jasp-stats/jasp-issues#2967]
### JASP Version

0.19.0

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

Label editor in data view

### What OS are you seeing the problem on?

Linux

### Bug Description

In the label editor I see duplicate entries for the same nominal value (0). Clicking on either entry correctly filters the data, yet only the lower value's text is used in analyses. A screenshot is included.

I have exported the data and examined it in a spreadsheet--all the values are numeric.

![Screenshot from 2024-10-15 09-51-20](https://github.com/user-attachments/assets/6bfa75b1-3890-4a90-bd88-b22387178068)

### Expected Behaviour

The label editor should show only one instance of each numeric value.

### Steps to Reproduce

Unfortunately, I cannot determine how to reproduce this.

Due to ethical limitations, I can't just share the whole data file. 

Suggestions of how I can help are welcomed.

### Log (if any)

none

### More Debug Information

none

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@ndpegram 
thx for the report. I have seen this too in the past. But it did not worry me / did not affect my analysis so far. Can you elaborate on how this affects your workflow?
It would be cool to tackle this issue, but it is also hard for me to reproduce and it may be of low prio, if it does not really affect the analysis besides being distracting.

**Comment by ndpegram** [comment]
Like yourself, it's not affecting my workflow. I'm reporting it as it was new to me, so you are aware of it.

**Comment by JorisGoosen** [comment]
Is it still the case in 0.19.1 ?

**Comment by JorisGoosen** [comment]
Ah, and, it also depends how you loaded the data. Was it hand-entered or loaded from some specific type of file?

**Comment by ndpegram** [comment]
Yes, the same behaviour is there in 19.1.

The data was originally imported via an SPSS file. It was later updated using the data editing functions in JASP. I created the data file from the existing data, opened it and the updated data (CSV) in LibreOffice. Copied across the added rows, and then updated JASP.

FYI: I looked at the exported JASP data and it appears correctly as numeric in LibreOffice.

**Comment by boutinb** [comment]
What would help us is to have such dataset. Could you send it to us (drag-and-drop on a comment of this issue). If the data are too sensitive, you can send it to our email address info@jasp-stats.org

**Comment by JorisGoosen** [comment]
ndepgram literally says they cant share it...

**Comment by JorisGoosen** [comment]
Yeah, so this is a "feature".

Spss supports having a numeric value for a label, so you could have "0" - "some label".
But then csv does not have this support, so when you turn it into a datafile (csv) it just writes the values. Which is 0-11  in your case.
You then copy this again to JASP, so without the labels. So all those copied rows are now *just* the number.

Because JASP needs to somehow look at the data and determine whether it is different. And because there are a lot of ways to work with data JASP matches on both the value and the label. To merge the two you just need to set the label of "0" - "0" to the label of the top "0" and then they will merge.

But this is, as far as I can guess from the description of the operations you did, definitely intended behaviour.
