### ISSUE TITLE
[Bug]: JASP does not open after installation

### ISSUE THREAD

**Issue by liezelkorf** [jasp-stats/jasp-issues#2968]
### JASP Version

0.19.1

### JASP Module

Unrelated

### What analysis are you seeing the problem on?

N.A

### What OS are you seeing the problem on?

Windows 10

### Bug Description

I have installed JASP  (and uninstalled it a number of times as well) but it just does not want to open.  When I choose it from the list of programmes on the start button nothing happens.  I know this is addressed elsewhere but the solutions either does not make sense or doe not work. Can someone please assist me in simple language? Thanks@

### Expected Behaviour

JASP sould open.

### Steps to Reproduce

1.Uninstalled and reinstalled JASP - also tried previous versions.
2.
3.
...

### Final Checklist

- [X] I have included a screenshot showcasing the issue, if possible.
- [X] I have included a JASP file (zipped) or data file that causes the crash/bug, if applicable.
- [X] I have accurately described the bug, and steps to reproduce it.

**Comment by tomtomme** [comment]
@liezelkorf 
thx for the report. How did you install? There are 3 methods:
![grafik](https://github.com/user-attachments/assets/25242f06-90c9-442a-965b-46abe094c4ca)

So you could try:
one of the other install methods.
disabling your anti-virus program temporarily, if you have one running
updating win10 fully and restart before installing
update your graphics drivers and restart also after installing (because some older intel drivers are problematic)
starting a command prompt by typing "command prompt" in the Start menu & then type "c:\Program Files (x86)\JASP\JASP.exe --safeGraphics" 
setting QSG_RHI_BACKEND=opengl via "cmd.exe"  (input setx "QSG_RHI_BACKEND" "opengl" /m as admin)

I would start with the first one and work my way back down to the more complicated ones.

Also, this information could help us: 
![grafik](https://github.com/user-attachments/assets/8b711ed6-a56f-42a8-9609-7c588fa7db2d)

**Comment by tonysultana** [comment]
Separately, I did have errors after installing on Win10 using the MSI installer, when selecting the installation for a single user without administrator rights. In my case, may JASP functions could not be found. I resolved it by rerunning the JASP installer and selected Repair.

It did fix the problem, but it would be good to fix the installer for MSI for a single user on a system.

Thanks.

**Comment by tomtomme** [comment]
Thx for the Report. That will be fixed with 0.19.2
Can this one be closed then?

**Comment by tonysultana** [comment]
Yes, for my issue with the MSI installer and a single user install, I think that it can be closed.

**Comment by tomtomme** [comment]
yep, that bug can be tracked here: https://github.com/jasp-stats/jasp-issues/issues/2876
