### ISSUE TITLE
Simple scatterplot without matrix

### ISSUE THREAD

**Issue by lindeloev** [jasp-stats/jasp-issues#298]
When doing a scatterplot between two variables in **Descriptives** or **Classical Regression --> Correlation matrix** or **Bayesian correlation matrix** with default options you get a plot with a lot of nothing:

![image](https://user-images.githubusercontent.com/1439417/52123649-133f3400-2627-11e9-8acf-9a3980812205.png)

That is not nice for students to copy-paste into their report. Only in **Bayesian correlation pairs** do you get the simple scatter plot. I suggest only doing the matrix layout if there is more than one pair or options about densities etc. are turned on?

(BTW, I still find it strange that there's a distinction between correlation matrix and pairs :-) I think it would be nicer to have an option in the widget to choose between a matrix or a pairwise layout in tables/figures. #72 )

**Comment by Bevers1** [comment]
Hello! 

Just wondering if this issue is still being looked at? I am looking to possibly switch my undergraduate teaching to JASP this September and visualizing data is going to be a key part of the course. 

Currently this is difficult when the obvious way of teaching scatterplots will be "descriptives --> Correlation plot", or "regression --> correlation matrix", but then in both options it displays a tiny scatterplot in an unfriendly and mostly blank matrix table. As lindeloev pointed out, it doesn't do this for Bayesian correlation Matrix, so may be a bug? (also, it appears previous versions of JASP did display a  larger non-matrix correlation plot - see https://www.youtube.com/watch?v=lRNIUP_m7yQ)

Thank you!

**Comment by EJWagenmakers** [comment]
OK let's look into this. First, with the Adam Sandler data set, I get this when I use Descriptives -> Correlation plot:
![image](https://user-images.githubusercontent.com/8603015/62159364-d45a1480-b311-11e9-8c03-6d6ebb512f53.png). This looks as we intended, but what we don't offer is a simple scatterplot, for instance as available in Bayesian correlation pairs -> Scatterplot. It would be nice to copy exactly this functionality ("Scatterplot") and insert it as a separate option just above "Correlation plot" in Descriptive Statistics. But wait -- what if there are ten variables, say, instead of just two? This needs some thought. Maybe offer scatterplot only for two variables? But how?

Second, I then go to Regression -> Correlation Matrix and now I see what you mean. If the options "Densities for variables" or "Statistics" aren't ticked, these matrix cells remain blank:
![image](https://user-images.githubusercontent.com/8603015/62159543-492d4e80-b312-11e9-834f-70ac10076e1b.png). I am just not 100% sure how to "fix" this. Anybody?
 
E.J.

**Comment by Kucharssim** [comment]
wrt Correlation matrix analysis, I believe the current behavior is what makes the most sense, given that it is supposed to produce correlation matrices. However, we also offer "Display pairwise table" in the Additional Options, which switches how the analysis outputs the correlations (instead of p x p correlation table, we report a correlation table with p choose 2 correlation pairs). I think this option could be renamed from "Display pairwise table" to "Display pairwise", and the "Correlation Matrix" option to "Scatterplot".

That way, in case:
1) "Display pairwise" is not checked, JASP would output the p x p correlation matrix and the current implementation of the plots.
2) "Display pairwise" is checked, JASP would output the pairwise table and (p choose 2) individual scatterplots. Selecting "Densities for variables" in this case would show the distribution plots along the axis, something like this:

![](https://deanattali.com/img/blog/ggExtra/ggmarginal-basic-example.png)

Not sure where to put "Statistics" if they are selected in this case, but I guess we could play around with it a little bit. I am assigning myself because I am currently rewriting the correlations, so I can look into this.

**Comment by Kucharssim** [comment]
This feature is implemented for the next release.
