### ISSUE TITLE
Error message while trying to create boxplots

### ISSUE THREAD

**Issue by knamesnik** [jasp-stats/jasp-issues#304]
I am not doing anything special, but I am trying to get descriptives per group with the following data:
Grouping variable: conditie, dependent variable: aut2v. 
This is what I get:
![image](https://user-images.githubusercontent.com/38688445/52553747-edfbb400-2de4-11e9-85ac-84cd39fc576c.png)

At the moment I try to get boxplots made, I get the following error message (tried multiple times):

![image](https://user-images.githubusercontent.com/38688445/52553798-15528100-2de5-11e9-99fd-60a91ed08c8e.png)

I have never seen this error before. Other grouping variables work fin in the same dataset. 
[Rekenvaardigheid instructor version.zip](https://github.com/jasp-stats/jasp-issues/files/2850365/Rekenvaardigheid.instructor.version.zip)

* JASP version: 9.0.2.Bain
* OS name and version: Windows

**Comment by AlexanderLyNL** [comment]
The problem in this case is that there are three missing values in the variable "condition". By default we should ignore the missing values in the split-by variable, but for some reason the default behaviour changed. Sorry for this, but this will be fixed in the next release. 

As a temporary solution, one work around would be to create a new variable, say, "conditionMiss" and to apply replaceNA to "condition" with replaceValue "Missing". This will create a new variable that can be used to split-by. 

@ASarafoglou 
Internally, this means that we have to set na.rm=TRUE, meaning that the not available entries are removed.

**Comment by TimKDJ** [comment]
In our current release the grouping variable is not allowed to contain any missing values.
This will be fixed in the next release of JASP.
