### ISSUE TITLE
Non-reproducible linear regression

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#332]
* JASP version: 0.9.0.1 and 0.9.2
* OS name and version:
* Analysis: Linear regression
* Bug description: Coefficients wrongly calculated in first run, correctly calculated in second run of OLS
* Add JASP files as a zip: 
* Screenshot: 
* Expected behaviour:
* Steps to reproduce: See JASP file 
[Linear regression exam.zip](https://github.com/jasp-stats/jasp-issues/files/3008014/Linear.regression.exam.zip)

**Comment by Kucharssim** [comment]
Hello @PeterKlaren,

thank you for your report. I can see that your saved .jasp file contains incorrect results, that's why they are shown at first before rerunning the analysis which overrides them. One option is that your .jasp file was generated with an earlier version of JASP that contained a bug. However, I cannot reproduce your saved incorrect values with no version of JASP going back down to 8.6.0. 

The upcoming version of JASP generates correct output as well so I assume that the problem should not arise again. I would recommend re-saving your updated .jasp file with the newest version of JASP to have the correct output. Please, keep us updated if the problem persists in the future.

Simon
