### ISSUE TITLE
Error: Failed to create OpenGL context ...

### ISSUE THREAD

**Issue by MAgojam** [jasp-stats/jasp-issues#355]
* JASP version:  0.9.2
* OS name and version: win 7 pro (ita)

Hi All,
the technicians of my University, have updated a previous version of jasp (working) with the last 0.9.2. on a virtual machines with win 7 pro.
When students launch jasp an error message appears (see attached screenshot).
![Errore_Jasp](https://user-images.githubusercontent.com/36552289/57550511-ed80a400-7366-11e9-93bd-68ed372674c4.PNG)

The technicians could not find a solution at the moment.
Can you give suggestions?

Thanks and best regards.
Maurizio

**Comment by JorisGoosen** [comment]
Well, the first thing that comes to mind is installing a better video driver. However I see that you mention virtual machines. Maybe it isn't so simple there.

However, the required OpenGL version is really quite old (released 14 years ago) and it should be possible to have it in a VM. What kind of VMs are you using? 
Here I run Win 10 pro in Virtual Box and that works perfectly fine.

**Comment by MAgojam** [comment]
Hi, @JorisGoosen.
Thank you for your answer.

The VMs used in the classroom, by students, are Virtual Box with win 7 pro (ITA), with a previous version of jasp installed, which has always worked without problems.
Upgrading to jasp 0.9.2 on VMs produces the reported error.
Unfortunately, I do not have administrator rights, and I cannot intervene to understand and find a solution, but with many difficulties, I have to ask the technicians of the University Information System to intervene.
I can tell you that on my PCs I have tried various VMs with different Windows OS, without being able to reproduce the error and to continue with the lessons, using jasp, the Students bring themselves and use their personal PC.

Cheers,
Maurizio

**Comment by JorisGoosen** [comment]
Hello Maurizio,

Aah, that is too bad. The problem here is that starting with 0.9.2 we have started changing the user interface of JASP to a more modern system and with the coming 0.10.0 release this will be fully implemented. Sadly enough that does mean that this new version will probably not work in the VM either... 

I would like to help to fix this problem but seeing as how I do not have access to the VMs your students use it is very hard for me to reproduce this. Is it possible to get the VMs upgraded to Windows 10 Pro? Because that might work better.

And as far as I know it is still possible to upgrade from 7 to 10 without cost so maybe your ict-departement can try this out? Even just once to see if that solves the problem or if something else is wrong.

**Comment by MAgojam** [comment]
Hi, @JorisGoosen.

We have only updated jasp to version 0.10.0 and the reported problems have disappeared.
We are happy, because we have finally returned to be able to use jasp.

Thanks and best regards.
Maurizio

**Comment by JorisGoosen** [comment]
Ooh that makes me happy as well, enjoy using the new version!
