### ISSUE TITLE
JASP error running repeated-measures ANOVA

### ISSUE THREAD

**Issue by TomdeGraaf** [jasp-stats/jasp-issues#358]
* JASP version: 0.9.0.1
* OS name and version: Max OS X High Sierra
* Analysis: repeated measures ANOVA
* Bug description: opened a csv file (attached), created 2 x 4 design, JASP reports error (and shuts down) when clicking the small arrow to add the variables to the design level. 
* Add JASP files as a zip: 
[TIF_beh_props.csv.zip](https://github.com/jasp-stats/jasp-issues/files/3196824/TIF_beh_props.csv.zip)

* Screenshot: 
![image](https://user-images.githubusercontent.com/50823243/58005347-c2741e00-7ae5-11e9-8ff3-f6e3a15d457a.png)

* Expected behaviour: not a crash
* Steps to reproduce: see above under bug description

**Comment by AlexanderLyNL** [comment]
Hi Tom,

Thanks for reporting this. The underlying problem is the interpreter has some problems with variable names that only consists of numbers. The workaround for the moment is to change the names of the variables, see the JASP file. This fixes it for the moment. This is a great use-case as in the new version, JASP will interpret these names better. I hope that this solves your problem, if not please reopen. 

Cheers,
Alexander

[TIF_beh_props.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3204822/TIF_beh_props.jasp.zip)
