### ISSUE TITLE
SEM Chi-square error result

### ISSUE THREAD

**Issue by acescos** [jasp-stats/jasp-issues#359]
* JASP version: Version 0.9.2
* OS name and version: Windows 10
* Bug description: There is an error in the output of SEM. 
SEM model:
`

data <- n200

ce <-

'

cause  =~ i1c + i2c + i3c

effect =~ i1e + i2e + i3e

effect ~  cause

'

fit <- sem (ce, data = data)

summary (fit)

`
Please, see script and data files:

[ce_model.txt](https://github.com/jasp-stats/jasp-issues/files/3204036/ce_model.txt)
[n200.xlsx](https://github.com/jasp-stats/jasp-issues/files/3204044/n200.xlsx)

The result produced by Jasp (on SEM lavaan) is Chi-square = 3.997, p-value = 0.857. 
* Screenshot: 
![2019-05-21](https://user-images.githubusercontent.com/36568488/58122449-12cfa680-7be0-11e9-8def-6d5533aa2359.png)
* Expected behaviour: The result produced by lavaan package on R software is Chi-square = 4.402, p-value (Chi-square) = 0.819.

Please, see the R output file
[Output_ce_model_lavaan_R.docx](https://github.com/jasp-stats/jasp-issues/files/3204060/Output_ce_model_lavaan_R.docx)

**Comment by AlexanderLyNL** [comment]
Hi acescos, 

Thanks for reporting this. The reason why the output of JASP differs from that of lavaan in R, is because JASP interprets variables as factors/ordinals, when they have fewer than 20 unique entries. 

To get the same result, I've changed the variables type to "scale" in JASP, and now the JASP output is the same as that of lavaan in R, see the JASP file. In the next version of JASP you can change the threshold of 20 to whatever you think is reasonable. The new standard will be 10. I hope that this clarifies the difference between the two. If not, please reopen. 

Cheers,
Alexander

[n200.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3204775/n200.jasp.zip)
