### ISSUE TITLE
[REQUEST] Factor Analysis with ordinal data (polychoric correlations)

### ISSUE THREAD

**Issue by mike-ology** [jasp-stats/jasp-issues#379]
As per the title, **it would be great to have the ability to conduct FA/CFA using ordinal data**. As most questionnaires are scored in this manner, I imagine it would be a feature that would get a lot of usage (it would from me, at least!).

Version 0.10 is looking great though, was very happy to see the option to conduct multigroup CFA's as I have just been learning how to run those in lavaan!

**Comment by SKnHub** [comment]
As requested above,  FA/CFA for ordinal data using polychoric or another suitable method would be a really useful feature addition for many users like me. With Ordinal/ Lickert data more widely in use, this will help in framing comprehensive analysis. 

Personally, need to depend on other packages along with JASP for my current analysis, Extremely impressed by the quick feature updates otherwise. JASP 12 was a surprise with many new additions!.

**Comment by boutinb** [comment]
@vankesteren Could you answer whether this request is in the pipeline?

**Comment by vankesteren** [comment]
I will look into this next week!

**Comment by mike-ology** [comment]
I realise that this issue was closed some time ago, but it doesn't seem that this feature has been added yet? CFA still only allows scale variables to be entered, and there is no indicate that scale variables with ordinal data are handled differently in the analysis.

**Comment by SKnHub** [comment]
True,  ordinal Factor analysis was not found included in the two subsequent jasp updates.Request the same at the earliest. On 10-Nov-2020 7:15 AM, Michael E <notifications@github.com> wrote:
I realise that this issue was closed some time ago, but it doesn't seem that this feature has been added yet? CFA still only allows scale variables to be entered, and there is no indicate that scale variables with ordinal data are handled differently in the analysis.

**Comment by boutinb** [comment]
@vandenman Can you have a look?

**Comment by richlv** [comment]
As this issue is still closed, should it be reopened or a new one created?

**Comment by juliuspf** [comment]
I think it is best to create a new feature request for the CFA only. The functionality for EFA and PCA is finished and will be included in 0.16.4.

**Comment by richlv** [comment]
Thank you for the quick reply, created #1723.
