### ISSUE TITLE
Why PCA is in "factor analysis" section?

### ISSUE THREAD

**Issue by MaksimRudnev** [jasp-stats/jasp-issues#389]
It's a rather old conceptual issue:
principal component analysis is not a factor analysis. It's been highlighted in virtually every recent factor analysis handbook and multiple articles. SPSS was harshly criticized for it. I realize the GUI-related concerns, but why reproducing their mistake? You could name the button "latent variables" or something alike.

JASP v.0.10

**Comment by TimKDJ** [comment]
@EJWagenmakers?

**Comment by EJWagenmakers** [comment]
Our main concern is to use labels that allow users to find what they're looking for. I am not sure whether "Latent variables" meets that objective. The first Google hit I landed on (https://www.theanalysisfactor.com/the-fundamental-difference-between-principal-component-analysis-and-factor-analysis/) argued that both are data reduction techniques, and only factor analysis is a latent variable model. But I thought that PCA retained all information, so the reduction aspect is not clear to me. Also, you could argue that all parametric statistical models have latent variables and do data reduction. So I am open to changing the name, but not at all cost. @vankesteren , what do you think?
E.J.

**Comment by AlexanderLyNL** [comment]
I don't think that "Latent variables" is a good description for PCA. Given a covariance matrix PCA finds the eigenvalues and eigenvectors, which aren't latent variables, but a linear combination of the ones you already have. 

The data are reduced by thresholding, that is, given p data columns, a p x p symmetric is computed, which has p (real) eigenvalues. These eigenvalues can be ordered by magnitude, and the reduction follows from retaining only the largest ones, thus, discarding the smaller ones. Say, k < p eigenvalues are kept and the corresponding k eigenvectors are then used as a reduced version of the p data columns. Each of these k eigenvectors defines a linear combination of the original p data columns. The different methods in PCA relate to different thresholding techniques to choose the number of k. 

EFA performs the data reduction differently by proposing latent variables/factors. This is actually unidentified due to rotations, and there are different methods to choose the number of factors. The different methods in EFA relate to the choice of rotation, and the selection of the number of factors. It is debatable whether this really defines latent variables, due to the arbitrariness of the rotation technique. 

CFA on the other hand is more a modelling tool and the problem of rotations is resolved based on assigning the observed variables to specific latent variables, though, other issues need to be dealt with. 

The explanation above is an oversimplification of course. We elaborate on these methods in the help file and I agree with EJ that it's important that the user easily finds the analyses.

**Comment by MaksimRudnev** [comment]
Indeed, PCA does not deal with latent variables in a strict sense, but neither does it with factors.

PCA is a data reduction when only part of the components is used, which is typical. FA is a data reduction only as a side effect, the primary purpose is to decompose true variance and measurement error, so SPSS's "Dimension reduction" is also quite imprecise.

"Latent" might not be a perfect label. There should be a label that points to the only common feature of PCA and FA - both are able to produce, in a structured way, new continuous variables which are not in the data yet.

**Comment by EJWagenmakers** [comment]
Data decomposition?

**Comment by tomtomme** [comment]
@MaksimRudnev 
More suggestions from a discussion with Copilot:
- Components & Factors
- Data Reduction
- Reduce & Model

Nothing optimal for my taste. Also "data decomposition" sounds strange. 
Feel free to close this, if you also can't find an optimal name. Maybe then "Factor" is not as bad, as it sounds.
