### ISSUE TITLE
Feature Request: Count different missing values separately in frequency table

### ISSUE THREAD

**Issue by tomtomme** [jasp-stats/jasp-issues#396]
Still valid for 0.19 beta for metric variables, where I cannot achieve this through setting labels as a hack.

* Enhancement: Count different types of missing values separately in frequency tables
* Purpose: Say I need a missing value -77 that means "I don't want to answer this question" and another -99 that means "I can't answer this question". Then in the frequency table it would be nice to show how often those values -99 and -77 are there. 
Many -77 would tell me that the question was inadequate to ask in that setting / group / situation. Many -99 would tell me that the question was unclear / phrased poorly / badly operationalized / missing a category.

Example: 

missing -77 3
missing -99 4

Instead of

missing all 7

**Comment by tomtomme** [comment]
I think this feature request is still valid. Maybe someone has now time to look into it again. Thx.

**Comment by vandenman** [comment]
@tomtomme would a frequency table in the screenshot below fulfill your needs?

![image](https://user-images.githubusercontent.com/21319932/99529484-2cea7080-29a0-11eb-80a8-46bff8b5772e.png)

**Comment by tomtomme** [comment]
absolutely!!! thx ! :D

**Comment by vandenman** [comment]
if you create an ordinal text variable like this:

![image](https://user-images.githubusercontent.com/21319932/99531400-f3673480-29a2-11eb-939b-ed35e22c7827.png)

then that should already work in the latest jasp version. just remember to filter out the missing values afterward.

**Comment by tomtomme** [comment]
Thanks. I tried to reproduce this. It works for ordinal and nominal and is a great workaround. However I need this also vor metric / scale data. I know I can switch scales, but its not very practical. 
Another caveat with your solution you mention:
After I counted the missing values I have to add them to the missing values afterward. Then, for a new dataset I have to remove those values from the missing values section again, and so on. So I would constantly add and remove them there. And if I forget that only at one point, my whole analysis is screwed. 

So what I would need: Add -77 -99 etc. once to the missing values section. Then ignore those values for all analysises except for the frequency table and maybe also for bar-charts (with an on/off switch to count missings for the user ideally).

Thank you so much for looking into this! 
I hope its not to complicated to implement!

**Comment by tomtomme** [comment]
Still valid for 0.16.4 for metric variables

**Comment by JorisGoosen** [comment]
> So what I would need: Add -77 -99 etc. once to the missing values section. Then ignore those values for all analysises except for the frequency table and maybe also for bar-charts (with an on/off switch to count missings for the user ideally).

This would require a fundamental change to how the data is read into all analyses.
This because to have those values be used as missing values in R they need to be "NA" there.
That also means the value itself is lost.

We could add an extra option for `readDataSetToEnd` for reading columns as `give-missing-values-value`. 
Then the R code could use that combined with the normal column to figure out which is missing or not.
Then that could be specially handled in frequencies just for this feature.

I don't think it is worth that to be honest.

I think I have a workaround for you though:

Just create your column, without any missing values specified as such.
When you use that in frequencies you get what you want.
Then you simply make a computed column next to it that copies the first and has missing values set. This you can then use in other analyses for the actual data.

**Comment by tomtomme** [comment]
ah great. yes with the new handling of missings per variable this is indeed a great workaround now! thx!
