### ISSUE TITLE
Confidence interval on descriptive analysis 

### ISSUE THREAD

**Issue by SterArcher** [jasp-stats/jasp-issues#427]
* Enhancement: Confidence intervals (CI) when one is doing descriptive stats
* Purpose: enable doing it in descriptive stats not under other other tests (like it says in the manual)
* Use-case: Posting confidence intervals with your results (for now I have to use other programs to calculate those).

**Comment by EJWagenmakers** [comment]
The problem here is that a CI is an inference on a model parameter. Do you wish to assume that we are dealing with estimating a single normal mean, such that y_i ~ N(mu,sigma)? But the values may be counts, or ratios, or variances...We do provide the standard error and a QQ plot, but I'm not sure we want to move to a CI...maybe if we use the bootstrap things will work out automatically...
EJ

**Comment by SterArcher** [comment]
I am not that much into statistics (I am a med student) and I cannot give you the answer in technical terms. The problem is that you have to post CI with your results and if there is no option like that in descriptive stats (like in other programs) you have to hustle with workarounds. I have posted screenshot of the descriptive stats dialog in prism 8.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/29688990/61576796-6d04bf00-aade-11e9-8212-bf6a8c1a75ed.png">

**Comment by juliuspfadt** [comment]
@SterArcher, I apologize for the late reply. I think this is fixed by now, could you check the latest release and reopen this issue if you feel it is unresolved.
