### ISSUE TITLE
Power Analysis

### ISSUE THREAD

**Issue by cjkoch** [jasp-stats/jasp-issues#44]
## Environment (for bugs)

* JASP version:
* OS name and version:
* Analysis: Graphing with CI or SE and effect sizes are important but it might also be helpful to include power analysis to support hypothesis tests.

**Comment by Glitchy-Tozier** [comment]
I think this feature would be a big step in differentiating JASP from other software, like SPSS.

Also having power analysis present would really help Linux users that don't want to learn R or mess around with WINE or virtual machines just to do power analysis. (Which would make Jasp especially attractive for them)

**Comment by tomtomme** [comment]
I would like to see Power-Analysis included in JASP too (even if G*Power works fine with wine on linux with no hassle)! Yes, its a huge task, but G*Power development is stalled since some years and is missing some important tests. Its also english only. I would add the german translation to JASP-Power :D

And there are R-packages for power-analyises that may make it easier to integrate into JASP? Like:

power-calculator-website with open source R-Code
http://powerandsamplesize.com

Package | Purpose
pwr |  for a variety of models
webpower |  for a variety of models
power and ES  |  for a variety of models
MBESS  |  for a variety of models
PANGEA | Power ANalysis for GEneral Anova designs
crossedpower | Power Analysis with Crossed Random Effects
SIMR, pamm, clusterPower, nlmeU| for linear mixed models
simglm | to calculate the power through simulation
asypow | Power calculations via asymptotic likelihood ratio methods
longpower |  for longitudinal data
PwrGSD |  for group sequential designs
pamm |  for random effects in mixed models
powerSurvEpi |  for survival analysis in epidemiological studies
powerMediation |  for mediation effects in linear, logistic, Poisson, and cox regression
semPower | for structural equation models (SEM)
powerpkg |  for the affected sib pair and the TDT (transmission disequilibrium test) design
powerGWASinteraction | for interactions for GWAS
gap | for case-cohort designs
ssize.fdr | for microarray experiments
powerEQTL |  for eQTL Analysis
PowerTOS |  for various study designs used in equivalence studies.
Superpower | for Factorial ANOVA designs

**Comment by Glitchy-Tozier** [comment]
I can't contribute much R knowledge but I definitely can help with the translating to German process.

**Comment by boutinb** [comment]
@tomtomme Maybe it could be use-case for our workshop? Not the whole power analysis, but some easy part.

**Comment by EJWagenmakers** [comment]
We want this in JASP at some point in the future, but we want to do it well and it is a pretty major extension imo.

**Comment by tomtomme** [comment]
I think this can be closed, now that the power-module is there. Obviously it misses ANOVAs and Regressions, but still the "foot is in the door" (german saying thats possibly not really translatable :D)
