### ISSUE TITLE
Solved: 2-Way ANOVA erroneously saying there are aliased coefficients in model. Wrong error message for empty cell in the interaction. 

### ISSUE THREAD

**Issue by DanielShowalter** [jasp-stats/jasp-issues#441]
* JASP version: 0.10
* OS name and version: Windows 10
* Analysis:
* Bug description: ANOVA function is claiming that predictor variables are linearly dependent when they are not. Have repeated this error on a separate computer. Have also conducted many 2-way ANOVA tests successfully in JASP.
* Add JASP files as a zip:

[Behavioral Risk Factor Surveillance Survey - BRFSS_Race_Sleep_Flu_dan.xlsx](https://github.com/jasp-stats/jasp-issues/files/3464228/Behavioral.Risk.Factor.Surveillance.Survey.-.BRFSS_Race_Sleep_Flu_dan.xlsx)

* Screenshot: 
![image](https://user-images.githubusercontent.com/15852713/62416099-e209e580-b602-11e9-90e7-325bac5fecd8.png)

* Expected behaviour: Should produce output for these variables since there is no linear combination of the predictor variables (this can be verified by running a correlation between them and seeing that it is nowhere near 1).
* Steps to reproduce: 
1. Import data from attached spreadsheet.
2. Run an ANOVA with CHECKUP1 as the Dependent and FLUSHOT6 and EDUCA as the factors.

**Comment by AlexanderLyNL** [comment]
The problem here is the data resulting in an empty cell in your EDUCA x FLUSHOT6 (6 x 2) table. There are only 2 people (id: 5961 and 6692) that scored a 1 in EDUCA and both of them score a 1 on FLUSHOT6. Hence, the cell EDUCA=1 x FLUSHOT6=2 is empty and the ANOVA with interaction can simply not be performed. The error message is not that informative and we should change that. 

If you're not interested in the interaction between EDUCA and FLUSHOT, then one way out would be to remove the interaction under the model tab. 

Another option would be to remove all cases, where EDUCA=1 from the analysis, which can be done with a filter. I've done this analysis for you, see the JASP file:
[Behavioral.Risk.Factor.Surveillance.Survey.-.BRFSS_Race_Sleep_Flu_dan.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/3464903/Behavioral.Risk.Factor.Surveillance.Survey.-.BRFSS_Race_Sleep_Flu_dan.jasp.zip)

Please reopen if something else's unclear. 

@JohnnyDoorn could you please keep check for an empty cell, when rewriting the analysis?

**Comment by DanielShowalter** [comment]
Ah, yes! I see. Thanks so much!
