### ISSUE TITLE
Effect size for paired Wilcoxon test

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#447]
For the attached data JASP shows a very strange result ror the paired Wilcoxon test: 

ES = -1 with 95% CI from -1 to -1

[LF_BefAft.zip](https://github.com/jasp-stats/jasp-issues/files/3488870/LF_BefAft.zip)

Nikita

**Comment by tomtomme** [comment]
@NikitaKhromov-Borisov 
since ALL data points after are higher than before, this seems to be correct. The effect of the ranked data is perfect. See also the footnote of the table that states that the ES is the rank-biserial correlation, which shows a perfect correlation here. This is sumulated or fake data I presume?

This can be closed.
