### ISSUE TITLE
Ordinal data for CFA in JASP

### ISSUE THREAD

**Issue by Jaurell** [jasp-stats/jasp-issues#462]
Hello.

I've noticed that you need to specify that data is continuous in JASP in order to be able to assign it to a factor in the CFA module. If I'm not wrong the module is based on the lavaan package in R. The package have robust estimators that should be able to handle skewed data and also ordinal data. Therefor i suggest that the limitation on what level of data that go into the CFA module should be removed.

> full support for analyzing categorical data: lavaan (from version 0.5 onwards) can handle any mixture of binary, ordinal and continuous observed variables
http://lavaan.ugent.be/features.html

**Comment by vankesteren** [comment]
This has been fixed, should be in one of the next releases of JASP!

**Comment by pnovoa** [comment]
Any update about this issue? I currently used JASP 0.14.1 but I have no clue on how to bound ordinal variables (measured indicators) to a factor.

**Comment by boutinb** [comment]
Sorry for the late answer, but your comment doed not appear in GitHub. It's always better to answer directly with the GitHub site.
This problem is solved in the next release. Hopefully 0.16 will be released over 1 or 2 months.
Kind regards,
Bruno

________________________________
Van: Pavel Novoa ***@***.***>
Verzonden: vrijdag 5 maart 2021 12:14
Aan: jasp-stats/jasp-issues ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: Re: [jasp-stats/jasp-issues] Ordinal data for CFA in JASP (#462)


Any update about this issue? I currently used JASP 0.14.1 but I have no clue on how to bound ordinal variables (measured indicators) to a factor.
