### ISSUE TITLE
Aliased coefficients error code

### ISSUE THREAD

**Issue by mlpetrun** [jasp-stats/jasp-issues#495]
* JASP version: 10.2
* OS name and version: Windows 10
* Analysis: two-way ANOVA
* Bug description: When I try to run a two-way ANOVA, I get an error code "there are aliased coefficients in the model."  Not sure what this means and I cannot find how to fix this via google.
* Steps to reproduce: 
1. Go to ANOVA > Select ANOVA
2. Move "treat" and "stress" to fixed factors. Move "distance traveled" to dependent variable
3. See error.
[Acute NAC BEH DATA FINAL Fall 2018.zip](https://github.com/jasp-stats/jasp-issues/files/3631782/Acute.NAC.BEH.DATA.FINAL.Fall.2018.zip)
![Screenshot (11)](https://user-images.githubusercontent.com/55547438/65254209-8962af00-dac1-11e9-8f0b-85284ad8b8e4.png)

**Comment by JohnnyDoorn** [comment]
Hi @mlpetrun 
I just took a look at your data, and there might be some unintentional periods in the factor level names:
![Screenshot_2019-09-20_10-47-58](https://user-images.githubusercontent.com/15704203/65313128-2726ae80-db94-11e9-90da-63d530ec2865.png)

This causes some combination of the factor levels (because you include the interaction term in your model) to have empty cells (i.e., 0 observations), which in turn leads to that error message. It's similar to the issue reported here: https://github.com/jasp-stats/jasp-issues/issues/441
You can either run a different SS type ANOVA, remove the interaction, or, and I think this makes most sense, remove the periods from the factor level names, so that each factor has 2 levels. I think the last approach is what was intended, and will probably fix your issue.

Kind regards,
Johnny

**Comment by mlpetrun** [comment]
Thanks for catching that!  That was one of the first things I checked in my csv file, but the periods were not showing in my raw file?  So I just retyped everything and it's working fine now.  Weird.
Thanks!

**Comment by JohnnyDoorn** [comment]
No problem - glad it worked out =)
