### ISSUE TITLE
JASP reports internal error 

### ISSUE THREAD

**Issue by LukeOU** [jasp-stats/jasp-issues#498]
* JASP version: 0.11.0.0
* OS name and version: Windows

* Bug description: JASP reports internal error when I want to run Bayesian T test or descriptives

* Screenshot: 
![obrazek](https://user-images.githubusercontent.com/55790015/65593572-0cd44280-df91-11e9-85e1-929721097921.png)

**Comment by JorisGoosen** [comment]
Could you check if, after you turn on logging, you have logfiles for both `Desktop` and `Engine`?

**Comment by LukeOU** [comment]
Thank you for your quick response. 

Sorry, but how can I get this information?

However, I wanted to finish my work so I uninstalled version "11" and installed the older version "10.2". And the analysis is ok in this older version now. 

Best,

Lukas


>>> Joris Goosen <notifications@github.com> 25.09.2019 13:33 >>>
Could you check if, after you turn on logging, you have logfiles for both `Desktop` and `Engine`?

**Comment by JorisGoosen** [comment]
If you have the time to install 0.11 you can open `Preferences -> Advanced -> Logging options`.
There you can enable `Log to file` and then choose `Show logs`.

It will open file explorer and show you a bunch of logs. And I am very curious whether you have `JASP ... Engine.log` files. Because there seems to be a correlation between people who have that problem on windows and cannot run specific analyses...

**Comment by LukeOU** [comment]
Ok, I did it - enclosed.

Thank you.

Lukas


>>> Joris Goosen <notifications@github.com> 25.09.2019 13:55 >>>
If you have the time to install 0.11 you can open `Preferences -> Advanced -> Logging options`.
There you can enable `Log to file` and then choose `Show logs`.

It will open file explorer and show you a bunch of logs. And I am very curious whether you have `JASP ... Engine.log` files. Because there seems to be a correlation between people who have that problem on windows and cannot run specific analyses...

**Comment by JorisGoosen** [comment]
@LukeOU I see nothing here on GitHub...

Maybe you can simply follow the link https://github.com/jasp-stats/jasp-issues/issues/498 and post it directly instead of emailing in a reply?
I think something went wrong there.

**Comment by LukeOU** [comment]
![obrazek](https://user-images.githubusercontent.com/55790015/65601071-b1f71700-dfa1-11e9-96ca-8923212aeddb.png)

**Comment by JorisGoosen** [comment]
@LukeOU thank you!

So it seems you have the same problem as in #474...
I will try to figure out what is going wrong there... Sadly enough I do not have a Windows system here with the same problem...

**Comment by LukeOU** [comment]
Well, thank you for your help. Fortunatelly, the older version is ok. Never mind, this stats software is great. Well done. Thank you. Good luck to manage this error soon.

**Comment by JorisGoosen** [comment]
Well, luckily the old version works!

**Comment by boutinb** [comment]
It seems to be a permission problem. Are you admin of your PC?

**Comment by boutinb** [comment]
Hi @LukeOU 
I have tried many configurations on different PC's, but I cannot reproduce this problem. So it seems that JASP cannot work properly with a peculiar component/feature/setting on Windows PC. It would help me a lot if you answer these questions so that I can maybe find the source of this problem.
. The problem might come from the character set used in your PC. Which language do you use on your PC? Do you use normal latin letters, special latin letters (like ü, ø, ę) or another alphabet?
. The problem might come from permission problem. Is your PC from your work, or is it your own PC. Has the account you use an administrator right (you can install anything without asking someone else), or do you need to use a special account to install JASP?
. The problem might also come from a particular hardware/Operating system. You said that you have Windows 10, but which edition is it? Is it Windows 10 Home edition, Windows 10 Enterprise, Windows 10 Education, Windows 10 Mobile?
. Also it is quite important for us to know exactly which analysis makes this crash: can you try both Descriptives Statistics and Reliability Analysis and tell us which one crashes?

We have also a version that does not need installation (http://static.jasp-stats.org/JASP-0.11.0.3-x64.zip), can you download it, unzip it, and check if this JASP version has the same problem?

I know it is a lot of questions, but we need your help to solve this problem.
Kind regards,
Bruno

**Comment by LukeOU** [comment]
Hi Bruno,

thank you for your support. 

To specify the problem and answer your questions:
1. I use Czech language and yes, there are some special characters not
used in English.
2. This is my work desktop PC with one account. I´m an administrator
and I´m allowed to install anything without permission. 
3. Windows Enterprise.
4. I checked what is not working: e.g. Descriptive, Bayes. T-test,
Bayes - ANOVA, Binomial Test.

But also I want to let you know that I had similar problem with older
version (I think 10.2.) where Descriptive did not work. And I think that
the problem is identical at my work laptop and my home PC as well.

Cheers,

Lukas


-----------------------------------
ass. prof. PhDr. Lukas Cipryan, Ph.D.
Exercise Physiology
Human Motion Diagnostic Centre
   & Department of Human Movement Studies;
University of Ostrava, Czech Republic
Phone: +420 553 46 2594. Mobile: +420605807925
Skype: lukas.cipryan



>>> bruno boutin <notifications@github.com> 30.09.2019 10:36 >>>
Hi @LukeOU 
I have tried many configurations on different PC's, but I cannot
reproduce this problem. So it seems that JASP cannot work properly with
a peculiar component/feature/setting on Windows PC. It would help me a
lot if you answer these questions so that I can maybe find the source of
this problem.
. The problem might come from the character set used in your PC. Which
language do you use on your PC? Do you use normal latin letters, special
latin letters (like ü, ø, ę) or another alphabet?
. The problem might come from permission problem. Is your PC from your
work, or is it your own PC. Has the account you use an administrator
right (you can install anything without asking someone else), or do you
need to use a special account to install JASP?
. The problem might also come from a particular hardware/Operating
system. You said that you have Windows 10, but which edition is it? Is
it Windows 10 Home edition, Windows 10 Enterprise, Windows 10 Education,
Windows 10 Mobile?
. Also it is quite important for us to know exactly which analysis
makes this crash: can you try both Descriptives Statistics and
Reliability Analysis and tell us which one crashes?

We have also a version that does not need installation
(http://static.jasp-stats.org/JASP-0.11.0.3-x64.zip), can you
download it, unzip it, and check if this JASP version has the same
problem?

I know it is a lot of questions, but we need your help to solve this
problem.
Kind regards,
Bruno

**Comment by boutinb** [comment]
Hi @LukeOU 
Could you try this version: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-WindowsJaspResultsHotfix-4fac875f1aaccfc0547bb72d5413341506536b0d.msi
This is an 'unsigned' version, that means that your PC will warn you that it does not know from whom it is. It might be also slower.

**Comment by LukeOU** [comment]
Dear Bruno,

I am very sorry for this delay. I tried today version 0.11.0.0. for the Independent T-test. It worked. But then I wanted to run Bayesian Independent T-test and the some error appeared. So I tried the version you sent me and it worked.

Cheers,

Lukas


>>> bruno boutin <notifications@github.com> 01.10.2019 14:42 >>>
Hi @LukeOU 
Could you try this version: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-WindowsJaspResultsHotfix-4fac875f1aaccfc0547bb72d5413341506536b0d.msi 
This is an 'unsigned' version, that means that your PC will warn you that it does not know from whom it is. It might be also slower.

**Comment by JorisGoosen** [comment]
Good!

**Comment by boutinb** [comment]
We have also an official version (0.11.1) with the fix you need (https://jasp-stats.org/download/)

**Comment by LukeOU** [comment]
Thank you, that´s a great news.

Lukas


>>> bruno boutin <notifications@github.com> 29.10.2019 12:05 >>>
We have also an official version (0.11.1) with the fix you need
(https://jasp-stats.org/download/)
