### ISSUE TITLE
Program closes

### ISSUE THREAD

**Issue by modelistatistik** [jasp-stats/jasp-issues#501]
After the last update, JASP shuts down after installing the program.

* Analysis: Machine learning
* Screenshot: ![index](https://user-images.githubusercontent.com/29062713/65700666-518ad700-e080-11e9-9e22-1fee9e142305.png)

**Comment by JorisGoosen** [comment]
Would you be so kind as to fill in the information that you now left blank? Such as "JASP version" and especially things such as "OS name and version".

We cannot help you otherwise.

**Comment by modelistatistik** [comment]
sorry. I just downloaded and installed the new version. It failed as it did in the screenshot. The program is installed in the windows operating system. 

What is the OS name?

**Comment by JorisGoosen** [comment]
OS name stands for "Operating System name" and it seems that in your case it is Windows, probably 10?

And when you say it fails as in the screenshot, you mean it crashes directly after starting or only after taking certain actions? Such as running an analysis or something?

**Comment by JorisGoosen** [comment]
@modelistatistik as you answered in the other issue, you use Windows 10.

Are you the administrator of your PC?

**Comment by modelistatistik** [comment]
Yes, true. 
OS name : Windows 10
I'm starting the JASP program. I am uploading any data file. Then when I open the machine learning analysis, it gives this error and shuts down.

**Comment by JorisGoosen** [comment]
That is too bad...

Could you try the `Frequencies -> Bayesian Linear Regression`, just to see if it doesn't crash then?

Because if it does not crash in that scenario it is highly likely you have the same problem that https://github.com/jasp-stats/jasp-issues/issues/474 has.

**Comment by modelistatistik** [comment]
hi,

You can download the video from the link below.
https://yadi.sk/d/CxtDmAeL_tlT5Q

**Comment by boutinb** [comment]
Hi @modelistatistik,
I have tried many configurations on different PC's, but I cannot reproduce this problem. So it seems that JASP cannot work properly with a peculiar component/feature/setting on Windows PC. It would help me a lot if you answer these questions so that I can maybe find the source of this problem.
. The problem might come from the character set used in your PC. Which language do you use on your PC? Do you use normal latin letters, special latin letters (like ü, ø, ę) or another alphabet?
. The problem might come from permission problem. Is your PC from your work, or is it your own PC. Has the account you use an administrator right (you can install anything without asking someone else), or do you need to use a special account to install JASP?
. The problem might also come from a particular hardware/Operating system. You said that you have Windows 10, but which edition is it? Is it Windows 10 Home edition, Windows 10 Enterprise, Windows 10 Education, Windows 10 Mobile?
. Also it is quite important for us to know exactly which analysis makes this crash: can you try both Descriptives Statistics and Reliability Analysis and tell us which one crashes?

We have also a version that does not need installation (http://static.jasp-stats.org/JASP-0.11.0.3-x64.zip), can you download it, unzip it, and check if this JASP version has the same problem?

I know it is a lot of questions, but we need your help to solve this problem.
Kind regards,
Bruno

**Comment by modelistatistik** [comment]
Thanks for interest. 

1. Turkish language. 
2. My special PC. Not work PC. 
3. Windows 10 Pro (Original Version)
4. Sure, this video : https://yadi.sk/i/t8MOftccEGsg3Q
5. Still problem continiue : https://yadi.sk/d/ExA9UQWehkowDQ

If there is anything I can help, please contact me.
We want to represent you as free and voluntary in Turkey.

Best regards, 

Gökhan Karakoç

**Comment by boutinb** [comment]
Hi @modelistatistik , could you try this version: http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-WindowsJaspResultsHotfix-4fac875f1aaccfc0547bb72d5413341506536b0d.msi
This is an 'unsigned' version, that means that your PC will warn you that it does not know from whom it is. It might be also slower.

**Comment by modelistatistik** [comment]
Hey,

Everything works correctly. Bless your hands.
What was the problem?

Thanks for helps. 

Gökhan Karakoç

**Comment by boutinb** [comment]
If your username on your PC contains non 'normal' latin characters, then some analyses cannot find the a temporary folder to write down some state...
We will make a hotfix version.
Thanks for your contribution.

**Comment by modelistatistik** [comment]
You're welcome. I'm glad this problem is solved. We can be your representative in Turkey:) Our completely voluntary and without any financial expectations:)

Our website:

https://www.modelistatistik.com/

**Comment by AlexanderLyNL** [comment]
Hi modelistatistik,

Thanks for your help. Could you please send me an email? {firstLetter}.[lastName]@jasp-stats.org

Cheers,
Alexander

**Comment by modelistatistik** [comment]
Hi AlexanderLyNL, 

Of course,

gokhan.karakoc@modelistatistik.com
If you need further information, please contact me.

Best regards, 
Gökhan Karakoç
