### ISSUE TITLE
Feature request: handling of TSV-files

### ISSUE THREAD

**Issue by larsgw** [jasp-stats/jasp-issues#511]
Sorry for not following the template, but it seemed a bit too elaborate for my purposes. I would like to be able to import (and export, sync, etc.) tab-delimited values files as `.tsv` instead of as `.txt`.

Is this something that I could work on? If so, can I get some general pointers? I saw the file menu is filtered in https://github.com/jasp-stats/jasp-desktop/blob/master/JASP-Desktop/widgets/filemenu/computer.cpp but I assume it'd need to now that `.tsv` is the same as `.txt` somehow when importing, where would that be?

**Comment by boutinb** [comment]
That' s true that JASP supports already tab separated value file, but the extension must be txt instead of tsv. The fix is not only in this file, but unfortunately it has to done in several files (you can see that if your seach for all csv entry in the code). If you feel able to do this, you can try it. If not I will do it for the next release.

**Comment by larsgw** [comment]
I'm still trying to build JASP to test it, but I have a patch at https://github.com/jasp-stats/jasp-desktop/pull/3575.

**Comment by boutinb** [comment]
Implemented for 0.12
