### ISSUE TITLE
Repeated Measures ANOVA Error 

### ISSUE THREAD

**Issue by alliecat966** [jasp-stats/jasp-issues#560]
* JASP version: 0.11.1

* OS name and version: macOS Catalina 
* Analysis: Repeated Measures ANOVA 
* Bug description: I am trying to conduct a repeated measures ANOVA in JASP. I have one repeated measures factor (a biomarker that is continuous, collected before and after an intervention so the levels, or repeated measures cells, are baseline and post). I would like to add one covariate (age) and three between subjects factors (Group (1,2,3), Gender (M,F) and Education Level (BA, MA, D, Other) to my analysis. Unfortunately, I am getting the following error when I add more than two between subjects factors: "Some parameters are not estimable, most likely due to empty cells of the design" and the analysis won't run. I don't have any missing data in those columns and my data set is in wide-form. I'm not sure what the problem is.
* Expected behaviour:
![Screen Shot 2019-11-25 at 11 07 56 AM](https://user-images.githubusercontent.com/58186887/69566759-0bb19880-0f75-11ea-84f3-e380c9dd4617.jpg)

**Comment by lazy-user** [comment]
Hi alliecat966,

you may have no missing raw data, but you likely have empty cells as indicated by JASP. An ANOVA creates groups of all possible combinations of your between-subjects factor conditions. That is, you may have no participant in group 1, who is male and has the education "other", etc. etc., and, thus, group size is zero and the ANOVA can't be run.

**Comment by FransMeerhoff** [comment]
Hi @JohnnyDoorn 

Can you please respond on this issue?

**Comment by JohnnyDoorn** [comment]
Hi @alliecat966 

In the new JASP release, the RM ANOVA has been rewritten and this error message will be clearer. What you can try for now, is using a different type of sum of squares, because different types deal with missingness in cells better than other types. If that does not work, you can try the nightly jasp build (sort of a beta version of JASP, with all new features added, but that still need some testing). 
http://static.jasp-stats.org/Nightlies/

I hope this solves your issue, please reopen if i still persists.
Kind regards,
Johnny
