### ISSUE TITLE
ANOVA requeste

### ISSUE THREAD

**Issue by ManuelP71** [jasp-stats/jasp-issues#580]
how about in the ANOVA, the expected mean square and root mean square?
Is it possíble?

**Comment by tomtomme** [comment]
@ManuelP71 
I guess this can be closed, since mean squares are displayed in ANOVA outputs (and to my knowledge have always been included). And it is not clear to me how "root mean square" is more useful here since we want to know the signal-to-noise ratio given by F.

Or are you talking about something else?
