### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by ergulkara2018** [jasp-stats/jasp-issues#586]
hi japs team ı am a jasp user and also beta tester.
recently take an internal error
data flie is open in SPSS at the same time.
unfortunaltely ı can share data but it ok in spss
thank you..

![Adsız](https://user-images.githubusercontent.com/43642291/72281521-c728ac00-364b-11ea-84da-5e9a43442e9d.png)

**Comment by boutinb** [comment]
Hi @ergulkara2018 Is it something happening for a particular SPSS file. In this case, can you send your SPSS and JASP files?

**Comment by FransMeerhoff** [comment]
Hi @ergulkara2018 

At the moment we cannot solve this problem, because we do not have a reproduction path.
Some days ago a request was done by boutinb to send us the SPSS file where the problem occurs.
If this is not possible please let us know, perhaps we can find another way to generate a reproduction path.

Kind regards 
Frans Meerhoff

**Comment by ergulkara2018** [comment]
hi Frans

sorry data is my dissertation data and I cant share right now.
ı am using japs long time this is first time something like that happen
with last version of program.
 if can help anything else let me know..


Best regards

**Comment by JorisGoosen** [comment]
@ergulkara2018 do you maybe have this same issue with other spss files as well?
As in, does it crash on all data?
And perhaps you can test with one of our [experimental "nightly" versions](http://static.jasp-stats.org/Nightlies/) because I've made some changes to the way spss files are read and maybe the problem is already gone. Be advised that we are still testing these versions to be sure they are good to go in release.

**Comment by JorisGoosen** [comment]
@ergulkara2018 could you test [this zipped version of the nightly](http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-8bd2b16cbec9898ab4c272b1bd9a2ebfd079087c.zip) or [this installer of the same](http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-8bd2b16cbec9898ab4c272b1bd9a2ebfd079087c.msi). It would be great if you could test it so that we know we solved the problem.

**Comment by ergulkara2018** [comment]
Ok I will and let you know

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________

**Comment by ergulkara2018** [comment]
hi current version is working fine. and problem solved thank you....

Android için Outlook <https://aka.ms/ghei36>'u edinin

------------------------------
*From:* Joris Goosen <notifications@github.com>
*Sent:* Tuesday, March 3, 2020 3:43:20 PM
*To:* jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
*Cc:* ergulkara2018 <ergunkara2018@gmail.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [jasp-stats/jasp-issues] internal error (#586)


@ergulkara2018 <https://github.com/ergulkara2018> could you test this
zipped version of the nightly
<http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-8bd2b16cbec9898ab4c272b1bd9a2ebfd079087c.zip>
or this installer of the same
<http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-8bd2b16cbec9898ab4c272b1bd9a2ebfd079087c.msi>.
It would be great if you could test it so that we know we solved the
problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jasp-stats/jasp-issues/issues/586?email_source=notifications&email_token=AKM63M5ET7GUUNLWGNFKL63RFT3ORA5CNFSM4KGG2EQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENTK4AQ#issuecomment-593931778>,
or unsubscribe

**Comment by JorisGoosen** [comment]
Great!

We will be releasing it as a proper version quite soon, we just need to iron out a few more bugs. You can keep using the nightly if you like, but keep in mind that there might still be some small problems we are working on.
