### ISSUE TITLE
Multiple crashes when filtering a large data set

### ISSUE THREAD

**Issue by rtbarber** [jasp-stats/jasp-issues#592]
I am working with a 1M+ record data set.  In order to cut that down a bit, I have applied several filters based on GE or LE.  The product periodically crashes when I apply the filter.  

Observations - the first time I apply the filter it seems to work fine.  However when I change it or add another item, it will fail.  

Running on Windows 10 Pro v 1809
I7-4770, 16G ram 64 bit
JASP 0.11.1 (just installed today)

**Comment by FransMeerhoff** [comment]
Hello @rtbarber 

Is it possible that you send us the data set you are working on, and give us a bit more detailed description of the filters, and sequence, you are using?
If not so, can you try to reproduce the problem with one on the data sets from the  Data Library (reached  from the open tab in our main menu; E.g. Machine Learning->Telco Customer Churn is a big data set)
Sorry for the inconvenience,

Kind Regards 
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hi @rtbarber 

We are almost in the phase of releasing a new version JASP 0.12.
Can you please reopen this issue if the problem still occurs.

Kind regard
Frans Meerhoff

**Comment by bstumpf16** [comment]
I've been having similar issues with periodic crashes after utilizing the filters. My data set has around 3,000 records and the filter is usually on a variable with two or three categories. I couldn't recreate it using the Telco Customer Churn data, but perhaps that's due to the number of variables? Telco Customer Churn seems to have 21 variables and my data has 252. 

Running on Macbook Pro
2.5 GHz Quad-Core Intel Core i7, 16 GB ram
macOS Catalina 10.15.3
JASP 0.12.2

**Comment by boutinb** [comment]
Can you send us your dataset?
