### ISSUE TITLE
"residual df = 0" in two-way ANOVA with one obs per cell

### ISSUE THREAD

**Issue by PeterKlaren** [jasp-stats/jasp-issues#599]
Using JASP 0.11.1, performing 2-way ANOVA on a 6x5 dataset with 1 value per cell (N = 30), JASP cannot work out the interaction component and produces the error "residual df = 0."
![image](https://user-images.githubusercontent.com/43278770/73142534-26e17700-4090-11ea-88ad-cd99779b5ed7.png)

R, however, can produce a 2-way ANOVA table with interaction term:
![image](https://user-images.githubusercontent.com/43278770/73142589-cef74000-4090-11ea-92f5-6cbb5218cd79.png)

Here's my datat.
[soybeanYield.txt](https://github.com/jasp-stats/jasp-issues/files/4114587/soybeanYield.txt)

Cheers,

Peter

**Comment by FransMeerhoff** [comment]
Hi @JohnnyDoorn 

Can you please have a look at this issue?

Cheers Frans

**Comment by JohnnyDoorn** [comment]
Hi @PeterKlaren ,

The aov function in R just fits the model to your data.
In order to get the Anova table, you can call the anova function on your aov object:
`anova(m1)`
However, if you do this in R, you get the following output:

Analysis of Variance Table

Response: Yield
                  Df  Sum Sq Mean Sq F value Pr(>F)
Spacing            4 125.661 31.4153               
Replicate          5   5.410  1.0819               
Spacing:Replicate 20  73.919  3.6959               
Residuals          0   0.000                       
Warning message:
In anova.lm(m1) :
  ANOVA F-tests on an essentially perfect fit are unreliable`

If you only have a single observation per cell, you have an undefined variance for each cell, which is necessary for computing the F-statistic.

Kind regards
Johnny

**Comment by AlexanderLyNL** [comment]
I consider this solved. Please reopen if something's still unclear.
