### ISSUE TITLE
Standard error bars in RM ANOVA plot

### ISSUE THREAD

**Issue by frdarya** [jasp-stats/jasp-issues#601]
* JASP version: 0.11.1
* OS name and version: MacOS, Windows 10
* Analysis: RM Anova
* Bug description: using the descriptive plots in repeated-measures ANOVA with standard error of mean as the error bar, produces error bars smaller than the actual value of the SEM (about half). I'm not sure whether this is a different way of calculating SEM for repeated measures [instead of SD/sqrt(N) ] or a bug?

Thanks!

**Comment by FransMeerhoff** [comment]
Hi @frdarya 

Could you please send us the JASP file where this problem occurs?
(You can do this by putting it in a zip file and drag it to this issue)

Kind regards
Frans Meerhoff

**Comment by frdarya** [comment]
Hi @FransMeerhoff ,
Here's the file, thanks!

[rt.zip](https://github.com/jasp-stats/jasp-issues/files/4139020/rt.zip)

**Comment by JohnnyDoorn** [comment]
Hi @frdarya ,

We follow a special procedure for the RM ANOVA plots. This is from our helpfile:
Display:
Display error bars: By selecting this option, error bars will be displayed in the plot. The error bars can either represent confidence intervals or standard errors. In order to get accurate confidence intervals and standard errors, the data are normalized by subtracting the appropriate participantʹs mean performance from each observation, and then adding the grand mean score to every observation. The variances of the resulting normalized values in each condition, and thus the size of the bars, no longer depend on the participant effects and are therefore a more accurate representation of the experimental manipulation. See Morey (2008) for a thorough discussion of this procedure.

We apply the procedure from Morey (2008), where some normalization is applied, so it is not as straightforward as sd / sqrt(n). See
Morey, R. D. (2008) Confidence Intervals from Normalized Data: A correction to Cousineau (2005). Tutorial in Quantatitative Methods for Psychology, 4(2), 61-64.

Please let me know if you have further questions about this, because it is a little tricky.

Cheers,
Johnny

**Comment by FransMeerhoff** [comment]
Hi @frdarya 

Was the answer of @JohnnyDoorn  enough explanatory?
If so then I can close this issue.

Kind regards
Frans Meerhoff
