### ISSUE TITLE
Logit regression matrix

### ISSUE THREAD

**Issue by breakbitero** [jasp-stats/jasp-issues#604]
This analysis terminated unexpectedly.

Error in chol.default(mat): la submatriz de orden 28 no es definida positiva

Stack trace
analysis(dataset = dataset, options = options, perform = perform, callback = the.callback, state = oldState)

.glmEstimatesTable(lrObj, options, perform, type = 'binomial')

mdscore::wald.test(glmObj[[2]], term = i)

wald.default(model = model, terms)

invmat(crossprod(X2, w * X2))

chol2inv(chol(mat))

chol(mat)

chol.default(mat)

**Comment by FransMeerhoff** [comment]
Hello @breakbitero 

Could you please send us the JASP file where this problem arise.
And send us the the information as described in the template issue;
* JASP version:

* OS name and version:
* Analysis: 
* Bug description:
* Expected behaviour:

This would help us a lot reproducing and solving the problem.

Kind regards
Frans Meerhoff

**Comment by FransMeerhoff** [comment]
Hello @breakbitero 

If this problem still occurs, please reopen  this issue (with the template questions filled in).
We cannot reproduce it.

Kind regards
Frans Meerhoff
