### ISSUE TITLE
Why does 0.11.1.0 keep crashing?

### ISSUE THREAD

**Issue by BrianFink-Lourdes** [jasp-stats/jasp-issues#623]
I cannot even get a procedure to run without getting the Internal Error, crash, report to github garbage. 

This is not acceptable.

And, when I click on JASP, it says this does not even have the full features yet and check back tomorrow. So, what is the most recent version?  AND, which version ACTUALLY WORKS???

**Comment by EJWagenmakers** [comment]
Hi Brian,

This must be a very frustrating experience. Of course JASP is not supposed to crash like this, and, luckily for other users, it very rarely does. But to prevent the same frustration for users that happen to have the same setup as you we'd like to try and fix this for you. But in order to fix it we do need more information. Of course, if it would crash like this on our systems, we would not have released it upon the world. So something peculiar/idiosyncratic is going on.

The most recent version is clearly indicated on our download page. The message about full features merely informs you that JASP is under constant  development. In fact, we are testing a new version now, and it will be out in a few weeks. It may be that this version fixes your problem, but maybe not. So if you have detailed information we'd like to help you. But it is up to you, I can imagine you need a little break from the frustration of the crashes. 

Cheers,
E.J.

**Comment by BrianFink-Lourdes** [comment]
There is nothing more I can provide. I downloaded JASP. If lucky, it can do a frequency table. Then, it crashes. It is not up to me. You provide the product. Your product does not work. Not my computer. It is JASP.
________________________________

**Comment by BrianFink-Lourdes** [comment]
JASP version: 0.11.1
OS name and version: It is an HP laptop computer. Microsoft Windows 10. Just installed 0.11.1 and all it does is crash. 
Analysis: Anything. It happens with t-test, ANOVA, descriptives. 
Bug description: It crashes. Every time. 
Expected behaviour: It should still work after ten seconds. Get the wheel of death spinning and then the same crash error box that directs me to this page. I tried removing Blocking Cookies, that did not work. 
Fix the thing!
Steps to reproduce: Open JASP 0.11.1.0
Go to '...' any task
Click on '....'
Scroll down to '....'
See error It crashes.

**Comment by BrianFink-Lourdes** [comment]
It sometimes runs for a few minutes where you can run some analyses. Then, it just crashes. Or, it just crashes over-and-over at the start whenever you breathe.

Heard the same horror stories of students with R. Apparently, that is why this is free. Some goofy internal engine crash error box pops up every time it crashes and then refers me to here. My students are going to go nuts dealing with this thing. If it could stay functioning, it might actually be a quality product.

**Comment by EJWagenmakers** [comment]
Hi Brian,

All our tests and feedback suggests that JASP is pretty stable. The kind of behavior you report is exceedingly rare, bordering on an anomaly. Of course we still want to help, but your experience is not par for the course. If your students encounter similar problems with JASP, please point them our way!

Cheers,
EJ

**Comment by JorisGoosen** [comment]
@BrianFink-Lourdes maybe you could try the [latest test version](http://static.jasp-stats.org/Nightlies/WindowsZip/JASP-nightly-development-641578951f327cbb832b8f6f37a3189a8e5b9877.zip).
This is a zip and if you unpack this somewhere and then run "JASP.exe" we can at least figure out if we perhaps have already solved the problem. And otherwise we can take a deeper dive into this issue. If you prefer to have an installer instead of unpacking a zip you can use [this link](http://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-development-641578951f327cbb832b8f6f37a3189a8e5b9877.msi)

**Comment by TimKDJ** [comment]
See latest response in https://github.com/jasp-stats/jasp-issues/issues/622

If you do not wish to help us debug your problem, then there is nothing we can do for you. We hope you'll find other software more to your liking.
