### ISSUE TITLE
Custom contrasts

### ISSUE THREAD

**Issue by pandelis** [jasp-stats/jasp-issues#627]
* JASP version: Nightly 0.12 Mar 6 2020
* OS name and version: Windows 7

On a classic ANOVA with one factor 
[04 ViagraContrasteInter.txt](https://github.com/jasp-stats/jasp-issues/files/4297573/04.ViagraContrasteInter.txt)

When I try to use custom contrasts in the last nightly such as "-2 1 1"
then I get "Nonconforming number of contrasts coefficients".
So I try to add another contrast such as "0 -1 1".
And then I get "Please specify non-zero contrasts weights". Then I tried to specify another contrast without a 0 coefficient and it does not work either.
I think that It would be very restrictive to just allow orthogonal contrasts.

Another problem is that in an ANOVA or RM ANOVA using 2 factors  it is not possible to determine contrasts using two factors
For instance in Music.Simple.txt
[04 Music.Simple.txt](https://github.com/jasp-stats/jasp-issues/files/4297570/04.Music.Simple.txt)
, it could be interesting to test if for inf40 if there is a difference between ABBA and Kenji.

For this, one possibility would be in the "Factors" window to select a factor "music*age" and then to have a table with the possible coefficients for the two factors.

Best

**Comment by JohnnyDoorn** [comment]
Hi @pandelis 

Thanks for the feedback! 
I did change it so that also non-orthogonal contrasts are possible, but the check was incorrect. Also the error message about nonconforming number is a little more user friendly now.

Unfortunately we did not mange to include contrasts for interactions in this release, so it will be in the next. 

Cheers,
Johnny

**Comment by pandelis** [comment]
Hi,

Thanks !
I tried with the 04:10 13-03-2020 version.

In classical ANOVA it continues to be not possible to enter only one contrats with a 3 modalities factor. 
In an RM ANOVA when I contrast Eye with Phasme and Larves results are different in JASP and in Statistica and UDSAnova.
![image](https://user-images.githubusercontent.com/3620214/76630061-aa233300-653f-11ea-8340-7e68ae4abe8f.png)
![image](https://user-images.githubusercontent.com/3620214/76630075-b14a4100-653f-11ea-8b91-7ac8f06efe45.png)
![image](https://user-images.githubusercontent.com/3620214/76630114-be673000-653f-11ea-993b-c51361464f6e.png)

Here are the datas:
[05 NourritureContrasteIntra.txt](https://github.com/jasp-stats/jasp-issues/files/4330054/05.NourritureContrasteIntra.txt)

Best,

**Comment by JohnnyDoorn** [comment]
Hi @pandelis, 

I just checked your data and corresponding RM ANOVA results - are you sure you specified the same analyses in those other softwares? Because I see there you get 1 and 7 degrees of freedom, while your attached text file would lead to 2 and 14. Or do you mean that the custom contrast result differs? From the marginal means, the JASP results seem correct.

Unfortunately having to specify at least 2 custom contrasts when there are more than 2 levels is a limitation of the R package we use (emmeans).

Cheers,
Johnny

**Comment by pandelis** [comment]
Hi,

Sorry for the delay of my response (coronavirus is complicating everything).
Unfortunately I rechecked the RM Anova contrast and I specified the same analysis in the other software. 
I checked another contrast (Phasme vs Oeil) and results differ too :
Here in Statistica
![image](https://user-images.githubusercontent.com/3620214/77416431-203b5b80-6dc4-11ea-805c-cdc93b36d00c.png)
Here in JASP
![image](https://user-images.githubusercontent.com/3620214/77416575-4bbe4600-6dc4-11ea-85fd-2759c9b3fda4.png)

The good news is that for normal ANOVA, results are consistent...

Best regards

**Comment by pandelis** [comment]
I discussed with the creator of [UDSAnova](http://udsanova.jlroulin.fr/). (a powerful free software for ANOVAs [but limited to ANOVAs]
He said that he had to compute contrasts manually to have the right "error term"...

Best

**Comment by JohnnyDoorn** [comment]
Does the UDSanova use the non-pooled error term? Because emmeans uses the pooled error term here, as this is in line with how the anova model is specified (we would need to fit a generalized linear model for the ANOVA instead to have an unpooled error term).

I am not getting a lot of information from teh udsanova output - such as its SE, t-value, estimated difference. These all seem to make sense for JASP (based on the descriptives and marginal means), so I'm still wondering where the difference could lie.

**Comment by pandelis** [comment]
Hi,
With a colleague, we found in the UDSAnova documentation that:
So the error term is the general term for between factors and contrast specific for within factors. 

Best

**Comment by pandelis** [comment]
Hi,
Here is a more precise answer from UDSAnova's author :

"There are several possible pooled error terms (depending on the location) and it also depends on the nature of the contrast and the presence or absence of an INTER factor. IF JASP uses a full pooled with Sattterwaith correction (I hope), it is for me the worst choice except in very special cases. Most generally, by default it is necessary to use a pooled error term on the between factors (if they exist) and specific on the within factor (specific to the conditions declared in the contrast) in most cases."

Best

**Comment by pandelis** [comment]
I don't know if it's a good idea to post in a closed topic but I think it's the best place to post this.

In case this could be useful, here are references (from the author of UDSAnova) concerning this problem of between and within term error in contrasts:

Winer, B. J. (1971). Statistical principles in experimental design. New-York: McGraw-Hill.
Myers, J. L. (2007). Fundamentals of Experimental Design. Collecting Spatial Data. Boston: Allyn & Bacon. https://doi.org/10.1007/978-3-540-31175-1_3
Myers, J. L., Well, A., & Lorch, R. F. (2010). Research Design and Statistical Analysis. Routledge. Retrieved from https://books.google.fr/books?id=nbsOIJ_saUAC

Best regards and continue with the great work !

**Comment by FranziKessler** [comment]
Hi Johnny, I am experiencing trouble with the customized contrasts in an ANOVA analysis with the latest JASP version (0.16.1). When I enter a customized contrast I keep getting the error "please specify an additional contrast". Am I doing something wrong? It should give me the difference between group level 1 and 5, right? 
Any help would be great and highly appreciated. Many thanks in advance! 
Best, Franziska
![jasp problem](https://user-images.githubusercontent.com/102532360/160415717-c8c3df02-75b0-4530-a520-0773ea7a9892.JPG)

**Comment by JohnnyDoorn** [comment]
Hi @FranziKessler ,

Hmm yes that is strange. What happens when you "Add contrast", and specify some other contrast in addition to the one that is already there?
Also, could you send me the jasp file with the error? that way I can look a bit more closely into it, because I cannot replicate this behavior with my own data set with a factor with 5 levels. Additionally, I see that you have 5 levels of your factor, but 3 df in your ANOVA table, so maybe there is something going on there as well? Do you have >1 observations for each level?

Kind regards,
Johnny

**Comment by FranziKessler** [comment]
Hi Johnny, 
thanks for your answer!  I excluded group 4 from the analysis as indicated in the clip. It results in exclusion group 4 for the predefined contrasts. But when I open the box to define custom contrasts, group 4 is still listed.  Hence the error message still occurs. (Please refer to the screen shots attached to  illustrate what I mean by that)

Best, Franzi
![custom contrast](https://user-images.githubusercontent.com/102532360/160602812-40996cd1-fa8a-4284-81da-890a0e959ec9.JPG)
![predefined contrasts](https://user-images.githubusercontent.com/102532360/160602828-d224a863-880f-419a-a79d-4826acf3b5b3.JPG)

**Comment by JohnnyDoorn** [comment]
Hi Franzi,

Hmm that's unfortunate, and something I need to pick up with the GUI programmers. In the meantime, would it be possible to edit the data file itself and exclude group 4? I can help you with this, if needed. 

Cheers,
Johnny

**Comment by FranziKessler** [comment]
Hi Johnny, 
sure no problem! I have created an extra variable as an adaptation of the original group variable with empty fields for any fields that are fours in the original group variable. That way I can simply use the adapted group variable as the fixed factor for the specific analysis. As it doesn't indicate a level 4 of the group variable, it is no problem any longer that level four is empty in the analysis of the filtered data set. 
Thanks a lot for your quick responses! It really helped me :)

Cheers, Franzi

**Comment by saurabhr** [comment]
I am doing a two-way repeated measures ANOVA where both the factors have three levels each. I have 9 planned comparisons for the interaction. Custom contrast won't let me add contrasts above 8 for the contrast in interactions.

**Comment by JohnnyDoorn** [comment]
Hi @saurabhr ,

could you make a separate issue for this please? You can use this link: https://github.com/jasp-stats/jasp-issues/issues/new/choose 
I think the maximum number of planned custom contrasts in JASP is 9:
![image](https://github.com/jasp-stats/jasp-issues/assets/15704203/7a64db6b-037d-488b-a515-3a2168d2c3e7)


Cheers
Johnny
