### ISSUE TITLE
bayesian multinomial errors

### ISSUE THREAD

**Issue by narcilili** [jasp-stats/jasp-issues#629]
* JASP version: 0.11.1.0

* OS name and version: windows 10
* Analysis: 
* Bug description:  there are two bugs. bug 1 when I use the expected counts field an error message appears. bug 2 the descriptive plot  shows the inverse of the data. in my case, yellow has 68 and green has 32 but the plot shows the inverse.
![jasp error](https://user-images.githubusercontent.com/61888367/76121286-3dcf9d80-602e-11ea-8cbd-418f6facab1b.JPG)

![jasp error 2](https://user-images.githubusercontent.com/61888367/76121348-6192e380-602e-11ea-8fb9-4b946fd9b99f.JPG)

**Comment by FransMeerhoff** [comment]
Hi @narcilili

Thanks for reporting this. 
However we think this problem is solved in our latest development version.
You could download that version at 
http://static.jasp-stats.org/Nightlies/
Would you be so kind to test that.
If that is not  possible, or if it is not fixed,  could you send us the data file or JASP file?
(You could do that by putting it in a zip file and drag and drop it to this issue)

@TimKDJ 
Could you please look at this issue too?

Kind regards
Frans Meerhoff

**Comment by narcilili** [comment]
Hello @FransMeerhoff,

Thank you for your help. In JASP 0.12 the bugs were fixed. 

Kind regards

narcilili

**Comment by narcilili** [comment]
Hello @FransMeerhoff,

JASP version: 0.12.2

OS name and version: windows 10

Bug description: the expected counts are inverted as shown in the photo below

**Comment by TimKDJ** [comment]
Thanks for the report @narcilili this will be fixed when 0.13 hits
