### ISSUE TITLE
Graphics missing when pasting into Microsoft Word

### ISSUE THREAD

**Issue by JimWeinrich** [jasp-stats/jasp-issues#632]
* JASP version: 0.11.1
I think it also affects 0.10, but I don't have access to that version as I type this.
It did not affect 0.9.

* OS name and version: MacOS Mojave 10.14.6
Microsoft Word for Mac, version 16.34

* Bug description: Unlike JASP 9 and earlier versions, when I Copy a set of Results to the clipboard and then paste into Microsoft Word, the graphics take up space but are blank.

I have attached a zip file with a sample JASP file, the Word document, and a screen shot of the Word document.

Less important: In Word, tables appear with extraneous dotted lines, compared with the JASP presentation. These extraneous lines don't print, so I'm guessing that this is not a bug, but is a setting inside Word that I am unaware of. But if it is a bug, please fix it, too!

* Expected behavior: The graphics appear flawlessly similar to their appearance in the JASP output panel, as they did in JASP 9 and earlier versions.

#### Steps to reproduce:
1. In JASP, open data library, descriptives, 'Fear of Statistics'
    (or open attached JASP file)
2. Click on triangle next to Results at top of page, choose Copy.
3. Switch to Microsoft Word. Create new document. Paste.
4. The text and table show up OK, but where the graphics should be are just empty spaces. It seems to be pasting SOMETHING there, but it appears blank. Double-click where the graphic should be, and Word will highlight something about the right size, but blank.

Apologies if this is just some setting I don't know about, but... I'm stumped! Thanks.

[JASP bug March 2020.zip](https://github.com/jasp-stats/jasp-issues/files/4304068/JASP.bug.March.2020.zip)

**Comment by FransMeerhoff** [comment]
Hi @JimWeinrich 

Thanks for reporting this. 

But I think this problem is solved on our latest version JASP 0.12 (with a lot of new features) that will soon be released.
You could check that on our latest nightly build :
http://static.jasp-stats.org/Nightlies/
A small warning here: The data library for this version must be updated to the latest version, but we will do that just before the final release, so a message will appear that the belonging JASP file is from an older version.

It would be nice if you confirm that your problem does not occur on the 0.12 version.

Kind regards
Frans Meerhoff

**Comment by JimWeinrich** [comment]
Sorry, I just downloaded the 0.12 nightly build for 2020 March 28 and it still has the problem ☹.
If you click where a graphic is supposed to be, a box highlights, but it's all white (blank).

[BayesianBeerGoggles.docx](https://github.com/jasp-stats/jasp-issues/files/4398108/BayesianBeerGoggles.docx)

**Comment by tomtomme** [comment]
@JimWeinrich 
Could you re-test with JASP 0.18.2?
And close this issue, if it is resolved by now?
Thanks!
