### ISSUE TITLE
Allow frequency tables for scale data

### ISSUE THREAD

**Issue by tilltoot** [jasp-stats/jasp-issues#647]
Many scale variables have a legitimate need for frequency tables.  For example "number of dogs in household" would be a scale (integer) variable.  It could be useful to know, for example, how many households have exactly four dogs.

Currently, to do this requires that I toggle variables back to ordinal for some reason.  It is hard to explain to my students why we need to do this.

Thanks for considering!!!

See also
https://github.com/jasp-stats/jasp-issues/issues/532

**Comment by FransMeerhoff** [comment]
Hi @vankesteren ,

Something to reconsider? See other issue in request.

Cheers Frans

**Comment by tomtomme** [comment]
I think its still valid. Its really hard for me to explain my students that metric variables are discrete or continuous - and then to explain to them, that JASP igores that and just tells the user to treat all metric variables as continuous.

**Comment by FransMeerhoff** [comment]
Hi @vandenman 
A recurring request. Can we make it a topic for 0.15 you think? Or do you have any other comment on this issue.
Cheers Frans

**Comment by vandenman** [comment]
So we could implement this but you'd get tables like these:

![image](https://user-images.githubusercontent.com/21319932/99643098-93c56380-2a4c-11eb-8e28-8a6cd036b7c8.png)

For most continuous data, you'd get a table with as many rows as there are observations and the frequency for each row is 1 because all observations are unique. If your data set contains many observations (~1000) the output would likely clog the entire results window in jasp. I'm not sure in what context a table like that is useful.

We could show the table when the number of unique observations of a variable is less than some prespecified value (e.g., 20). Nevertheless, the distinction between different types of variables (nominal, ordinal, continuous) is supposed to reflect the distinction between data types. If you want to do e.g., linear regression or ANOVA, the variables must have the correct types.

**Comment by EJWagenmakers** [comment]
What if we provide the table that corresponds to the histogram? So we indicate how many observations fall into a specific interval.

**Comment by vandenman** [comment]
@EJWagenmakers like a stem and leaf table? Granted, you still have to count the frequencies here though.

![image](https://user-images.githubusercontent.com/21319932/99646983-73e46e80-2a51-11eb-9e16-82600a1deb8f.png)

**Comment by tomtomme** [comment]
Stem and leaf plot is nice! How did you make it?
But what EJWagenmakers suggests is an automatic construction of categories / classes. The histogram does this already. It shows for example values from 0 to 5, then 5 to 10 etc. It would be even better for the user to define the number of bins themselves. That might be however another issue.
To limit construction of the table to a certain number of unique observations would be ok, too. But what number would that be. If I measure on a scale from 1 to 100 points (no decimals allowed) and if I then have thousands of measurements, then the table with all 100 unique values and their frequencies could be useful to me.

**Comment by vandenman** [comment]
> But what number would that be.

I'd say a checkbox with a default of 20 that people can modify f necessary. But I'm open to other suggestions!

**Comment by tomtomme** [comment]
Go for it! As long as the user can change it after the fact it is fine! :D
