### ISSUE TITLE
Xorg forwarding

### ISSUE THREAD

**Issue by FidgetteSpinneur** [jasp-stats/jasp-issues#652]
JASP from flathub, newest as of time of writing, Linux (Ubuntu 18 as well as CentOS 7)

Greetings! We're trying to run JASP on an Xorg display forwarded over an SSH connection.

```
# flatpak run org.jaspstats.JASP
qt.qpa.xcb: could not connect to display
```

Setting the `-platform <anything>` flag in the command just yields a segfault:

```
org.jaspstats.J[5535]: segfault at 7fd943b22a10 ip 00007fd9446ddcec sp 00007fff389188a8 error 7 in libQt5Gui.so.5.12.7[7fd944671000+3eb000]
```

Do you have any tips as to how to proceed?

Thanks!

**Comment by JorisGoosen** [comment]
Aah, that is interesting. Honestly I haven't tried running JASP over ssh till now, neither flatpak nor a local build.

I will have a look to see if that could work or not. It is not the ideal software to run over one of those connections though, everything is rendered in openGL through QML and ssh-forwarding usually works best with pure X11 applications. 

But turning on software rendering in JASP (which disables all animations) might do the trick. After it actually manages to start like so...

**Comment by JorisGoosen** [comment]
Hmm, so it seems this is related to flatpak... If I run a locally built JASP it operates fine through an SSH-X11-Forwarded display. But flatpak doesn't want to cooperate.

Apparently the Qt/kde-platform plugin for flatpak has some kind of setting or problem with xcb..

I'm afraid there isn't really a quick solution here. Well, except for building JASP yourself and running it from there. 

Maybe I'll have the chance to have a look at this later, I'll need to take an in-depth look again when we upgrade to a newer Qt. 

Aah, that might actually be part of the problem!

Which Qt do you have installed locally? 
Because maybe it has something to do with that. flatpak is stuck right now on Qt 5.12 because [there was trouble with support for webengine in the newer versions (>=5.13)](https://bugs.kde.org/show_bug.cgi?id=414175)

Maybe it has something to do with that? Flatpak on flathub is stuck with qt 5.12 and probably your local system has a different version of Qt. I know mine does.

I will however not be messing up my system to test this out now, sorry. It would be a lot of work right now for a rather niche concern (even though I rather like forwarding over SSH so it *would* be nice if it worked). But it would still be good info to know which version of Qt you run in your system, what is the output of `qmake --version` for you?

**Comment by FidgetteSpinneur** [comment]
`Which Qt do you have installed locally?`

None, just tried on a completely virgin Ubuntu 16.04 -- same symptoms, but the only QT files on the system are the ones that come with the flatpak.

`I'm afraid there isn't really a quick solution here. Well, except for building JASP yourself and running it from there.`

We'll look into that then. Thanks!

**Comment by JorisGoosen** [comment]
Aah actually I just found https://github.com/flatpak/flatpak/issues/397

And I can actually run the flatpak version of JASP over SSH if I do the following:
```
#First check what our actual DISPLAY value is
echo $DISPLAY
# I get localhost:10.0
flatpak run --command=sh org.jaspstats.JASP  -c "DISPLAY=localhost:10.0 /app/bin/org.jaspstats.JASP --safeGraphics"
```

Maybe you can try this?
And I still highly recommend switching it to safe graphics, the extra argument to the app turns it on permanently so you can leave it out after JASP started once.

**Comment by FidgetteSpinneur** [comment]
`Maybe you can try this?`

I think we're in business! It's not exactly fast in any way, but there are pictures and colours on the screen.

Thanks a lot!

**Comment by JorisGoosen** [comment]
Yeah that is too bad but it won't ever be fast this way I'm afraid. The way JASP is drawn is not really compatible with xorg forwarding.

I was thinking splitting up the option for safeGraphics from disabling animations. That might be useful in this scenario.

**Comment by JorisGoosen** [comment]
I'll also add this info to the Linux documentation, but at least you can now use it this way!

Can I ask a question though, just curious, why do you want to run JASP through an ssh tunnel?

**Comment by FidgetteSpinneur** [comment]
> Can I ask a question though, just curious, why do you want to run JASP through an ssh tunnel?

That's just the thing, I don't consider our use case particularly niche.

We provide interactive use of our HPC cluster through Thinlinc (https://www.cendio.com/thinlinc/what-is-thinlinc), but the resource-intensive processes are started via a batch system on the dedicated compute nodes, and, in case of interactive programs, the display is forwarded via SSH.

Thanks!

**Comment by JorisGoosen** [comment]
Aah yeah, supporting such a setup properly is a future plan of us. Right now JASP already consists of two applications, the front-end and the separate back-end that runs R and the computational stuff. 

It would be nice if the communication between them goes through https/ssh something. That way the gui could just run locally the R process(es) could be on the cluster. But because all the data is now stored in shared memory this isn't feasible yet.

Nice to hear you can work around it like that and Ill make sure to uncouple the animation from the software rendering, maybe that speeds it up a little bit.

**Comment by JorisGoosen** [comment]
So Ive added a preference in the application to disable animations without also switching to software rendering. Im curious to hear if that works a bit faster then the way you run it now.

Right now a beta is building in the flathub-beta repository. If you feel so inclined you can try it out, otherwise it will be a part of the next release anyway.
