### ISSUE TITLE
buttons used to put variables in the dependent variables, covariates, and WLS Weights box does not work when making a linear regression

### ISSUE THREAD

**Issue by juanespinoza427** [jasp-stats/jasp-issues#654]
* JASP version: 0.11.1.0
Windows
* OS name and version: Dell Inspiron 15 3000 Series
* Bug description: the 3 buttons for putting in variables in their respective box do not work
They will not let me put a variable I want into the dependent variable box. 
![picture of JASP](https://user-images.githubusercontent.com/62970733/78087033-8d2a9480-7374-11ea-9358-ce4cfd1f89af.PNG)
<!--- A note from the developers:
[Thesis Project____ (Responses).xlsx](https://github.com/jasp-stats/jasp-issues/files/4412090/Thesis.Project____.Responses.xlsx)   the file up in my account is a (.csv)

**Comment by AlexanderLyNL** [comment]
Hi Juanespinoza427,

Your variables are identified as text variables. For instance, the symbol next to the highlighted variable "Do you know what a Super PAC is?" tells me that it's a nominal, i.e., discrete, variable and the letter "a" in that symbol tells me it's been read as a text. 

A scale symbol is shown in the bottom right of "Dependent Variables", "Covariates" and "WLS Weights", which means that for these boxes a scale, i.e., continuous, variable is recommended and expected. 

If the responses to "Do you know what a Super PAC is?" are "yes" and "no", then it makes sense for the program to read this variable as a text variable. Strictly speaking linear regression cannot deal with discrete variables, and requires dummy coding. Instead of doing a linear regression, I'd then advice to do an ANOVA. If your dependent variables are both continous and discrete, then you'd might want to look into an ANCOVA. You can find these analyses under the ANOVA button in the ribbon at the top. 

Without the data at hand I'm not sure what's happening here exactly, but it might be that the responses are numbers, but a special entry is such as "???" is used for missing values. In that case, the whole variable/column is viewed as a text variable. One way to have jasp recognise entries such as "???" as a missing value, you can go to the main menu (Hamburger top left) - Preference - Data and add your missing data text into the Missing Value List. 

In that same menu you can find "Import threshold between Categorical or Scale" which is by default set to 10. This means that if there are fewer than 10 unique integers in, say, the variable "What is your age?" that variable is read as a nominal. For instance, if the responses to "What is your age?" are 

21, 22, 23, 24, 25, 26, 27, 28, 29, 30

then this variable will be viewed as a nominal variable. If it has more than 10 unique integers, say, 

21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31

then the variable is viewed as a continuous variable. If 10 is too many you can change this. If the unique responses are 

21, 22, 23, 24, 25, 26, 27, 28, twenty nine, 30

or 

21, 22, 23, 24, 25, ??, 27, 28, 29, 30

then the variable is viewed as a text nominal.  More information regarding variables and variables types can be found here:

https://jasp-stats.org/getting-started/

More information on how to view and edit your data can be found here:

https://jasp-stats.org/2018/05/15/data-editing-in-jasp/

I hope that this helps. 

Cheers,
Alexander
