### ISSUE TITLE
unclear warning message with Bayesian regression with interaction term

### ISSUE THREAD

**Issue by drbenvincent** [jasp-stats/jasp-issues#658]
* JASP version: 0.11.1
* OS name and version: MacOS 10.15.3
* Analysis: Bayesian linear regression with 2 main effects + interaction
* Bug description: Results are outputted, but below the main comparison table the following warning message is given
![Screenshot 2020-04-03 at 11 49 44](https://user-images.githubusercontent.com/6765047/78352992-3bb31d00-75a1-11ea-9a4d-2d75cd337525.png)

Note that there also 2 rows for the Null model, which is similar to #419. 

I'd be grateful for any advice on how important this warning is. Does this mean the results are invalid, or can the warning be ignored? I do want to include the interaction effects as I am attempting to do a moderation analysis. It is not clear from the warning what I should try to do about changing the model prior.

Having said that, the duplication of the Null model and the warning message disappear if I chose a uniform for the model prior. Maybe that is the fix? I'd be very appreciative of some confirmation that this is kosher.

![Screenshot 2020-04-03 at 11 58 03](https://user-images.githubusercontent.com/6765047/78353690-6651a580-75a2-11ea-8359-7765fea42992.png)

JASP file attached...
[problem.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4426701/problem.jasp.zip)

**Comment by vandenman** [comment]
So the reason we show this footnote is that the `BAS` R-package gave this as a warning message. In principle, there is nothing wrong with the results though. Since then the `BAS` R package got updated and removed the warning. Likewise, we have also removed this footnote. So in the upcoming release, you can just ignore this. I've refreshed your file with the latest development version and the results are unchanged.

![image](https://user-images.githubusercontent.com/21319932/78368392-dcb2cf80-75c3-11ea-8a39-3be4677ee738.png)

The duplicate Null model was also a bug in `BAS` but that's been fixed since then and should also be fixed in the upcoming release.

So for now, I'd just ignore the warning message.

**Comment by AlexanderLyNL** [comment]
I consider this issue fixed. Please reopen if something's still unclear.
