### ISSUE TITLE
"save as" for png format does not work as it should

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#66]
When I copy a figure, it is in standard png format and it works fine. 
When I select "save as" and then indicate the png format, the plot does not have the right background. I think this occurs because with "save as" the plot is highlighted, but I'm not sure. Attached are two figures: the good one obtained using the old method (simply "copy") and the poor one obtained using "save as".
![correlationmatrix](https://user-images.githubusercontent.com/8603015/27625322-893a278c-5be4-11e7-9415-75572aa6ffaa.png)
<img width="750" alt="correlationmatrix2" src="https://user-images.githubusercontent.com/8603015/27625324-8b9db26e-5be4-11e7-95c2-730d16abe85e.png">

**Comment by JorisGoosen** [comment]
Ok, with the new white/transparent feature almost all plots have a switchable background. Only the matrixplot (Correlation Plot in Descriptives) still has a small issue:
<img width="886" alt="Schermafbeelding 2019-07-03 om 10 46 37" src="https://user-images.githubusercontent.com/29062713/60577609-f0ed4600-9d7f-11e9-88f7-c720218af41c.png">

The subplots do not become transparent, while the overall background does.

However, that means that this issue is solved.
