### ISSUE TITLE
CFA model comparison option 

### ISSUE THREAD

**Issue by Marian-Popa** [jasp-stats/jasp-issues#673]
Model comparison in CFA is gone in JASP .12 
* Enhancement:
Reintroduce the model comparison option in CFA / Advanced options, because model comparison is a key strategy in SEM.

**Comment by vankesteren** [comment]
Hi @Marian-Popa 

I'm not sure what you mean, because model comparison was never an option in the CFA section (`Factor -> Confirmatory Factor Analysis`) and has to be done by making several CFA models and comparing their AIC, BIC, Chi-square, or other relevant fit metrics.

I do see now that in the SEM analysis (`SEM -> Structural Equation Modeling`) this is no longer available, whereas it was available in a previous version of JASP (in a pretty buggy form). This now also needs to be done by creating multiple analyses and comparing their fit metrics. We are working on creating an updated version of SEM with excellent model comparison functionality for a future release (not too distant in the future!).
