### ISSUE TITLE
SEM: problem with Parameter Estimates

### ISSUE THREAD

**Issue by jainahi** [jasp-stats/jasp-issues#704]
* JASP version: 0.12.1.0

* OS name and version: Windows 7 32 bits
* Analysis: Structural Equation Modeling
* Bug description: When I add residual correlations to my model's lavaan sintax (~~) so much values from the table "Parameter estimates" disappear. Maybe it is due to my inexperience with SEM.
* Expected behaviour: I would expect that these values do not disappear :)

#### Steps to reproduce:
1. Go to SEM.
2. Click on Structural Equation Modeling (not Mediation Analysis)
3. Write in the lavaan syntax box something like this:

# latent variables
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
     dem65 =~ y5 + y6 + y7 + y8
   # regressions
     dem60 ~ ind60
     dem65 ~ ind60 + dem60
   
![1](https://user-images.githubusercontent.com/64253412/80195285-e5735000-861b-11ea-89e5-fe3e43066509.jpg)

4. There is not problem here, but if I specify residual covariances i.e. I add:

# residual covariances
     y1 ~~ y5
     y2 ~~ y4 + y6
     y3 ~~ y7
     y4 ~~ y8
     y6 ~~ y8 

 
5. ... I See that values from the table Parameter Estimates disappear.

![2](https://user-images.githubusercontent.com/64253412/80195297-e7d5aa00-861b-11ea-876d-9e263134ba96.jpg)

**Comment by vankesteren** [comment]
Hi Jaime, 

thanks for submitting the issue here! In this way, others can (hopefully) benefit from the answer too :)

This problem occurs when the standard errors cannot be computed. I don't know exactly what went wrong based on your information, but this could be due to many different reasons -- model misspecifications, extreme nonnormality of the residuals,  and more. __The SEM module will receive an upgrade soon to better show that something went wrong.__

However, I can give a few pointers based on your screenshot. Specifically, I see that you are specifying many residual covariances, even within a single latent variable. You should critically assess whether all these residual covariances make sense: what would be the (substantive) reason for adding `AII_DECENTERING ~~ AII_NonAtt + AII_NonJdg` to a model which already includes `AII =~ AII_DECENTERING + AII_NonAtt + AII_NonJdg`? Is there some reason you would expect additional covariance between these items over and above that explained by the latent variable? Simply adding residuals because they make the model fit better is generally bad practice, because you are likely overfit to your sample (sometimes called "capitalizing on chance" in the context of SEM).

I hope this helps!

Erik-Jan
