### ISSUE TITLE
p value shown as 0.00 instead of <.001

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#706]
* JASP version: 0.12.2
* OS name and version: macOS Catalina 10.15.4
* Analysis: Classical ANOVA
* Bug description: In the Assumption Checks, the _p_ value is shown as 0.00.
![ANOVA_teachers](https://user-images.githubusercontent.com/5346286/80250006-34000900-8673-11ea-9e66-004054cd0217.jpg)
* Expected behaviour: The _p_ value is expected to be shown as <.001 just like in the ANOVA table and the Post Hoc Tests.

#### Steps to reproduce:
1. Click on ANOVA > Classical ANOVA.
2. Under 'Assumption Checks', check 'Homogeneity tests'.

[ANOVA_teachers.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4531121/ANOVA_teachers.jasp.zip)

**Comment by JohnnyDoorn** [comment]
Hmm that is very weird, as I cannot reproduce the issue on my 0.12.2 (flathub/Ubuntu):
![Screenshot from 2020-04-28 10-48-30](https://user-images.githubusercontent.com/15704203/80467232-d3582100-893d-11ea-94ca-3d063c910167.png)

@boutinb  can you reproduce this?

**Comment by boutinb** [comment]
It is due to the 'Fix the number of decimals' setting (in Preferences/Results): if it is set to 2 then you get 0.00, if it is set to 3, you have 0.004

**Comment by JohnnyDoorn** [comment]
Ah of course! it is still weird, because the code looks normal:
`  leveneTable$addColumnInfo(name="p",   title=gettext("p"),   type="pvalue")`

**Comment by boutinb** [comment]
I see that the formats in the result are the same for all p values. Maybe something wrong in javascript. I have a look.

**Comment by boutinb** [comment]
This bug existed in 0.11 already.
When number of decimals is set to 2, and p-value is 0.01 > p > 0.001, then p-value is set to 0.00, instead of '< 0.01'
When p-value is p < 0.001, then it shows '< 0.001' (even if number of decimals is 2). I think it should show also '< 0.01'.
I saw also that when number of decimals is 4 and p is 0.0003, then is shows also '< 0.001'.
I remember that there was a discussion (long ago), about how many decimals we should show the p-value, and I remember vaguely that we chose not to display exact value of p-value < 0.001. @EJWagenmakers do you remember this discussion?

**Comment by EJWagenmakers** [comment]
1. "When number of decimals is set to 2, and p-value is 0.01 > p > 0.001, then p-value is set to 0.00, instead of '< 0.01'"

I think it makes sense to show '< .01' in this case (NB I think we don't show the leading zero when we use the inequality signs). 

2. When p-value is p < 0.001, then it shows '< 0.001' (even if number of decimals is 2). I think it should show also '< 0.01'.

I recommend  '< .001' (note I leave out the leading zero) even if number of decimals is 2.

3. "I saw also that when number of decimals is 4 and p is 0.0003, then is shows also '< 0.001'."

That seems strange, it should just show the precise p-value here.

**Comment by boutinb** [comment]
I will make these changes.
For the time being, for @djdekker, the best workaround is to set the number of decimals to 3.
