### ISSUE TITLE
missing counts

### ISSUE THREAD

**Issue by NikitaKhromov-Borisov** [jasp-stats/jasp-issues#729]
* JASP version: 0.12.2

* OS name and version: Windows 10
* Analysis: Frequencies
* Bug description: for the attached data I receive the report on the missing counts
There is no such report with other CTs
[Operat.zip](https://github.com/jasp-stats/jasp-issues/files/4570940/Operat.zip)

**Comment by vandenman** [comment]
It looks like JASP detects some spurious rows in the data set. If you create a filter and use `!is.na(Count)` as R code JASP filters out the empty rows in the data set and the analysis is run normally.

**Comment by NikitaKhromov-Borisov** [comment]
thanks, however, I don't know how to use a filter. Moreover, it seems the problem is not due to data, because the same data are analyzed at the next day, but the same confusion appears with another data set, with which there was no problem earlier.

**Comment by vandenman** [comment]
There seems to be something odd in the CSV file, because `readr::read_csv` also reads in 19 rows while `utils::read.csv` (a base R function) reads in only 8 rows. Regardless, that's something on our end to look at. 

In the meantime, to use the filter you can follow the steps below. That should at least allow you to run the analysis until we sort out why the empty rows are read in.

1. In the data view click on the circled icon:
![image](https://user-images.githubusercontent.com/21319932/81005587-7fbe6980-8e4e-11ea-932d-dab38bd6fc51.png)

2. The filter window opens up, click on R (circled in red):
![image](https://user-images.githubusercontent.com/21319932/81005679-9ebcfb80-8e4e-11ea-8d94-c58ebd31833e.png)

3. Add the R code and click on `Apply pass-through filter`.
![image](https://user-images.githubusercontent.com/21319932/81005804-cca24000-8e4e-11ea-8c30-f989aa294807.png)

4. The filter out rows should now be greyed out from the data view:
![image](https://user-images.githubusercontent.com/21319932/81005955-096e3700-8e4f-11ea-9e1d-2dc289ea0a81.png)

**Comment by NikitaKhromov-Borisov** [comment]
Thank you, that's great!

**Comment by NikitaKhromov-Borisov** [comment]
Thanks
Best regards,

Dr. Nikita Khromov-Borisov
Commission on Pseudoscience
Russian Academy of Sciences (RAS)
RUSSIA

http://independent.academia.edu/NikitaKhromovBorisov
https://www.researchgate.net/profile/Nikita_Khromov-Borisov

пн, 4 мая 2020 г. в 22:38, Don van den Bergh <notifications@github.com>:
