### ISSUE TITLE
fails to run 2x2 Bayesian Repeated Measures ANOVA

### ISSUE THREAD

**Issue by drbenvincent** [jasp-stats/jasp-issues#774]
* JASP version: 0.12.2
* OS name and version: MacOS 10.15.4
* Analysis: 2x2 repeated measures ANOVA, Bayesian
* Bug description: Analysis is not run, with the following error

![Screenshot 2020-05-28 at 15 36 51](https://user-images.githubusercontent.com/6765047/83155381-14885000-a0f9-11ea-8a7b-0afe8e14e981.png)

I've attached JASP file (zipped)

[example.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4696214/example.jasp.zip)

**Comment by vandenman** [comment]
Thanks for the bug report!

This looks like the same error as https://github.com/jasp-stats/jasp-issues/issues/737. If you have a variable named `subject` in your data set, a temporary workaround is to rename that variable to something else, e.g., `subject2`.

**Comment by drbenvincent** [comment]
So that kind of works :) Although the column name was `subj` initially, so I think the issue is broader than just a column called `subject`. Changed it to simply `s`. The ANOVA worked :) 

Although asking it to plot the QQ plot gives rise to a similar issue. And this is now of course with no columns `sub` or `subject`.
<img width="358" alt="Screenshot 2020-05-29 at 08 25 09" src="https://user-images.githubusercontent.com/6765047/83233223-501d2b80-a186-11ea-9bfb-a94b7e375000.png">

(Incidentally, there's a lot of JASP crashing by the way)

Thanks so much for the solution so far!

**Comment by vandenman** [comment]
> Although the column name was subj initially

Unfortunately, we internally used the name subject and when decoding and encoding<sup>1</sup> variable names a name like `subj` would be partially matched in `subject` (for more details, see https://github.com/jasp-stats/jasp-desktop/pull/4086).

If you experience any other bugs/ crashes, please make an issue and we'll assign the appropriate person to fix it so that the next release won't have these issues!



<sup>1</sup>We encode variable names to support foreign characters that R may not handle well, e.g., Greek, Hebrew, or even just á.
