### ISSUE TITLE
Simple Interaction Effects

### ISSUE THREAD

**Issue by FelipeMAffonso** [jasp-stats/jasp-issues#781]
* Enhancement: JASP can handle ANOVA and simple simple effects very well. However, after a significant three-way interaction (A*B*C), it is important to, say, run A*B at different levels of C. There's no way to do that.
* Purpose: Simple interaction effects.
* Use-case: Many experiments in the social sciences with three-way interactions start with the three-way interaction, followed by the significant simple interactions, and then the simple simple effects. 

**Describe the solution you'd like**
Some point and click option to calculate simple interaction effects easily. Ideally, I would be able to tell the software that I want to test A*B within every level of C.

**Comment by FelipeMAffonso** [comment]
Quick comment: ideally, this would also be done in mixed designs, within designs, and the like

**Comment by JohnnyDoorn** [comment]
Hi @FelipeMAffonso 

Great suggestion - I was toying with this when I implemented the simple main effects: to just have full conditional ANOVA tables for each level of a factor. However, I'm not entirely sure how to tackle this from a multiplicity correction perspective though - do you have any literature you recommend on this?
I think to have only the interaction effect displayed for each level of a factor is not advisable, since the interpretation of a model with just an interaction effect (without looking at the main effects) is often not straightforward and can be misleading. 

Kind regards
Johnny

**Comment by FelipeMAffonso** [comment]
Hi @JohnnyDoorn 

Here is a blog post (with very very good references too!) that talk about multiplicity in multiway ANOVAs: http://daniellakens.blogspot.com/2016/01/error-control-in-exploratory-anovas-how.html

Well.. Here is also the link of one of the references about multiplicity in multiway ANOVAs (the blog talk about this as well): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4828473/

I think that having a way to calculate this (even if the researcher needs to set different alphas, etc.) would be nice.

Thanks!

Felipe

**Comment by tomtomme** [comment]
@FelipeMAffonso 
Can you check if this is covered by our new PROCESS module available in version 0.18.2?
