### ISSUE TITLE
randomized complete block design

### ISSUE THREAD

**Issue by narcilili** [jasp-stats/jasp-issues#793]
* Enhancement: randomized complete block design feature in the anova section. including Bayesian anova
* Purpose: many agriculturists will find it useful. it may inadvertently lead them to Bayesian analysis
* Use-case: in the field of agriculture especially

**Comment by boutinb** [comment]
@JohnnyDoorn Could you have a look to this request?

**Comment by tomtomme** [comment]
@narcilili 
This is still missing, in BANOVA, right?
Could you give some more details like a paper or R-Package this could be based on?

**Comment by tomtomme** [comment]
@narcilili 
Since a block seems to refer to a special type of repeated measures, it should be possible to use JASPs RM ANOVA module for this design.
This is related to the "split-plot" design discussed here: #1682

Would be cool, if you could shed more light on the terms complete block and split plot. Since they stem from agricultural research, we are not very familiar with those and we may be mistaken here.

**Comment by Lia-UC** [comment]
I tried randomized complete block design using JASP (df= (t-1)*(r-1))but it could not since for this design the observation would be 1 cell.
and it was said "duplicate participant column added to model terms" or with the ANOVA it was said "df=0"
In SPSS usually used build term to make the model and added the treatment and replication as main effective not full factorial.

**Comment by JohnnyDoorn** [comment]
Hi @Lia-UC ,

Just a guess, but have you tried going to the "Model" tab and removing the interaction effect there? That way you only have two main effects in the model, which perhaps does not give an error. 

Cheers
Johnny

**Comment by Lia-UC** [comment]
Thank you for your replies. It works after I remove the interaction effect in the model. Thank you so much..
