### ISSUE TITLE
Pearson's r Heatmap is displayed incorrectly

### ISSUE THREAD

**Issue by Glitchy-Tozier** [jasp-stats/jasp-issues#798]
* JASP version: 0.12.2

* OS name and version: Linux Mint 19.3
* Analysis: Correllation
* Bug description: Pearson's r Heatmap is displayed incorrectly... I think.
* Expected behaviour: Better visibility. See attached picture 

#### Steps to reproduce:
1. Opened the data-csv 
[Datensatz_9_AB_bsp05.xlsx](https://github.com/jasp-stats/jasp-issues/files/4742536/Datensatz_9_AB_bsp05.xlsx)
2. Started Regression -> Correlation
3. Selected Pearson's r Heatmap.
4. See error (see picture 
![Screenshot from 2020-06-07 18-58-08](https://user-images.githubusercontent.com/59611881/83975048-0b5d6700-a8e1-11ea-93d2-275db9077c7c.png)

**Comment by Glitchy-Tozier** [comment]
I had 110% zoom... turning it off didn't change anything though.

**Comment by boutinb** [comment]
@vandenman Can you have a look?

**Comment by vandenman** [comment]
We can adjust the default size of the figure to handle larger variable names a bit better. In the meantime, you hover with the mouse over the figure, you should see a little icon in the bottom right corner. If you click on that icon and move the mouse around you can resize the figure.

![image](https://user-images.githubusercontent.com/21319932/84026820-48cbfe00-a98e-11ea-900a-7c8f6b26825f.png)

**Comment by Glitchy-Tozier** [comment]
There hasn't been any updates, so it's probably still relevant.

**Comment by tomtomme** [comment]
@Glitchy-Tozier
I do not see this as an issue, since you can change font family in jasps settings nowadays if you need heatmaps for just a few vars with long var names. And even then you can resize. 
Also, in general you do not need a heatmaps for such a small number of correlations, correct?
The heatmap is needed if you have many correlations and already for >3 variables the default font size works okay if the var names are as long as in your example: 

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/9c2271ae-a687-44e7-bd14-2d5021cb06b9)

and here with another font 

![image](https://github.com/jasp-stats/jasp-issues/assets/4428185/e742e058-cbcb-44b3-b95f-c2dc2e623689)

Do you agree? Then we could close this.

**Comment by Glitchy-Tozier** [comment]
Seems reasonable, let's close this issue!
