### ISSUE TITLE
Error trying to create a Flexplot Iin Visual Modeling

### ISSUE THREAD

**Issue by pafro1767** [jasp-stats/jasp-issues#804]
* JASP version: JASP 0.12.2
* OS name and version: Windows 10, Version 10.0.18363 compilation 18363. 64-bit.
* Analysis: Visual Modeling -> Flexplot
* Bug description:
This analysis terminated unexpectedly. 
Error in parse(text = x, keep.source = FALSE): :1:16: unexpected symbol
1: PUNT_TOTAL~V2. sexo
                   ^
Stack trace
withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)
analysis(jaspResults = jaspResults, dataset = dataset, options = options)
flexplot:::flexplot_jasp2(jaspResults, dataset, options)
.flexPlotRes(jaspResults, formula, dataset, options, ready)
as.formula(paste0(options$dependent, '~', paste0(variables, collapse = '+')))
formula(object, env = baseenv())
formula.character(object, env = baseenv())
formula(eval(parse(text = x, keep.source = FALSE)[[1]]))
eval(parse(text = x, keep.source = FALSE)[[1]])
parse(text = x, keep.source = FALSE)
* Expected behaviour:
According to your blog entry, the plot should have been produced, but I can't get one, not even changing the variables (I've already runned several bivariate analysis and I'm building a multivariate model, dataset contains information of knowledge of students based on different variables (I can email you the data, but they cannot be made public as they are part of a thesis). The dependent variable is ordinal and all the independent are nominal. I've also tried to compute the dependent variable into a easier, with less levels nominal variable and the error continues.

#### Steps to reproduce:
1. Go to 'Visual Modeling (Beta)'
2. Click on 'Flexplot
3. See error
![Captura de pantalla (167)](https://user-images.githubusercontent.com/66952788/84657965-67de0900-af15-11ea-952c-eda2f0ef2c6d.png)
'

**Comment by boutinb** [comment]
Hi @dustinfife, can you have a look to this problem?

**Comment by dustinfife** [comment]
It seems you are trying to visualize a categorical outcome variable. There's *some* support for that in flexplot in R (e.g., for logistic regression), but not in JASP as of right now. 

@boutinb: is there a way to do a conditional restriction in a box? I want users to be able to specify categorical variables IF there's no other variables in the Independent Variable(s) or Paneled Variable(s) box. Otherwise, no categorical variables allow. 

Any ideas?

**Comment by boutinb** [comment]
I have just tried to reproduce this problem with an ordinal in Dependent variable and some nominals in Independent variables, and I don't get any error. Maybe to be sure could you send the data to dustin and me directly?
For your question, @dustinfife, you can only specify the allowed kinds of columns statically now. I will make an issue to make it dynamically so that you can do something like that:
`allowedColumns: if (independentVariables.count == 0 && paneledVariables.count == 0) then <all columns> else <all columns but categorical>`
Is that what you want?

**Comment by pafro1767** [comment]
Sure! Shall I send them to the @uva.nl email shown at your profile page?
Thanks a lot for helping me!

**Comment by boutinb** [comment]
Yes!

**Comment by tomtomme** [comment]
@pafro1767 
I guess this is resolved by now? Can you confirm?
