### ISSUE TITLE
Support new statistical tests implemented in the bayes4psy package

### ISSUE THREAD

**Issue by TarandeepKang** [jasp-stats/jasp-issues#806]
* Enhancement: support the new statistical tests in this package
* Purpose: from the paper, it looks as if the tests available, as well as future planned additions, would be broadly useful in the social and behavioural sciences
* Use-case: common types of data analysis in psychology

**Is your feature request related to a problem? Please describe.**
 

There are some of the tests in this package already implemented, several are not, at least as far as I'm aware. Given that this package aim is to solve common analytical problems in psychology, the included procedures are likely to be of broad interest and use. Authors are also planning, according to the paper to add additional tests to enable analysis of neuroscientific data. 

**Describe the solution you'd like**
 

**Describe alternatives you've considered**
  only alternative is when your programming using her, which is not suitable for those unable to program

**Additional context**

The paper is published in Frontiers in Psychology, https://doi.org/10.3389/fpsyg.2020.00947

**Comment by TarandeepKang** [comment]
Apologies the typos, my dictation software is playing up today! In the "Describe Alternatives" section it is meant to read: "the only alternative is manual programming using R, which is not suitable for those who cannot program yet."

**Comment by EJWagenmakers** [comment]
Hi TarandeepKang,

Thanks for the heads-up. I did see this paper, and wondered why the authors didn't approach us to make a JASP module out of it. Anyway, the authors use the ROPE procedure, and in the future we'll revamp the Bayesian analyses so that this information can be extracted easily. Since this is on our agenda I am closing this issue. Again, thanks for pointing this out!

Cheers,
E.J.
