### ISSUE TITLE
Custom contrast for ANOVA: cannot specify just 1 contrast

### ISSUE THREAD

**Issue by mservantufc** [jasp-stats/jasp-issues#814]
JASP version: 0.12.2

* OS name and version: Windows 10
* Analysis: Custom contrast
* Bug description: when specifying only 1 contrast, the following warning appears in the contrast table: "Please specify an additional contrast".
* Expected behaviour: JASP should be able to compute only one contrast, there is no reason for needing to specify an additional contrast.

JASP file:

[therapie.zip](https://github.com/jasp-stats/jasp-issues/files/4825204/therapie.zip)

**Comment by tomtomme** [comment]
I needed to start fresh with the anova, probably the file is so old, but then just defining one contrast just worked fine. Even though I early on got an error because your categorial data contains spaces. But that vanished after starting with a fresh anova.

@mservantufc
If this is not solved on your side, feel free to reopen.
