### ISSUE TITLE
i got "unable to start png() device" message in path diagram when i try to run SEM...

### ISSUE THREAD

**Issue by BLueBLack053** [jasp-stats/jasp-issues#835]
i got "unable to start png() device" message in path diagram when i try to run SEM...

Please can you answer to me? or i need to write new issue?

**Comment by JorisGoosen** [comment]
So that means the engine now works then?

**Comment by BLueBLack053** [comment]
yeah, engine work well now.
But after then, i got "unable to start png() device" message in path diagram when i try to run SEM
Sorry too much question T^T

**Comment by JorisGoosen** [comment]
Are you now using the version of JASP I send you?
Because maybe you could use this one: http://static.jasp-stats.org/JASP-0.13.0.0-64bit.msi
It is the unsigned version of 0.13 that we are releasing tomorrow.

**Comment by JorisGoosen** [comment]
Perhaps you could add the logs of this problem?

**Comment by BLueBLack053** [comment]
Actually, i used the version of 0.13 when engine works well
But i got "unable to start png() device" message, and i delete 0.13 and reinstall 0.12
And same message is shown

here is the logs after "unable to start png() device" message

[JASP 2020-07-02 02_28_53 Engine 1.log](https://github.com/jasp-stats/jasp-issues/files/4859409/JASP.2020-07-02.02_28_53.Engine.1.log)
[JASP 2020-07-02 02_28_53 Engine 2.log](https://github.com/jasp-stats/jasp-issues/files/4859410/JASP.2020-07-02.02_28_53.Engine.2.log)
[JASP 2020-07-02 02_28_53 Engine 3.log](https://github.com/jasp-stats/jasp-issues/files/4859411/JASP.2020-07-02.02_28_53.Engine.3.log)
[JASP 2020-07-02 02_28_53 Desktop.log](https://github.com/jasp-stats/jasp-issues/files/4859412/JASP.2020-07-02.02_28_53.Desktop.log)
[JASP 2020-07-02 02_28_53 Engine 0.log](https://github.com/jasp-stats/jasp-issues/files/4859413/JASP.2020-07-02.02_28_53.Engine.0.log)

**Comment by JorisGoosen** [comment]
Aah yes I see.

Im sorry but apparently something goes wrong because of your username, which Im guessing is in hangul. Because I see the following error in the log:
`C:/Users/???/AppData/Local/JASP/temp/20548/tmp0/\file48f819d060bf`

We really tried to get everything working properly with all sorts of charactersystems. But somehow this is still going wrong...
I will need to have a look at this.

In the meantime there is a workaround for you. It is a little bit annoying but it should work. If you make a new user on your computer with a name that is just latin characters then the plot will work as well.

Sorry about the inconvenience.

**Comment by BLueBLack053** [comment]
Oh, yeah

after i make new user with just latin characters, i can solve problems

Sincerely thank your kind help

**Comment by JorisGoosen** [comment]
Idem here, in the next version you should be able to use your normal account.
