### ISSUE TITLE
Dataset from SPSS breaks all analyses

### ISSUE THREAD

**Issue by Liesbeth-Tip** [jasp-stats/jasp-issues#838]
Hi, I get the following when trying to get my descriptives:
This analysis terminated unexpectedly.
Error in analysis(dataset = dataset, options = options, perform = perform, : unused arguments (perform = perform, callback = the.callback, state = oldState)

It happens only with one dataset, another dataset works fine.
I have missing values (88 and 99) in this dataset but have changed my preferences to include them.
This used to be a password-protected file in SPSS but I saved it without the password so that is not it (I noticed that files that are password-protected don't open)

I use:
* JASP version:0.12.2.0
Windows 10

**Comment by JorisGoosen** [comment]
I saw you had trouble running 0.13 so I guess you cannot use that until we fix that problem.

There were some changes to the backend of JASP for reading files from SPSS that might have fixed this problem. Because in the previous version there was an issue with certain types of missing values.

But that would not have caused all analyses to break I think.

Is it possible for you to send me the datafile so that I can see if I can reproduce it? 
And if the bug is still present I could also fix it. 

If there is sensitive info in it you might consider changing some fields or something. ANd then see if it still breaks JASP.

If you want to mail it to me you can at "j.c.goosen at uva.nl".

**Comment by JorisGoosen** [comment]
Ive heard nothing.

**Comment by Liesbeth-Tip** [comment]
Hi Joris,
My apologies! I had not checked the messages recently. I somehow managed to solve the problem by updating missing values with a lot of extra values. Sorry for not responding!
Best wishes,
Liesbeth

________________________________
Van: Joris Goosen <notifications@github.com>
Verzonden: dinsdag 28 juli 2020 11:37
Aan: jasp-stats/jasp-issues <jasp-issues@noreply.github.com>
CC: Liesbeth-Tip <liesbethtip@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [jasp-stats/jasp-issues] Dataset from SPSS breaks all analyses (#838)


Ive heard nothing.

**Comment by JorisGoosen** [comment]
No problem, glad to hear it works!
