### ISSUE TITLE
mixed ANOVA results ≠ repeated ANOVA results

### ISSUE THREAD

**Issue by kornbrot** [jasp-stats/jasp-issues#842]
* JASP version: 0.13
* OS name and version: mac OS cartalina  10.15.5
* Analysis: design Between (2)xWithin(2)xwithin 3 
*** Results from  comparing repeated and mixed methods  do not agree**
Why not? Is there a good theoretical reason?
Spreasdsheeet has long and wide version of data and results form mixed and repeated
Results form analyses in SPSS also shown
SPSS repeated, wiithin subjects is identical with JASP repeated
SPSS repeated multivariate is identical with SPSS mixed Satherwaite -but multivatiate is not recommended for good reason
JASP mixed NOT equal to JASP repeated BUT Fmixed*580/696, Fadjusted in spreadsheet,  is close to but not identical with JASP re
[KornbrotJASPeg.xlsx](https://github.com/jasp-stats/jasp-issues/files/4875185/KornbrotJASPeg.xlsx)
peated

* Expected behaviour:

**Comment by kornbrot** [comment]
To obtain REPEATED import wide form Spreadsheet
Construct repeateed
To obtain MIXED import long form Spreadsheet
MIXED analysis with pno as groupng factor

It would be so WONDERFUL if it worked!

**Comment by FBartos** [comment]
Hi @kornbrot , 

I looked into the dataset and verified that results we provide in Mixed Models module correspond to the results you would get from R:

```
df    <- read.csv2("D:/Downloads/KornbrotJASPeg_long.csv")
df$w1 <- as.factor(df$w1)
df$w2 <- as.factor(df$w2)
df$b1 <- as.factor(df$b1)

fit_lmer <- lmerTest::lmer(freq ~ w1 * w2 * b1 + (1 | pno), data = df)
anova(fit_lmer)

fit_afex <- afex::mixed(freq ~ w1 * w2 * b1 + (1 | pno), data = df)
fit_afex
```

Could you please send me the JASP analysis file for the repeated measures ANOVA analysis? I tried to specify the same model but I did not manage to do so. Could it be because there are 3 levels of w1 instead of 2?

![image](https://user-images.githubusercontent.com/38475991/86731096-7d83b180-c02f-11ea-97c8-13fb5f9c6ae0.png)

Also, I looked into the reasons why the results might differ. I am not an SPSS user, but I found that there might be a difference in whether you specify the models using 'RANDOM' vs 'REPEATED' syntax.
