### ISSUE TITLE
Analysis of Effects: Across Matched Models

### ISSUE THREAD

**Issue by EJWagenmakers** [jasp-stats/jasp-issues#852]
Maybe not a bug, but I agree with this user (https://forum.cogsci.nl/index.php?p=/discussion/6290/how-to-compute-the-bayes-factor-inclusion-in-jasp#latest) that it is strange and potentially confusing that the table of effects shows prior and posterior inclusion probabilities that do not compute to the inclusion BF. It seems more straightforward to report the prior and posterior inclusion probabilities that form the basis of the inclusion BF. @vandenman @AlexanderLyNL

**Comment by vandenman** [comment]
I'll look at this more in detail in August but your reply looks correct to me.

One way to make this less confusing is to also report posterior exclusion probabilities for matched models. That way, the inclusion Bayes factor can always be computed with just the quantities in the table. For Bayesian linear regression, we could also report prior exclusion probabilities since there we don't have the guarantee that prior_incl / prior_excl = 1 because the model prior is not necessarily uniform.
