### ISSUE TITLE
Jasp 0.13.0 uses ms-gamingoverlay links (thus the XBox game bar to be installed)

### ISSUE THREAD

**Issue by donovaly** [jasp-stats/jasp-issues#862]
JASP 0.13.0, Windows 10, 2004

To reproduce: 
1. call JASP as normal user (no admin privileges)

result: you always get this Windows dialog:
![rdJphNSOrp](https://user-images.githubusercontent.com/1828501/86778210-6312fd80-c05a-11ea-9bdb-5fc7a91f805f.png)
(translation of the dialog: "You need a new app to open this ms-gamingoverlay-link".
When I now click OK, Windows Store offers me to install the XBox Game bar. (Our admin uninstalled the XBox game bar because gaming is not allowed at work.) But why does JASP needs a game bar?

I have no clue what this means and why I need it. I was never asked this using JASP 0.12.x on my private PC at home, but there I kept the XBox game bar since it is by default installed by Windows 10.

**Comment by EJWagenmakers** [comment]
Yeah this makes no sense. Statistical analysis is not gaming. 
@JorisGoosen ?

**Comment by JorisGoosen** [comment]
Ah wow, what a weird error. It seems that because we use OpenGL to render JASP Microsoft has decided we need the xbox game bar. And steal links somehow?

I didn't even know you could *not* install that bar. I will have a look and see if I can do something about this.

Very aggressive policy at work btw @donovaly because this game bar by itself really doesn't allow for any gaming...

**Comment by JorisGoosen** [comment]
Aah if I can believe the following website you can get rid of this warning by doing the following:
https://www.minitool.com/news/ms-gaming-overlay-popup.html

And if that helps I would suggest asking your admin to disable this by default. Because if the gamebar is removed then this option should be off...

**Comment by JorisGoosen** [comment]
And I mean specifically the part called "Option 1: Disable Game Bar"

**Comment by donovaly** [comment]
> Aah if I can believe the following website you can get rid of this warning by doing the following:
> https://www.minitool.com/news/ms-gaming-overlay-popup.html

Many thanks. This helps.

> And if that helps I would suggest asking your admin

They are already annoyed why I make so much trouble - I should not waste my time in 0.x programs (like the version number says anything about the bug level). Also therefore I opened issue #861.

However, thanks for the workaround. The question is now how to communicate the solution.

**Comment by JorisGoosen** [comment]
> However, thanks for the workaround. The question is now how to communicate the solution.

Well, they kind of broke the system by roughly removing the gaming bar without disabling such settings... But good luck communicating to annoyed system admins!

**Comment by shun2wang** [comment]
Now we have made a (beta) version that might fix this issue: could you try this version https://static.jasp-stats.org/Nightlies/Windows/JASP-nightly-fixMsGamingOverlay-1823b6a99d09cc70fd68d9103c9d6f4c8693bf27.msi ? (this version is not signed, so you will get a Windows warning about this).

With thanks.
