### ISSUE TITLE
difficulty to change from nominal to ordinal variable

### ISSUE THREAD

**Issue by elenapapanik** [jasp-stats/jasp-issues#866]
* JASP version: jasp 0.13.0.0-64bit

* OS name and version: windows 10 pro, 2004
* Analysis:  I imported my raw data in JASP but impossible to change the column type. 
* Bug description: I follow the guidelines to change the column type, I click as appropriate, but no change takes place.
[pms-covid19.zip](https://github.com/jasp-stats/jasp-issues/files/4890769/pms-covid19.zip)

**Comment by AlexanderLyNL** [comment]
The reason why this is not working, is because almost every one of your columns are read in as text. Whenever a column contains an entry that cannot be converted into a number, this column will be interpreted as a text column. 

For instance, in V2 there's an entry such as `8-12`, which is read as a text, because it is unclear for R on how to convert that into a number. Furthermore, in V3 there are in addition to the entry `2-5` entries such as ` <= 1 \omega \rho \alpha` which cannot be interpreted as a number either. For V17 there are entries such as `45+` which are also read in as text. 

Whenever a column is a text column, it cannot be converted into a number. The `8-12` seems reasonable as a number, but unfortunately the computer is not smart enough to convert this into text. If you really want to make this into a number, then you can change that entry into 8, or 9, or 10, or 11, or 12. However, that's not actually correct. The data you recorded are categories, so it makes sense to analyse them as such. Perhaps you'd might be interested to use the analyses designed for categorical variables. 

I hope that this explains what happens here. Please reopen the issue if it's still unclear. 

Cheers,
Alexander

**Comment by elenapapanik** [comment]
Thanks a lot
