### ISSUE TITLE
Move explanatory footnote text to "Show info for this analysis"

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#877]
* Enhancement: Move explanatory footnote text to "Show info for this analysis"
* Purpose: Keep output as clean as possible; distinguish results from their interpretation
* Use-case: All explanatory footnotes 

**Is your feature request related to a problem? Please describe.**
In the Paired Samples T-Test, an explanatory footnote is printed below the Assumption Checks:

<img width="351" alt="explanatory note" src="https://user-images.githubusercontent.com/5346286/87220145-c99d6180-c361-11ea-91ff-9f6fd6b30b5f.png">

Two thoughts about this gentle reminder to the user:

1. This note concerns the interpretation of the p value of the Shapiro-Wilk test **in general** (not in this particular analysis, because there is no significant result here). I think the output of an analysis should only contain footnotes that are applicable to the present analysis. Notes about the interpretation of statistical tests **in general** should not be found in the output pane, but in a help file (or the user can look them up in any statistics book).
2. I think that notes in the output section should only concern the output itself (or the way it was calculated), not the interpretation of the output.

**Describe the solution you'd like**
I'd suggest to move this footnote to the "Show info for this analysis" section.

<img width="621" alt="help section" src="https://user-images.githubusercontent.com/5346286/87220321-0ddd3180-c363-11ea-80e3-9ed40fb7ea65.png">

**Comment by AlexanderLyNL** [comment]
I agree, with this. Though, I leave it open as a first issue for someone starting with programming. It's not that big of a nuisance I reckon.

**Comment by tomtomme** [comment]
I disagree - kind of.
Maybe make a checkbox in JASPs main menu, where you can toggle those hints on and off. Beginners would toggle them on, professionals would toggle off.

And the shapiro-wilk-hint should be moved directly to the t-Test result table. There is already a hint if Levene's Test is significant, so the move would make this consistent.

Those hints should be with the t-Test table in any case. Even if the t-Test does not show a significant effect, informations about assumption checks are of value, since you then have a hint what biased p and why it is high. Sure, normality and equality of variances are only one of many factors for p to be high.

I would even argue to extent those hints: 
Instead of reporting p<0.05 they should report the exact p-values. There are varying guidelines how high the alpha level should be for assumption checks. The community usually agrees that one should justify alpha and not just set a fixed cut off. We should reflect this and not just call something significant or not. Just report the exact p-value.

For beginners I would suggest to grey out the results of assumption checks, IF e.g. n>150, because then the central limit theorem applies for normality and at the same time those tests get really sensitive (Levenes also). If n>150 we could hint to additionally check graphs (Q-Q plot, Histogram for normality and flexplot / rainbow plot for variance equality) if the user still feels that the assumption checks are needed.
For Levene's Test:  
We could add the information, that one should switch to Welchs Test if the user decides that Levenes p is low enough without telling him to switch exaclty when p<0.05.

**Comment by tomtomme** [comment]
@djdekker 
What do you think of the compromise I proposed?

**Comment by EJWagenmakers** [comment]
This strikes me as a matter of taste, and for now I am happy with what we have. There are some general plans for improvement and those may address this as well. So I am closing this.
