### ISSUE TITLE
JASP stops working in Windows 10

### ISSUE THREAD

**Issue by Prof360** [jasp-stats/jasp-issues#881]
* JASP version: 0.13

* OS name and version: Windows 10
* Analysis:  Stops working
* Bug description:  Keep getting a message form Windows saying "The program has stopped working" and then it shuts it down
* Expected behaviour:  I expect it to keep working more than 5 minutes at a time.  I uninstalled it, then reinstalled it, but it still keeps shutting down after a few minutes

<

**Comment by JorisGoosen** [comment]
Sorry to hear JASP keeps crashing on you.

Could you help me out by describing the problem a bit more?
As in, does JASP work for a bit?
Can you load data?
Can you actually run an analysis at all?
Does it crash for every analysis?
Are you using your own data?
Can you open a file from the data library and refresh that?

Because with the information you have now given me I cannot begin to figure out what is going wrong.
