### ISSUE TITLE
Large difference in Bayes Factors in Student vs. Wilcoxon One Sample T-Tests

### ISSUE THREAD

**Issue by estherweijman** [jasp-stats/jasp-issues#887]
* JASP version: 0.13
* OS name and version: macOS High Sierra 10.13.6
* Analysis: Bayesian One Sample T-test
* Bug description: There's is a large difference in the Bayes Factors with the student and Wilcoxon signed-rank test, even though the variable and other settings are the same for the two procedures. 
* Expected behaviour: Somewhat similar Bayes Factors for the two procedures.

Steps to reproduce:
1. Go to T-tests
2. Click on Bayesian One Sample T-test
3. Add dprime to variables
4. Repeat steps for Wilcoxon signed-rank test
5. See unexpected difference

[GithubBFissue.jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4932374/GithubBFissue.jasp.zip)

**Comment by EJWagenmakers** [comment]
@JohnnyDoorn 
Thanks for sending the .jasp file. I looked, and I think this makes sense. Anytime there is a large discrepancy between the parametric and the nonparametric procedure this suggests a closer examination of the data. And indeed, the data are not normally distributed. In particular, there are many outliers, and there are clusters of dprime where a number of people have exactly the same dprime. So I conclude, with some caution because I did not dig really deep. that the nonparametric result is the one that is preferred.
![image](https://user-images.githubusercontent.com/8603015/87771551-cbaf6680-c820-11ea-80f6-b282ae7506ab.png)

E.J.

**Comment by EJWagenmakers** [comment]
However, when I run the classical Student t and Wilcoxon, I get about the same result! (with both p-values being very low). Let me run the Bayesian Wilcoxon again, with more iterations....
@JohnnyDoorn : dprime is positive on average, but the Bayesian measure of effect size is *negative*. How come?

**Comment by EJWagenmakers** [comment]
This is with 10,000 iterations:
![image](https://user-images.githubusercontent.com/8603015/87772725-69effc00-c822-11ea-99e7-d55309fa1c41.png)

Maybe the discrepancy has something to do with how ties are handled?

**Comment by JohnnyDoorn** [comment]
Hi @estherweijman ,

Thanks for reporting this. The Wilcoxon signed rank test was recently implemented while we were still working out the statistical details. We had chosen to add some steps to the algorithm to make it more stable, but it turned out that this can lead to very conservative Bayes factors that should not be conservative. In the next release, we will have removed this step and use other means to make the algorithm more stable. 

Kind regards,
Johnny

**Comment by estherweijman** [comment]
Hi @EJWagenmakers and @JohnnyDoorn, 

Thank you both for your explanations and efforts. Are you able to give an indication of when the next release will be available (roughly)?

Kind regards, 
Esther

**Comment by boutinb** [comment]
We plan to release a new version beginning of September
