### ISSUE TITLE
RESULTADOS DIFERENTES ENTRE SEM Y CFA

### ISSUE THREAD

**Issue by AlejandroPeru** [jasp-stats/jasp-issues#897]
* JASP version: 0.13.1

* OS name and version: Windows 10
* Analysis: CFA and SEM
* Bug description: The model is not admissible: lavaan WARNING: covariance matrix of latent variables
                is not positive definite;
                use lavInspect(fit, "cov.lv") to investigate.
He econtrado el error cuando utilizo Análisis factorial confirmatorio. Sin enbargo cuando ejecuto la misma sintaxis en SEM si funcia, no encuentro ese error. En otros experimentos que he realizado he encontrado también  resultados diferentes entre CFA y SEM. 
No sé si podrian aclarar mi duda de por qué sucede resultados diferentes

**Comment by EJWagenmakers** [comment]
Google translate:
"I have found the error when I use Confirmatory Factor Analysis. However when I run the same syntax in SEM if it works I can't find that error. In other experiments I have carried out I have also found different results between CFA and SEM.
I don't know if they could clarify my doubt why different results happen"

**Comment by AlexanderLyNL** [comment]
I vaguely remember a discussion where it is mentioned that in the R code CFA does an extra check, which is not done for SEM. 

https://github.com/jasp-stats/jasp-test-release/issues/91#issuecomment-500772935

Regarding differences between CFA and SEM, I'd be happy to see an inventory of it, so we can look into them further. One obvious thing that can differ is due to column type.
