### ISSUE TITLE
Missing data in descriptives but... nothing seems missing!

### ISSUE THREAD

**Issue by itremont** [jasp-stats/jasp-issues#910]
* JASP version: 0.13.1

* OS name and version: MacOS 10.15.6
* Analysis: descriptives
* Bug description: I opened a dataset converted from excel to csv format. There are 35 cases of patients with COVID-19 admitted to the UTMB hospital in Galveston, Texas. All these subjects died, and are part of a larger cohort. I am running interim descriptives to screen for data integrity. When I run a descriptive  I get 9 more, labeled as "missing data".  I do not see the missing nine as included in the dataset, but they appear as computed under descriptives. 
* Expected behaviour:
I expect zero missing cases

#### Steps to reproduce:
1. Go to '..Neur-COVID Data 7-26-2020.'
2. Click on '.Open file...'
3. Scroll down to '.run descriptives, select age, or sex, etc and look at the output table
[NEUR - COVID Data -7-26-2020 (2).xlsx](https://github.com/jasp-stats/jasp-issues/files/4983361/NEUR.-.COVID.Data.-7-26-2020.2.xlsx)
...'

 NOTE: I HAVE INCLUDED THE EXCEL FILE AND THE JASP file

[NEUR - COVID Data -7-26-2020 (2).xlsx](https://github.com/jasp-stats/jasp-issues/files/4983367/NEUR.-.COVID.Data.-7-26-2020.2.xlsx)

[NEUR - COVID Data -7-26-2020 (2).jasp.zip](https://github.com/jasp-stats/jasp-issues/files/4983377/NEUR.-.COVID.Data.-7-26-2020.2.jasp.zip)

**Comment by Kucharssim** [comment]
Hello @itremont,

thank you for reporting this issue and for the enclosed files - I can reproduce the problem you found.

The problem is that JASP loads the file with the last 9 rows empty. This is because the exported `.csv` file also has 9 rows empty, you can see that by opening the file in a text editor - the file ends with a bunch of empty data:
![Screenshot 2020-07-28 at 10 20 09](https://user-images.githubusercontent.com/7093546/88638653-13a17980-d0bc-11ea-8acf-3fe927f7cd43.png)

I don't know why Excel exports the `.csv` with the empty rows. However, when I open your `.xlsx` file, delete the 9 rows below your data, and save as `.csv` again, then it works: the file does not contain empty rows anymore.

I hope this solves your problem.

**Comment by itremont** [comment]
Dear Simon & Joris: 
I appreciate your finding a fix so fast. Yes, that does it. 
I apologize if I keep bringing up issues that may be trivial.  I ain’t no computer geek. 
Ivo

**Comment by JorisGoosen** [comment]
Luckily we are computer geeks and we do not mind helping at all!
