### ISSUE TITLE
Missing Reliability Analysis

### ISSUE THREAD

**Issue by socialpsysteph** [jasp-stats/jasp-issues#911]
* JASP version: 0.13.1

* OS name and version: Windows 10
* Analysis: When I open up JASP, there is no drop down menu under Descriptives. The option to run a reliability analysis is missing.
![Annotation 2020-07-27 144414](https://user-images.githubusercontent.com/62213961/88579229-b94edd00-d017-11ea-97c9-535828c80b73.png)

**Comment by Kucharssim** [comment]
Hello @socialpsysteph,

since JASP version 0.13, Reliability is its own module. To activate it, click on the `+` sign on the upper right of the JASP window, and click on `Reliability` to activate the module, see the screenshot:

![Screenshot 2020-07-27 at 20 50 31](https://user-images.githubusercontent.com/7093546/88579813-f2547500-d04a-11ea-986e-fbff3d4c1c40.png)

**Comment by socialpsysteph** [comment]
Oh, thank you so much!!
