### ISSUE TITLE
Issues with display of icons and characters 

### ISSUE THREAD

**Issue by frdcv** [jasp-stats/jasp-issues#929]
*** JASP version:** 0.13.1 (64 bits)

*** OS name and version:** Windows 10
* Analysis: Checkmarks and other characters or icons appear as empty rectangles.
* Bug description: Please see the attached image. Checkmarks and other special characters like greek letters are not appearing in JASP, instead, it shows empty/blank rectangles. My default app language is English on my system settings. This might be a local configuration issue, but nothing that I've tried has worked so far: 1) Running the program in Windows Safe Mode; 2) Running it after cleaning cache and registry (with CCleaner); 3) Using compatibility with a previous Windows version.
* Expected behavior: Special characters should appear on the screen as expected.

Thank you in advance,

Screen capture of the issue:
![JASP issue showing chars and icons](https://user-images.githubusercontent.com/68574437/89658707-7a7d1a80-d894-11ea-995b-e19a700c61f5.jpeg)

**Comment by boutinb** [comment]
Seems to be a fonts issue. JASP uses Sans Serif family fonts, and it depends on the machine (and the characters that has to be displayed) to specify which specific fonts wil be used. Apparently your machine does not have a Sans Serif fonts that can display special symbols. 
It is possible to add fonts to your machine: https://www.digitaltrends.com/computing/how-to-install-fonts-in-windows-10/
I am not so sure which fonts should be used.
@JorisGoosen: I see that there was a attempt to load the FreeSans font in JASP but this was removed. There was a problem with this one? And can you advise @frdcv which fonts he should load?

**Comment by JorisGoosen** [comment]
Sadly enough the font in JASP is not configurable at the moment.
FreeSans works and is inside JASP but not used because people were complaining it wasn't "pretty" enough I think.

For @frdcv 's problem though: maybe the system default font could be changed and maybe that would use a different font? 
Im not at all sure of this though...

**Comment by JorisGoosen** [comment]
@frdcv what are your "region" settings?

**Comment by frdcv** [comment]
Hi! @JorisGoosen, @boutinb, thank you for helping me with this. Today I tried changing the system font to **SansSerif** via editing the registry, as described here: winaero.com/blog/change-system-font-windows-10/
It did not work out, as the error remained.
As for my language setting, my default app and windows display language is English (United States). This is also in my "system locale" setting. I've tried enabling and disabling the "Beta: Use UNICODE UTF-8 for worldwide language support" but it did not work.
Any additional ideas? I don't have trouble with it, but I want to use JASP with my students, and I wanted to fix this issue first.

**Comment by AlexanderLyNL** [comment]
Hi Fausto, 

Any chance your username has a character with an accent such as ñ? 

Cheers,
Alexander

**Comment by boutinb** [comment]
Hi @frdcv, to know which font is used, I will teach you how to modify a file that describes the analyse options (of the Descriptives analysis), in order to add a text that prints the family font that is currently used. This file is in:
C:\Program Files\JASP\resources\Descriptives\qml folder and its name is Descriptives.qml.
. First, make a backup of this file: with File Explorer, go to the folder, and copy Descriptives.qml.
To be able to modify the file, you need to start an editor with administrative right. For this, you can do the following:
. Search for the editor (notepad for example), and right-click on the icon: you get the possibility to Run as administrator.
. From the editor, open Descriptives.qml.
. After the 'columns: 1' line, add this line: ' Text { text: "font: " + fontInfo.family } ':
`
Form

{
	columns: 1
	Text { text: "font: " + fontInfo.family }
...
`
. Start JASP with a data file, and open the Descriptives analysis. You should see something like that:
<img width="625" alt="Screen Shot 2020-08-12 at 13 13 06" src="https://user-images.githubusercontent.com/503332/90009051-a84fce00-dc9d-11ea-83aa-935c086ba9db.png">

Can you tell me then which font is used?

**Comment by frdcv** [comment]
> Hi Fausto,
> 
> Any chance your username has a character with an accent such as ñ?
> 
> Cheers,
> Alexander

@AlexanderLyNL 
Hi Alex!, no, just my four initials, they are as common as the ABCD.

**Comment by frdcv** [comment]
> Hi @frdcv, to know which font is used, I will teach you how to modify a file that describes the analyse options (of the Descriptives analysis), in order to add a text that prints the family font that is currently used. This file is in:
> C:\Program Files\JASP\resources\Descriptives\qml folder and its name is Descriptives.qml.
> . First, make a backup of this file: with File Explorer, go to the folder, and copy Descriptives.qml.
> To be able to modify the file, you need to start an editor with administrative right. For this, you can do the following:
> . Search for the editor (notepad for example), and right-click on the icon: you get the possibility to Run as administrator.
> . From the editor, open Descriptives.qml.
> . After the 'columns: 1' line, add this line: ' Text { text: "font: " + fontInfo.family } ':
> `
> Form
> 
> {
> columns: 1
> Text { text: "font: " + fontInfo.family }
> ...
> `
> . Start JASP with a data file, and open the Descriptives analysis. You should see something like that:
> <img alt="Screen Shot 2020-08-12 at 13 13 06" width="625" src="https://user-images.githubusercontent.com/503332/90009051-a84fce00-dc9d-11ea-83aa-935c086ba9db.png">
> 
> Can you tell me then which font is used?

Hi Bruno @boutinb! It shows SansSerif. Great tutorial btw. What would you suggest next?

![JASP issue showing chars and icons2 jpeg](https://user-images.githubusercontent.com/68574437/90314575-5ba50680-deda-11ea-901b-14f2625b408b.png)

**Comment by frdcv** [comment]
Just in case, I have tried by changing the default windows font from Segoe UI to Tahoma, and the same issue still remains.
Regards

**Comment by boutinb** [comment]
@frdcv Now you know how to change dynamically a QML file, you can add the following line in Descriptives.qml:
```
Form
{
    Component.onCompleted: jaspTheme.font = "Segoe UI"
    Text { text: "font: " + fontInfo.family }
    columns: 1
....
```
Check then that the font is really changed in Descriptives (it shows 'font: Segoe UI'). If this is the case, this code change the fonts for all analyses, so also the Distribution - Normal.
On my PC, the "Segoe UI" font renders correctly the symbols.
I know this is not the right way to solve your problem, but I want to be really sure that, if I add a feature so that you can change the font in the Preferences settings of JASP, that it will really solve your problem.

**Comment by frdcv** [comment]
Dear Bruno (@boutinb),

It worked beautifully! Now I can see my check icons, Mu and Sigma as intended. Thanks a lot to you and to @AlexanderLyNL!
Best regards and success! I will now proceed to mark this conversation as closed.

![Picture1](https://user-images.githubusercontent.com/68574437/90406131-57a7ee80-e06a-11ea-98a9-1b6b2d6aa117.png)

**Comment by boutinb** [comment]
In the next release, you will be able to change default preferences to solve this.
