### ISSUE TITLE
Factor Analysis item issue

### ISSUE THREAD

**Issue by hallcg1** [jasp-stats/jasp-issues#932]
Good morning,

I am a student and relatively new to JASP. I have been experimenting with a couple of data sets provided by my professor, and it seems when I try to run a Factor Analysis on the data set, I am unable to get the item(s) to move to the Variable column. I have tried the same data set with other tests in JASP, but only when I try to run a Factor Analysis with the program do I encounter this issue. I tried to upload the .sav files, but this site does not support that format.

I have tested the data in other software packages and I am able to run the analysis, just not in JASP for some reason. 

Any guidance or assistance would be greatly appreciated.

Chris

* JASP version: 13.1.0

* OS name and version: Windows 10 Home
* Analysis: Factor Analysis
* Bug description: See above
* Expected behaviour: Move item(s) to the variable column

#### Steps to reproduce:

![Capture](https://user-images.githubusercontent.com/69393341/89715020-4ffc9180-d968-11ea-9a35-e53fab2fbfa9.PNG)

**Comment by AlexanderLyNL** [comment]
Hi Chris,

One underlying assumption of PCA is that the variables you apply it on are continuous variables, see the ruler at the right bottom of the box "Variables". The items in the left box are interpreted as ordinal (three bars), which is why they cannot be entered in the analysis. 

To overrule this PCA restriction, you can change the type of your variables in the data pane. Alternatively, you can go to 

   Preferences - Data - Import threshold between Categorical or Scale 

and change the default 10 value to a lower value. After a restart all your items will then be interpreted as continuous variables and you can move all your items into the "Variables" box. Hope that this clarifies things. Please close this issue if this solves your issue. 

Cheers,
Alexander

PS: To add data files, or preferably the jasp-files you can zip them first before adding them to the thread.

**Comment by hallcg1** [comment]
Thank you for the quick response, Alexander. I adjusted the Preferences and I am still having the same issue. I have included an image before of my current settings, and have also included the zipped data files that I have been testing.

Chris
![Capture](https://user-images.githubusercontent.com/69393341/89715444-31e46080-d96b-11ea-93ee-278b69c1efb4.PNG)
[Data files.zip](https://github.com/jasp-stats/jasp-issues/files/5045636/Data.files.zip)

**Comment by AlexanderLyNL** [comment]
Hi Chris,

The reason why 9 doesn't works, is because you have about 4 unique values per column. So to have jasp interpret every column with 4 or more values as a continuous variable, you have to change that 9 into a 4. 

For your data set, however, I changed your columns from ordinal to scale manually. I can only do this for 

[Sense of Humor Scale Example (3).jasp.zip](https://github.com/jasp-stats/jasp-issues/files/5045773/Sense.of.Humor.Scale.Example.3.jasp.zip)

because the other data set consists of columns consisting of strings, and it's unclear for the program to automatically change these into numbers. For 

Factor Analysis Managerial Scale Example (4)

you have to encode each column with numbers. This can be done for instance with the compute column functionality. 

However, as your data are really ordinal, I don't think that PCA provides you with the right answers. 

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Correction, you can do the same thing for 

Factor Analysis Managerial Scale Example (4)

and change the type of each column from ordinal to scale. The provided columns are not text variables, but ordinals with labels. So you can change the type of the columns. 

Cheers,
Alexander

**Comment by hallcg1** [comment]
Thank you for the clarification, Alexander!  I appreciate you explaining this for me. :-)
