### ISSUE TITLE
Getting inappropriate descriptives for nominal variable

### ISSUE THREAD

**Issue by djdekker** [jasp-stats/jasp-issues#939]
* JASP version: 0.14 nightly of August 14 (075f70b4e3b7cd994b0efe9bf78da79cc6468b83)
* OS name and version: macOS 11.0 Big Sur (public beta)
* Analysis: Descriptives
* Bug description: After changing variable type from scale to nominal, the descriptives are not updated.
* Expected behaviour: Statistics like mean, median and std. deviation are not shown for nominal variables.

#### Steps to reproduce:

1. Open arsenal_players.csv.
2. Notice that JASP regards the jersey number as a scale variable.
3. Click 'Descriptives' and put 'jersey number' in the Variables box.
4. In the spreadsheet, change 'jersey number' into a nominal variable.
5. Notice that the output table is not updated: Mean, Std. Deviation, Minimum and Maximum are still being shown, although 'jersey number' is now a nominal variable.
6. It is also still possible to get additional statistics like median and mode for the nominal variable.

[arsenal_players.csv.zip](https://github.com/jasp-stats/jasp-issues/files/5080845/arsenal_players.csv.zip)

**Comment by AlexanderLyNL** [comment]
Hi djdekker,

Thanks for the report. However, this is expected behaviour. The number used for a nominal variable are there to convey group membership. Neither their face value, nor the resulting means and variances of these numbers have a proper interpretation. The rows Mean, Std. Deviation, etc are still shown because they are ticked in the section "Statistics". An alternative would be to remove these rows, but that would provide bad user feedback, because they are ticked. Another alternative would be to fill it with NaN, but I don't think that that looks particularly nice.  

I agree that it might be fun to figure out the average jersey number, but it'll be nothing more than that, as I don't think that such an average has any specific meaning. 

Cheers,
Alexander

**Comment by AlexanderLyNL** [comment]
Okay, clearly I misread your message. I remember that at one stage we indeed removed the output such as Mean, Std. Deviation, etc for nominal and ordinal variables. However, it seems that we reverted that change again. I can't remember why exactly. My guess now is that there was some uproar about it and that we caved in. 

I do agree with the original poster though that Mean, Std. Deviation etc are not interpretable for nominal variables.

**Comment by tomtomme** [comment]
@djdekker & @AlexanderLyNL 
nominal vars coded numerically still show mean, SD, etc.
Since dichotomous vars are imported as nominal by JASP, I see why this makes sense. I would leave this as is. Students have to learn that they can do many things, but not all results are meaningful. This starts here.
What do you think about this perspective?

**Comment by djdekker** [comment]
I agree. It's a good thing for students to learn that not all output is interpretable, so I understand the choice. 👍
