### ISSUE TITLE
Crashes when there's a very large correlation matrix 

### ISSUE THREAD

**Issue by abnormally-distributed** [jasp-stats/jasp-issues#94]
* JASP version: 0.8.2.0
* OS name and version: Windows 10 
* Analysis: Bayesian Correlation Matrix 
* Steps to reproduce: Load up all 294 nodes and try to correlate them. It crashes. 
[Eigenvector Adult.zip](https://github.com/jasp-stats/jasp-desktop/files/1361333/Eigenvector.Adult.zip)

**Comment by tomtomme** [comment]
This is fixed for me at least since 0.18.2 beta flatpak build.
The boost-lib might have got an upgrade.

However:
Export of the results to PDF is broken. As soon as I create a table that is bigger than one page, it is messed up. Export to html & jasp file is fine. 
All files included in this zip:
[Eigenvector.Adult.zip](https://github.com/jasp-stats/jasp-issues/files/13728903/Eigenvector.Adult.zip)
