### ISSUE TITLE
Read ~/.Renviron on linux at startup

### ISSUE THREAD

**Issue by CdeMills** [jasp-stats/jasp-issues#952]
* Enhancement: Take into account R_*_USER variables found in ~/.Renviron
* Purpose: R permits to have packages installed in some path where the user has write access by defining 3 variables: R_HOME_USER, R_PROFILE_USER and R_LIBS_USER. This way, user installed packages take precedence over system-packages. This mechanism should be used by JASP, including during its compilation and installation, to match R behavior
* Use-case: keeping the main R library managed by the system package manager and the system administrator. Give users the ability to install / update their own packages

**Is your feature request related to a problem? Please describe.**
After compiling and installing JASP into a user-managed directory, it still looks only at /usr/lib/R for installed packages at startup.

**Describe the solution you'd like**
Reading ~/.R_environ and prepending user PATHS to system PATHS

**Describe alternatives you've considered**
The flatpack package uses KDE as graphical interface. CentOS-8 uses gnome, so the size of the dependant packages is huge. Moreover, any discrepancy between OS GUI version and flatpack GUI version will result in the same problem. 

**Additional context**
When launched from RStudio (the desktop version), R uses the user packages as it should. As JASP is a layer above R, the same should happen.

**Comment by vandenman** [comment]
Not a complete solution but a workaround is:

- set the environment variable `R_HOME` to wherever you installed R (leave it empty for `/usr/lib/R`).
- set the environment variable `JASP_R_Library` to wherever you want your library to be.

That way, the R version I use when building jasp matches the current release, as do all the R packages. At the same time, if I want to use R for something else (research, analyses, toy projects) I'm not bound to the R version or package versions used by JASP. Note that the libpaths of this approach have `JASP_R_Library` as first entry and then whatever the default is for your `R_HOME`.

If you're building JASP using Qt Creator you can set the environment variables here:

![image](https://user-images.githubusercontent.com/21319932/91576848-2cfe4580-e948-11ea-8fa2-f7bae11dbf0f.png)

that way the environment variables are only set when you're building JASP. 

Maybe @JorisGoosen knows a different way to use the default environment variables used by R.

**Comment by CdeMills** [comment]
Hello,
thanks for the tip. Tried ... but didn't work. And qt-creator is only for qt4 ?

Regards

Pascal

**Comment by JorisGoosen** [comment]
Im not sure I understand the issue here?

It seems that @CdeMills wants to use their own R-library right?
I think it should be possible to set R_HOME to whatever and you can use the local R however you like as far as I know.
Just start JASP like: `R_HOME=/usr/bla/bla jasp`

It would be good to support the R environ properly for those people compiling JASP themselves. It is just that usually people don't do that or are even interested in R and all the normally distributed versions (macOS, Windows and flatpak) all contain a separate R version because otherwise it becomes a nightmare to figure out bugs.

I think the `JASP_R_LIBRARY` is only used during the qmake part btw, so it won't work *after* compiling...

QtCreator is for qt5 as well.
