### ISSUE TITLE
Multinomial test issue

### ISSUE THREAD

**Issue by romanogino** [jasp-stats/jasp-issues#996]
* JASP version: 0.13.1

* OS name and version: Windows 10 2004
* Analysis: 
* Bug description: Multinomial test issue
* Expected behaviour: table but something happen
![2020-10-01_225802](https://user-images.githubusercontent.com/1270242/94886850-41979700-043a-11eb-9a41-a5cb947fa667.jpg)
![2020-10-01_225722](https://user-images.githubusercontent.com/1270242/94886859-452b1e00-043a-11eb-9aef-3bd17cf09cbb.jpg)

.

**Comment by boutinb** [comment]
@Kucharssim Can you have a look?

**Comment by Kucharssim** [comment]
Dear @romanogino,

thank you for the report. Unfortunately, I am unable to reproduce the error that you show with the screenshot. Would it be possible to send us the your data so that we can investigate the problem? That would help us a lot.
(Note that GitHub accepts attachments only as .zip files uploaded directly to the website.)

**Comment by romanogino** [comment]
The data file. Perhaps names are very long. Survey is coming from Google Forms.
[Encuesta_Percepción_Cozumel_2020.zip](https://github.com/jasp-stats/jasp-issues/files/5327692/Encuesta_Percepcion_Cozumel_2020.zip)
Best regards.
